stacks-network/stacks-core

blockstore/lib/config.py

I have use_https=False in my configuration, but blockstored still uses SSL sometimes. this seems to fix it.

don't parse use_https twice.

---

blockstore/lib/config.py

DHT code expects an array of servers and ports, not a string.

Use parsed servers instead of server string

---

README.md

Noticed error in link for detailed install instructions `https://github.com/blockstack/blockstore/wiki/Usage` to `https://github.com/blockstack/blockstore/wiki/Installation`

Update link in README.md file

---

blockstack/blockstackd.py

Variable hold bitcoind options was spelled incorrectly causing the following error:
```
(venv) larry@blockstack-explorer-1:~/blockstack-integration-tests$ blockstack ping
[2016-10-28 04:03:20,676] [DEBUG] [spv:103] (15653.140276675929920) Using mainnet
[2016-10-28 04:03:20,885] [DEBUG] [cli:210] (15653.140276675929920) Enabling advanced methods
[2016-10-28 04:03:20,930] [DEBUG] [client:134] (15653.140276675929920) Loaded storage driver 'disk'
[2016-10-28 04:03:20,930] [DEBUG] [client:134] (15653.140276675929920) Loaded storage driver 'blockstack_resolver'
[2016-10-28 04:03:20,931] [DEBUG] [client:134] (15653.140276675929920) Loaded storage driver 'blockstack_server'
[2016-10-28 04:03:20,931] [DEBUG] [client:134] (15653.140276675929920) Loaded storage driver 'http'
[2016-10-28 …
```

fix getinfo rpc call name error failure

---

blockstack/lib/scripts.py

Comment indicates that minimum name price is 1 satoshi, but minimum name price is `NAME_COST_UNIT` which is currently set to 100 satoshis.

minimum name price no longer 1 satoshi

---

api/search/README.md

as some useres might not have the command `mkvirtualenv` which
comes with virtualenv wrapper.
`virtualenv` creates a new venv just as `mkvirtualenv` does.

Change `mkvirtualenv` to just `virtualenv`

---

blockstack_client/backend/crypto/utils.py
setup.py

pycrypto was being used for legacy decryption, but cryptography can take care of that now

Removing dependency on pycrypto

---

blockstack_client/cli.py

I believe the problem for the api service and cli interface was just in the re-execing of `blockstack`  
The actual core blockstack server will probably still get angry about whitespace, but this should solve the problems for the macOS app deployment since I don't think it runs an actual core node.

fixing core api service whitespace issue on macOS

---

blockstack_client/rpc.py

It seems that `wallet_keys` (method argument) should be transformed into JSON string and sent to API, not `wallet` (a module).

fixed typo in backend_set_wallet

---

blockstack_client/cli.py

fixes secret setting so that passed passwords work when not in --debug mode (re-exec code isn't called)

Secret cli args weren't being processed when debug flag unset

---

README.md

The badge at the top of the readme uses `blockstack-server` as PyPi package which doesn't exist (anymore?). This PR changes it to just `blockstack`.

Correct old PyPi package name

---

blockstack_client/backend/drivers/_skel.py

Fixes a missing `return`, a typo and updates the log name

Fix minor flaws in driver skeleton

---

docs/setup_core_portal.md

the `.desktop` file didn't work out of the box. This one will work, even if the `blockstack:` is `blockstack://whatever` or `blockstack:whatever`.

[documentation] strip any '//' after 'blockstack:' in .desktop file

---

blockstack_client/actions.py
blockstack_client/backend/queue.py
integration_tests/blockstack_integration_tests/scenarios/name_transfer_not_enough_coin.py

Also makes the integration test check for the proper error returns:
Adds `errors` field to blockstack info responses
```
{
"advanced_mode": true, 
"cli_version": "0.14.2.0", 
"consensus_hash": "de5d6aa94003c5aa6de3f747453ebf80", 
"last_block_processed": 396, 
"last_block_seen": 396, 
"queues": {
"update": [
{
"confirmations": 113, 
"errors": [
"Failed to broadcast transfer transaction: Unable to transfer name:\n  * check \"get_balance\" failed.  "
], 
"name": "foo.id", 
"tx_hash": "e2cdc0a352e9aab813f950a8c2fab0d6699ac26cd01f6108bbfd78e18aa7018f"
}
]
}, 
"server_alive": true, 
"server_host": "localhost", 
"server_port": 16264, 
"server_version": "0.14.2.0"
}
```
For now, the only error supported is the above -- transfer operations failing.

make the errors component of the info response only appear if there is an error

---

blockstack_client/actions.py
blockstack_client/rpc.py
blockstack_client/wallet.py
docs/api-specs.md
integration_tests/blockstack_integration_tests/scenarios/rest_register_recipient_minconfs.py

```
GET /v1/wallet/balance/<minconfs>
```
will return a balance that includes txns with the specified number of minimum confirmations (integration test checks that it works with zero)
```
GET /v1/wallet/balance
```
is unchanged.

Support for setting minimum confirmations for wallet balance

---

blockstack_client/backend/nameops.py
blockstack_client/backend/queue.py
blockstack_client/backend/registrar.py
blockstack_client/rpc.py
integration_tests/blockstack_integration_tests/scenarios/rest_register_recipient_set_key.py

Registrar now tracks the owner address of the multi-op registration. The owner's private key is scrypted using the wallet password (which was already stored in registrar memory using our secrets passing mechanism), and then stored in the registrar's queue.db. When the registrar's owner key has changed over the course of a registration (from either a call to `/v1/wallet/keys/` or the registrar restarting), the registrar detects this, and uses the encrypted key to proceed with registration. If the wallet password changes, however, the registrar will be SOL.

Registrar tracking owner address

---

blockstack_client/rpc.py
integration_tests/blockstack_integration_tests/live_tests/api_tests.py

This ensures that core checks that on Authorization, one of two things must be satisfied:
1. If the client is authorizing with an API password, the Origin header must be present and either `http://localhost:8888` or `http://localhost:3000`
2. If the client is authorizing with an app session token, the Origin header must be present and equal to the `app_domain` in the session token.

Verifying `Origin` headers in blockstack-core

---

integration_tests/blockstack_integration_tests/scenarios/rest_register_update.py
integration_tests/blockstack_integration_tests/scenarios/rest_register_update_zf.py
integration_tests/blockstack_integration_tests/scenarios/rpc_register_sync_zonefile.py
integration_tests/blockstack_integration_tests/scenarios/testlib.py

Per issue #525, we had about 6-8 failing integration tests for functionality which should work and be correctly tested. There were two causes
1. Change in the response format of improperly formatted zonefiles.
2. Tests which required restarting the API endpoint were also closing the blockstackd RPC socket. Solved with sending a SIGKILL (the underlying problem, that the test runner's forking pattern leaves the RPC socket open for listening in the API endpoint, isn't solved, but the tests work now and this isn't an issue in production, where the forking pattern is different).

Fixes a handful of integration tests

---

blockstack_client/actions.py
blockstack_client/rpc.py
blockstack_client/version.py
blockstack_client/wallet.py
docs/api-specs.md

Version bump to 0.14.4.1
includes fix for Issue 531 --> subdomain not found on /v1/names/{}/ now returns 404 + `{'status':'available'}`
Wallet migration path now uses groups to determine when the wallet hasn't changed between series.
Also, now the command line `whois` works for subdomains:
```
$ blockstack whois created_equal.self_evident_truth.id
{
"address": "1AYddAnfHbw6bPNvnsQFFrEuUdhMhf2XG9", 
"blockchain": "bitcoin", 
"last_txid": "0bacfd5a3e0ec68723d5948d6c1a04ad0de1378c872d45fa2276ebbd7be230f7", 
"satus": "registered_subdomain", 
"zonefile_hash": "48fc1b351ce81cf0a9fd9b4eae7a3f80e93c0451", 
"zonefile_txt": "$ORIGIN created_equal\n$TTL 3600\n_https._tcp URI 10 1 \"https://www.cs.princeton.edu/~ablankst/created_equal.json\"\n_file URI 10 1 \"file:///tmp/created_equal.json\"\n"
}
``` …

Hotfix for Issue 531, Wallet Migration, and command-line `whois`

---

blockstack_client/actions.py
blockstack_client/backend/nameops.py
blockstack_client/backend/registrar.py
blockstack_client/rpc.py
docs/api-specs.md
integration_tests/bin/blockstack-test-all-junit
integration_tests/blockstack_integration_tests/scenarios/rest_update_with_key.py
integration_tests/blockstack_integration_tests/scenarios/testlib.py

This adds support for issuing updates with a specified owner key. This will allow browser to submit a zonefile UPDATE for a name owned by an address in browser but *not* in the core wallet.
The api specification includes a new property for the `PUT /v1/names/{name}/zonefile` endpoint for setting the `owner_key`, this is tested in the new integration test `rest_update_with_key.py`
(Issue #538)

Support for issuing updates with an owner key

---

blockstack_client/client.py
blockstack_client/config.py
blockstack_client/constants.py
blockstack_client/proxy.py
blockstack_client/rpc.py
integration_tests/bin/blockstack-test-scenario
integration_tests/blockstack_integration_tests/scenarios/testlib.py
subdomain_registrar/subdomains_registrar.py

Adds HTTPS support to blockstack proxy.
Requires new config variable `blockstack-client.protocol` to specify either `HTTP` or `HTTPS`.
Default configures (and migrates node.blockstack.org-pointed configs) to using `https://node.blockstack.org:6263`

Adds HTTPS support to blockstack proxy

---

blockstack_client/actions.py
blockstack_client/backend/registrar.py
blockstack_client/rpc.py
docs/api-specs.md
integration_tests/blockstack_integration_tests/scenarios/rest_transfer_with_key.py

This adds support for passing the 'owner_key' field to the API endpoint for name transfer. This is required for browser to support transfers.
Closes issue #553

Add support for passing owner key to transfer

---

docs/install-api.md

`uwsgi` expects a template for `index.html` which needs to be generated. This adds this additional step to the instructions.
cc @kantai

Add instructions for generating index template

---

build_docs.sh

Needed to get moved manually from `/tmp/index.html` to `api/templates/index.html` which can be handled by the script automatically
cc @kantai

Change path for index template of the API

---

api/nginx/blockstack_api.ini

I installed the APT version of uwsgi because the pip one didn't work on Debian 9. This version seems to need the info that this uwsgi is a Python one.
I didn't test this against the pip version, but I hope that it continues to work with this config directive :D
cc @kantai

Add explicitely Python to uwsgi config

---

api/config.py
api/search/fetch_data.py

Adds a new flag for "fetch_data" which only fetches profiles for names that had zonefile updates since the last indexing. This allows us to quickly index new names. (Core currently configured to do this fast update every 12 minutes).
Closes issue #554

Update search index with new profiles

---

Dockerfile
README.md

This PR adds a `Dockerfile` for `blockstack-core`. The image created is simply an Ubuntu VM with blockstack installed and runnable. The major issue with the image is the size (~1GB). Don't know how much of this can be reduced. To run pull down this branch and follow the `Running In Docker` instructions in the README.md.

Add dockerfile and build/run instructions

---

build_docs.sh
docs/api-specs.md

This PR adds functionality to automatically put the current version number into the API examples.
(uses `sed -i <regex>`, don't know how portable this is)
cc @kantai

Use newest version in API documentation

---

docs/aglio_templates/mixins.jade

Now the link automatically points to the current server that serves the API doc.
Needs an environment variable `NOCHACE=1` for `aglio` to don't cache the page when not edited `public.jade` or `api-specs.md`.
cc @kantai

Remove the explicit domain

---

images/community/snap/README.md

Because only an upstream maintainer would be able to use the simple continuous delivery infrastructure that we provide in https://build.snapcraft.io, I had to build my own pipeline for continuous delivery.
I let my imagination run wild, to play with the boundaries of our integrations, and ended up with a git branch that mutates itself :) Any reviews on that Travis-CI job will also be appreciated.
We now have v0.14.4.1 in the beta channel for all the supported architectures, and a process to update the snap in the edge channel every day without manual intervention. So I will start the call for testing with the Ubuntu community as soon as you approve this branch and process.
If things work nicely, I hope to release the next tag to the candidate channel, and make the following tag our first …

Add info about snap install and continuous delivery

---

integration_tests/bin/blockstack-test-scenario
integration_tests/blockstack_integration_tests/tests_skip.txt
integration_tests/test-launcher

This is now in a working state. To run the tests have a configured `kubectl` client and `docker` installation. First build and then push the images to an image repository reachable from your cluster. Next configure the reporting to an `influx` server. The tests requires a reachable instance of `influxdb`. Then run the tests:
```bash
$ ./test-launcher push-images
$ export INFLUX_HOST="db-influxdb.monitoring"
$ export INFLUX_USER="myuser"
$ export INFLUX_PASS="mypass"
$ export INFLUX_SSL="False"
$ ./test-launcher run-all-kube
```
I'm building out reporting, but currently you can get the results by logging into the `influxdb` instance and running queries. The tests take about an hour (53 min for longest test, and ~10 min to scale the cluster) to run:
```
> select count(runtime) from …
```

Run Docker tests on Kubernetes

---

blockstack_client/actions.py
blockstack_client/backend/nameops.py
blockstack_client/backend/queue.py
blockstack_client/backend/registrar.py
blockstack_client/rpc.py
docs/api-specs.md
integration_tests/blockstack_integration_tests/scenarios/rest_register_recipient_opt_key.py
integration_tests/blockstack_integration_tests/scenarios/rest_register_renew_with_key.py
integration_tests/blockstack_integration_tests/scenarios/rest_transfer_with_key.py

Adds `owner_key` and `payment_key` options to RESTful register, update, transfer, and renew endpoints.
For *registers*, because it is a multiple-transaction operation, these private keys must be retained by the core node. As before, the core node stores this `scrypted` using the wallet password in the registrar queue db.

Add payment_key option to RESTful transactions

---

images/docker/api/Dockerfile
images/docker/core/Dockerfile
images/docker/testmode/Dockerfile

`lsof` is required by core to check that application secrets aren't read by another process. This is used when the `--debug` flag is passed to `api start`.

Add `lsof` to developer docker containers

---

Dockerfile

Revert to using a dockerfile which builds from source rather than apt.
Due to apt issue here: (#595)

Revert to building docker image with pip

---

Dockerfile

Same changes from the PR on develop (too lazy to rebase here, will just merge back into develop from master) -- use pip instead of apt packages, which are currently out of date for certain python packages.

update the core container to install via pip rather than apt

---

.gitmodules

According to https://www.git-scm.com/docs/gitmodules
.gitmodules files must live in the top-level directory of the repository. This broke some automated build processes.

Fixes submodule for blockstack-consensus-data

---

blockstack/blockstackd.py
blockstack/lib/config.py
blockstack/version.py
blockstack_client/version.py

This fixes the migration complaint code path in blockstackd. You now need to explicitly add a given version to the config.versions_need_upgrade if that version should trigger the "upgrade your client.ini" complaint.
Resolves #591 
This also bumps the develop branch's version number! 0.16 here we come!

Fix blockstackd migration complaint

---

integration_tests/bin/blockstack-test-scenario

New versions of bitcoind changed the default rpc-port for regtest mode. This was causing our integration test framework to fail to connect to bitcoind.

specify rpc-port for bitcoind in regtest mode

---

api/resolver.py
build_docs.sh
docs/api-specs.md

Resolver endpoint drops support for multiple usernames on /v2/users (this was a great vector for griefing a server), and then add support for responding to requests on `/v1/users` -- per issue #628 
Example:
https://core.blockstack.org/v1/users/muneeb.id
Documentation is updated to reflect the endpoint.

Remove multiname lookups on /v2/users and support a /v1/users endpoint

---

api/resolver.py

remove /v2/users/$, /v2/namespaces/, /v2/namespace/ endpoints, as they were no longer supported

Remove unsupported /v2/ endpoints from API

---

blockstack_client/actions.py
blockstack_client/backend/nameops.py
blockstack_client/backend/safety.py
blockstack_client/rpc.py
blockstack_client/version.py
integration_tests/blockstack_integration_tests/live_tests/api_tests.py

And adds
`?single_sig=1` query string to the price lookup, which forces the price calculator to use a dummy single signature.
This should bring the price-estimation into line with the actual costs.
Our fee estimation still seems to be a bit on the high side (names should be closer to 0.001 btc than 0.002 btc), but will run that down later.

Price endpoint computes with pre+reg only

---

blockstack_client/backend/nameops.py
blockstack_client/operations/preorder.py
blockstack_client/operations/register.py
blockstack_client/operations/transfer.py
blockstack_client/operations/update.py
blockstack_client/tx.py

adds a `dust_included` flag to tell the tx serialization code not to add any more dust fees, because those fees are already included in txfee, this prevents double-adds of dust fees.
This reduces preorder-register cost by sum total ~53000 satoshi or like $2.50

Prevent double counting of dust fees

---

blockstack_client/rpc.py

See issue #636 #637 
Not enough btc to pay fee now returns 400 (previously was a 500 error), and the message: `Not enough inputs for transaction (total: 4999292165, to spend: 4999292165, fee: 955).`
```
[2017-10-07 15:00:36,496] [DEBUG] [registrar:1043] (1.140572132112128) Registrar sleeping for 1
[2017-10-07 15:00:37,131] [DEBUG] [rpc:3924] (1.140572499130112) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
origin: http://localhost:8888
content-length: 165
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
dnt: 1
host: localhost:6270
referer: http://localhost:8888/wallet/send
content-type: …
```

Withdraw API Behavior

---

blockstack_client/backend/registrar.py

Addresses issue #648 which prevents successful registrations in recent Windows installs.

Address Registrar Lockfile Hardlinking Problems in boot2docker

---

build_docs.sh

The API call for `ping` shows only the first three (major, minor and patch) version numbers. The API doc for `ping` shows all four. This commit fixes it.

Don't show the whole version at api docs

---

blockstack_client/app.py
blockstack_client/rpc.py
blockstack_client/schemas.py

The application private key is no longer a required field of the `APP_SESSION_REQUEST` object. It was not needed by core (it was only being used to generate the datastore ID from the address of the uncompressed pubkey).
For `blockstack-browser` to send the session request without an app private key, it will need to use a new version of core.

Remove requirement of app private key

---

blockstack_client/config.py
blockstack_client/subdomains.py

Resolving subdomains can make certain queries lag right now (the subdomain processing happens client-side -- @jcnelson is looking into moving that into the indexers / or the resolver)
This hotfix no-ops the subdomain lookups on the client unless you turn on support in the client.ini with the field:
```
[subdomain-resolution]
resolving_subdomains = True
```

Opt-in for resolving subdomains on the client

---

blockstack_client/rpc.py

This fixes an issue where the `renew` command wouldn't correctly transfer the name to a new address when called from the CLI.

Pass recipient address to renew in the funky call graph

---

blockstack_client/proxy.py
integration_tests/blockstack_integration_tests/live_tests/api_tests.py

This should make `blockstack-core` pass CI tests again.
There were two issues:
1. `get_historic_name_at` doesn't exist on node.blockstack.org, and the previous patch release requires the call.
2. `get_zonefiles` wanted to make http requests when communicating on port `6263`.
In the long run, problem 2 is cause by the fact that we are breaking up host, protocol, and port in the blockstack `client.ini` and there's lots of code that disregards one or two of those config variables. We should just have 1 connection string config variable.

Fixes error behavior when communicating with older nodes

---

blockstack_client/backend/drivers/common.py

Introduces `index_update_manifest()` function that updates the manifest when the index pages change as a result of content changes that result in different paths or urls. One driver that requires this functionality is ipfs, whose addresses are hashes of their associated content: when the content changes, so does its address. 
In order to trigger the `index_update_manifest()`, the `driver_config()` call inside the driver's `storage_init()` needs to set the following parameter:
```python
DVCONF = driver_config(
...
driver_info={
'dynamic_index': True,
},
...
)
```
This PR also includes an exception for handling faux-URLs of the type `ipfs://{hash}` inside `get_chunk_via_http()` to support the IPFS driver.

ENH: introduces index_update_manifest(), and handling of ipfs://

---

docs/subdomains.md

Explains the two options you must add to the docker run command in order for the subdomain registrar service to be resolved from interactive mode. (part of me feels like I'm just saying words but I think that makes sense!)

Added documentation for interaction testing subdomain registrar service

---

blockstack_client/rpc.py
blockstack_client/version.py
circle.yml

Return a 404 error on missing subdomains, instead of 500 for the `/v1/names/` endpoint.

404 on missing subdomain instead of 500 status code

---

api/resolver.py

This is now performed from within the profile.get_profile code.

Remove subdomain / name parsing logic from the flask app

---

blockstack/lib/schemas.py
blockstack/version.py
blockstack_client/version.py

You can test the difference in validation on the name:
`aaron.blockstack_berlin.id`

Quick fix on subdomain name validation

---

blockstack/version.py
blockstack_client/rpc.py
blockstack_client/version.py

Currently, `v1/names/<foo.id>` returns a 500 status code if the name is expired. This changes that to a 404.

Expired Names Should Return 404, Not 500

---

blockstack_client/rpc.py
blockstack_client/version.py

This doubles the allowable name length in 'name' lookup URLs in `rpc.py` --- this is to accommodate for subdomain name lookups.

Increasing the max name length in rpc.py

---

docs/api-specs.md

This PR adds a deprecated notice to the /v1/names/zonefile endpoint for consistency.
The [category description](https://blockstack.github.io/blockstack-core/#managing-names) states that it should be and @jcnelson did confirm this in Slack.
---
Follow up for https://github.com/blockstack/blockstack-core/pull/796

Add deprecated notice to /v1/names/zonefile

---

docs/api-specs.md

- schema was inconsistent with response
- indentation and quotes were not consistent
This was a task from contribute.blockstack.org. Wasn't sure how to get example of an error code for this endpoint.

Update /v1/node/ping schema and fix styling

---

circle.yml
integration_tests/blockstack_integration_tests/live_tests/api_tests.py

Sometime in the past few days, CircleCI's images stopped working because `virtualenv` no longer exists as a command.
Rather than try to band-aid the behavior in our circle.yml, file, I figured now would be a good time to upgrade our CircleCI build to CircleCI version 2.0. That broke _other surprising things_ because the `test` module doesn't exist in the Docker standard python builds. Anyways, enough complaining, this updated `circle.yml` file + `api_tests.py` works.

Fix Circle CI behavior

---

blockstack_client/rpc.py
integration_tests/blockstack_integration_tests/scenarios/name_pre_regup_subdomain_lookups.py
integration_tests/blockstack_integration_tests/scenarios/subdomain_registrar_redirect_test.py
integration_tests/blockstack_integration_tests/scenarios/testlib.py
integration_tests/deployment/docker/Dockerfile.tests

This changes the behavior of the API endpoint to return a 301 HTTP redirect when it gets a `/v1/names` request for a not-yet-registered subdomain.
It looks up the domain's zonefile, reads the `_resolver` URI and redirects to the `/v1/names` endpoint listed there. If no such URI exists, or the api endpoint fails to read the zonefile, it responds with 404 (as it did before), with a `more` field with a little more information about the failure.
This implements the blockstack-core side of #750 
The integration test `name_pre_regup_subdomain_lookups.py` was modified to test for the 301 redirection.

Feature: Redirect for pending subdomains

---

api/search/basic_index.py
api/search/utils.py
docs/api-specs.md

This does 3 things:
1. Allows valid non-id subdomains to index correctly (this bug relates to the `/api/` directory's _own_ definition of `isValidName`
2. Add `fullyQualifiedName` key to the search result set -- the `username` field is currently rather strange -- it returns only the domainname part if the name is in the `id` namespace, but the fullyQualifiedName otherwise. Fixing that is unfortunately a breaking-change, which we should make at some point, but for now, `fullyQualifiedName` will work.
3. Document those changes in `api-specs.md`

Improve search endpoint for fully qualified names

---

blockstack/lib/client.py
blockstack_client/rpc.py
docs/api-specs.md

This adds a `page=` query string to the API endpoint for history, and forces it's use (as in defaults to page=0).

Force pagination in history API endpoint

---

blockstack_client/rpc.py
blockstack_client/version.py

This patches the zonefile return when looking up the resolver entry for a subdomain registrar.
The zonefile record is returned as base64 by the initial lookup, and it must be decoded before returning -- this is currently leading to 500s on the deployed server.

Hotfix Zonefile Lookup for Resolver URI Entry

---

.dockerignore
.gitignore
integration_tests/bin/blockstack-test-scenario
integration_tests/blockstack_integration_tests/scenarios/testnet_simple.py
integration_tests/deployment/docker/Dockerfile.testnet.simple
testnet/testnet_simple.sh

This adds the ability to run scenarios with checks for globally installed gaia, subdomain registrar, and tx broadcaster turned off (these checks default to on, so the default behavior doesn't change).
It also adds a testnet scenario which doesn't depend on the existence of gaia or the subdomain registrar, as well as a Dockerfile which will start the simple testnet with just these commands:
```
docker build . --file integration_tests/deployment/docker/Dockerfile.testnet.simple --tag blockstack-core:testnet-simple
docker run -it -e BLOCKSTACK_TEST_START_GAIA=0 -e BLOCKSTACK_TEST_CHECK_SUBDOMAIN_REGISTRAR=0 blockstack-core:testnet-simple
```
And then you can connect to the testnet homepage via (`$(docker-ip):8000`) as well as the bitcoind, and core api endpoints.

Add scenario for stripped down testnet

---

blockstack/lib/config.py

The environment variable `BLOCKSTACK_ATLAS_SEEDS`, if present, will override the node's `atlas_seed_peers` setting. If this environment variable is set on first run (i.e., no `blockstack-server.ini` exists yet), the value of the variable will be written into the `.ini` file instead of the default value.

Add environment variable for overriding atlas_seed_peers setting 

---

blockstack_client/backend/drivers/ipfs.py

Proposed storage driver for IPFS in response to #430
Before using, you will need to use pip to install ipfsapi.
You will also need a local running instance of IPFS.
Uses the ipfs MFS for mutable files.

storage driver for IPFS

---

blockstack_client/backend/drivers/ipfs.py
blockstack_client/backend/drivers/ipfsindex.py

Experimental indexed storage driver for IPFS in response to [#430](https://github.com/blockstack/blockstack-core/issues/430)
!Not fully tested yet
This IPFS driver uses an index similar to the one in the dropbox.py driver.
Assumptions:
- The writing/deleting user operates on an IPFS node, which contains a public/private key pair tagged with his blockstack id. The driver maps this IPNS (Hash of this public key) address to the current valid index manifest.
[example index manifest](https://gateway.ipfs.io/ipns/QmfYEYcX9KY9PUuwr1a4VgNgtAxJ81ZEsNF4Tid6GTp87z)
Problems:
- Currently, an IPNS publish operation is **very** slow. In the implementation, the IPNS publish runs asynchronously in the background, which might cause consistency problems.
- On every insert/update/delete the IPNS address has …

Indexed storage driver for IPFS

---

blockstack_client/backend/drivers/common.py
blockstack_client/backend/drivers/storjstore.py

Implemented basic support for storj driver based on requirements mentioned in #430 
The driver can be exercised by setting the config parameters for Storj such as username, password, bucket name.
The implementation can be further improved by making minor improvements to storj-python-sdk

Add storage driver support for storj

---

docs/wire-format.md

Adds a small description of how the zone file hash is computed in our wire format.

Add note about zone file hash to wire format

---

integration_tests/deployment/docker/Dockerfile.tests

This updates the integration test dockerfile so that it can be used with the current integration tests:
Example:
```bash
docker build . --file integration_tests/deployment/docker/Dockerfile.tests --tag blockstack-core:tests
docker run -it blockstack-core:tests blockstack-test-scenario blockstack_integration_tests.scenarios.name_pre_regup_subdomain
```

Update testing dockerfile

---

api/config.py
api/resolver.py
api/server.py

For the `getInfo` call used to fill the information on the core.blockstack landing page, use the BASE_INDEXER_API_URL if set. If not, read from blockstack-server config file (existing behavior).

For client.getinfo, use env var if set

---

api/deployment/blockstack_api.ini

PyMongo and UWSGI don't get along very well -- see this thread for more information:
https://jira.mongodb.org/browse/PYTHON-1497
So instead we'll only load the application post-fork (this guarantees that the PyMongo instance is initialized post-fork).
This led to some intermittent performance problems in our search endpoint. Tested via pointing our standard monitoring routines at a test-endpoint (thanks @wileyj !)

Fix PyMongo's Anger at UWSGI

---

api/config.py
api/search/server.py

This sets a low (60 second) cache timeout for empty result sets from the search endpoint.
You can test this by running:
```
DEBUG=True FLASK_APP=api.server EMPTY_CACHE_TIMEOUT=30 DEFAULT_CACHE_TIMEOUT=80 python -m flask run
```
With a mongo server running locally (and search data in the mongo instance):
```
curl http://127.0.0.1:5000/v1/search?query=NoResultExpected -I | grep Cache
Cache-Control: public, max-age=30
```
```
curl http://127.0.0.1:5000/v1/search?query=ResultExpected -I | grep Cache
Cache-Control: public, max-age=80
```
This uses the ENV variable `EMPTY_CACHE_TIMEOUT` to control this behavior.

Set low cache on empty result

---

api/server.py

This simply tweaks the account history cache specification to 1 minute.
I kind of dislike the fact that this kind of change requires repo commits.
I could add support for a config file here.

Hotfix to set account history cache to 1 minute

---

circle.yml

This adds a pretty simple CircleCI definition for the rust -- it just runs `cargo test` unit tests (there currently aren't any).

Add CircleCI definition for Rust implementation

---

api/server.py

This removes the behavior from the API shim that forces JSON responses.
This resulted in the `/zonefiles/` endpoint being unusable because it returns the raw zonefile.

Stop forcing JSON responses in API

---

api/README.md
api/config.py
api/server.py
docs/api-specs.md

Implements #901 ---
This adds a new endpoint: `/v1/index_files`, which can be configured to return URLs for getting search index dumps. By default (if left unconfigured), this returns 404.
You can test this behavior locally:
```bash
$ cd blockstack-core
$ pip install .
$ pip install -r ./api/requirements.txt
$ FLASK_APP=api.server flask run
```
Then:
```http
$ curl localhost:5000/v1/index_files -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v1/index_files HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 404 NOT FOUND
< Content-Type: application/json
< Content-Length: 62
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
< …
```

Add /v1/index_files endpoint

---

api/README.md
api/config.py
api/server.py

The API service (UWSGI proxy) previously wouldn't timeout requests to blockstack-core.
This resulted in some bad behavior in the event that the blockstack-core was experiencing heavy load --- the UWSGI workers would all be indefinitely tied up while waiting for responses from blockstack-core.
This adds an environment variable option:
```
BSK_SEARCH_API_TIMEOUT
```
Which takes a floating point number representing the number of seconds before timeout (default = 10).
This _also_ fixes what seems to be an existing typo in this file on `master`
You can test this via:
Starting blockstack-core:
```bash
$ blockstack-core start
```
Start a proxy with a really small timeout:
```
$ cd blockstack-core
$ pip install -r api/requirements.txt
$ BLOCKSTACK_DEBUG=1 BSK_SEARCH_API_TIMEOUT=0.0001 …
```

Hotfix: Add timeouts to UWSGI proxy

---

src/burnchains/bitcoin/bits.rs
src/burnchains/burnchain.rs
src/burnchains/mod.rs
src/chainstate/burn/db/burndb.rs
src/chainstate/burn/db/mod.rs
src/chainstate/burn/distribution.rs
src/chainstate/burn/mod.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/burn/operations/leader_key_register.rs
src/chainstate/burn/operations/mod.rs
src/chainstate/burn/operations/user_burn_support.rs
src/chainstate/burn/sortition.rs
src/core/mod.rs
src/util/mod.rs
src/util/uint.rs

This PR adds support for cryptographic sortition.  It does so by updating the `BlockSnapshot` struct, so that the call to `next_snapshot()` not only generates a new consensus hash, but also looks through all block commits and user support burns accepted in this block, calculates the burn weight behind each block header, projects the burn weights for each block candidate into partitions of the [0, 2**256 - 1) integer range, and uses a `SortitionHash` as a 256-bit integer to pick a winning block.  The `SortitionHash` is a rolling hash of PoW block header hashes and successful sortitions' VRF seeds, so it cannot be predicted in advance.  Here's an example output:
```
INFO [1550544732.106] [src/burnchains/burnchain.rs:482] Burn quota for 125 is 10752
DEBUG [1550544732.106] …
```

Peer network code review 2/18/2019

---

README.md

Refers to Gaia using "user-selected" rather than directly referring to specific backends.

Update README with Gaia changes

---

circle.yml

Force all cargo tests to run single-threaded so the network tests don't trip over themselves.

force single-threaded tests

---

src/main.rs
src/vm/checker/typecheck/tests/contracts.rs
src/vm/checker/typecheck/tests/mod.rs
src/vm/contexts.rs
src/vm/mod.rs
src/vm/tests/simple_apply_eval.rs

Implement a new `local` command `local repl`. 
Uses the rust stdin/stdout so input interactivity is limited -- notably input cursor operation. The SDK project can wrap this stdin/out pipe to provide a more full-featured terminal lib. 
Initial implementation is currently stateless, but still quite useful for local dev & testing purposes since it performs type checking and (stateless) evals on expressions. 
Next iterations for providing state require something like:
* Execute evals within an implicit `transient` contract state and commit the savepoints. 
* Allow top-level (contract level) expressions and have them "appended" to `transient` contract source / ast. 
Providing REPL support for multiple contracts requires something like:
* Define a special function (available only in local dev / …

REPL and eval_raw local commands

---

src/vm/docs/mod.rs
src/vm/functions/mod.rs

We have docgen matching enforced for all native functions -- as in every func must have a corresponding doc object. 
But no way to ensure that every func variant is enumerated during the actual generation. 
This macro appears to be the least invasive technique to achieving this. 
Is this idiomatic usage of macros? Is there a better way to do this?

Use macro for generating a list of all NativeFunctions - use for docgen

---

Cargo.toml
build-scripts/start-builds.sh

Context: https://github.com/blockstack/smart-contract-sdk/pull/1#discussion_r288163153

Rename clarity CLI bin output file from `clarity` to `clarity-cli`

---

Cargo.toml
circle.yml

This adds back in a codecov.io reporting system to our CircleCI definitions.
It also turns off tests for the clarity bin, since they were just duplicates.
Note -- the "deploy" definition of our circle definition is also suddenly breaking for some reason, but I think that's unrelated to these changes.

Fix Code Coverage Reporting

---

src/vm/docs/mod.rs

The examples in `mod.rs` aren't formatted to be cut and paste into files or commands because of the `=>` instead of legal comments like `;; Returns blah blah`
this fixes that problem

Updating to enable cut and paste examples

---

src/vm/docs/mod.rs

The inclusion of constructions such as `<A>` in input and output types broke the documentation generation. This change replaces `<A>` with `(A)` constructions and fixes the documentation generation.
@kantai not clear to me if this causes problems -- were they `<>` syntactically necessary? I took them as shorthand for replacement with type/element.

Fixing change which broke the documentation generation

---

.gitignore
build-scripts/build-dist-mac-x64.sh
build-scripts/docker-run.sh
build-scripts/start-builds.sh
circle.yml

Fixed for cross-compiling with latest osxcross.
CircleCI builds are faster -- now using a minimal archive of osxcross that is pre-packaged for use in the `buildpack-deps:stretch` docker image (Rust's base image). 
The dependency archives are uploaded as releases on a fork of osxcross here https://github.com/blockstackpbc/osxcross/releases
The fork & release packages also pin the version so the MacOS build doesn't break again in the same way in the future.

Fix macos dist build script

---

src/vm/checker/read_only/tests.rs
src/vm/checker/typecheck/mod.rs
src/vm/checker/typecheck/natives/mod.rs
src/vm/checker/typecheck/natives/options.rs
src/vm/checker/typecheck/tests/contracts.rs
src/vm/checker/typecheck/tests/mod.rs
src/vm/functions/mod.rs
src/vm/types.rs

This PR:
* Forces all arguments to `eq?` to be of the same type. If they are not, this is a type error. Previously, `eq?` would have just returned `'false`.
* Fixes a bug in `TypeSignature::admits(...)` which would cause a list-type of the same atomic-type as the input to incorrectly return "true"
Addresses #998

`eq?` type enforcement

---

src/clarity.rs

This adds a CLI command to the `local` commands (and the `clarity-cli`) for generating a random Stacks address for testing purposes:
```
$ clarity-cli generate_address
SPGQ9PNGMSN4B5NVZB265FT5BSGZ1Z7T0EMWJBWS
```
Implements #1008

Add random address generation

---

src/vm/docs/mod.rs

This PR:
* Fixes `eq?` in the current docgen
* Adds `define`, `define-map`, `define-read-only`, `define-public` to `vm::docs::make_json_api_reference()`
Resolves Issue #1016 
You can test this either locally or with the built docker image for this branch. For example:
```
$ docker run -it quay.io/blockstack/blockstack-core:feature_add-defines-to-docs blockstack-core docgen
```

Add `defines` to vm::docs

---

src/vm/callables.rs
src/vm/checker/errors.rs
src/vm/checker/typecheck/mod.rs
src/vm/checker/typecheck/natives/mod.rs
src/vm/checker/typecheck/tests/mod.rs
src/vm/contexts.rs
src/vm/contracts.rs
src/vm/database/sqlite.rs
src/vm/docs/mod.rs
src/vm/errors.rs
src/vm/functions/arithmetic.rs
src/vm/functions/boolean.rs
src/vm/functions/database.rs
src/vm/functions/define.rs
src/vm/functions/lists.rs
src/vm/functions/mod.rs
src/vm/functions/options.rs
src/vm/functions/tuples.rs
src/vm/mod.rs
src/vm/parser.rs
src/vm/tests/contracts.rs
src/vm/tests/datamaps.rs
src/vm/tests/defines.rs
src/vm/tests/lists.rs
src/vm/tests/simple_apply_eval.rs
src/vm/types.rs
src/vm/variables.rs

This PR refactors the `vm::errors` types so that they are categorized as:
* Interpreter Errors: these are errors in the interpreter's implementation. they should perhaps be replaced by panics.
* Unchecked Errors: these are errors that should be caught by the TypeChecker before execution. They should only occur when testing the interpreter runtime separately from the TypeChecker.
* Runtime Errors: these are errors that may occur during the execution of a smart contract.
As the codebase matures further, I expect some of those RuntimeErrors to migrate to UncheckedErrors (bad type descriptions, in particular). Additionally, ParserErrors may get their own categorization as well. In general, this PR isn't meant to be the final say in the error handling in the interpreter, but rather a necessary …

Classifying Interpreter Errors

---

circle.yml
src/clarity.rs

This addresses:
1. #1011 as well as other `.expects` usage in the CLI.
2. #1003 
This PR also adds a job to Circle definition to test the CLI against the "okay" executions in the demo markdown.

Friendlier panics

---

sip/sip-002-smart-contract-language.md

This updates the `(tuple ...)` syntax, the response types of public functions, and replaces any mentions of `null` with `none`.

Update SIP-002 with latest syntax

---

src/vm/functions/arithmetic.rs

Remove our own implementation of checked_pow in favor of the supplied routine in rust 1.34.
#919

Remove checked_pow

---

sip/sip-003-peer-network.md

And it was fascinating!
I have a few questions:
> 1.  The sender creates a `GetBlocksInv` message for a range of blocks it wants,
and sends it to the receiver.
How can the range be known, initially? Can you pass a wildcard?
> The Stacks peer network implements a flooding network for blocks and transactions in order to ensure that all peers receive a full copy of the chain state as it arrives on the network.
Is there a specific behavior for the propagation of the transactions, where the goal would probably to hit the miners / validators ASAP?  
As a developer, if I'm running my node, is the propagation of my users' transactions being prioritized (vs relaying)?
> If the data has not been seen before by the peer, and the data is valid, then the peer forwards it to a subset of its neighbors …

Reading SIP 003

---

src/vm/docs/mod.rs

Reimplementing the reference, I found an error in the `mod.rs` file for the Clarity reference.

Fixing incorrect signature

---

sip/sip-005-blocks-and-transactions.md

There's a couple small, and a couple large edits of SIP-005 in this PR:
* Update language used to describe _sending accounts_.
* Add "whitelisting" concept to the post-condition constraints.
Larger:
* Replace netstring encoding of Clarity values with the JSON schema.
* Add sections (with "todos") for encoding Clarity type signatures and Clarity code bodies
* Alter the description of stored data and metadata for contracts -- contract metadata must include their defined function bodies. Contract data must _also_ include the contract's defined asset types. NFTs could not be efficiently implemented the way it is currently described in the sip/sip-005 draft (where that data is associated with the owner of the NFT's account data, rather than a key computed via the contract name and NFT key).

Edits on SIP-005

---

src/chainstate/stacks/index/marf.rs
src/chainstate/stacks/index/storage.rs
src/clarity.rs
src/vm/analysis/mod.rs
src/vm/ast/mod.rs
src/vm/clarity.rs
src/vm/contexts.rs
src/vm/contracts.rs
src/vm/database/key_value_wrapper.rs
src/vm/database/marf.rs
src/vm/database/mod.rs
src/vm/database/sqlite.rs
src/vm/errors.rs
src/vm/mod.rs
src/vm/tests/contracts.rs
src/vm/tests/forking.rs

Provide a high-level interface for interacting with Clarity:
`vm::clarity::ClarityInstance`:
This struct owns a MARF connection. To begin interacting with the Clarity VM, you call `begin_block` on this struct, which begins a new block, and returns a `ClarityBlockConnection`
`vm::clarity::ClarityBlockConnection`:
This struct is used for interactions within a single block and must be either committed or rolled back before any other block can be started from the parent `ClarityInstance`. It exposes:
* analyze_smart_contract
* initialize_smart_contract
* save_analysis
* run_contract_call
And:
* rollback_block
* commit_block
Both of which consume the instance.

High level Clarity interface

---

src/vm/docs/mod.rs

See some small mistakes in the Clarity reference dos in terms of formatting. This is a fix.

Update clarity reference docs

---

circle.yml
src/clarity.rs

This PR is addressing an issue raised by @moxiegirl, where the eval command is expecting a contract-name instead of a contract-id.

Eval command should be expecting contract-id

---

api/server.py

This changes the cache-control setting for `/v1/info` from the default (which I think is 1800) to 30 seconds (in line with the consensus hash).
You can test this by starting up the API service (`./api/server.py`) with blockstack-core, and curling `/v1/info`

Set low cache-control policy for v1/info

---

src/vm/callables.rs
src/vm/tests/defines.rs

This patch ensures that the interpreter will throw a CheckedError when a defined function is passed a non-exact argument match. Previously, it allowed extra arguments (which would go unused) to be supplied.

Check exact argument length in defined functions

---

src/util/macros.rs
src/vm/analysis/errors.rs
src/vm/errors.rs
src/vm/representations.rs
src/vm/types/mod.rs
src/vm/types/serialization.rs

This implements a more compact Clarity value serialization:
All values have a 1-byte header indicating the type:
```
00 => int
01 => uint
02 => buff
03 => bool (true)
04 => bool (false)
05 => principal (standard)
06 => principal (contract)
07 => response (ok)
08 => response (err)
09 => optional (none)
10 => optional (some)
11 => list
12 => tuple
```
* `int` and `uint` types are followed by the big endian encoding of the 128-bit integer.
* `buff` types are followed by a 4-byte big endian length, and then the byte data.
* `bool` and `none` values are represented with only the 1-byte header.
* standard `principal`s are followed by a 1-byte version and 20-bytes of address data.
* contract `principal`s are followed by a standard principal, a 1-byte length for the contract name, and then the …

More compact Clarity value serialization

---

setup.py

This forces cachetools 2.0.0 to be installed.  Cachetools 4.0.0 (currently the latest) is incompatible with Python 2.

require cachetools 2.0.0

---

src/vm/mod.rs
src/vm/types/serialization.rs

This resolves some simple OOM issues in Value deserialize (#1276) by checking that the length is less than the Clarity max value size. This only solves OOM issues within a single iteration. Recursive calls in `deserialize_read` can cause other issues, which will be resolved in a subsequent PR.
This PR also fixes an ordering bug in the stack depth check in `vm::eval` -- argument evaluation must count against the stack depth limit.
Tests are provided for both fixes.

Resolve OOM issue in value deserialize: #1276

---

src/vm/contexts.rs

Per #1280 -- the answer is yes, we can remove ordered_map from the Clarity metadata serialization, since that metadata is no longer included in the MARF commitment. This PR removes that code.

#1280: Ordered Map No Longer Required

---

sip/sip-001-burn-election.md

Now that we have PoX, this PR removes "tunable proofs" as a concept from SIP 001.  Instead, it only describes proof of burn mining.

SIP 001 Updates

---

sip/sip-007-stacking-consensus.md

Add delegation section to SIP-007

feat: add delegation to sip-007

---

sip/sip-005-blocks-and-transactions.md

Update SIP-005 to reflect removal of fungible and non-fungible asset transfers from token transfer payloads.

Remove non-STX asset transfer from SIP-005

---

README.md

In addition to #1328, fixes a few links that were still referencing the old repo. Also updated first sentence based on title of whitepaper.

Replace blockstack-core with stacks-blockchain part 2

---

src/vm/ast/definition_sorter/tests.rs
src/vm/ast/expression_identifier/mod.rs
src/vm/ast/mod.rs
src/vm/ast/sugar_expander/mod.rs
src/vm/representations.rs

Because the sugar expander can create new AST nodes, the expression identifier needs to run a second time after the sugar expansion.

Fix: correct expression id labeling post-sugar-expansion

---

src/chainstate/stacks/auth.rs
src/chainstate/stacks/block.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/headers.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/miner.rs
src/chainstate/stacks/mod.rs
src/chainstate/stacks/transaction.rs
src/core/mempool.rs
src/core/mod.rs
src/testnet/node.rs
src/testnet/run_loop.rs
src/util/db.rs
src/util/retry.rs
src/vm/analysis/analysis_db.rs
src/vm/clarity.rs
src/vm/database/marf.rs
src/vm/mod.rs
src/vm/tests/integrations.rs
src/vm/tests/mod.rs
src/vm/types/mod.rs

This PR implements admission checks for transactions into the mempool.
Transactions are checked to ensure they:
1. Parse correctly
2. Have paid fees
3. Paying accounts have enough funds for stacks transfers and fees
4. Nonces are correct (note: this precludes replace-by-fee for the moment)
5. Payload specific checks (e.g., ContractAlreadyExists for publishes)
These checks _require_ querying chainstate. To this end, there was some refactoring to allow the checking code to use a read-only Clarity database connection.

Mempool Admission Checks

---

circle.yml

This fixes a bug in our CI caused by an unmet dependency for grcov (our code coverage tool).

fix: add package required for latest grcov

---

src/blockstack_cli.rs

This PR
* changes the output of `blockstack-cli generate-sk` to valid JSON
* fixes #1366

Generate valid json in blockstack-cli generate-sk

---

src/vm/docs/mod.rs

This PR
* corrects an example in the documentation, replacing `eq? ` by `is-eq`

Replace eq? with is-eq in example

---

src/vm/docs/mod.rs

This PR
* corrects examples in the documentation, replacing `define` by `define-private`. `define` has been removed.

Replace `define` by `define-private` in documentation

---

src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/events.rs
src/testnet/helium/event_dispatcher.rs
src/vm/analysis/type_checker/contexts.rs
src/vm/analysis/types.rs
src/vm/costs/mod.rs

Part of https://github.com/blockstack/stacks-blockchain/issues/1266
Adds the contract ABI JSON to sidecar messages for deploy-contract tx types

feat: include contract ABI JSON in sidecar tx msg

---

sample-programs/tokens-mint.clar
src/clarity.rs

I learned that `clarity-cli eval` will advance to a new block. Testing certain scenarios required me to evaluate queries that wouldn't advance the chaintip. So, I added this, thanks to @jcnelson 's tip.
I tried to abstract some of the `eval` logic to be a little bit DRY, but there is still a good bit of repetition. The only real change is to use `at_chaintip` instead of `at_block`. I would love to see how someone with more Rust experience would do this - I mainly didn't know how to separate the proc into something reusable.

feat: add eval_at_chaintip to clarity-cli

---

Cargo.toml
benches/large_contract_bench.rs
src/util/hash.rs
src/vm/database/marf.rs

While poking around the large_contracts::rollback_log_memory_test trying to figure out some good estimates for initial block limits, I profiled the optimized version of that code. It turned out to be spending 90% of its time in `to_hex()`, so I tried to optimize that function a little bit using a with_capacity allocation and `write!`.
Before:
```
$ cargo bench --no-run
....
$ time ./target/release/large_contract_bench-386d9fe25a932f3f rollback
Gnuplot not found, disabling plotting
Testing rollback_log_memory_test
Success
Gnuplot not found, disabling plotting
real	0m17.965s
user	0m17.458s
sys	0m0.484s
```
After:
```
$ cargo bench --no-run
....
$ time ./target/release/large_contract_bench-386d9fe25a932f3f rollback
Gnuplot not found, disabling plotting
Testing rollback_log_memory_test …
```

Faster and less mallocing to_hex()

---

src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/contracts.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/miner.rs
src/core/mempool.rs
src/testnet/helium/tests.rs
src/vm/analysis/analysis_db.rs
src/vm/analysis/tests/costs.rs
src/vm/clarity.rs
src/vm/contexts.rs
src/vm/database/clarity_db.rs
src/vm/database/key_value_wrapper.rs
src/vm/database/mod.rs
src/vm/tests/contracts.rs
src/vm/tests/integrations.rs
src/vm/tests/large_contract.rs

This addresses #1376, by adding a third struct to vm::clarity -- `ClarityTransactionConnection` -- the three structs in vm::clarity correspond to:
1. ClarityInstance -- a struct that lives across blocks.
2. ClarityBlockConnection -- a struct for a single block. Aborts/commits operate on the whole block.
3. ClarityTransactionConnection -- a struct for a single transaction within a block. Aborts/commits operate on the whole transaction.
processTransaction and processTransactionPayload have been updated to use ClarityTransactionConnection. Tests are added for the transaction rollback functionality (and tests which previously required aspects to be commented out due to #1376 have had those parts uncommented).
While editing db::transactions, I also cleared out the compiler warnings from …

Enable TX-level rollbacks in Clarity connections

---

src/net/chat.rs
src/net/download.rs
src/net/neighbors.rs
src/net/p2p.rs
src/net/poll.rs
src/net/server.rs

This fixes #1416 and #1423.  Now, calling `PeerNetwork::run()` will poll readiness on both the p2p and http server sockets and their clients.  Interacting with the RESTful API should be noticeably faster.

Unified net server socket polling

---

src/net/http.rs
src/net/mod.rs

Fixes problems @zone117x was seeing when using the node with a forward proxy.

Support up to 64 HTTP headers

---

src/chainstate/burn/db/burndb.rs
src/chainstate/stacks/db/blocks.rs
src/net/relay.rs
testnet/src/neon_node.rs

The Neon miner would begin sending bad commits if a sortition was missed and never recover.
This behavior can be tested by just generating a bunch of bitcoin blocks locally after a few successful sortitions.
```
$ bitcoin-cli -datadir=$PWD -conf=$PWD/bitcoin.conf generatetoaddress 10 ...
```
The issue was caused by the Neon node incorrectly generating block commits.

Fix Neon miner's block commits

---

Dockerfile
testnet/conf/local-follower-conf.toml
testnet/conf/local-leader-conf.toml
testnet/src/tests/mod.rs

The `bitcoin-neon-controller` has also been updated and now includes a conf matching these ones.
Steps:
- run `bitcoind`, assuming the following config:
```
disablewallet=0
txindex=1
chain=regtest
server=1
rpcuser=helium-node
rpcpassword=secret
```
- run bitcoin-neon-controller with `cargo run local-leader.toml.default`
- run `cargo testnet start --config testnet/conf/local-leader-conf.toml`
- run `cargo testnet start --config testnet/conf/local-follower-conf.toml`

Resolve local leader / local follower config discrepancies

---

sip/sip-005-blocks-and-transactions.md

This resolves #1491 -- the description of NFT Post-Conditions in SIP-005 was incorrect. NFT names are serialized using the Clarity value serialization.

Correct the description of post-conditions in SIP-005

---

testnet/conf/local-follower-conf.toml
testnet/conf/local-second-miner.toml
testnet/src/config.rs
testnet/src/neon_node.rs
testnet/src/run_loop/neon.rs

This adds a config setting to direct the neon run_loop to try and initialize the node as a miner or non-miner. It still performs an initial UTXO check, so that you get a fast error in the event that you are trying to mine but haven't gotten any UTXOs.
This PR also improves on the "genesis detection" behavior of a miner -- basically, if a node doesn't have a chain tip, it should try to mine a genesis block.

Neon node configurable as miner/not-miner

---

README.md

This adds a note that libssl source is required for compiling Stacks blockchain on many distros. See  #1501

Readme: add requirement note for libssl

---

docs/rpc-endpoints.md
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/transactions.rs
src/net/http.rs
src/net/mod.rs
src/net/rpc.rs
src/vm/ast/errors.rs
src/vm/clarity.rs
testnet/src/tests/integrations.rs
testnet/src/tests/mempool.rs
testnet/src/tests/mod.rs

This addresses #1430 by making the `reason` field a well-defined set of strings, and making `reason_data` provide structured error data.
This also makes the "ok" response a JSON string, so that the `/v2/transactions` result is more in line with the other RPC endpoint responses (which are otherwise all JSON).

/v2/transactions HTTP improvements

---

testnet/src/tenure.rs
testnet/src/tests/integrations.rs

This fixes previously bad mempool polling behavior (it would only obtain TXs accepted at exactly the current chain tip).
One test needed to be modified because of this change (it relied on the exact order of attempted applications from the block builder)

Mocknet to use StacksBlockBuilder::build_anchored_block 

---

src/blockstack_cli.rs
src/clarity.rs
src/net/mod.rs

These are two CLI commands that are helpful when debugging issues on testnet:
`blockstack-cli deserialize-tx`
```
$ TX=80800000000400ac4c9ee4b46177277081ba8f9494bde950b8a021000000000000000000000000000000010000721047d6db33d19ec889e4d7806cc51fab30f064311eeaed6d5555a0d5b3fb2b37b30426001325314a797cb8593a307d77fceaf53f5e02f015a053f4ff7ccf6e03020000000000051a79f327494e237a5fa36a43f88b033c365acd136e00000000000003e800000000000000000000000000000000000000000000000000000000000000000000
$ echo $TX | blockstack-cli deserialize-tx
Origin Address: SP2P4S7Q4PHGQE9VGG6X8Z54MQQMN1E50455MMT7Q (main) / ST2P4S7Q4PHGQE9VGG6X8Z54MQQMN1E5047ZHVAF7 (test)
Nonce: 0
TokenTransfer(Standard(StandardPrincipalData(26, [121, 243, 39, 73, 78, 35, 122, 95, 163, 106, 67, 248, 139, 3, 60, 54, 90, 205, 19, 110])), 1000, …
```

Some helpful debugging tools

---

Dockerfile
testnet/bitcoin-neon-controller/Dockerfile

Requested by devops. Also simplifies a bunch of glibc lib curls in the `bitcoin-neon-controller` dockerfile.

Use alpine in primary docker image

---

src/burnchains/burnchain.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/neon.rs

Adding some high level logs so that testnet participations can be visible upfront.
Include a minor miner experience enhancement - we're now hitting the listunspent endpoint before the block syncing, so that you can terminate your node / hit the faucet / restart the node without having to wait for the sync, when you're out of UTXOs.

Additional logs

---

testnet/bitcoin-neon-controller/Cargo.toml
testnet/bitcoin-neon-controller/config.toml.default
testnet/bitcoin-neon-controller/local-leader.toml.default
testnet/bitcoin-neon-controller/src/main.rs

Per devx request, the faucet is using 2 additional RPC methods that needs to be whitelisted.
This will be a config from now on - we should not have to recompile the project for updating the whitelist.

BTC Faucet support

---

src/vm/docs/mod.rs

This PR
* fixes the length parameter in calls to `as-max-length?`

[docs] as-max-length? use uint, not int

---

src/vm/docs/mod.rs
src/vm/functions/iterables.rs
src/vm/tests/contracts.rs
src/vm/types/signatures.rs

`as-max-len` needs to update the returned iterable's runtime type.

Fix #1591: as-max-len should update runtime type annotation

---

src/vm/analysis/type_checker/tests/mod.rs
src/vm/ast/definition_sorter/mod.rs
testnet/bitcoin-neon-controller/Cargo.toml

This resolves #1625 by fixing a bug in `vm::ast::definition_sorter` --- tuple constructors weren't parsed correctly when probing for dependencies (they need to look for lists of pairs, but the previous code was looking for lists of lists of pairs).

Fix: Detecting dependencies in tuple constructors

---

Cargo.toml
src/lib.rs
src/net/http.rs
testnet/stacks-node/src/tests/integrations.rs

This adds percent-decoding to the RPC request handler --
This is necessary for resolving #1622 (from the stacks-blockchain node's perspective -- separately, clarity-js-sdk will need to add support for encoding this URL).

Percent decode URL paths in RPC requests

---

src/chainstate/stacks/address.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/events.rs
src/vm/clarity.rs
src/vm/tests/large_contract.rs
testnet/stacks-node/src/event_dispatcher.rs

This PR addresses:
#1608, #1609, #1568
By doing the following:
1. Adding a new Error type to the clarity::Error enum for the event that a post condition callback aborted a transaction.
2. Modifying the TransactionReceipt struct to include a `post_condition_aborted` boolean for tracking whether or not a transaction which would have otherwise succeeded was aborted due to a PostCondition
3. Replacing `success` with `status` in `"transactions"` events. This field can (for now), take one of three values:
a. "success" -- the transaction succeeded and was committed.
b. "abort_by_response" -- the transaction did not succeed, because the transaction was aborted during its execution (e.g., the `contract-call` returned `(err foo)`).
c. "abort_by_post_condition" -- the transaction would have …

PostCondition handling in TransactionReceipts

---

testnet/bitcoin-neon-controller/Cargo.toml
testnet/bitcoin-neon-controller/src/main.rs

With this PR, we should have a graceful boot sequence, event if the stacks-node is booting the bitcoin-controller, and the bitcoin-controller booting before the bitcoin chain (tested locally).
Since we already have a backoff implemented in the `get_utxo` method, the only changes required are at the bitcoin-neon-controller.

Fix boot sequence

---

docs/event-dispatcher.md
src/burnchains/burnchain.rs
src/chainstate/burn/mod.rs
src/chainstate/stacks/db/blocks.rs
src/net/mod.rs
src/net/p2p.rs
src/net/relay.rs
src/net/rpc.rs
src/net/server.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This implements #1547 and #1653:
1. It requires a new event observer endpoint for mempool transactions. Previously the event dispatcher just posted to a single endpoint, now there are two endpoints:
a. `/new_block`, which POSTs the same JSON object it previously posted to the root.
b. `/new_mempool_tx` which POSTs a JSON array containing new raw transactions.
2. It adds a `parent_index_block_hash` field to the "new block" JSON object.
3. It adds support for integration testing the event dispatcher in `neon_integrations.rs` -- this uses `warp` as the test event observer.

Event Dispatcher: Mempool txs events + parent_index_block_hash

---

src/vm/analysis/trait_checker/tests.rs
src/vm/analysis/type_checker/mod.rs
src/vm/tests/traits.rs

This PR is addressing #1621, by allowing trait inference when a principal is being passed (as a literal) to a user defined function.

Relax trait inference

---

.github/actions/docsgen/Dockerfile.docsgen
.github/workflows/docs-pr.yml
src/net/connection.rs
src/vm/docs/mod.rs
src/vm/functions/options.rs
src/vm/tests/simple_apply_eval.rs

While working on porting over examples to support moving the `u` prefix to a suffix (see, #1669), it occurred to me that it wouldn't be _too_ hard to get the docs examples to actually get tested. This PR implements that, separately from the implementation of #1669 (since that's going to be a pretty large breaking change, that should get staged before making it into our main branch), as there's definitely benefit to be had from just adding this functionality.
This PR:
1. Fixes an implementation bug discovered via the examples -- `try!` was yielding the inner error type, rather than a `(err ...)` object.
2. Adds self-testing docs, by setting up a docs-specific environment for executing the examples. If we want to integrate a sandbox into the docs-site at some point, we can set up the …

Self-Testing Clarity Docs + Fix try! bug

---

.github/workflows/docs-pr.yml

I fat finger merged the github action with the repo I was using for testing. This patch corrects that.

Fix: Github action: open PR against the _correct_ docs.blockstack repository

---

src/clarity.rs

To support this issue in clarity-js-sdk: https://github.com/blockstack/clarity-js-sdk/issues/77

Feature: allow specifying initial stx balances with clarity-cli

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/core/mempool.rs
src/lib.rs
src/net/neighbors.rs
src/net/poll.rs
src/vm/analysis/trait_checker/tests.rs
src/vm/clarity.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/mempool.rs

This PR addresses #1686 and #1687 by doing a couple things:
1. Uniqueness changes in the mempool sqlite table -- rather than the unique property being applied to the tuple `(origin_addr, sponsor_addr, origin_nonce, sponsor_nonce)`, it is now unique in each of:
a. `txid`
b. `(origin_addr, origin_nonce)`
c. `(sponsor_addr, sponsor_nonce)`
2. Replace-by-fee logic just looks at the address and nonce, regardless of the fork.
3. The mempool also allows "replace across fork" -- if prior transaction `tx'` is in a different fork than the candidate transaction `tx`, then it allows the replace in all cases.
4. Allow transaction chaining up to depth 5
It also includes a nicety for compiler warnings in our test builds:
```
#![cfg_attr(test, allow(unused_variables, unused_assignments))]
```

Some nonce fixes

---

testnet/bitcoin-neon-controller/src/main.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/neon_integrations.rs

I should have clicked with this feedback: https://github.com/blockstack/stacks-blockchain/pull/1718#discussion_r450489368
Since we are creating the connection manually:
```rust
let stream = match TcpStream::connect(self.endpoint.clone())
```
We don't want to suffix the endpoint with `/` anymore, and we should produce a parsing error when such a value is provided in the settings (mimicking the behaviour of `rpc_bind`, `p2p_bind`, `prometheus_bind`).
This PR is fixing this.
While testing this PR with a local sidecar, I noticed that the `Content-type` header was being added twice:
```
POST /new_block HTTP/1.1
host: 127.0.0.1:3000
content-length: 979
date: Tue, 07 Jul 2020 03:50:10 GMT
content-type: application/json
content-length: 979
```
This PR is also addressing this issue.

Fixes on event dispatcher

---

sip/sip-004-materialized-view.md
sip/sip-005-blocks-and-transactions.md

Very interesting and useful read.  I learned a lot by reading in details, and will probably need to re-read many times...  Thank you for writing these SIPs, it helps in understanding the code further and how things are supposed to work.
I do have one question on https://github.com/psq/stacks-blockchain/blob/sip/sip-typos-2/sip/sip-005-blocks-and-transactions.md#calculating-the-state-of-an-account
instead of being just a `c32check-encoded address`, shouldn't this be either that, or a contract address, as contract can have balances as well.  Plus the implementation of `make_key_for_account` takes a `PrincipalData`, which supports both types.

a few more typos for sip-004 and sip-005

---

Dockerfile
testnet/stacks-node/src/monitoring/mod.rs
testnet/stacks-node/src/monitoring/prometheus.rs

The command currently being used for building a stacks-node with prometheus support: 
```
cargo build --features "monitoring_prom" --release --target x86_64-unknown-linux-musl --workspace=./
```
is compiling the stacks lib with the `monitoring_prom` feature flag, but not cascading the flag to the `stacks-node` target.
As a result, when using this command, the code from the `stacks` lib behind the feature gate was included in the build, however the code in `stacks-node` behind the feature gate, was not checked / compiled / included. 
This PR is addressing this issue by revisiting the build procedure. 
A docker build (http://hub.docker.com/repository/docker/ludovic/stacks-node) was produced using the Dockerfile from this PR, and used for spawning a new follower in the `neon-staging` …

Update Dockerfile to produce a stacks-node bin with monitoring enabled

---

src/net/connection.rs
src/net/http.rs
src/net/mod.rs
src/net/rpc.rs
testnet/stacks-node/src/tests/integrations.rs

Previously, if the RPC handler failed while parsing a request from HTTP to a RequestType, the RPC server would return 400 and an empty HTTP body. This led to some not very friendly error messages (e.g., #1703)
This PR adds a test for that case, as well as introducing an error handling scheme for cases like these (currently only used for deserialization errors and 404s).
This change is relatively straight-forward, though there's one tricky part -- the StacksHttp::read_payload error handling needs to return to its caller as if it read the full content-length of the socket. Without that, the RPC server would continue reading the prior request's body when trying to process a subsequent request on the same socket.

Nicer RPC deserialization errors

---

src/vm/docs/mod.rs

Working on the new docs, this line caused an issue with rendering the content of the reference descriptions, it thought that <trait-alias> was a JSX element. This PR wraps that so it will render as inline-code.

fix: wrap <trait-alias> as code in description

---

src/chainstate/stacks/index/marf.rs
src/chainstate/stacks/index/storage.rs

This corrects an error in the MARF storage that would lead to invalid states -- `trie_ancestor_hash_bytes_cache` needs to be cleared whenever there is a change in the open block (whether it is flushed, dropped, or extended).

Fix `trie_ancestor_hash_bytes_cache` usage in MARF

---

sip/sip-007-stacking-consensus.md

1/400th would make it so that you reduce by 25% every 100 reward cycles, making it 0.5 (50%) over 200 cycles

fix reward decrease ratio per cycle

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/miner.rs

This is a  possible implementation of the `withdraw reward` functionality for the `miner-rewards` contract.  It also removes the `authorized` part as discussed with @jcnelson via discord.
Unexpectedly, meaning I had originally not thought that part through, for the contract to be able to disburse STX to miners, not only does the reward code need to update the amount `available` for a given miner, it also needs to credit the contract with the corresponding STX so the contract can transfer them when requested.  Would there be a different way to approach this?
Also, having a miner withdraw by sending a transaction, if that miner also mines the block, will mean we have 2 transactions for the same address in a block, and the admission checks in `mempool.submit` will fail if you send in the …

implement withdraw-reward

---

testnet/stacks-node/src/neon_node.rs

The check for winning a sortition needs to check:
1. That the Stacks block hashes are the same
2. That the latest burn block the miner saw when the block commit was produced is the _parent_ of the sortition in which the block won.
This PR updates the check to perform (2) using the parent burn header hash (the parent consensus hash isn't available for this check). In the event that a PoX fork causes the same block hash to win the sortition in different PoX forks, this will just lead the miner to attempt to mine it's own now invalid block, which should be ultimately okay.

Fix: #1786, check should be mined_block.parent = miner's latest view

---

src/vm/analysis/trait_checker/tests.rs
src/vm/functions/database.rs
src/vm/functions/mod.rs
src/vm/tests/traits.rs

Address https://github.com/blockstack/stacks-blockchain/issues/1815
When optimising for O(1) retrieval in https://github.com/blockstack/stacks-blockchain/pull/1644/commits/084ec6e3222e1ad5bd8c44775484acdfc79b6323, I should have cascade the fact that the `lookup_callable_contract ` method should be used, instead of accessing the hashmap directly.

Fix trait lookup

---

src/chainstate/stacks/db/blocks.rs
src/vm/analysis/type_checker/mod.rs
src/vm/functions/database.rs
src/vm/functions/mod.rs
src/vm/types/signatures.rs
testnet/stacks-node/src/tests/mempool.rs

Fix https://github.com/blockstack/stacks-transactions-js/issues/92
The current code is obviously not enough as it would need to check that `other` is a `PrincipalType` that implements the trait.
Anything else that should be checked?  Is this opening the door for other potential problems when it should not return `true` for a `TraitReferenceType`?  And is `other == self` also a valid case for a `TraitReferenceType`?  I would think so.
Any suggestion on how to write tests for this, except by calling `admits_type` directly with various combinations?  I'm also curious why the fix done for https://github.com/blockstack/stacks-blockchain/pull/1679 would not address this case?
The full fix also requires https://github.com/blockstack/stacks-blockchain/pull/1817 from @lgalabru.

fix for clarity-transaction-js-92

---

src/vm/costs/mod.rs

tiny PR fixing a typo in the comment above the `LogN` cost assessment function

fix: typo in LogN cost function comment

---

src/burnchains/burnchain.rs
src/burnchains/mod.rs
src/net/mod.rs
src/net/rpc.rs
testnet/stacks-node/conf/krypton-follower-conf.toml
testnet/stacks-node/src/config.rs

Additional adjustments:
- https://github.com/blockstack/stacks-blockchain/issues/1882

Krypton deployment + adjustments

---

circle.yml
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox-mainnet.clar
src/chainstate/stacks/boot/pox-testnet.clar
src/chainstate/stacks/boot/pox.clar
src/chainstate/stacks/db/mod.rs
src/net/mod.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This addresses a few things:
1. `chainstate.get_reward_addresses` needs to take the current burnchain block height as an additional argument. The reward cycle being queried is the current block height, even though it is evaluated at the anchor block.
2. The default constants in the `pox.clar` change depending on the mainnet flag. I think this could be DRY'd a bit with the Burnchain config object, but I think we can leave that to a future issue (will open an issue for that).
3. The reward set is sorted by address. This ensures that every node has the same ordering of the reward set (resolving #1860).
This also adds a new bitcoind integration test for PoX which sets up an address, issues a contract call to the pox contract and checks that the registered address receives BTC after the …

PoX Krypton Fixes

---

src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox-mainnet.clar
src/chainstate/stacks/boot/pox-testnet.clar
src/chainstate/stacks/boot/pox.clar
src/chainstate/stacks/events.rs
src/net/http.rs
src/net/mod.rs
src/net/rpc.rs
src/vm/contexts.rs
src/vm/functions/special.rs
testnet/stacks-node/src/event_dispatcher.rs

This PR is addressing 3 requests coming from Devx:
- Mechanism to let the sidecar know that a transaction stacked some STX: this PR is introducing some events `STXLockEvent`, emitted when locking is happening
- Ability to discover PoX parameters: this PR is introducing a new RPC endpoint `v2/pox`, returning the following:
```json
{
"contract_id": "ST000000000000000000002AMW42H.pox",
"first_burnchain_block_height": 0,
"min_amount_ustx": 150000000000,
"registration_window_length": 250,
"rejection_fraction": 25,
"reward_cycle_id": 0,
"reward_cycle_length": 1000
}
```
- Ability to confirm that a user is eligible to PoX: the readonly method `can-stack-stx` is now centralizing all the guard conditions evaluated when `stack-stx` was being called, to make sure that we have the same behavior.

PoX adjustments for Devx

---

src/net/p2p.rs
src/net/poll.rs

This should cause the follower node to _not_ freeze up after a few hours.

Fix event ID resource leak for connecting sockets that time out

---

Cargo.toml
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
testnet/stacks-node/Cargo.toml

This adds a compile-enabled feature for storing to a table a copy of the transaction ID and transaction data whenever a transaction is processed. This lets you figure out whether or not a particular TXID was processed, and if so, what the result of it was.
```
$  cargo build --workspace --features tx_log
$ ./target/debug/stacks-node krypton
```
And then to find a transaction...
```
$ echo 'SELECT index_block_hash, result FROM transactions WHERE txid = "9e4ef900f521dd7c07c1c22e4b58b33df656880c8035bdb5e2b0c44ba8356af6"' | sqlite3 -separator ", " /tmp/stacks-testnet-f7c1618951418340/chainstate/chain-00000080-testnet/vm/index
87cbab207957c48bcb5b56943b26ef78c30ae4d6110dbdc7af21b9d93ca3946d, (ok true)
```

Feature: Store all transactions as they are processed for debugging

---

src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox.clar
src/chainstate/stacks/transaction.rs
src/clarity.rs
src/net/neighbors.rs
src/vm/analysis/errors.rs
src/vm/analysis/read_only_checker/mod.rs
src/vm/functions/special.rs
src/vm/tests/mod.rs

This PR adds delegation and pooling support to the pox contract. It does so by adding four public methods:
* `delegate-stx` - This method creates a delegation relationship between the sender and the designated principal. This _does not_ lock the corresponding STX. Rather, it allows the designated principal to perform the lock, subject to the constraints of the sender:
* a maximum amount the delegator is allowed to lock and stack
* optional reward address that must be used
* optional expiration burn block height
* `revoke-delegate-stx` - This method allows the sender to revoke their designated delegator
* `delegator-stack-stx` - This method is called by a delegator to _lock_ a single stacker's STX, _but does not_ add the pox-addr to the reward cycles. Rather, when invoked, it adds the …

PoX Delegation / Pooling

---

src/burnchains/mod.rs
src/chainstate/coordinator/mod.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox.clar
src/chainstate/stacks/db/headers.rs
src/core/mod.rs
src/net/neighbors.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/syncctl.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR implements a few different things:
1. It implements the threshold adjustment described in SIP-007 (#1947)
2. When a Stacker reward address uses _more_ than the threshold, the address is repeated in the reward set (#1924)
3. The chains coordinator, when booting the node, executes `set-burnchain-parameters` on the PoX contract.
4. To speed up the integration tests in the `stacks-node`, this parameterizes the wait time in the syncctl module.
The implementations of 1 and 2 are tested via unit tests, as well as some integration paths in the `pox` test in `neon_integrations` (which also tests 3).

PoX: Threshold Adjustment and Reward Address Repetition

---

src/burnchains/mod.rs
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox.clar
src/net/inv.rs
src/net/mod.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR implements #1897, by adding `burn-block-ht` parameters to `stack-stx` and `delegate-stack-stx`, which must correspond to the next reward cycle (this parameter ensures that the transaction could not be replayed in a Stacks fork occurring at a much later burn block). Further, this PR requires that PoX participation cross a threshold before activation.
Closing #1897

PoX: Enforce anchor block recency with burn-block-height parameter

---

.github/actions/docsgen/Dockerfile.docsgen
.github/workflows/docs-pr.yml
src/main.rs
src/vm/docs/contracts.rs
src/vm/docs/mod.rs

This PR adds `vm::docs::contracts`, which supports (somewhat) auto-generating JSON documentation for boot code contracts. Currently, this is just documentation for the `pox.clar` contract.
It does this by:
* generating a signature, input, and output types from the type checker for public and read-only functions
* evaluating any error code constants to generate error code documentation
* requiring a "description" for each published public and read-only function defined
This also adds the new JSON documentation to the PR robot (as well as changing the PR robot's git email address so that it can sign the CLA).

Auto-generation of PoX contract docs

---

.github/actions/bitcoin-int-tests/Dockerfile.net-tests
net-test/bin/faucet.sh
net-test/bin/start.sh

This adds a Dockerfile that can run the net-test scripts, as well as adding more 500 logging to the faucet, and a fallbackfee option to bitcoind (this was necessary to run for me: bitcoind was consistently failing to estimate fees otherwise).

Add Dockerfile that can run net-test scripts

---

sip/sip-007-stacking-consensus.md
src/burnchains/burnchain.rs
src/burnchains/mod.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/mod.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/address.rs
src/chainstate/stacks/boot/mod.rs
src/net/mod.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR changes `OUTPUTS_PER_COMMIT` to 2.
This requires that all commitments, regardless of whether or not they were burn commitments, have `OUTPUTS_PER_COMMIT` outputs (i.e., if intending to burn, then the tx would require 2 burn outputs).

PoX: Two reward addresses per block

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This adds:
`burn_block_hash`
`burn_block_height`
`miner_txid`
To the block events sent out via the event_dispatcher.

#1950 - add burn block info to events

---

testnet/stacks-node/src/config.rs

With the number of PoX outputs increasing, the default burn cap has to increase to clear the dust UTXO limit.

Fix: set default burn cap for multiple commits

---

Cargo.lock
Cargo.toml
Dockerfile
Dockerfile.stretch
src/blockstack_cli.rs
src/chainstate/stacks/index/marf.rs
src/clarity_cli.rs
src/lib.rs
src/main.rs
src/util/log.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/main.rs

This PR does an initial port of our logging macros to [slog](https://github.com/slog-rs/slog). This allows us to add key-value pairs to our logs which could be parsed immediately by tools like kibana. Eventually, we could also support scoped/contextual logging, which would allow us to filter logs from different subsystems (e.g., logs from the net module could have a different logging backend), and out-of-thread logging which could improve performance when logging lots of data. This would also allow us to plug into syslog if we wanted to do that.
The only potential downside here is that this does involve including a few crates from `slog-rs`, and there's a fair bit of code there. This could _perhaps_ be remedied by something like a feature gate, but that would require that we implement a …

Discussion: Structured logging via `slog`

---

Cargo.toml
src/util/log.rs
testnet/stacks-node/Cargo.toml

This re-enables debug logs in release builds (slog uses rust's debug-assertions by default to turn off debug logs during release builds).

fix: enable debug logs in release build

---

sip/sip-007-stacking-consensus.md
src/burnchains/bitcoin/blocks.rs
src/burnchains/bitcoin/mod.rs
src/burnchains/burnchain.rs
src/burnchains/db.rs
src/burnchains/mod.rs
src/chainstate/burn/db/processing.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/distribution.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/burn/operations/leader_key_register.rs
src/chainstate/burn/operations/mod.rs
src/chainstate/burn/operations/user_burn_support.rs
src/chainstate/burn/sortition.rs
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/block.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/miner.rs
src/core/mod.rs
src/net/inv.rs
src/net/mod.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR implements the sunset phase of PoX, per the description in SIP-007.
In particular:
* [Before Sunset](https://en.wikipedia.org/wiki/Before_Sunset) - everything here behaves the same as before -- there are 2 commit outputs required for every block commit, selected using the PoX anchor block logic.
* After sunset begin, Before sunset end - an additional output is required in each block commit. This output is the "sunset burn", and it must be greater than the required sunset ratio (described in SIP-007: for each reward cycle during the sunset phase, the sunset burn ratio must be > the progress percentage through the sunset phase).
* After sunset end - the first output of the block commit must be a burn output, and it is the only output counted in the block commit
This is tested with …

PoX Sunsetting

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

Fixes #2010.  Current calculation overpays by a factor of 2048 (should use `attempt-1` as multiplier, and fee is per kb, not per byte

fix rbf calculation - fixes #2010

---

src/vm/docs/mod.rs

As a developer, I want to know how to create a tuple in clarity. The signature spec and the given example contradict each other.
For details refer to issue https://github.com/blockstack/docs/issues/496
No
Rebuild docs once merged.
No

fix: correct tuple signature

---

deployment/helm/stacks-blockchain/.helmignore
deployment/helm/stacks-blockchain/Chart.yaml
deployment/helm/stacks-blockchain/README.md
deployment/helm/stacks-blockchain/templates/NOTES.txt
deployment/helm/stacks-blockchain/templates/_helpers.tpl
deployment/helm/stacks-blockchain/templates/configmap.yaml
deployment/helm/stacks-blockchain/templates/deployment.yaml
deployment/helm/stacks-blockchain/templates/metrics.yaml
deployment/helm/stacks-blockchain/templates/role.yaml
deployment/helm/stacks-blockchain/templates/rolebinding.yaml
deployment/helm/stacks-blockchain/templates/service.yaml
deployment/helm/stacks-blockchain/templates/serviceaccount.yaml
deployment/helm/stacks-blockchain/templates/tests/test-connection.yaml
deployment/helm/stacks-blockchain/values.yaml

To help make the stacks blockchain as easy as possible to run in a variety of ways, this PR adds a public Helm chart for the community to easily deploy a stacks node to a local or remote Kubernetes cluster.
```bash
brew install minikube helm
minikube start
helm repo add blockstack https://charts.blockstack.xyz
helm repo update
helm install stacks-blockchain blockstack/stacks-blockchain
```
No
Not required, but they will be added afterwards (likely this week as it's docs week)

Add public helm chart

---

src/vm/contexts.rs
src/vm/database/clarity_db.rs
src/vm/database/key_value_wrapper.rs
src/vm/tests/forking.rs

This address #1840 (see the description in that issue, or the added unit test for more information about the prior buggy behavior.
Yes, this is a consensus-breaking change, because it changes Clarity behavior.
No documentation updates needed.
A witnessing unit test for the formerly bad behavior is included here.

Fix: Clarity `(at-block)` behavior

---

docs/event-dispatcher.md
src/chainstate/stacks/events.rs
src/vm/functions/special.rs
testnet/stacks-node/src/event_dispatcher.rs

1. Add event_index for ordering events (the dispatch matrix scrambles the event order).
2. Add `locked_address` field to stx_lock_event
No.
No -- the sample event payload in `event-dispatcher.md` has been updated.

Minor event dispatcher updates

---

src/vm/docs/mod.rs
testnet/stacks-node/src/keychain.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/mempool.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Fix #1934 by mixing the burn block height into the microblock private key rotation. When attempting RBF, don't rotate the private key (this is just to make testing more deterministic).
Bug fix
No
No
These changes are covered in existing tests, and required updating two tests' "find_microblock_key" logic.

Fix 1934: mix burn block height into microblock pubkey

---

README.md

Add `--depth=1` to the `git clone...` instructions. 
Reduces disk usage and network download time by around 80%.

chore: git clone efficiency in readme

---

src/vm/contexts.rs
src/vm/mod.rs
src/vm/tests/simple_apply_eval.rs

Fixes #2053, by waiting until after eval'ing function arguments to put an applied function on the stack. To prevent excessive apply/eval recursion, the call stack needs to track apply-depth in addition to stack depth.
- Bug fix
Yes, this is a consensus breaking change.
This includes a test that witnesses the original issue #2053, which now passes. The apply-depth change is covered by the existing tests:
```
vm::tests::contracts::test_arg_stack_depth
vm::tests::contracts::test_cc_stack_depth
vm::tests::contracts::test_cc_trait_stack_depth
```

Fix: #2053, apply should not add functions to stack while evaling args

---

net-test/bin/txload.sh
src/core/mempool.rs
testnet/stacks-node/src/tests/integrations.rs

Addresses #2009, including making MAXIMUM_MEMPOOL_TX_CHAINING by setting node.max_mempool_tx_chaining in the config file, new default is 25 (from 5)

bump MAXIMUM_MEMPOOL_TX_CHAINING to 25, make it configurable, resolves #2009

---

src/burnchains/burnchain.rs
src/burnchains/mod.rs
src/chainstate/burn/db/processing.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/distribution.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/burn/operations/mod.rs
src/chainstate/burn/sortition.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/block.rs
src/core/mod.rs
src/util/db.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs

This implements mean of min and median block mining #1315.
There's a couple things happening in this PR:
1. Identification of miners is done through UTXO chaining.
2. User burn operations may identify multiple block commits (the prior implementation relied on VRF key validation, which cannot be done before Stacks block reveal)
3. The burn distribution is calculated using a mean of min and median burns over a 6-block window.
- New feature
Yes -- this is a consensus breaking change. Miners _do not_ need to change their behavior, though doing so would probably be advantageous.
There's unit test coverage for the new implementation of `BurnSamplePoint::make_min_median_distribution`. Integration with the sortdb / burnchain processing code is covered by existing integration tests (the …

#1315: Min/Median Block Mining

---

testnet/stacks-node/src/config.rs

Fixing
```bash
stacks-node xenon
```
so we have a one-liner for spinning up a follower node running on Xenon

Fix URL for simple follower mode

---

.github/workflows/clarity-js-sdk-pr.yml

Adds a new GH Action workflow which creates a PR in the clarity-js-sdk repo to update the [clarity-native-bin tag reference](https://github.com/blockstack/clarity-js-sdk/blob/master/packages/clarity-native-bin/src/index.ts#L12) in source code. This GH action will run anytime a new release is published, so it should automatically hook into our current release process through the [stacks-blockchain GH workflow](https://github.com/blockstack/stacks-blockchain/actions?query=workflow%3Astacks-blockchain).
The PR created will be auto-assigned to @hstove and @zone117x, and will need to be approved & merged.
Contributes to closing https://github.com/blockstack/clarity-js-sdk/issues/99
Once this is merged, I'll need to work on automating the NPM publish for clarity-js-sdk to close the above …

add gh workflow for updating clarity-js-sdk

---

src/chainstate/stacks/db/transactions.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This fixes #2097 by not "unwrapping" transaction response results. A unit test was added for the specific behavior of #2097 in the `blockstack_lib` (where there wasn't an issue -- the transaction receipt contained the correct result), and an assertion was added to an existing neon_integrations test that ensures that the returned result is actually the whole result, not an unpacked value.

Fix: #2097, event dispatcher should not unpack response results

---

src/vm/analysis/type_checker/mod.rs
src/vm/callables.rs
src/vm/contexts.rs
src/vm/costs/mod.rs
src/vm/functions/database.rs
src/vm/tests/costs.rs

This PR implements #2042 -- it allows a CostTracker to intercept the cost calculation of contract-call invocations when specific targets are used.
This will be used in the cost voting system to allow STX holders and miners to introduce new "native" Clarity functions by specifying a new cost for those functions.
- New feature
No, this is not a breaking change.
No.
This PR includes unit tests covering the behavior of the LimitedCostTracker with contract-call interceptions.

Cost-tracking: #2042, intercepting contract-call costs

---

.github/workflows/clarity-js-sdk-pr.yml
.github/workflows/stacks-blockchain.yml
.github/workflows/v1-v2-migration.yml

Adds a new Github workflow to automate the change, commit, and PR creation of updating the chainstate and chainstate consensus files for the V1 -> V2 migration.
Upon an authorized `repo_dispatch` POST to this repo, the workflow will kick off. It'll download the chainstate files from GCS, commit that to a new branch created from `master`, and create a new PR displaying those changes and some metadata of the files, while assigning multiple people as reviewers and assignees.
[An example of the PR can be found here](https://github.com/blockstack/gh-action-testing/pull/1).
No
No

adding gh workflow for v1 -> v2 migration

---

src/chainstate/stacks/block.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR makes `next`'s Xenon mode use `Xe` as the magic bytes for Bitcoin operations.
The PR implements this by doing two things:
1. Actually parsing the `magic_bytes` field in the burnchain config from the node config file.
2. Checking if the burnchain mode is set to xenon, and if so, using the default Xenon magic bytes (this makes it so that people don't need to update their config files if they aren't running just the default xenon config).
Related: #1926

Xenon Magic Bytes

---

README.md
deployment/helm/stacks-blockchain/README.md
deployment/helm/stacks-blockchain/templates/configmap.yaml
deployment/helm/stacks-blockchain/values.yaml
net-test/etc/stacks-follower.toml.in
net-test/etc/stacks-master.toml.in
net-test/etc/stacks-miner.toml.in
testnet/stacks-node/Stacks.toml
testnet/stacks-node/conf/argon-follower-conf.toml
testnet/stacks-node/conf/krypton-follower-conf.toml
testnet/stacks-node/conf/local-follower-conf.toml
testnet/stacks-node/conf/local-leader-conf.toml
testnet/stacks-node/conf/local-second-miner.toml
testnet/stacks-node/conf/neon-follower-conf.toml
testnet/stacks-node/conf/xenon-autonomous-follower-conf.toml
testnet/stacks-node/conf/xenon-follower-conf.toml
testnet/stacks-node/conf/xenon-miner-conf.toml
testnet/stacks-node/src/config.rs

Closes https://github.com/blockstack/stacks-blockchain/issues/2151
We changed a config variable name from `mstx_balance` to `ustx_balance` in a previous PR. This PR fixes all the example tomls and readme references. 
For backwards compatibility, the `mstx_balance` option was fixed so that it still works but prints a deprecation notice -- added this after report of sudden broken balance config.

fix: `mstx_balance` to `ustx_balance` in tomls and readmes

---

src/chainstate/stacks/events.rs

with the addition of `TransactionOrigin`, `transaction.serialize_to_vec()` fails to build because it does not know how to process the new field.  This fixes that.

fix --features=tx-log which no longer builds

---

src/blockstack_cli.rs
src/burnchains/mod.rs
src/chainstate/stacks/auth.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/db/unconfirmed.rs
src/chainstate/stacks/miner.rs
src/chainstate/stacks/mod.rs
src/chainstate/stacks/transaction.rs
src/core/mempool.rs
src/net/http.rs
src/net/mod.rs
src/net/relay.rs
src/net/rpc.rs
src/net/server.rs
src/vm/clarity.rs
testnet/stacks-node/src/run_loop/mod.rs
testnet/stacks-node/src/tests/mempool.rs
testnet/stacks-node/src/tests/mod.rs

This PR adds transaction fees to the miner's block reward.  Per SIP-001, each miner gets all of its anchored block's transaction fees, as well as 40% of the microblocks it produces (awarded in each Stacks fork in which a subsequent anchored block confirms them), as well as 60% of the microblocks it confirms.  It also renames `fee_rate` to `tx_fee`, now that we're making it so transactions pay the fee they advertise (instead of a Kth-highest fee per epoch).

Implement transaction fees

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/genesis_data.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/neon.rs

Closes https://github.com/blockstack/stacks-blockchain/issues/2176

Allow small test genesis file to be used in mocknet mode

---

.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
.github/workflows/stacks-blockchain.yml
src/address/c32.rs
src/blockstack_cli.rs
src/chainstate/burn/operations/mod.rs
src/chainstate/coordinator/comm.rs
src/chainstate/coordinator/mod.rs
src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/index/marf.rs
src/chainstate/stacks/index/storage.rs
src/clarity.rs
src/net/chat.rs
src/net/p2p.rs
src/net/server.rs
src/util/log.rs
src/vm/clarity.rs
src/vm/database/clarity_db.rs
src/vm/database/marf.rs
src/vm/database/sqlite.rs
src/vm/docs/mod.rs
src/vm/errors.rs
src/vm/tests/costs.rs
src/vm/tests/forking.rs
src/vm/tests/mod.rs
testnet/stacks-node/src/neon_node.rs

This addresses #2045 -- removing the savepoints, and using the same DB transaction to build MARF tries as "side-store" writes.
The primary changes here are to `vm::database::marf` (which propagate to `vm::clarity`):
* In order to be used, a caller of the `MarfedKV` struct needs to create either a Writable or a ReadOnly db connection. The Writable connection wraps a `MarfTransaction` instance -- this is used to ensure that a ClarityBlockConnection always corresponds with one MarfTransaction (guaranteeing atomicity of side-store operations, importantly the _metadata_ side store operations).
* Unconfirmed state still requires the ability to "undo" metadata side store operations. This is because unconfirmed state may be "sqlite committed", and then later dropped. This is implemented by doing …

Clarity DB Fixes

---

.github/workflows/stacks-blockchain.yml

Changes the full and sample genesis tests to make them non-blocking for releases, since they could take over an hour and there's some inconsistent errors delaying releases.
No
Nada

Nonblocking genesis tests

---

net-test/bin/start.sh

Running tests with testground, occasionally an instance or two would fail to confirm the BTC faucet transaction after 10 attempts. 
Increasing this int from `10`->`20` has helped in local testing, no more failures of this type have been caught. 
For details refer to issue #2046 
Due to this change, it may take longer to confirm BTC faucet tx in `./net-test`, but functionally nothing should be affected.

increase the number of attempts to confrim BTC transaction from 10->20

---

sip/sip-008-analysis-cost-assessment.md

There is a small typo in sip/sip-008-analysis-cost-assessment.md.
Should read `system` rather than `sytem`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, sytem -> system

---

src/chainstate/stacks/index/bits.rs
src/chainstate/stacks/index/marf.rs
src/chainstate/stacks/index/mod.rs
src/chainstate/stacks/index/node.rs
src/chainstate/stacks/index/proofs.rs
src/chainstate/stacks/index/storage.rs
src/chainstate/stacks/index/trie.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR does 2 things to trim the RAM usage of the MARF implementation. This has the most significant impact on genesis block processing, which previously had a maximum memory usage of ~3 GB, but in this PR has ~400MB max memory usage.
The two things are:
1. Make the `dump_traverse` routine used in flushing the TrieRAM to a buffer a consuming function. This allows the method to modify the `data` vec in place, rather than constructing a new vec. This provides about a 50% memory saving (when tested, went from 3GB to 1.6GB usage).
2. Use `Box` allocations for TrieNodeType variants for Node48 and Node256. This provides a significant memory savings, because it changes the size of `TrieNodeType` from ~2.5kb to ~100 bytes. That in turn allows the `data` vec in the TrieRAM to allocate …

MARF RAM Improvement

---

src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/boot/cost-voting.clar
src/vm/database/clarity_db.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR addresses #2223 by using `block-height` rather than `burn-block-height`.

Update cost-voting to use block-height over burn-block-height

---

src/chainstate/burn/operations/mod.rs
src/chainstate/stacks/db/mod.rs

Per @zone117x request, we're generating a receipt with the lockup events inserted at genesis time.

Add lockup events

---

src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/mod.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This updates the magic bytes for Xenon, which will cause a Xenon reset.

Update Xenon magic bytes for reset

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/operations/leader_block_commit.rs
testnet/stacks-node/src/neon_node.rs

The PoX anchor selection logic assumes it can always find the parent of a sortition winner -- this is not true if the parent is the genesis block (this leads to a panic #2240)

Fix: PoX Anchor Counting

---

src/util/pipe.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Opening this PR to try and fix some of the current test errors we're seeing. So far:
1. Fix the stack overflow caused by one of the pipe util tests.
2. DRY `neon_integrations` and `clear()` the event observer between runs.

Test fixes

---

src/vm/tests/simple_apply_eval.rs
src/vm/types/mod.rs

This fixes #2239, and provides a witnessing test.

Fix: #2239 merge types on runtime merge

---

src/burnchains/burnchain.rs
src/util/log.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/neon.rs

Actual lines changed is < 20, most of the diff is whitespace adjustment by `cargo fmt`.

Use thread-names instead of thread-ids in logs.

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/miner.rs

The miner should be able to continue mining an anchor block even if the parent microblock stream fails to load -- it should default to mining without confirming the parent microblock stream.

Do not abort mining a block if the microblock stream failed to load

---

src/util/log.rs

This uses the new thread names in our `slog_json` builds as well.

Chore: use thread names in slog_json as well

---

.github/actions/bitcoin-int-tests/Dockerfile.atlas-test
.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
.github/workflows/bitcoin-tests.yml
.github/workflows/stacks-blockchain.yml
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/headers.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/miner.rs
src/clarity.rs
src/vm/contexts.rs
src/vm/database/clarity_db.rs
src/vm/docs/mod.rs
src/vm/functions/assets.rs
src/vm/tests/assets.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/helium.rs

This fixes #2232 by using the clarity_db MARF to store the current liquid supply of STX.
This PR also tries to play some tricks with our current integration tests workflows:
1. It creates a separate workflow for the integration tests, which allows them to be re-run without re-running the other jobs (the dist and build-release jobs are non-trivial executions).
2. It runs the tests in separate `cargo test` commands. This solves any issues that may be caused by using lazy_statics to track test state _and_ it makes the tests "fail fast".
3. It separates the atlas integration test into its own test runner.

Immediate updates of `total-liquid-ustx`

---

src/burnchains/bitcoin/indexer.rs
src/vm/functions/assets.rs
src/vm/types/signatures.rs

Per
https://rust-lang.github.io/rust-clippy/rust-1.49.0/index.html#absurd_extreme_comparisons:
"Checks for comparisons where one side of the relation is either the
minimum or maximum value for its type and warns if it involves a case
that is always true or always false."
No functional changes.

Remove "absurd comparisons" as identified by Clippy.

---

Cargo.lock
Cargo.toml

Addresses the following from `cargo audit`:
ID:       RUSTSEC-2020-0071
Crate:    time
Version:  0.2.16
Date:     2020-11-18
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0071
Title:    Potential segfault in the time crate
Solution:  upgrade to >= 0.2.23
Dependency tree:
time 0.2.16
Besides `rusqlite`, there are a few other dependencies flagged by `cargo
audit`, but upgrading them is a bit more invasive.

Upgrade `time` crate to version `0.2.23`.

---

.dockerignore
.github/workflows/stacks-blockchain.yml
Dockerfile
Dockerfile.stretch
build.rs
src/lib.rs
src/net/rpc.rs
testnet/stacks-node/src/main.rs

* Updates the package name and version displayed in the `/v2/info` endpoint.
* The `server_version` at `/v2/info` and `stacks-node version` command should now read something similar to:
```bash
"stacks-node v24.3.2.0-xenon (build-metadata:0087561+, release build, linux [x86_64])"
```
```bash
docker run --rm build-metadata-stretch stacks-node version
stacks-node v24.3.2.0-xenon (build-metadata:0087561+, release build, linux [x86_64])
```
* Disables triggering a release when a tag is pushed up. cc @kantai 
* I disabled this because since we added a GH workflow which creates a new `clarity-js-sdk` PR upon each `stacks-blockchain` release, a new tag that gets created by the standard release workflow will create a loop, causing the release workflow to run again and attempt re-releasing the …

Update build metadata. don't trigger from pushed tags anymore

---

benches/block_limits.rs
src/chainstate/stacks/boot/costs.clar
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/contracts.rs
src/chainstate/stacks/db/mod.rs
src/vm/clarity.rs
src/vm/contexts.rs
src/vm/costs/mod.rs
src/vm/database/clarity_db.rs
src/vm/database/mod.rs
src/vm/functions/assets.rs
src/vm/functions/database.rs
src/vm/functions/mod.rs
src/vm/functions/special.rs
src/vm/mod.rs
src/vm/tests/costs.rs
src/vm/variables.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/integrations.rs

This sets initial pessimistic block limits for mainnet. These are set based on evaluating:
* `stx-transfer?`
* `stx-stack`
* Simple large contract analysis
* `secp256k1-verify`
Far and way, of those, `stx-stack` is the most expensive, and governs the limits imposed on the `write-count` and `read-count` for the MARF. With these block settings, at most 50 such operations could occur in a block. On simple tests, even 50 such operations take around a minute to process (the test MARF is seeded with 500,000 account entries).
The benchmarking tests can be found in the `feat/block-limits` branch, which is separated here, because there's code in that branch to support benchmarking and profiling which should not necessarily be merged yet.

Pessimistic block limits

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This sets the Xenon magic bytes to `X4` in preparation for the next Xenon reset.
It also disables the Atlas Github job. It doesn't disable the test, but for now, this Github job isn't providing much value.

Set Xenon magic bytes to X4

---

bns-test/test/name_prices.test.ts

Tests for the `btc` namespace price patch implemented in the Stacks 1.0 export here: https://github.com/blockstack/stacks-blockchain/pull/2277

Add bns.clar test for btc namespace price params

---

.github/workflows/v1-v2-migration.yml

Updates the `v1-v2-migration` Github workflow to incorporate committing the `name_zonefiles` to the `stx-genesis` directory.
Also adds the block height to the PR description.
[Here's an example of what the PR will look like.](https://github.com/blockstack/gh-action-testing/pull/1)
Closes https://github.com/blockstackpbc/devops/issues/553
Closes https://github.com/blockstackpbc/devops/issues/555
No.
No.

Update v1-v2-migration GH workflow to commit name_zonefile files

---

.github/workflows/stacks-blockchain.yml
build-scripts/Dockerfile.linux-arm64
build-scripts/Dockerfile.linux-armv7
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.linux-x64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64

Fixes the version info in distributables:
```
./stacks-node version
stacks-node 92d9860 (binary-version-fix:92d9860+, release build, macos [x86_64])
```
Closes https://github.com/blockstack/stacks-blockchain/issues/2299
No
No
[All distros can be downloaded and tested here](https://github.com/blockstack/stacks-blockchain/actions/runs/473111235)

Fix version info in distributables

---

src/net/connection.rs

The latest Xenon reset (2.0.0-rc1) increased the initial costs of Clarity functions (and increased the block limit), but did not increase the default runtime limit for read-only calls over the API interface. This PR does that.

Update default read-only limits for network calls

---

deployment/helm/stacks-blockchain/values.yaml
testnet/stacks-node/Stacks.toml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/config.rs

Motivated by the current surges on Mainnet, this PR is introducing 3 new settings:
- `satoshis_per_byte`
- `leader_key_tx_estimated_size`
- `block_commit_tx_estimated_size`
And getting rid of `burnchain_op_tx_fee`.
The current default is 50 sats/bytes, it's been tested on Testnet for a [key registration](https://mempool.space/testnet/tx/2f4e3187b3b8bf9d7aafc8e618159f19e2616d667e5bf684d242600144563fa7) and a [block commit](https://mempool.space/testnet/tx/36292112c685da83a0066b8b9aaf4177a10964dfd31204d3003a6d536f17b1dc). 
I took some time to refactor the logic for satoshis allocation, which will squash a few bugs with the UTXOs filtering (minimum amount was incorrect).
I see a TODO about RBF, any action we should take here?

Ability to configure the satoshi_per_byte for BTC transactions

---

testnet/stacks-node/src/neon_node.rs

This PR is improving a patch for a bug that I spotted a few months ago (https://github.com/blockstack/stacks-blockchain/commit/750687e86a98b5f0820b1a5c818266d68e6c1ebb).
The patch above was essentially inefficient when a key_register op is sitting in the mempool during multiple blocks.

Fix key registration spanning over multiple blocks

---

.github/workflows/v1-v2-migration.yml

Updates the base branch used in the v1-v2 migration GH workflow to `next`.
Once merged, `master` will need to be merged into `next` so this change propagates into the workflows for both branches.

Update base branch in GH workflow

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/neon_node.rs

This PR is following up on #2271
Its goal is to let the node crash when the p2p run loop failed, and the chain events are being observed.

Follow up #2271

---

src/burnchains/burnchain.rs
src/chainstate/stacks/boot/genesis.clar
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/mod.rs
src/core/mod.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/syncctl.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR does a couple things:
1. Sets a last burn block to process to burn block `700_000` -- this is enforced by skipping the burnchain processing once `last_block` has reached the limit.
2. Adds a `genesis.clar` contract that prints a message when the genesis block is processed.
3. Alters the interaction between `neon`, `neon_integrations` and `syncctl` such that the `neon_integrations` tests always unconditionally download burn blocks.

Stacks 2.0 Settings

---

bns-test/package.json
bns-test/src/bns-client.ts
bns-test/test/name_register.test.ts
src/chainstate/stacks/boot/bns.clar
src/chainstate/stacks/db/mod.rs

As a contract developer I want to check properties of the user based on the username
This PR
* adds a method `get-name` that returns the username of a given principal
* fixes #2322 
No
No tests

fix: add get-name #2322

---

testnet/stacks-node/src/config.rs

- Updating the builtin config for `stacks-node mainnet`
- Fine tuning `wait_time_for_microblocks` - from 5s to 2m
- Fine tuning `microblock_frequency ` - from 5s to 30s

Config updates

---

testnet/stacks-node/src/config.rs

the peer to peer port should be 20444, while the rpc port is 20443.  Without the correct port, the node will not sync beyond the the first 2 cycles.

fix seed host ports

---

src/net/db.rs

Pick initial peers at random, so when the neighbor walk tries to keep a bootstrap node in the neighbor set, it picks one at random.

Pick initial peers at random

---

.github/workflows/stacks-blockchain.yml
testnet/stacks-node/src/tests/neon_integrations.rs

This PR should fix flakiness in the microblock integration test on github actions by adjusting the microblock frequency in the test.
It also disables the nettest action for now: that action hasn't passed in github actions for a while now, and it is a very long running test, which can delay other test runners.

Test: Fix microblock integration

---

.github/workflows/stacks-blockchain.yml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR forces a `mainnet` configured node to start with default settings for `magic_bytes`, `block_limit`, `use_test_genesis`, and without settings for `initial_balances` -- these settings, if applied, would cause the node to misbehave and other nodes in the network would consider the node to be invalid (and vice-versa).

Feat: panicking enforcement of mainnet configs

---

src/core/mod.rs

This corrects the peer version to match the config peer version in `stacks-node::config`

Fix: peer version to 0x18 rather than 0x17

---

src/blockstack_cli.rs
src/burnchains/burnchain.rs
src/chainstate/stacks/db/mod.rs
src/core/mod.rs
src/net/chat.rs
src/net/codec.rs
src/net/neighbors.rs
src/net/p2p.rs
src/net/relay.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/monitoring/prometheus.rs
testnet/stacks-node/src/tenure.rs
testnet/stacks-node/src/tests/mempool.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/neon_integrations.rs

We want to re-deploy a Xenon (based on `v2.0.1`) for an ongoing Hackathon, and we're experiencing the issue with the PEER_VERSION that we were experiencing for Mainnet launch, which probably means that a codepath recently changed, revealing that discrepancy.
This PR is streamlining the usage of `PEER_VERSION`, and fixing a few places where it's being hard coded.
This PR should not affect Mainnet, but will fix our Testnet.

Streamline usage of PEER_VERSION

---

src/chainstate/stacks/db/blocks.rs
src/core/mempool.rs
src/vm/clarity.rs
testnet/stacks-node/src/tests/mempool.rs
testnet/stacks-node/src/tests/mod.rs

This implements #2354, applying some checks to transfer transactions before admitting them to the mempool:
1. If `recipient = origin`, then reject the transaction from the mempool
2. If `amt == 0`, then reject the transaction from the mempool
Either of these would already disqualify the transaction from being included in a block, but by applying these checks before mempool admission, clients are able to correct the error.

Feature: Check transfer semantics before mempool admission

---

benches/block_limits.rs
src/vm/clarity.rs
testnet/stacks-node/src/tests/neon_integrations.rs

The aim of this PR is to test behavior when a block is approaching its `block-limit`, and is full of transactions that are expensive to analyze (in this case, mostly invoking `(contract-call? ...)`).
Additionally, it contains a benchmarking function for a similarly expensive contract.

Test: nearly full block

---

.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This is one method for addressing #2364 -- during initial bootup, a `stacks-node` instance will query a set of "height hint" peers. The node will _not_ begin mining until it reaches the max height returned by those peers.
This PR also sets a default set of height hint nodes, as well as providing more proactive default bootstrap node selection for mainnet configurations (i.e., if the `bootstrap_node` field is _not_ set in the config, but the config is a mainnet config, use the default set).

Feature: Do not mine while node is initially syncing Stacks blocks

---

src/chainstate/stacks/miner.rs
src/core/mempool.rs
src/core/mod.rs
src/main.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR addresses the most immediate mempool issue #2389, by modifying the walk logic to "try again" if there are mempool entries received at a particular height _but not_ in the same fork.
This PR also adds a `try-mine` CLI command, as well as a diagnostic envar `MEMPOOL_BAD_BEHAVIOR` which executes the mempool walk in the manner that causes #2389.
This leaves unaddressed two potential issues:
1. Transactions received into the mempool at block `A`, but block `A` is "forked away". Those transactions will not appear in the miner's walk. However, such transactions will be viable for "replace-across-forks", such that if the transaction is rebroadcasted (not re-signed or fee upgraded), the miner will replace the existing tx in the mempool. (Issue: #2394)
2. Mempool transactions are evaluated …

Fix: #2389 Mempool walks, add `try-mine` CLI command

---

.github/workflows/bitcoin-tests.yml
src/net/atlas/db.rs
testnet/stacks-node/src/tests/neon_integrations.rs

After investigation, it turns out the atlas test was broken for a good reason.
- Attachment serving broke with a recent refactoring
- The BNS pricing table changed and the value provided was too low, as a consequence the `namespace-preorder` contract call was failing.

Fix: atlas attachment serving + broken test

---

Cargo.lock
Cargo.toml
src/vm/database/structures.rs

This gets around `serde_json`'s default depth limit, using a `stacker` enabled deserializer.

Fix: serde_json depth limit

---

testnet/stacks-node/src/event_dispatcher.rs

See: https://github.com/blockstack/stacks-blockchain-api/pull/430
This change is required by the API to report miner balances correctly.

`tx_fees_streamed_produced` missing from the reward payload

---

CHANGELOG.md
src/chainstate/burn/db/sortdb.rs
src/chainstate/stacks/db/blocks.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR addresses the superficial issues of #2444 (https://github.com/blockstack/stacks-blockchain/pull/2452 addresses a more underlying issue), by changing the RBF fallback logic. It also patches the way `winning_txid` is fetched by the sortition db (using the primary key fields to grab the winning block).

Fix: #2444, RBF fallback logic, and winning_txid fetching

---

docs/event-dispatcher.md

Docs shows `"amount"` rather than the actual field name `"amt"` for burnchain block rewards
See https://github.com/blockstack/stacks-blockchain/blob/ad145207ce9979ed1bf44af2839dd2938c79a0f5/testnet/stacks-node/src/event_dispatcher.rs#L134

fix: update /new_burn_block payload schema

---

CHANGELOG.md
src/chainstate/stacks/db/blocks.rs

This is an emergency hotfix that stops the node from accidentally deleting a valid parent block in the event that its descendant microblock stream is invalid for some reason.

do NOT delete the parent anchored block if the microblock stream is too heavy

---

CHANGELOG.md
src/chainstate/stacks/db/transactions.rs
src/vm/database/key_value_wrapper.rs

This is a hotfix release for improved handling of static analysis storage and improved `at-block` behavior. The chainstate directory of 2.0.8 is compatible with the 2.0.7 chainstate. More details in `CHANGELOG`.

Fix: improved analysis db storage

---

CHANGELOG.md
Cargo.toml
src/chainstate/stacks/db/blocks.rs

Backport #2496 to master.
EDIT: Closing #2496 in favor of this one.  The original PR text follows.
Fix a TOCTTOU bug in the code that checks that the node doesn't yet have an anchored block (this is important now, because both the p2p thread and relayer thread can store new anchored blocks).

fix/block store push tocttou (master)

---

README.md

This PR adds a release/hotfix section to the readme. This is meant as a rough draft for now to start discussion on the policy here. This includes a proposed release cadence.

Docs: add release/hotfix section to readme

---

CHANGELOG.md
docs/rpc-endpoints.md
docs/rpc/api/trait/get-is-trait-implemented.example.json
docs/rpc/api/trait/get-is-trait-implemented.schema.json
docs/rpc/openapi.yaml
src/net/http.rs
src/net/mod.rs
src/net/rpc.rs
testnet/stacks-node/src/tests/integrations.rs

Added a RPC endpoint to determine if a given trait is implemented in a contract, either explicitly or implicitly.
Fixes #2382 
For some background, a trait is explicitly implemented in a contract if the contract has `impl-trait <trait info>`. Implicit implementation means a contract implements the traits without the declaration above. 
- I made trait_id (type `TraitIdentifier`) a field in HttpRequestType::GetIsTraitImplemented, even though the GET request independently passes in a trait name, trait contract address, and trait contract name. I did this because I thought it would be cleaner to parse the API path at a higher level, and pass down consolidated information (in the form of the struct `TraitIdentifier`. However, this is not consistent with how the contract data is passed (which …

feat: RPC endpoint /v2/traits/<contract-info>/<trait-info>

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/util/db.rs

This updates the two block truncation/deletion paths in the StacksChainState such that microblock is moved to an "invalid" table and block data is renamed to `.invalid`. This ensures that invalidated data is retained for debugging or recovery purposes.

Feature: keep invalidated block data

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/headers.rs
src/util/db.rs

Currently when we check if a block is attachable, we check if there exists an unprocessed parent. This PR additionally checks that the block's parent has been received. 
Fixes #2212.
Ran `cargo test`. The test `chainstate::stacks::miner::test::test_mempool_mining_heuristics` is failing, but it is also failing on the head of `develop` branch, so it isn't caused by the changes in this PR.

fix: fixed block attachability logic

---

.github/actions/open-api/Dockerfile.open-api-validate
src/main.rs
src/vm/docs/mod.rs

This PR adds a typechecker pass to the unit-tests in `vm::docs` and corrects the mis-typed examples in the docs (addressing #2560).
This PR also includes a nice extension to the `decode-tx` function in `main`, verifying the inputted transaction and outputting the origin address as a C32 address.

Fix: Typecheck in `vm::docs` and correct examples

---

testnet/stacks-node/src/main.rs

This makes the panic handler print out the abort/panic message supplied by the panic.

Feature: stacks-node panic handler to print abort messages

---

CHANGELOG.md
Cargo.lock
README.md
src/vm/types/serialization.rs

This is a low-priority hotfix release to address a bug in the deserialization logic. The chainstate directory of this fix is compatible with 2.0.10.
This also adds a section to the README file that describes our 5 number versioning scheme.

Fix: better deserialization error handling

---

testnet/stacks-node/src/main.rs

This is an update on the previous panic output fix PR which uses the display fmt to produce the panic output. This produces nice outputs for cases like `.unwrap()` and `.expect()` while the previous approach only worked for `panic!` macro invocations:
```
$ stacks-node start
...
Process abort due to thread panic: panicked at 'called `Result::unwrap()` on an `Err` value: MissingOption(Keys(["--config", ""]))', testnet/stacks-node/src/main.rs:123:71
```

Use display fmt for panic output

---

src/net/rpc.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/integrations.rs

This PR fixes #2599 -- it also resuscitates the `integrations::integration_test_get_info` test, which had some modifications at some point that added another "round" of operations, but didn't update the round-dependent checks.

Fix: #2599 - trait rpc lookups for implicitly implemented traits

---

src/net/inv.rs
src/net/rpc.rs
testnet/stacks-node/src/tests/integrations.rs

second attempt in fixing #1641 to allow calling any function as read-only.  the call will fail if any write happened during the call.
For example, this allows calling public functions that call use `contract-call?`, which can not be used in a read-only function, even if the called contract function itself is read-only.

Implement #1641 rpc call public functions as read-only - take 2

---

src/vm/docs/mod.rs

This PR is a small update of the documentation of `define-map`. Clarifying that maps take any key types and any value types.

Update documentation of define-map

---

testnet/stacks-node/src/main.rs
testnet/stacks-node/src/operations.rs

This PR adds the `key-for-seed` command to the `stacks-node` binary. It outputs the associated secret key hex string and WIF formatted secret key for a given "seed" value:
The seed value can either be read from a config file, or supplied as a free CLI arg.
```
$ ./target/debug/stacks-node key-for-seed --config=./testnet/stacks-node/conf/local-leader-conf.toml 
INFO [1621344961.200296] [testnet/stacks-node/src/main.rs:81] [main] stacks-node 0.1.0 (develop:5f6c1fd68+, debug build, macos [aarch64])
Hex formatted secret key: 66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925
WIF formatted secret key: 5JbPTc935MFttEwiXUMnC5EBwmaGH3TZYE22a72J2bQREjxJseN
```
```
$ ./target/debug/stacks-node key-for-seed 0000000000000000000000000000000000000000000000000000000000000000
INFO …
```

Feat: Add seed -> secret key output commands

---

src/chainstate/stacks/db/unconfirmed.rs
testnet/stacks-node/src/event_dispatcher.rs

Add microblock header hashes to the `/new_microblocks` payload. This required in order for event observers to detect micro-forks once an anchor block is received.

feat: emit microblock header hash to event observer

---

src/chainstate/burn/distribution.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/monitoring/mod.rs
src/monitoring/prometheus.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Fixes #2651 
Added the following metrics in prometheus: 
- Miner's computed relative miner score as a percentage (Gauge)
- Miner's computed commitment, the min of their previous commitment and their median commitment
- Miner's current median commitment
The latter two metrics are u128 values. Prometheus's IntGauge only captures 64 bit values, so I used two IntGauges for both of the metrics (one for the high 64 bits, and another for the low 64 bits). 
Ran `BITCOIND_TEST=1 cargo test --release --features monitoring_prom -- --test-threads 1 --ignored neon_integrations::bitcoind_integration_test` in the `testnet/stacks-node` directory.  Pinged the prometheus endpoint and got the value of all tracked metrics, which I then checked against expected value.
> Note: When running an integration test …

Feat: added mining-related prometheus stats

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

This fixes #2644 by simply re-ordering the UTXO staleness check so that it occurs before the RBF-limit check. This ensures that if stale UTXOs reached the "RBF limit" a miner will recover by resetting the UTXO cache.
- Bug fix
No
This can be tested on testnet, where current tBTC mining behavior rapidly exposes the #2644 issue.

Fix: #2644 reorder UTXO staleness and RBF-limit check

---

README.md

Removing the unnecessary $ from terminal commands.
Referring to : https://github.com/blockstack/docs/issues/1190

docs: remove redundant $ from terminal commands

---

Cargo.lock
Cargo.toml
src/burnchains/bitcoin/indexer.rs
src/burnchains/burnchain.rs
src/burnchains/indexer.rs
src/core/mod.rs
src/lib.rs
src/main.rs

This removes the `tini` dependency.
The only codepath that actually used the tini reader was a CLI command for replaying chainstate (this CLI command may already have been defunct), but that codepath only needed the tini reader for determining the first burn block hash and first burn timestamp, both of which were otherwise available.

Chore: remove tini dependency

---

testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/neon.rs

This fixes #2710 -- the mocknet/helium miner had a logic bug that would lead to a panic if a burn block occurred without a sortition in it.

fix: logic bug in mocknet/helium miner #2710

---

testnet/stacks-node/src/tests/neon_integrations.rs

This is a simple attempt to tweak some of the settings in `neon_integrations` to speed those tests up some. So far, this just tweaked the microblock integrations tests (picked up about 15-20 minutes locally).

chore: try to speed up some integration tests

---

src/chainstate/coordinator/comm.rs
src/net/download.rs
src/net/poll.rs
src/vm/database/sqlite.rs

Fixes 2698
This PR fixes 12 build warnings in the rust code that we get when we run 'cargo build'. This greatly simplifies the output.
After this change the build compiles without warnings.

[clean-up] Fix build warnings in 'cargo build'

---

src/vm/docs/mod.rs

This PR adds text about the return value of the `var-set` Clarity function. This clarification came from discussion that I had with @reedrosenbluth regarding the usage of `asserts!` with the `var-set` function, where we discovered that it was not possible for `var-set` to return any other value than `true`.
No
No
No tests are required for this PR.

docs: added text on the return value of var-set

---

src/vm/costs/cost_functions.rs
src/vm/costs/mod.rs
src/vm/functions/assets.rs
src/vm/functions/mod.rs

This PR adds an `Unimplemented` cost variant to the Clarity CostFunctions, which is useful while #2717 is still open.

Clarity 2: Add `Unimplemented` cost variant

---

src/burnchains/mod.rs
src/types/proof.rs
src/vm/analysis/type_checker/natives/mod.rs
src/vm/functions/crypto.rs
src/vm/tests/simple_apply_eval.rs
src/vm/types/signatures.rs

This PR makes the BufferLength instance variable private. The rationale for this is that the BufferLength constructor enforces the Clarity TypeSignature invariant that a TypeSignature fails to construct if the described type is too large.
As part of this, this also refactored the BufferLength constants to be lazy_statics, so that the length check is applied to the constants on first use.

Chore: BufferLength code quality

---

src/vm/docs/mod.rs

This PR fixes two typos that were identified in the documentation for the Clarity language reference. A community contributor initially tried to open PRs agains the automatically generated JSON file in the docs repository, but this is the permanent fix.
List the APIs or describe the functionality that this PR breaks.
Workarounds for or expected timeline for deprecation
No
No tests required

fix: typos in Clarity docs

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/transactions.rs
src/deps/bitcoin/network/encodable.rs
src/net/http.rs
src/net/inv.rs
src/util/retry.rs
src/vm/types/serialization.rs
testnet/stacks-node/src/syncctl.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR fixes all the warnings generated by current rust stable in `develop` when run with `cargo check --workspace --tests` (previously, warnings were only addressed in `cargo check`)

Chore: fix all warns in `cargo check --tests --workspace`

---

README.md

This PR removes the significantly outdated testnet versions from the README, and updates the descriptions of the existing testnets to reflect the current state of Stacks 2.0. Additionally, some minor linting errors in the MD are addressed.
No
No testing required

Remove outdated testnet versions from README

---

src/burnchains/burnchain.rs
testnet/stacks-node/src/tests/neon_integrations.rs

With this fix, we're only considering the `target_block_height` if this value is relevant.
The `sync_with_indexer` function is reading the burnchain state from the bitcoin-node and should be considered as the source of truth, and should ignore / correct the hint when it's determined as off.
Address #2783.

Only consider target_block_height when relevant

---

src/chainstate/coordinator/tests.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/headers.rs
src/chainstate/stacks/db/unconfirmed.rs
src/chainstate/stacks/miner.rs
src/clarity_vm/clarity.rs
src/codec/mod.rs
src/core/mempool.rs
src/net/db.rs
src/net/http.rs
src/net/inv.rs
src/net/mod.rs
src/util/db.rs
src/util/uint.rs
src/vm/analysis/errors.rs
src/vm/contexts.rs
src/vm/costs/mod.rs
src/vm/functions/arithmetic.rs
src/vm/tests/assets.rs
src/vm/tests/simple_apply_eval.rs
src/vm/types/mod.rs
src/vm/types/serialization.rs
testnet/stacks-node/src/syncctl.rs

Switched all occurrences of {i, u}{8, 16, 32, 64, 128}::max_value() to {i, u}{8, 16, 32, 64, 128}::MAX. Did the same for the function min_value. I did this by searching for occurrences of max_value/min_value and replacing them one by one (since `ExecutionCost` also has a method named max_value).
These functions are set to be deprecated in a future rust version: https://doc.rust-lang.org/std/primitive.i64.html#method.min_value
Ran `cargo test`.

fix: switched all occurrences of max_value/min_value to MAX/MIN

---

.github/workflows/clarity-js-sdk-pr.yml

Updates the clarity-js-sdk Github workflow to:
* Remove Hank as a reviewer of new PRs
* Update the same PR if it's still open instead of creating a new PR for each release
* Only run on releases and not pre-releases.
* Add a `dependencies` label to the PR
For details refer to issue https://github.com/hirosystems/devops/issues/750
No
No

ci: update clarity-js-sdk gh workflow

---

src/vm/docs/mod.rs

This PR 
* extends the documentation of `nft-transfer?` and `ft-transfer?` clarifying that any user can call these functions if not guarded properly.
There was some confusion as seen here: https://github.com/blockstack/docs/issues/1249
No

Clarify difference between stx-transfer? and (n)ft-transfer?

---

.github/actions/bitcoin-int-tests/Dockerfile.atlas-test
.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
.github/actions/bitcoin-int-tests/Dockerfile.net-tests
.github/actions/bitcoin-int-tests/Dockerfile.rustfmt
migration-verification/Dockerfile

This PR upgrades the rust containers in our testing dockerfiles from `buster` to `bullseye` (the new Debian stable).
This fixes an issue with the recent rust nightly in our code-coverage tests -- one of the packages interacting poorly with profiling builds in `buster`.

Build: buster -> bullseye in rust testing dockerfiles

---

.github/stale.yml

Changes:
- wait 1 yr before marking issues stale. Even at 180 days, many
important issues keep going stale.
- add more labels to exempt list.
- wait 30 days before closing stale issues.

chore: tweak stale bot settings

---

testnet/stacks-node/src/tests/neon_integrations.rs

Opening this PR to clean up some of the integration testing in `develop`.
The first cleaned up test is `fix_2771`, which as previously written could lead to an infinite loop if an event got dropped by the test (leading to 6 hour GH actions for failures).
I suspect one of the microblock tests also requires a fix, as the merge from `master -> develop` caused an issue there.

Chore: Integration tests cleanup

---

src/burnchains/mod.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/stacks/block.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/miner.rs
src/net/mod.rs
testnet/stacks-node/src/tests/epoch_205.rs

This PR implements #2904.  It adds the following three changes:
* It makes it so that when pre-processing an anchored block (such as one downloaded or pushed to the node), the node will not store it if its parent is in a different epoch and it confirms a microblock stream.
* It makes it so the block-processing logic in `append_block()` will reject a block whose parent is in a different epoch and who has a parent microblock.
* It makes it so the anchored block miner will not confirm a microblock stream if the anchored block it produces builds on a parent in a different epoch.
The test coverage here is only in `miner.rs` -- there is no neon integration test.  This is because in order to test this new consensus behavior, we need fine-grained control over how the blocks and microblocks get …

2.05: make it so a block whose anchored parent is in a different epoch cannot confirm a microblock stream

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/stacks/miner.rs
src/clarity_vm/clarity.rs
src/clarity_vm/tests/epoch_switch.rs
src/core/mod.rs
src/net/chat.rs
src/net/mod.rs
src/net/neighbors.rs
src/net/p2p.rs
src/net/relay.rs
src/vm/database/clarity_db.rs
src/vm/docs/mod.rs
src/vm/tests/mod.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/integrations.rs

This PR repurposes the lowest byte in the `peer_version` field in the `Preamble` struct so that p2p messages can inform remote peers of their _maximum supported_ epoch.  For 2.0, this field is ignored, but the value in all 2.0 nodes right now is `0x00` on mainnet and `0x01` on testnet.  For 2.05 and up, this value must be `0x05` or later once the 2.05 epoch activates (on both mainnet and testnet).  Before the epoch activates, a 2.05 peer will accept connections from either a 2.0 peer or a 2.05 peer.
This PR alters the `is_preamble_valid()` method in `ConversationP2P` to enforce the above constraints. If the remote peer's epoch marker in the `peer_version` field is greater than or equal to the local node's epoch marker, then the connection is accepted.  If it isn't, then as long as the …

Stacks 2.05: make p2p network reject connections from 2.0 peers after the epoch switch

---

src/chainstate/stacks/boot/costs-2-testnet.clar
src/chainstate/stacks/boot/costs-2.clar
src/chainstate/stacks/boot/mod.rs
src/clarity_vm/clarity.rs
src/vm/analysis/tests/costs.rs
src/vm/tests/costs.rs
src/vm/tests/mod.rs

This PR implements #2894 and #2890 -- using the cost contract from the latest results in the `clarity-benchmarking` repository.
SIP-012 hasn't been updated with these costs yet, but will be.
This PR expands the costs unit tests to instantiate and use the costs-2 contract for cost tracking.

Instantiate `costs-2.clar` with latest results from benchmarking

---

src/chainstate/burn/db/sortdb.rs

This alters the migration behavior of the SortitionDB -- on connect, it inserts epochs when migrating. On open(), if the database isn't migrated, it errors.

Fix: insert epochs on migration in SortitionDB::connect

---

src/net/chat.rs
src/net/db.rs
src/net/neighbors.rs
src/net/p2p.rs
src/net/rpc.rs

This PR updates the peer database query logic to only select for neighbors whose peer version epoch marker meets or exceeds a given epoch marker, which in turn is derived from whatever epoch the node is currently in.  A 2.05 node running in the 2.0 epoch will return neighbors with either `0x00` or `0x05` as their epoch marker, but a 2.05 node running in the 2.05 epoch will only return neighbors with `0x05` (note that the neighbors returned depends not on the epochs the node supports per se, but on where the node is in processing the burnchain).  The logic here prevents a node from serving neighbors that are no longer compatible with the current consensus rules to peers that ask for them -- either via `/v2/neighbors` or via a `GetNeighbors` p2p request.

Stacks 2.05: only report neighbors in the current or later epoch

---

src/chainstate/stacks/boot/costs-2.clar

This syncs the (seemingly last) set of changes from SIP-012 to the `costs-2.clar` contract in `next-costs`.

chore: sync costs-2.clar with SIP-012

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/db/mod.rs
src/core/mod.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/run_loop/neon.rs

This fixes #2899 by adding a top-level `check_chainstate_db_versions()` method in `src/chainstate/coordinators/mod.rs` that inspects the sortition DB and chainstate DB, and verifies that their current schemas are supported in the given epoch (if they exist at all).  I made the `RunLoop::start()` method in the neon node invoke this early in its initialization, so that if the node is starting from existing chainstate, it will abort if the epoch of the last sortition processed is not supported by either of the chainstate schemas.  I added a unit test to `src/chainstate/stacks/coordinator/tests.rs` that verifies that an epoch 2.0 sortition DB and epoch 2.0 chainstate DB cannot be opened if the system is in epoch 2.05.
In writing this, I also refactored the code for generating directories and …

Stacks 2.05: make the node abort if it starts in epoch 2.05 but still has epoch 2.0 chainstate

---

src/clarity_vm/clarity.rs
src/vm/costs/mod.rs
src/vm/mod.rs

Per some discussion on #2940 -- the existing LimitedCostTracker's split free/limited implementation was very brittle, and a simple refactor into an enum would fix that. This PR is a pure refactor of the LimitedCostTracker into that enum. The scope of the changes are pretty limited: none of the LimitedCostTracker's fields were exposed outside the `costs/mod.rs` file.

chore: refactor LimitedCostTracker into Free and Limited variants

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/neon_integrations.rs

No new features in this PR; this just fixes #2912 by adding an integration test to verify that we can pack a *lot* more compute power into a microblock stream after the 2.05 epoch transition.

Stacks 2.05: add integration test to verify that the miner can pack a 2.05-sized epoch into a microblock stream

---

.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
.github/workflows/bitcoin-tests.yml
.github/workflows/stacks-blockchain.yml
codecov.yml

Codecov does not need a token to be provided when uploads are from a public repository:
https://docs.codecov.com/docs/frequently-asked-questions#where-is-the-repository-upload-token-found
This removes the codecov token (which is also a defunct token) from our codecov.yaml.

Chore: remove token from codecov.yml

---

src/chainstate/coordinator/tests.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/miner.rs
src/chainstate/stacks/mod.rs
src/net/mod.rs

Fixes #2914
Added `setup_block` and `finish_block` to consolidate some logic in block assembly. 
Refactored following functions:
- `epoch_begin` in `miner.rs`
- `append_block` in `chainstate/stacks/db/blocks.rs`
Reviewer notes: 
- The one change I'm aware of between the existing implementation and my refactor is that the follower used to panic if the call to `get_stacks_block_anchored_cost` fails (when getting the parent execution cost). The code now returns an error. I can make this panic if need be. 
To review this, I went through the code paths of both the follower and miner and ensured all the logic was being executed. 
- follower: checked that all the lines in `append_block` are still being called (and in a order that still makes sense). 
- miner: checked that the logic in …

Refactor: merge block assembly paths for follower and miner

---

CHANGELOG.md
src/cost_estimates/pessimistic.rs
src/cost_estimates/tests/cost_estimators.rs

This change adds a field to the pessimistic cost estimator's lookup key. It doesn't change the table schema, so it's compatible with existing cost estimator tables, though it will end up resetting cost estimates. This change allows the cost estimator to differentiate between contracts with different contract senders. In most respects, this PR is a fix for incorrect behavior on the part of the pessimistic estimator, but I'm not sure this rises to the level of necessitating a hotfix, as the cost estimator's current behavior still allows miners to progress the network, albeit slightly less efficiently. If necessary, though, this could be rebased as a hotfix very easily (the patch is essentially a one line change).

Feat: update pessimistic cost estimator to differentiate by contract sender

---

testnet/stacks-node/src/config.rs

fixes https://github.com/blockstack/stacks-blockchain/issues/2991
1) Create a directory `chainstate/estimates`
2) Ensure this exists
3) Use this for the new estimation db's

fix: Create a separate directory for `estimates` tables

---

.github/workflows/bitcoin-tests.yml
.github/workflows/stacks-blockchain.yml

This adds cancel-in-progress behavior to our PR Github actions, where if you push new commits to a PR, it cancels any in progress actions associated with that PR.

CI: add cancel in progress behavior to PR actions

---

src/chainstate/burn/db/sortdb.rs

This PR improves querying the canonical chain tip by a couple orders of magnitude, using this One Weird Trick (tm).
It improves network responsiveness considerably, and probably also helps chain boot-up (but I need to test this to get an actual number).
It's so much faster on the Foundation's public node that RPC queries that used to take ~200 ms now take 0 ms.  I don't even know what the true multiplier is.  I'm dumbfounded that we didn't find this sooner.
Please consider adding to 2.05.0.1.0.

fix: significantly increase the speed of most RPC endpoints

---

README.md

Removes the `Hiro PBC regtest network` step from the release process in the README, as the regtest network has been decommissioned late 2021.
- API reference/documentation update
No

chore: remove regtest from release process in readme

---

.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.generic.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
src/chainstate/stacks/miner.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This updates the MinedBlock event's serde serialization to do hex serialization of the txid. Previously, the txid would be serialized like a number array.

Fix: MinedBlock event txid

---

.github/workflows/stacks-blockchain.yml

CI already builds and uploads a `macos-arm64` target, but it's not included as an asset in releases. This adds the macos-arm64 build in the `create-release` job.

Fix: add macos-arm64 builds to releases

---

Cargo.lock
Cargo.toml
clarity/Cargo.toml
testnet/puppet-chain/Cargo.toml
testnet/puppet-chain/src/main.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/monitoring/prometheus.rs
testnet/stacks-node/src/tests/neon_integrations.rs

It looks like #2990 was caused by a bug in an dependency (used by the event observer, so it's only being invoked on configured listeners).
This PR updates the relevant dependencies, which required a few lines of code changes as well.

Chore: Update async-h1 and related dependencies

---

testnet/stacks-node/src/run_loop/neon.rs

Download headers *before* trying to find the first sortition block header.

fix: download headers before instantiating burnchain

---

src/chainstate/stacks/db/blocks.rs
src/monitoring/mod.rs
src/monitoring/prometheus.rs

We want to log a bunch of new metrics (#3024). This one adds "block fullness", which we have been talking about lately. 
This supports ingestion of this data into prometheus without needing to launch a custom server.
This PR logs the 5-dimensional `ExecutionCost` for the just seen block in the `append_block` function run by the followers and miners.
No testing yet! Since this is for diagnostics, we can hook it up to the prometheus monitoring system and see if it looks right.

feat: Prometheus Block Fullness Metrics

---

CHANGELOG.md
src/chainstate/coordinator/mod.rs
src/net/p2p.rs
src/net/relay.rs

2 metrics weren't as correct as they should be.
- `stacks_node_stacks_tip_height` was moved to the relayer. in tests, this proved to be a more effective location to track the data vs what `/v2/info` was reporting
- moved `stacks_node_neighbors_*` out of the pruning loop. this resulted in the metric being set more often, but the actual count of neighbors was far more accurate when compared to `/v2/neighbors`
- no changes were made to the mempool tx metric, to get this more accurate will be a far heavier lift. leaving for future work
- script used for testing: https://gist.github.com/wileyj/881eda423366134bc25e3fb5ec39ccbb
Some existing metrics were not as correct/up to date as they should be compared with `/v2` output.
- `stacks_node_stacks_tip_height` was moved to the relayer. 
- moved …

updating metrics for issue 2987

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
benches/block_limits.rs
benches/large_contract_bench.rs
benches/marf_bench.rs

Merged changes from master into the side branch. 
This branch was created to resolve merge conflicts between develop and master for release 2.05.0.1.0.

Release 2.05.0.1.0 merge

---

Cargo.toml
clarity/Cargo.toml
testnet/stacks-node/Cargo.toml

This fixes an issue in `develop` currently where the `slog-json` feature wasn't propagating to the necessary dependencies of `stacks-node`.

Fix: slog-json feature in `develop`

---

testnet/stacks-node/src/config.rs

Fixes https://github.com/stacks-network/stacks-blockchain/issues/3098.  Sets the new time to 30s, based on real-world benchmarks with `develop`.

fix: set the default subsequent-attempt time to 30s

---

build-scripts/Dockerfile.linux-arm64
build-scripts/Dockerfile.linux-armv7
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.linux-x64
build-scripts/Dockerfile.macos-arm64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64

A recent cargo/rust change made the build arg `--workspace` error if a value was provided, since then all platform dist builds have been broken in CI with an error message like:
```
#9 ERROR: process "/bin/sh -c cargo build --release --workspace=./ --target x86_64-unknown-linux-gnu" did not complete successfully: exit code: 1
------
> [build 6/7] RUN cargo build --release --workspace=./ --target x86_64-unknown-linux-gnu:
#0 0.080 error: The value '=./' was provided to '--workspace' but it wasn't expecting any more values
```
This PR should fix that.

fix: CI error while building dist files

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/coordinator/mod.rs
src/net/p2p.rs
src/util_lib/db.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/neon.rs

This PR fixes a couple of boot-up issues related to schema migrations and always-allowed peers when booting a 2.05.0.2.0-rc1 peer.  In particular:
* This PR fixes a runtime panic that arises when booting from genesis due to the unavailability of the first block snapshot.
* This PR fixes a runtime panic that arises when booting from non-migrated chainstate due to needing the first block snapshot before attempting migrations to the latest schemas.
* This PR makes it so that the public key of an always-allowed peer is reset from the config file on each boot-up.
* This PR makes it so that an always-allowed peer is only considered to have timed out if it has replied to a previous message first (this is specific to always-allowed peers since they are always considered authenticated, which …

Bootup fixes for 2.05.0.2.0-rc1

---

testnet/stacks-node/src/node.rs

With the changes to the event handling in `develop`, the mocknet node (`node.rs`), was broadcasting duplicate events. This doesn't really effect any production nodes, but would impact people using this for testing.

Fix mocknet events in RC

---

CHANGELOG.md
src/chainstate/stacks/index/file.rs
src/chainstate/stacks/index/storage.rs
src/chainstate/stacks/index/trie_sql.rs
src/util_lib/db.rs

This fixes #3121 by making it so the MARF migration code to move trie blobs to a .blobs file will vacuum the DB periodically during the migration (i.e. every 4096 blocks).  I've confirmed this works on a live setting -- the database file now shrinks over the course of the migration.

fix: incrementally vacuum the MARF DB when migrating

---

clarity/src/vm/analysis/arithmetic_checker/mod.rs
clarity/src/vm/analysis/errors.rs
clarity/src/vm/analysis/read_only_checker/mod.rs
clarity/src/vm/analysis/type_checker/natives/conversions.rs
clarity/src/vm/analysis/type_checker/natives/mod.rs
clarity/src/vm/analysis/type_checker/tests/mod.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/functions/conversions.rs
clarity/src/vm/functions/mod.rs
clarity/src/vm/tests/simple_apply_eval.rs
clarity/src/vm/types/serialization.rs
src/clarity_vm/tests/costs.rs

This PR adds `to-consensus-buff` and `from-consensus-buff` methods to the `Clarity2` native methods.
- Implements #2693 by allowing arbitrary Clarity types to be transformed into buffers
- Implements the buffer serialization aspects of the https://github.com/stacksgov/sips/pull/57 proposal
These methods are both fallible -- this may be surprising in the case of `to-consensus-buff`, but the reason is that some legal Clarity values serialize into buffers that are larger than the maximum Clarity value size; this is because of the type prefix and length encoding.
The typing of `to-consensus-buff` produces a buffer size which is the maximum possible buffer size for its input. In the case of uints, ints, and bools this is always correct. For other types, however, it will be an overestimate in …

Implement consensus de/serialization in Clarity

---

contrib/core-contract-tests/tests/bns/name_register_test.ts

The latest version of clarinet (that this repo is using, by using the tag `latest`) is not backward compatible with previous versions of the typescript bridge.
This PR is updating the version of the library being imported.

fix: use latest clarinet test lib

---

.vscode/extensions.json

The `matklad.rust-analyzer` vscode rust extension changed its ID to `rust-lang.rust-analyzer` in Feb 2022.
See https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html
This fixes the vscode error prompt due to the no longer existent plugin ID being specified.

chore: update vscode rust-analyzer extension ID

---

src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/miner.rs

This fixes #3140 by considering the evaluated epoch of a matured miner reward's block's parent.  If the parent block was evaluated in epoch 2.1, then the correct 40/60 fee split begins to occur between the parent and child blocks' miners (as it should have been).  Before this happens, the buggy behavior described in #3140 continues to happen.
Do not merge until #3142 is merged, since it depends on code in that branch.

Fix/microblock fees 

---

src/clarity_cli.rs

This PR adds support for a `--c` flag to gather code coverage when using `clarity-cli`. I'm really just re-adding functionality that got squashed when https://github.com/stacks-network/stacks-blockchain/pull/2592 was merged.
Requesting review from @kantai , as I'm mainly copying the code from his PR.
This also closes #3160.

feat: add coverage flags to clarity-cli

---

CHANGELOG.md
src/chainstate/stacks/miner.rs
src/core/mempool.rs
src/core/tests/mod.rs

#2975 added "compiler-enforced logging" to the mining paths, to make sure each transaction outcome was logged. The idea with "compiler-enforced logging" is that the type system is used to make it very hard/impossible to forget to log a transaction outcome.
However, there were still some changes for outcomes to not be logged.
This PR moves the requirement to output a "transaction outcome" object up a level, to `MemPoolDB::iterate_candidates`, to which the `todo` function must now return an `Option<TransactionEvent>`, which are then collected and output by `iterate_candidates`.
Now there be no chance to forget to log an outcome, except for the "drawback" listed below.
- fixes #3130
Drawback:
* `iterate_candidate` asks that `todo` return an `Option<TransactionEvent>`, returning `None` if the …

fix: add logging for some tx outcomes that were missing

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs
testnet/stacks-node/src/tests/neon_integrations.rs

- Address TOML config parsing issues from https://github.com/stacks-network/stacks-blockchain/issues/2511
- Added a new subcommand `check-config` to enforce config parsing without starting the node.
Example config parsing error:
```
$ cargo stacks-node check-config --config=config-test.toml
INFO [1655834280.871193] [testnet/stacks-node/src/main.rs:82] [main] stacks-node 0.1.0 (validate-config:892d64c5c, debug build, macos [aarch64])
INFO [1655834280.872547] [testnet/stacks-node/src/main.rs:115] [main] Loading config at path config-test.toml
WARN [1655834280.875656] [testnet/stacks-node/src/main.rs:129] [main] Invalid config: node.seed should be a hex encoded string
```
where `config-test.toml` is
```
[node]
seed = "bad-hex-string"
```

chore: TOML config parser improvements

---

CHANGELOG.md
src/chainstate/stacks/db/blocks.rs
src/monitoring/mod.rs
src/monitoring/prometheus.rs

Adds output to prometheus for "transactions in last block".
We don't currently have any way to get this value from existing outputs, and want to add it to the dash.

feat: Add tx/block to prometheus outputs

---

src/monitoring/mod.rs

This fixes a build error in `develop` currently.

Fix type error in monitoring_prom build

---

.github/actions/bitcoin-int-tests/Dockerfile.code-cov
CHANGELOG.md
src/net/db.rs

This fixes #3165 by storing the new private key given to `PeerDB::connect()` to `local_peer` if it is `Some(..)`.

fix: store the private key to local_peer if given to PeerDB::connect()

---

clarity/src/vm/analysis/type_checker/natives/mod.rs
clarity/src/vm/analysis/type_checker/natives/sequences.rs
clarity/src/vm/analysis/type_checker/tests/mod.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/functions/principals.rs
clarity/src/vm/tests/principals.rs

I discovered two mismatches between the typechecker and the runtime in new Clarity functions.
This PR fixes those mismatches, and adds a typing test to the documentation self-tests. This ensures that the typechecker's inferred types for all the examples admit the resulting value.

Fix in `next`: Type mismatches on new functions

---

CHANGELOG.md
stacks-common/src/util/log.rs

Adds the environment variable `BLOCKSTACK_FORMAT_TIME` to use human-readable time:
```
$ cargo stacks-node check-config
INFO [1658776091.841531] [testnet/stacks-node/src/main.rs:82] [main] stacks-node 0.1.0 (human-time:8a83e72f31+, debug build, macos [aarch64])
ERRO [1658776091.841989] [testnet/stacks-node/src/main.rs:58] [main] Process abort due to thread panic: panicked at 'called `Result::unwrap()` on an `Err` value: MissingOption(Keys(["--config", ""]))', testnet/stacks-node/src/main.rs:113:71
ERRO [1658776092.441379] [testnet/stacks-node/src/main.rs:60] [main] Panic backtrace:    0: backtrace::backtrace::libunwind::trace
```
```
$ STACKS_LOG_FORMAT_TIME="%Y-%m-%d %H:%M:%S" cargo stacks-node check-config
INFO [2022-07-25 14:09:58] [testnet/stacks-node/src/main.rs:82] [main] …
```

Adds human-readable time to logger

---

clarity/src/vm/docs/mod.rs

There is no mention of microstacks in this documentation, which could be
confusing for new developers. This commit specifies the units for the
amounts used in  `stx-get-balance`, `stx-account`, `stx-transfer?` and
`stx-burn?`.
I did not see any consistency with line-wrapping, so I just eye-balled it to something that looked reasonable compared to the existing strings, but would be happy to make changes to that if you want.
One thing I am unclear on is whether https://docs.stacks.co/docs/write-smart-contracts/clarity-language/language-functions gets generated from this file or if I should also open a PR one that repo.
N/A
N/A - documentation improvement only

docs: clarify amounts in microstacks

---

clarity/src/vm/docs/mod.rs

Change the docs so that Functions and Keywords are sorted by name.
This change was proposed in the comments of #2716.
- towards #2716

feat: Sort keywords and functions by name in the docs

---

src/burnchains/burnchain.rs

Minor tweak to the initial burnchain header sync. If no headers are synced, add a small delay before retrying. 
Without a retry delay, if the bitcoind rpc endpoint isn't yet ready, this function pegs system resources and generates a ton of logs in a brief period of time. 
This happens when spinning up bitcoind regtest environments in something like docker-compose. There of course are other work arounds with deployment & configuration scripts that try to wait for bitcoin rpc to be ready before initializing the stacks-node, but it's cumbersome and this tweak is cleaner IMO.

fix: avoid pegging system resources during initial header sync when bitcoind rpc isn't yet available

---

.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.generic.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
clarity/src/vm/clarity.rs
clarity/src/vm/contexts.rs
clarity/src/vm/database/clarity_db.rs
clarity/src/vm/database/structures.rs
clarity/src/vm/types/mod.rs
src/burnchains/burnchain.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox-2.clar
src/chainstate/stacks/boot/pox_2_tests.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/miner.rs
src/clarity_vm/clarity.rs
src/clarity_vm/database/mod.rs
stacks-common/src/util/log.rs

This PR implements automatic unlocks for PoX 2.
Stackers who do not qualify for a slot in a reward set when the reward set is selected will be automatically unlocked after the reward set is selected. The auto unlock occurs 1 bitcoin block after the auto-unlock.
This requires a _lot_ of complexity in `pox-2`. This PR adds a test for the simple use case, but probably more testing is needed.

PoX 2 Unlock

---

.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.generic.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis

This fixes the currently broken CI by using rust stable for all our testing. `grcov` is for some reason broken in _only one_ of the Docker actions, so the coverage doesn't get uploaded from the unit tests, but fixing that can be done separately from just fixing the build.

CI: use rust stable for code coverage tests

---

docs/rpc/api/core-node/get-pox.example.json
docs/rpc/api/core-node/get-pox.schema.json
src/net/mod.rs
src/net/rpc.rs

Fixes https://github.com/stacks-network/stacks-blockchain/issues/3262
Fixes the `contract_id` value in the `GET /v2/pox` response, along with the associated contract variables, so that it uses the active PoX contract.
Also adds an additional properties to the response in order to help clients perform the correct Stacking operations.
The `contract_versions` array which exposes contract ID and PoX activation information for each PoX version, and a simple `current_burnchain_block_height` property so that clients do not have to perform an additional lookup to `/v2/info` for the value while constructing a PoX transaction. 
Example:
```json
{
"contract_id": "ST000000000000000000002AMW42H.pox-2", <-- fixed
"first_burnchain_block_height": 0,
"current_burnchain_block_height": 123, <-- new …
```

Add PoX-2 info to `/v2/pox` RPC endpoint

---

clarity/src/vm/database/structures.rs
src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/boot/pox-2.clar
src/chainstate/stacks/boot/pox_2_tests.rs
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/mod.rs
src/clarity_vm/database/mod.rs
src/clarity_vm/special.rs

This PR adds two new methods to `pox-2`:
* `stack-increase`: this method increases the lockup for the stacker, and adds the new amount to the reward sets of the remaining cycles for the user
* `delegate-stack-increase`: this method increases the lockup for the supplied stacker, adding the new amount to the partially-stacked state
As part of this work, this also removes the `total-ustx` field from the `stacking-state` map. The rationale for this is to normalize some of the state in the PoX-2 contract: this field is not used for any checks, but it would be "replicated" in several other states: that's at least the `stx-account` lock amount and the reward-set entries for the stacker in each cycle. Because of the "increase" methods, the `total-ustx` field would either be out of sync with the …

2.1: Feature: `stack-increase` for PoX-2

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/stacks/db/mod.rs

The current db version <-> epoch checks in `next` do not work -- on restarting a node, the DB version cannot run in 2.1. If restarted while in "Epoch 1.0", that also will cause a panic.
This PR changes the version/epoch checks to make it possible to restart in 2.1, and to make Epoch 1.0 supported by all DB versions.

2.1 Fix: usable version checks for DBs and epochs

---

.github/actions/bitcoin-int-tests/Dockerfile.code-cov
.github/actions/bitcoin-int-tests/Dockerfile.generic.bitcoin-tests
.github/actions/bitcoin-int-tests/Dockerfile.large-genesis
src/core/mempool.rs

This PR implements two changes in the mempool iteration:
1. Defunc'ing of the fee_estimates table
2. Only deserialize txs that are going to actually be considered
This is still a draft while testing is under way both for performance and correctness.

Hotfix: denormalize mempool iteration, only deserialize considered txs

---

.github/workflows/ci.yml

This disables the arm64 builds since they overwrite the amd64 builds. 
https://hub.docker.com/r/blockstack/stacks-blockchain/tags
This will be superseded by https://github.com/stacks-network/stacks-blockchain/pull/3199 which will re-enable arm64 builds.

disable arm64 builds

---

clarity/src/vm/docs/mod.rs

Documents the corner cases for `pow`
- fixes #3295

docs: add details for corner cases of `pow`

---

.github/workflows/bitcoin-tests.yml
clarity/src/vm/ast/mod.rs
clarity/src/vm/ast/parser/mod.rs
src/burnchains/bitcoin/spv.rs
src/chainstate/burn/db/sortdb.rs
src/clarity_vm/tests/large_contract.rs
src/net/p2p.rs
src/net/relay.rs
stacks-common/src/deps_common/bitcoin/network/encodable.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR just backports some missing unit and integration tests from 2.05.0.3.0 that we simply forgot to include in the release.

Chore/unittests 2.05.0.3.0

---

src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/miner.rs
src/core/mempool.rs
src/core/tests/mod.rs
testnet/stacks-node/src/config.rs

This is the cleaned up version of `simple-iterator` discussed in #3326 and #3313.
To-do before checking in:
* verify that a snapshot chainstate creates a DB with the right query plan
* can do as part of bringing up mock miner from snapshot.. then can check the query plan

Mempool improvements

---

.github/workflows/bitcoin-tests.yml
src/burnchains/mod.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/coordinator/tests.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/epoch_21.rs

This addresses #3346.  It's much the same as the code that added the epoch 2.05 marker:
* It modifies the consensus logic for `LeaderBlockCommitOp` to require an epoch 2.1 marker in the `memo` bits after Epoch 2.1
* It changes the miner to use the epoch 2.1 marker when mining (this is backwards-compatible with epoch 2.05)
* It adds test coverage for both validating `LeaderBlockCommitOp`s in epoch 2.1 as well as mining through the epoch 2.1 transition.
~~Note that this is currently based on PR #3358, so let's get that merged first.~~ EDIT: this is now ready

Feat/3346: epoch marker for LeaderBlockCommitOp

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

This fixes a regression from the recent merge from master into next: https://github.com/stacks-network/stacks-blockchain/pull/3358/files#diff-06a6e88675e542d59fefd0f0e8b3738028510b196074d2a7c77a07f79383a79cL317-R348. The ability to configure pox-2 activation block height in regtest mode no longer worked.
This function
```rs
fn default_burnchain(config: &Config) -> Burnchain {
let (network_name, _network_type) = config.burnchain.get_bitcoin_network();
let working_dir = config.get_burn_db_path();
let mut burnchain = Burnchain::new(&working_dir, &config.burnchain.chain, &network_name)
.expect("Failed to instantiate burnchain");
config.update_pox_constants(&mut burnchain.pox_constants);
burnchain
}
```
was refactored and the `update_pox_constants` call was dropped:
```rs
fn …
```

[Stacks 2.1] fix: regression with pox_2_activation config

---

testnet/stacks-node/src/event_dispatcher.rs

- fixes #3258
1) Replace "recipient" field with the generalized recipient (currently it's hard-coded to miner).
2) Use "miner_address" to encode the miner address.
* waiting to see how the tests do on CI

fix: Miner rewards event for alternative recipients

---

clarity/src/vm/events.rs
src/clarity_vm/special.rs

Resolves https://github.com/stacks-network/stacks-blockchain/issues/3413
Adds the pox contract ID used to the `stx_lock_event` payloads. This is working as expected in API integration tests. Not sure if it needs test changes in this repo as well. 
This follows the same convention used in the similar `contract_event` payload of including `contract_identifier: string` in the event JSON.

[Stacks 2.1] Include pox contract in `stx_lock_event` payloads

---

clarity/src/vm/types/signatures.rs

fix: resolve regressions in Clarity1 type-checking

---

clarity/src/vm/analysis/type_checker/tests/mod.rs
clarity/src/vm/types/signatures.rs

`ListUnionType` and `CallableType`s need to be concretized before
checking if they can be admitted.

fix: concretize `other` in `admits_type`

---

src/burnchains/mod.rs
src/chainstate/coordinator/tests.rs

Change the reporting of the active contract to use pox_2 after v1_unlock_height instead of at v1_unlock_height.
Fixes #3422

pox-2 is default contract at v1_unlock_height+1

---

src/core/mod.rs

There is no functional difference, since the 2.05 and 2.1 block limits
are identical, but this could cause confusion or a problem later on if
something changes.
- fixes #

fix: use 2.1 block limits

---

stacks-common/src/util/hash.rs

These minor changes are helpful for other users of stacks-common, specifically, subnets.

chore: expose some of the hash functions as public

---

clarity/src/vm/ast/parser/v1.rs
src/net/http.rs

With the addition of the v2 parser, some of the regex expressions were
moved up to representations.rs so that they could be shared and reused.
This has proven to be a problem, because the strange behavior of the v1
parser was not preserved (e.g. allowing long contract names in
contract-call parameters, but not in contracts).
Fixes: #3470

fix: revert all regex changes in the v1 parser

---

clarity/src/vm/analysis/type_checker/v2_1/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts.rs
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts/compute.clar
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts/impl-compute.clar
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts/use-compute.clar
clarity/src/vm/types/signatures.rs

A trait processed during epoch 2.05 which contains a trait type for one
of its parameters will have a `TraitReferenceType` in its function
signature. This behavior changed when we split off the updated
type-checker and continued to run the old one in 2.05, but this one case
was not modified accordingly.
Fixes: #3489
- fixes #

fix: handle `TraitReferenceType` in 2.1

---

clarity/src/vm/analysis/type_checker/v2_1/mod.rs

This is related to #3490, but handling the type check for arguments to contract call transactions.

fix: fix arg-check for passing 2.05 trait in 2.1

---

.github/workflows/bitcoin-tests.yml
.idea/stacks-blockchain.iml
CONTRIBUTORS.md

Updated the `stacks-bitcoin-integration-tests` workflow file to allow running the workflow through the GitHub UI. This can be helpful if a workflow was manually stopped for any reason.

chore: enable manual start of btc integration test workflow 

---

.github/workflows/bitcoin-tests.yml
.github/workflows/ci.yml
clarity/src/vm/ast/errors.rs
clarity/src/vm/ast/parser/v2/mod.rs

This addresses #3541 by eliminating the recursion in `parse_list` and `parse_tuple` (which were the only recursive calls in `parse_node()`.  It replaces that recursion with a do-while loop in `parse_node()`. The return value of `parse_node()` is unchanged: it still returns the next expression at the "current level" of the AST, however, for list and tuple expressions, it does this without invoking `parse_node()` again.
To do this, I added a new enum for open tuple expressions and open list expressions (i.e., expressions which are waiting on child nodes), and broke the logic from `parse_list` and `parse_tuple` into the handlers for those open expressions. This means that the logic is now more spread out than before, and relies on the `parse_node()` loop.
- fixes #3541
This makes the V2 AST …

2.1: Eliminate recursion in `parse_list` and `parse_tuple`

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/epoch_21.rs

This PR doesn't add any new features.  It just increases test coverage by verifying that PoX 2 will activate if it is instantiated at the very end of a reward cycle, and the v1 unlock height passes at the very beginning of the next.

[testing] Add integration test to verify that v1 unlock height and epoch 2.1 work as expected

---

clarity/src/vm/analysis/arithmetic_checker/tests.rs
clarity/src/vm/analysis/contract_interface_builder/mod.rs
clarity/src/vm/analysis/mod.rs
clarity/src/vm/analysis/type_checker/v2_05/tests/contracts.rs
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts.rs
clarity/src/vm/analysis/types.rs

It can be useful for clients to know during which epoch a contract was
published. This was a specific request from the Clarinet team.

feat: add epoch to abi RPC endpoint

---

README.md
src/chainstate/stacks/db/accounts.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/tests/block_construction.rs
src/core/tests/mod.rs
src/net/relay.rs
src/util_lib/bloom.rs

I stumbled upon some more tests with concurrency issues, with the same old root cause of copy-pasted hard-coded test names. Took the opportunity to spread the usage of our `function_name!()` macro.

Fix: more hardcoded test names

---

clarity/src/vm/docs/mod.rs

The api reference for `principal-construct` and `principal-destruct` was built with the wrong argument
---
Idea: An other option would be to pass `function` (and do it for every other `make_for_simple_native` calls here) to limit the risk of having the same issue in the future
```rust
PrincipalDestruct => make_for_simple_native(&PRINCPIPAL_DESTRUCT_API, &function, name),
PrincipalConstruct => make_for_simple_native(&PRINCIPAL_CONSTRUCT_API, &function, name),
```
I wanted to limit the footprint of my PR but let me know if I should perform this change 
N/A
Improve the LSP.
The output type is displayed in VSCode (and other editors) on hover 
N/A

docs: fix principal -construct -destruct api reference

---

CHANGELOG.md
src/chainstate/stacks/db/transactions.rs

When top-level code in a contract publish causes a runtime error, the transactions should be accepted, but the contracts should not be created, and that is the existing behavior of the stacks blockchain.
However, the transaction receipts for these transactions do not indicate that a failure occurred. This leads to pretty confusing API and explorer results. This PR fixes that by returning a receipt with result set to `(err none)`
- fixes #3154

Fix: Transaction receipts for runtime errors in contract publish

---

CONTRIBUTORS.md

Adds documentation explaining how to locally setup a pre-commit hook
- fixes #3570

[eng quality] pre-commit hook docs

---

CHANGELOG.md
testnet/stacks-node/src/config.rs

Testnet nodes currently do not sync with the default config.  This is because at reward cycle 360, the 2.05 PoX anchor block rules differ from the 2.1 rules -- 2.05 believes that there is an anchor block, while 2.1 does not.
A while back, we added a config option `always_use_affirmation_maps` which forced the node to use the 2.1 rules all the time.  This was meant to allow us to stress-test #2707.  The value for this config option defaults to `true`, meaning that the node uses the 2.1 rules by default in epoch 2.05.  While this isn't a problem on mainnet, it prevents nodes from syncing on testnet due to the above.
This PR switches this config option's default value to `false`.

fix: always_use_affirmation_maps defaults to false

---

CHANGELOG.md
src/chainstate/stacks/db/transactions.rs

feat: add `vm_error` to analysis failure receipts

---

clarity/src/vm/docs/mod.rs

Fixed places in the docs that used `None` or `(none)`.

Consistent use of `none` in docs

---

CHANGELOG.md
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/run_loop/neon.rs

This PR reduces the chain-liveness poll frequency. This was driving the issues facing Hiro's testnet miner yesterday.

Fix: reduce chain-liveness poll frequency

---

CHANGELOG.md
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/tests/block_construction.rs
src/core/mempool.rs
src/main.rs
src/net/p2p.rs
src/net/relay.rs
src/net/rpc.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tenure.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/mempool.rs
testnet/stacks-node/src/tests/mod.rs

This fixes the mempool admission behavior in #3623 by supplying a pointer to the current burn state (sortition db) to the mempool admission logic.
Will update this PR with regression testing before merging.
- fixes #3623

Fix: Incorporate unlocks in mempool admitter, #3623

---

src/net/mod.rs
src/net/p2p.rs

When working on tests for the microblock tip sync protocol, I realized that `ibd` was set to true in the call to `TestPeer::step()`. Since `ibd=true`, the mempool (and microblock) sync protocol were effectively skipped over in the unit test. To avoid this problem, I am passing ibd as a parameter to `step_with_ibd`. 
The mempool sync tests are now fast (because the protocol now runs correctly), so I was also able to remove the timeout. I thus also removed the `#[ignore]` above the tests.

fix/ updated mempool sync protocol tests

---

src/burnchains/burnchain.rs

Incremental refactor PR to clean up deprecated variable name.
Rename burn_chain_tip to burnchain_tip to normalize naming conventions
- https://github.com/stacks-network/stacks-blockchain/issues/2779

:truck: Rename burn_chain_tip to burnchain_tip

---

CONTRIBUTING.md

@jcnelson:
> Even if GPT-4 produced perfect, bug-free code (which I very much doubt), it's not even clear that we could use it for licensing reasons. GPT-4-generated code is a derived work from other peoples' code, which may not be GPL-compatible (and we don't know who these people are, so there's no way we could get them to sign the CLA)
> 
> I think for now, we should have a very strict policy of no AI-generated code. We should add that to the CONTRIBUTING file.

Add AI code policy

---

src/chainstate/burn/operations/peg_out_request.rs

This PR adds a `PegOutRequestOp::stx_address()` method to derive the stacks address of an sBTC holder requesting to peg out.
Closes https://github.com/stacks-network/stacks-blockchain/issues/3647

[sBTC] Add stx_address method to PegOutRequestOp

---

clarity/src/vm/docs/mod.rs

This PR adds information about `stx-get-balance` in the docs to clarify the the return value is the unlocked balance of the user.

Update documentation of stx-get-balance

---

src/core/mod.rs
testnet/stacks-node/src/config.rs

Sample config.toml and `/v2/pox` RPC response:
```toml
[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0
[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 103
[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 104
[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 106
[[burnchain.epochs]]
epoch_name = "2.2"
start_height = 108
[[burnchain.epochs]]
epoch_name = "2.3"
start_height = 109
[[burnchain.epochs]]
epoch_name = "2.4"
start_height = 110
```
```json
{
"contract_id": "ST000000000000000000002AMW42H.pox-3",
"pox_activation_threshold_ustx": 600057388429055,
"first_burnchain_block_height": 0,
"current_burnchain_block_height": 132,
"prepare_phase_block_length": 1,
"reward_phase_block_length": 4,
"reward_slots": 8,
"rejection_fraction": 3333333333333333, …
```

feat: allow epoch2.2 through epoch2.4 to be configured in regtest mode

---

CHANGELOG.md
clarity/src/vm/analysis/errors.rs
clarity/src/vm/types/signatures.rs
src/chainstate/stacks/db/transactions.rs

This is a high-priority hotfix for an issue that could impact miner availability.

Hot fix: yield too large supertype from checks

---

clarity/src/vm/docs/mod.rs
src/chainstate/stacks/boot/contract_tests.rs
src/chainstate/stacks/miner.rs
src/core/mempool.rs
src/cost_estimates/pessimistic.rs
src/deps/httparse/mod.rs
src/main.rs
stacks-common/src/deps_common/bitcoin/blockdata/transaction.rs

This is a chore PR to merge PR #3735.

Chore: replace u32::max_value() with u32::MAX

---

.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
.github/workflows/image-build-alpine-binary.yml
.github/workflows/image-build-debian-binary.yml
.github/workflows/image-build-debian-source.yml

Resolves an issue with the dockerhub repo being named differently than the github org https://github.com/stacks-network/stacks-blockchain/actions/runs/5193175067
reverts the image name from the testing repo of `${{ github.repository }}` (i.e. `stacks-network/stacks-blockchain`) -> `blockstack/${{ github.event.repository.name }}` (`blockstack/stacks-blockchain`)
https://hub.docker.com/u/blockstack

hardcode the dockerhub org

---

.github/actions/docsgen/Dockerfile.docsgen

updates `.github/actions/docsgen/Dockerfile.docsgen` to use bullseye rather than stretch for the base image. 
This action has not been completing successfully in a while, some of the package repos are 404'ing during the build phase. 
Example failures: https://github.com/stacks-network/stacks-blockchain/actions/runs/5052004488/jobs/9064421170

Update docs-pr base image

---

CONTRIBUTING.md

The `cargo fmt` command recommended to include in the `pre-commit` hook will run on all files, instead of just the changed files as intended. This change uses `rustfmt` to just run on one file at a time as intended.

docs: use `rustfmt` instead of `cargo fmt` in pre-commit

---

.github/workflows/bitcoin-tests.yml

ex: https://github.com/stacks-network/stacks-blockchain/actions/runs/5510601197
not sure of the root cause here, but the last i had checked this docker image was around 8GB in size. 
there *should* be plenty of space available on the runner (historically this has been true) - so either the free space is less now for some reason, or we're using more space than we have in the past. 
this is a test workaround that does 3 things:
1. prints`dh -f` output
2. runs [this action](https://github.com/jlumbroso/free-disk-space/releases/tag/v1.1.0) to reclaim space
2. prints `df -h` output again

workaround to failing actions for "no space left"

---

src/chainstate/stacks/miner.rs
src/monitoring/mod.rs
src/monitoring/prometheus.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/keychain.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Adds prom metrics for last mined block. 
This PR also includes a fix to a bug introduced in Epoch 2.1, related to segwit addresses. Essentially, there was a mismatch between the representation of the miner address stored for prometheus and the representation of the miner address within the decoded LeaderBlockCommitOp. 
To fix this, it was necessary to update the representation of the miner address within the prometheus related code. 
- fixes #3263

Add prom metrics for last mined block

---

stacks-common/src/util/hash.rs

compiler warning on parenthesis
- fixes #3817

minor compiler fix

---

Cargo.toml
clarity/Cargo.toml
stackslib/Cargo.toml

Workspace level profiles

---

CHANGELOG.md
src/chainstate/stacks/db/transactions.rs

Add `txid` to logs for errors during a contract deploy transaction. The transaction id is not currently included in these logs, and it makes finding the errors more difficult.
- none

Add txid to contract deploy logs

---

CHANGELOG.md
testnet/stacks-node/conf/mainnet-follower-conf.toml
testnet/stacks-node/conf/mainnet-miner-conf.toml
testnet/stacks-node/conf/mainnet-mockminer-conf.toml
testnet/stacks-node/src/config.rs

This PR adds 3 new bootstrap nodes to the default list alongside the existing `seed.mainnet.hiro.so` node. 
Sample configs are also adjusted to add these 3 extra nodes. 
the three regionally diverse nodes:
- est.stacsknodes.org @`54.91.222.127` (EST timezone)
- cet.stacksnodes.org @`3.122.176.89` (CET timezone)
- sgt.stacksnodes.org @`52.77.118.154`  (SGT timezone)
Simple test to ensure they're being loaded at runtime (via `stacks-node mainnet` on this branch):
```
➭ curl -sL localhost:20443/v2/neighbors | jq -r
{
"bootstrap": [
{
"network_id": 1,
"peer_version": 402653193,
"ip": "35.194.79.91",
"port": 20444,
"public_key_hash": "6d6ce48c436ecd4bb0f7549f944c1a5321c2339c",
"authenticated": true,
"stackerdbs": []
},
{
"network_id": 1,
"peer_version": 402653193,
"ip": "52.77.118.154", …
```

Adding more default bootstrap nodes

---

testnet/stacks-node/src/config.rs

reverts an unintended change in #3899 where the xenon (testnet) bootstrap nodes were changed. 
this PR reverts that line to the previously used value. 
```
bootstrap_node: Some("029266faff4c8e0ca4f934f34996a96af481df94a89b0c9bd515f3536a95682ddc@seed.testnet.hiro.so:20444".to_string()),
```

revert change to xenon bootstrap node list

---

CONTRIBUTING.md

Current pre-commit hook in docs pipes `stderr` to /dev/null. This is how it ignores non-Rust files, but it also allows broken code in Rust files. I changed to use `grep` to filter out files that don't end in `.rs` instead
Also, I changed it to use `xargs`, which results in less code and allows it to check multiple files in parallel

docs: Fix pre-commit hook, and simplify/parallelize using `xargs`

---

CHANGELOG.md
stackslib/Cargo.toml

This is a follow up to #3955. I previously missed the fact that `stackslib` enabled `developer-mode` in the default feature set. This should not be the case.
- fixes #3945

Fix developer mode issue

---

src/core/mempool.rs

The warning about failing to cache mempool nonces shows up very often during normal execution of the node. It should not be a warning. This PR lowers it to a debug message.
```
error caching nonce to sqlite: database is locked
```
- fixes #

fix: lower warning about mempool nonce caching to `debug!`

---

.github/workflows/bitcoin-tests.yml
Cargo.lock
stacks-signer/Cargo.toml
stacks-signer/src/main.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/tests/signer.rs

`wsts`, like many rust libraries, uses the `tracing` crate for logging.  This PR subscribes to the `tracing` logs using the default `RUST_LOG` environmental variable, which allows setting log levels on a per-module basis, in both the `stacks-signer` binary and the `signer::test_stackerdb_dkg` integration test.
- fixes #

Enable signer tracing

---

.github/workflows/stacks-blockchain-tests.yml
pox-locking/src/events.rs
pox-locking/src/lib.rs
pox-locking/src/pox_1.rs
pox-locking/src/pox_2.rs
pox-locking/src/pox_3.rs

Closes https://github.com/stacks-network/stacks-blockchain/issues/3937
To run clippy ONLY in pox-locking:
`cargo clippy -p pox-locking --no-deps --tests --all-features `

Address clippy complaints in pox-locking repo

---

libsigner/src/runloop.rs
stacks-signer/src/cli.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs

This PR is ongoing, fixing bugs are required (found through testing stacker db on mainnet)

Bugfixes for signer when testing CLI through mainnet develop node

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
clarity/src/vm/analysis/errors.rs
clarity/src/vm/analysis/type_checker/v2_05/tests/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/tests/mod.rs
clarity/src/vm/ast/mod.rs
clarity/src/vm/ast/parser/v1.rs
clarity/src/vm/ast/parser/v2/mod.rs
stacks-common/src/types/net.rs
stacks-common/src/util/hash.rs
stacks-common/src/util/log.rs
stacks-common/src/util/macros.rs
stacks-common/src/util/pipe.rs

- fixes #3979
- fixes #4020 
- fixes #4021 
- fixes #4022
- see #3934

Enable clippy in CI

---

.github/workflows/image-build-alpine-binary.yml
.github/workflows/image-build-debian-binary.yml
.github/workflows/image-build-debian-source.yml

Fix related to recent repo name change. 
@CharlieC3 
https://github.com/search?q=repo%3Astacks-network%2Fstacks-core%20github.event.repository.name&type=code
Fix is simple - add an extra docker tag to push an image to the `stacks-blockchain` docker repo, along with an image using the new name `stacks-core`

Add new docker tag to address repo name change

---

contrib/side-cars/fee-estimate.sh

This PR adds a small side-car script to `contrib/side-cars/fee-estimate.sh` which can both report the latest sats/vbyte fee reported from Blockcypher, and continuously update a miner's config file with that fee.  This builds on @tippenein and @AcrossFireX's work [here](https://github.com/stacks-network/stacks-core/issues/4073).

[Node] side-car script to get sat/vbyte fee estimations

---

clarity/src/vm/docs/mod.rs

This just fixes some errors in one of the examples in the docs. No code changes.
- N/A

docs: fix invalid example in docs

---

stackslib/src/chainstate/stacks/db/transactions.rs
stackslib/src/net/api/tests/mod.rs
stackslib/src/net/atlas/download.rs
stackslib/src/net/download.rs
stackslib/src/net/p2p.rs
stackslib/src/net/stackerdb/config.rs
stackslib/src/util_lib/db.rs
stackslib/src/util_lib/strings.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

Fix compiler warnings while running `cargo build` and `cargo test`
Also fix doc comment in `stackslib/src/net/stackerdb/config.rs` that was incorrectly interpreted as a doc test and failing, causing an error

fix: Address warning messages and errors in `cargo build` and `cargo build`

---

contrib/core-contract-tests/tests/bns/name_register.test.ts
contrib/core-contract-tests/tests/bns/name_register_test.ts

Epoch 2.4 introduced an extra block in the simnet start sequence, causing names to expire one block later than before. This fixes the failing tests in `feat/pox-4`.
- fixes failing tests in https://github.com/stacks-network/stacks-core/pull/4085

Argon: Pox 4 - Adjust Lease Timing for Epoch 2.4 Compatibility in BNS tests

---

clarity/src/vm/types/signatures.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_22.rs
testnet/stacks-node/src/tests/epoch_23.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer.rs
testnet/stacks-node/src/tests/stackerdb.rs

fix: #2810 
This simply uses a HashSet for `event_observers` which means it might not be exactly what the issue asked for but I'm putting it here for discussion. It wouldn't be particularly hard to WARN in the case of inserting an event observer which is already specified, but maybe it's sufficient to just disallow it?
(didn't add any tests because it ends up just testing HashSet's insert..)

Fix: duplicate events

---

contrib/side-cars/config/fee-estimate.json
contrib/side-cars/config/stacks-block-delay-event-trigger.json
contrib/side-cars/fee-estimate.py
contrib/side-cars/stacks-block-delay-event-trigger.py

This Draft PR contains two python scripts that handle two different needs.
1. `fee-estimate.py`updates the miner toml value `satoshis_per_byte` with the current estimate averaged between multiple fee estimation APIs.
2. `stacks-block-delay-event-trigger.py` runs a specified binary when the stacks block is created too long after a bitcoin block.
- Documentation of these can be found within the docstrings of the corresponding files.
- Reasonable defaults that require user defined values can be found under `./contrib/side-cars/config/` for both scripts/
- fixes ongoing issues; will create an issue after this draft is loosely considered to be needed.
The user will need to install python and a few dependencies when they run for the first time, but that will be very easy to detect as the …

Add sidecar scripts for fee estimation and stacks block delay detection

---

Cargo.lock
Cargo.toml
stacks-signer/Cargo.toml
stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/runloop.rs
stacks-signer/src/stacks_client.rs
stacks-signer/src/utils.rs
stackslib/Cargo.toml
stackslib/src/chainstate/stacks/mod.rs
stackslib/src/chainstate/stacks/transaction.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/tests/signer.rs

Update `wsts` to `v5.0.0`
This commit also contains the following changes:
- Make `ThresholdSignature` wrapper around `wsts::common::signature` in order to use `verify()`
- Eliminate `p256k1` from `Cargo.toml`
- Use a common version of `wsts` for all workspace members
I had to update all workspace members, including `stacks-signer`, because it wouldn't build if `stackslib` was using a different version of `wsts`

chore: Update `wsts` to `v5.0.0`

---

clarity/src/vm/clarity_wasm.rs

We return the `index` instead of the increment in the Tuple's match branch in `wasm_to_clarity_value` .
Added tests will be in the [`clarity-wasm` repo](https://github.com/stacks-network/clarity-wasm).

Fix wrong return value in `wasm_to_clarity_value`

---

clarity/src/vm/functions/mod.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

Set `maxburncap` argument in `sendrawtransaction` to allow the miner to submit transactions with burns (specifically to send to the `OP_RETURN` output, which is why only one test failed: only "sunset" burns fit in the category).
This was new behavior in Bitcoin 25.0: https://bitcoin.org/en/releases/25.0/#updated-rpcs
- Fixes the `neon_integrations::pox_integration` test

fix: set maxburncap to 1BTC in sendrawtransaction (new in Bitcoin 25.0)

---

.github/workflows/atlas-tests.yml
.github/workflows/bitcoin-tests.yml
.github/workflows/create-cache.yml
.github/workflows/epoch-tests.yml
.github/workflows/slow-tests.yml
.github/workflows/stacks-core-tests.yml

use bitcoin 25.0 for tests

---

.github/workflows/ci.yml

this is a minor fix in how the CI triggers due to issues noticed downstream in `next`. 
pull_request_target is not working the way that was expected, in that it is building against the target branch, and not the base branch. 
this commit fixes that. 
once merged, a second PR from develop-> next will be opened.
this is also addressed in master in https://github.com/stacks-network/stacks-core/pull/4160

use pull_request to trigger ci runs

---

.github/workflows/bitcoin-tests.yml
stacks-signer/src/runloop.rs
stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/mockamoto/tests.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR adds support to the nakamoto node for interim block mining (i.e., blocks within the current tenure) with a configurable wait time between such blocks. This PR also refactors the `chainstate::nakamoto::miner` module to match the actual usage of the miner interfaces, and moving the `TestPeer` specific method out into `TestPeer` itself.
This adds a new `nakamoto_integration` test which mines 10 nakamoto tenures, each with 2 blocks in the tenure.

Nakamoto-Node: Support for interim block mining

---

stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/runloop.rs
testnet/stacks-node/src/tests/signer.rs

`stacks-signer` is currently using a very basic `wsts` `Coordinator` implementation that doesn't handle non-responsive or malicious signers.  This has been fine for testing so far, but for Nakamoto we will need to sign all blocks using `wsts`, so we have to handle these and other errors.
`wsts` has a better `Coordinator` which supports the `FIRE` meta-protocol; it uses timeouts to handle non-responsive signers, returns errors identifying malicious signers, and correctly identifies when the number of malicious and/or non-responsive signers is large enough to make progress on any round impossible.
This PR therefore enables the `FIRE` coordinator.
- fixes #4169

Enable `FIRE` coordinator for `stacks-signer`

---

stacks-signer/src/runloop.rs
stackslib/src/chainstate/nakamoto/mod.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This fixes two issues surfaced by the interim blocks mining in nakamoto-node.
1. The IssueBlock directive should use the tenure block _not_ the chain tip block for the directive. The interim-mining integration test has been updated to deal with this.
2. `calculate_matured_miner_rewards` should use the `coinbase_height`, not the block height. This was caught by running a long-running node with interim mining turned on, rather than an integration test. There's no integration test for this new behavior, but there probably should be. The issue surface from a panicking assertion because the 150th Stacks block had a coinbase height < 100, so the maturity lookup returned an empty list, triggering a panic. In testing mode, the maturity height is _2_, which means that it would be hard to surface …

Nakamoto Fixes: IssueBlockCommit and Reward Maturity Lookups

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/tests/neon_integrations.rs

The stacks miner's bitcoin operation handling tracks submitted transactions via the `ongoing_op` mechanism. When deciding whether or not to attempt an RBF, it checks if the `ongoing_op` has been confirmed. Currently, it does this via the burnchain_db, however, this will not work if the transaction is confirmed, but it was unparseable. In this case, the miner will continuously attempt to RBF an already confirmed transaction, leading to bitcoin mempool rejections.
This scenario surfaced during the nakamoto "controlled testnet" testing through a pretty convoluted series of events:
1. The neon_node (required for booting through epochs 2.0-2.5) is set to mine very quickly (i.e., very low `wait_on_blocks` time)
2. The regtest bitcoind network is set to mine a new block whenever it sees a …

Fix: RBF-mechanism should check bitcoin RPC

---

Cargo.lock
stackslib/src/chainstate/stacks/boot/docs.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/clarity_vm/clarity.rs
stackslib/src/net/api/getpoxinfo.rs
testnet/stacks-node/src/mockamoto/tests.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR removes `pox-reject` from pox-4 and relevant code in boot/mod.rs
- fixes #4108

pox-4: remove pox-reject

---

stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR adds pox4 signer key read/write and useful helpers to interact with pox4 functions. The focus is to add base Rust tests to be used as a foundation for upcoming work items like #4059, #4058, #4147, and so on. There is also a basic check to make sure that a signer key is 33 bytes and to prevent key reuse. 
- #3970
- #4207
I kept this PR as narrow as possible for the purpose of unblocking other work and to (hopefully) make a merge straightforward. Processing the signer keys, calculating the aggregate key, and the signer StackerDB work is slated for subsequent PRs.
Comprehensive PoX4 smart contract tests will also be introduced in a different PR. (Pending `clarunit` tooling.)

PoX-4 signer key read/write with base Rust tests

---

stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/net/p2p.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR fixes the "burn output" selection in the nakamoto-node to use `get_nakamoto_next_recipients()`. It also includes a refactor of the `get_reward_set()` invocations in nakamoto to pass in the cycle start height (as is done in 2.x) rather than "current burn height". This eliminates the need for the `+ 1` in the reward cycle number (commit eee3f20e78842abe0bb68eaf8fe60f70a3f49917)
* Includes a test with alternating stackers, this ensures that the reward set changes between each cycle. Improper handling of `get_next_recipients()` would cause a block-commit to be rejected (and the test to fail).

Fix: commit burn out selection in nakamoto-node

---

testnet/stacks-node/src/monitoring/mod.rs
testnet/stacks-node/src/monitoring/prometheus.rs
testnet/stacks-node/src/run_loop/boot_nakamoto.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR:
1. Updates the prometheus thread to return errors to the JoinHandle rather than panicking in an unchecked async task. The PR doesn't change the behavior to _handle_ or _exit_ on the error, it retains the previous behavior of "basically just issue a warning but otherwise execute the node". 
2. Stores the thread's `JoinHandle` to the runloop struct.
3. Moves the `JoinHandle` from the neon runloop to the nakamoto runloop (if the `boot_nakamoto` loop needed to start the neon runloop). If the nakamoto runloop has a thread handle, it doesn't attempt to spawn a new prometheus thread.
4. Extends the `nakamoto_integrations::simple_neon` test to check the prometheus output before and after nakamoto block processing.
- fixes #4214

Fix: nakamoto-node shouldn't respawn prometheus thread

---

testnet/stacks-node/conf/testnet-follower-conf.toml
testnet/stacks-node/conf/testnet-miner-conf.toml
testnet/stacks-node/src/config.rs

Relevant forum post with details: https://forum.stacks.org/t/minor-network-changes-and-dns-updates-on-january-16th-2024/16125
I made two PRs to propogate this change to `master` and `develop` branches quickly.
Related PR: https://github.com/stacks-network/stacks-core/pull/4237
Updates the testnet Hiro bootstrap nodes to use a different port for the testnet seeds.
~DO NOT MERGE UNTIL CHANGES ARE LIVE (Est Jan 16th, an update will be made to the forum post).~
Good to merge!

master: update default testnet hiro bootstrap node

---

clarity/src/vm/clarity_wasm.rs

This PR fixes a few inconsistencies between reading and writing of values in Wasm memory.
The tests for this PR will exist in the [clarity-wasm repo](https://github.com/stacks-network/clarity-wasm), since those issues are linked to property testing in this repo.

Clarity-Wasm: fix inconsistencies between reading and writing values in memory

---

stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/block.rs
stackslib/src/chainstate/stacks/mod.rs
stackslib/src/chainstate/stacks/transaction.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

Related to closing #3932 -- TenureChange payloads don't need stacker signatures, because stackers have to sign the block header, which incorporates the TenureChange payload in its tx hash.
The signer binary doesn't need to do anything special to validate these payloads: they have to sign off on blocks anyways, and the content of tenure change transactions is validated by the stacks-node's block proposal validation endpoint already.
Conveniently, this also doesn't place much of a burden on the stacks-node miner either: the nakamoto-neon miner was already constructing tenure change transactions in self-signing-mode , so this PR just makes it construct those transactions all the time.
Closes #4258

Nakamoto: remove stacker signature fields from tenure change payload

---

stacks-signer/src/config.rs

Make `DKG` fully robust against non-participation

---

clarity/src/vm/clarity_wasm.rs

This PR fixes the reading of in-memory values in `link_set_variable_fn` for clarity-wasm.
This is the exact same issue as in `define-data-var` in #4259.
As in the other PR, the tests will happen in the clarity-wasm repo.

Fix clarity-wasm linked function for `var-set`

---

stackslib/src/net/api/liststackerdbreplicas.rs
stackslib/src/net/api/mod.rs
stackslib/src/net/api/tests/liststackerdbreplicas.rs
stackslib/src/net/api/tests/mod.rs
stackslib/src/net/db.rs
stackslib/src/net/mod.rs
stackslib/src/net/stackerdb/sync.rs

Got one quick PR for the upcoming 2.4.0.1.0 release -- the ability to ask a node for the list of nodes it knows replicate a given StackerDB.  If a user adds a StackerDB replica to their node, they can assess how quickly other (public) nodes learn of it.

Feat: add an endpoint for listing which nodes host a stackerdb replica
