stacks-network/stacks-core

stackslib/src/chainstate/stacks/boot/pox-4.clar

The `signer-key` arg was added in the wrong position in the `delegate-stack-extend` function. It broke the pox4 synthetic event generation here:
https://github.com/stacks-network/stacks-core/blob/2684ce5adb6692592a5b19963987441905acf759/pox-locking/src/events.rs#L287-L289
Error messages:
```
ERRO [1706021370.455103] [pox-locking/src/events.rs:437] [chains-coordinator-0.0.0.0:20443] Failed to run data-info code snippet for 'delegate-stack-extend': Unchecked(TypeValueError(UIntType, Sequence(Buffer(2296955a3ce00133e4eeaaeb62a667a77c42f71004bb0e4ee3118750b09e67fd22))))
ERRO [1706021370.455261] [pox-locking/src/events.rs:457] [chains-coordinator-0.0.0.0:20443] Failed to synthesize PoX event: Unchecked(TypeValueError(UIntType, Sequence(Buffer(2296955a3ce00133e4eeaaeb62a667a77c42f71004bb0e4ee311 …
```

Fix pox4 delegate-stack-extend

---

stackslib/src/burnchains/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/boot/contract_tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/chainstate/stacks/boot/signers.clar
stackslib/src/chainstate/stacks/boot/signers_tests.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/clarity_vm/clarity.rs
stackslib/src/net/mod.rs

Now rebased onto #4269.
Work in progress that adds:
- PoX4 changes, takes signer key `(buff 33)` parameter where needed, converts and stores them as `principal`.
- The `.signers` StackerDB contract.
- Uses #4269 Nakamoto `make_reward_set()` to calculate the signer slots.
- Fills in the mocks/todos in #4269 pertaining to the signers.
- Writes the signer set to `.signers`.
- Basic unit tests that Stacks using two different signer keys and checks they exist in the signers StackerDB contract.
As for the coupling of PoX reward slots and signer keys we have some open questions. (#4247 and others.)
This PR should unblock @friedger's work on the `.voting` boot contract.
Addresses:
- #4058
- #3980
- #3957

.signers StackerDB contract and PoX 4 signer key changes

---

Cargo.lock
Cargo.toml
stacks-signer/Cargo.toml
stacks-signer/src/client/mod.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/runloop.rs
testnet/stacks-node/src/tests/signer.rs

Introducing a deterministic but dynamic signer coordinator selection by hashing signer public keys and stacks tip consensus hash. 
- Relates to #3915
- Not exactly a VRF selection so still open if a more complex selection process is needed.
- Selection is similar to the approach discussed [here](https://github.com/stacks-network/sbtc/discussions/335); but stacks_tip_consensus_hash is used instead of latest sortition VRF seed
- Signer Integ. tests are updated to use the calculate_coordinator instead of picking the coordinator statically .

Select stacks-signer coordinator dynamically

---

.github/workflows/docs-pr.yml
clarity/src/vm/docs/mod.rs

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
NA

Use GITHUB_OUTPUT envvar instead of set-output command as the latter is deprecated

---

stacks-signer/src/config.rs

This small change makes the `stackerdb_contract_id` config variable for the signer an optional field. When it isn't provided, it defaults to `BOOT_CODE_ADDR.signers`.
Although all testing (unit and functional) is currently done with "mock" contracts, it might make sense to wait for #4263 before merging. We can also choose to merge this into that PR.

feat: default to `.signers` boot contract in signer config

---

libsigner/src/events.rs
libsigner/src/tests/mod.rs
stacks-signer/src/runloop.rs

I've been documenting the workflow for running the signer, and I think it would be helpful to expose a `GET /status` endpoint to help setup and monitor the signer. This PR responds with `200 OK` for that endpoint.
Note that this could potentially conflict with an event observer path in the future. I'm not sure if the Stacks Blockchain API exposes a similar endpoint on the event receiver, but if so, we should follow use same route. @zone117x does that exist?
I could also imagine having an endpoint similar to `/v2/status` on the node, where more helpful state is returned, but I'm not sure how much we want to expose the fact that a specific IP is running a specific signer.

Add `/status` endpoint to signer

---

libsigner/src/tests/mod.rs

https://github.com/stacks-network/stacks-core/pull/4280 modified a test in `libsigner` to test the `/status` endpoint. Because I didn't realize that the test signer thread was configured to exit after 5 events, I designed the test wrongly. Tests would pass locally and sometimes on CI, but I realized later that the tests would sometimes [fail](https://github.com/stacks-network/stacks-core/actions/runs/7702938804/job/20992694860?pr=4277) in CI because a thread would receive an event before it was shutdown.
This PR:
- Removes the `/status` endpoint testing in the original test
- Adds a new test that's specifically for the status endpoint

fix: modify test_simple_signer to fix intermittent failure

---

pox-locking/src/events.rs

In #4329 (just merged) one of the synthetic events used an incorrect arg index in the print for `stack-stx`.
I also noticed that `stack-aggregation-increase` and `stack-aggregation-commit` have diverged argument signatures - `-increase`'s third arg is `reward-cycle-index`, whereas `-commit`'s third arg is `signer-key`. I've made a separate `match` branch to reflect this change.

fix: incorrect arg index in synthetic event

---

stackslib/src/chainstate/stacks/boot/signers-voting.clar
stackslib/src/chainstate/stacks/boot/signers_voting_tests.rs

As discussed during Un/block meeting, the simplest/fastest solution for #4231 is simply to update the print statement found in 'vote-for-aggregate-public-key.'
The node will then take this information & then check whether the consensus threshold was met / a new aggregate public key has been submitted. 
Since this is a simple print statement update there are no additional test to write.

Updated Vote Print Statement

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
clarity/src/vm/database/clarity_db.rs
clarity/src/vm/errors.rs
docs/rpc/api/core-node/get_stacker_set.400.example.json
docs/rpc/api/core-node/get_stacker_set.example.json
docs/rpc/openapi.yaml
stackslib/src/burnchains/burnchain.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/signer_set.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/signers.clar
stackslib/src/chainstate/stacks/boot/signers_tests.rs
stackslib/src/chainstate/stacks/boot/signers_voting_tests.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/net/api/getstackers.rs
stackslib/src/net/api/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Implement #4295 and #4298
Implementation of #4295 is kind of subtle, and will have to impose additional constraints on Epoch-2.5 (one of which isn't implemented in this PR, but could be added, I suppose). 
Reading the reward set state from the calculation performed for `.signers` is only possible _after_ that calculation is performed (due to the general nature of causality and the linear passage of time). This calculation is performed during the first block of a prepare phase. This does not pose a challenge for nakamoto, because that's the block it chooses as the PoX anchor block anyways, so, of course it can read that data. For Epoch 2.5, however, this _is_ a challenge: the PoX anchor block always comes _before_ the prepare phase.
To deal with this, this PR splits the reward set loading …

Reward set calculation and RPC endpoint

---

clarity/src/vm/analysis/type_checker/contexts.rs
clarity/src/vm/clarity_wasm.rs
clarity/src/vm/types/signatures.rs

This PR fixes two issues for Clarity-Wasm:
1. The representation in memory is only two Wasm values, but we tried to read 22 (+`name`),
2. Creating lists of qualified principal would make both the compilation and the evaluation crash, because those would be typed as `ListUnionType`, which does not have a defined representation in our ABI.
Those fixes are extensively tested with property testing in the Clarity-Wasm repo.

Clarity-Wasm: fixes for the `principal` type

---

stackslib/src/chainstate/coordinator/comm.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/cost_estimates/tests/common.rs
stackslib/src/net/p2p.rs
testnet/stacks-node/src/nakamoto_node/peer.rs

This implements #4328 by adding a signaling bool to the coordinator channels structs. It's a bit cludgier than I would otherwise want, but I think it's the best we can do without majorly refactoring the coordinator's signatures (which is probably a good idea, but one best left to the future).
This is a draft for now, because it depends on `feat/larger-stackerdb`, but it could be cherry-picked/rebased to `next` instead.

Feat: trigger stackerdb refresh when .signers is written

---

CHANGELOG.md
pox-locking/src/events.rs
stacks-common/src/util/secp256k1.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/net/tests/mod.rs
stackslib/src/util_lib/mod.rs
stackslib/src/util_lib/signed_structured_data.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer.rs

This closes #4247, which is to ensure that all Signers are using signing keys that they either control, or are controlled by the account they're delegating to.
- closes #4247 
This is done by adding a `signer-sig` param to:
- stack-stx
- delegate-stack-stx
- stack-aggregation-commit
The signature follows [SIP018](https://github.com/stacksgov/sips/blob/main/sips/sip-018/sip-018-signed-structured-data.md) for signed structured data. Following SIP018 has the benefit of built-in wallet support, so signers can use hardware wallets and apps to generate these signatures. 
Following SIP018, the structured data is `{ reward-cycle, reward-cycle }`, where `reward-cycle` is the _current_ stacking cycle where the transaction is made. The `domain` is `{ app: "pox-4-signer", version: "1.0.0", chain-id …

feat: require signatures to prove control of `signer-key` in pox

---

Cargo.lock
Cargo.toml
libsigner/src/messages.rs
stacks-signer/src/runloop.rs

Update `wsts` dependency to get malicious DkgPrivateShares handling

---

Cargo.lock
Cargo.toml
stacks-signer/Cargo.toml

fix building & cross compilation, including `stacks-signer`, tested building for the following:
* linux-glibc-x86-64
* linux-glibc-arm64
* linux-glibc-armv7
* linux-musl-x86_64
* linux-musl-arm64
* linux-musl-armv7
* windows-x86_64
* macos-x86_64
* macos-arm64
ty @wileyj and @hugocaillard

fix: buids on various archs/platforms

---

Cargo.lock
Cargo.toml
stacks-signer/Cargo.toml

ref:  https://github.com/stacks-network/stacks-core/pull/4331
these are the equivalent changes for `master` and `develop`. 
fix building & cross compilation, including stacks-signer, tested building for the following:
- linux-glibc-x86-64
- linux-glibc-arm64
- linux-glibc-armv7
- linux-musl-x86_64
- linux-musl-arm64
- linux-musl-armv7
- windows-x86_64
- macos-x86_64
- macos-arm64
*note*: target branch here is for develop since there is a workaround in place already in `master`. this change won't affect that workaround the next time develop is merged to master
cc: @zone117x @hugocaillard

fix: builds on various archs/platforms re: PR 4331

---

stackslib/src/burnchains/burnchain.rs
stackslib/src/chainstate/stacks/db/transactions.rs
stackslib/src/main.rs
stackslib/src/net/inv/epoch2x.rs

Add `stacks-inspect replay-block` command to validate blocks. This already exists on various branches in the repository, but IMO is extremely useful and should be in `next`
This is currently failing on some blocks. I don't know if it's a problem with the command, or there have been consensus breaking changes in `next`. Example of a failing block:
```console
❯ cargo build --release --bin=stacks-inspect
❯ target/release/stacks-inspect replay-block /home/jbencin/data/
...
Failed processing block! block = 0002e2d15493097bf26309cdf0b121d1fd240c458621fe66469d2b226ecb361d, error = InvalidStacksBlock("Block 9a3c37a60075192c8d1b4355d0efbc766781e291e6ca0656411b7a3c9e438ab0 state root mismatch: expected ae68136f3d621d4c3f8097f1973d04069540a6a0888551f1b541e2a61faf87cc, got …
```

test: Add `replay-block` command

---

.github/workflows/github-release.yml

During workflow testing a release in a downstream fork, an unexpected error kept surfacing:
```
Poetry could not find a pyproject.toml file in /github/workspace or its parents
```
https://github.com/wileyj/stacks-blockchain/actions/runs/7878083852/job/21495965471#step:4:11
updating this specific action's commit to the latest release v1.0.1 resolves the immediate issue. 
we'll be moving this workflow out of this repo (possibly refactoring it using bash or something, since it's a simple task that really shouldn't fail due to a python dependency).

[CI] fix error in release step that generates checksums

---

clarity/src/vm/database/clarity_db.rs
pox-locking/src/events_24.rs
pox-locking/src/lib.rs
stacks-signer/src/runloop.rs
stackslib/src/burnchains/mod.rs
stackslib/src/burnchains/tests/affirmation.rs
stackslib/src/burnchains/tests/db.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/core/mod.rs
stackslib/src/net/mod.rs
stackslib/src/net/tests/inv/epoch2x.rs
stackslib/src/net/tests/mod.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_22.rs
testnet/stacks-node/src/tests/epoch_23.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This fixes two issues in `next` which result in changes to the evaluation of stacks blocks prior to Epoch 2.5 (i.e., the first hardfork epoch of `next`).
The first issue was relatively straightforward and is solved by 999fe9bd29cde5a3b248e2ece1b2511bcfaa1731. The automatic unlocks for `pox-3` lockups in preparation for `pox-4` must be applied on `Epoch25`, _not_ `Epoch24`.
The second issue was more difficult to diagnose because its a little more subtle (and therefore scarier!) but it is solved by 
6f0936a69f55918bd93a87e132d743a36902ea95. PoX event synthesis, introduced for `pox-2` and `pox-3`, assesses a cost in the block limit. This means that any changes to those functions is consensus-critical. I don't think that this is a great position to be in with those synthesis functions, …

Fix(Nakamoto): Block evaluation issues in `next`

---

Cargo.toml

Enable "fat" link-time optimization. This will slow down the linking stage of release builds slightly, but will allow the linker to optimize the code better by optimizing over the entire dependency graph
A quick benchmark with `hyperfine` shows an improvement of **1%** in processing the first 3000 blocks:
```console
❯ hyperfine -w 3 -r 10 "stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000" "stacks-core.next/target/release/stacks-inspect.lto-fat replay-block /home/jbencin/data/next/ first 3000"
Benchmark 1: stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000
Time (mean ± σ):     31.134 s ±  0.073 s    [User: 27.134 s, System: 3.852 s]
Range (min … max):   31.038 s … 31.303 s    10 runs …
```

chore: Enable "fat" link-time optimizations for release builds

---

Cargo.lock
Cargo.toml
clarity/Cargo.toml
stacks-common/Cargo.toml
stacks-common/src/address/c32.rs
stacks-common/src/util/vrf.rs
stackslib/Cargo.toml
stackslib/src/burnchains/bitcoin/network.rs
stackslib/src/burnchains/tests/burnchain.rs
stackslib/src/chainstate/burn/mod.rs
stackslib/src/cost_estimates/tests/fee_rate_fuzzer.rs
stackslib/src/net/neighbors/neighbor.rs
stackslib/src/net/neighbors/walk.rs
stackslib/src/net/prune.rs

As part of Brice working to unify the `TestSigners` and `SelfSigner` structs, etc., it became clear that having multiple versions of the various rand libraries was going to create headaches. This PR sets workspace versions for `rand`, `rand_core`, and `rand_chacha`, as well as updates `ed25519-dalek` to facilate some unification here.
The biggest interface changes were: `gen_range` accepting a _range_ argument rather than two low, high args, and changes to the `ed25519-dalek` interfaces. As part of this, I removed the `Deref` impls for `VRFPublicKey` and `VRFPrivateKey` -- those were only used to invoke the `as_bytes` and `to_bytes`, so I just added those explicitly. The problem with having `Deref` impls here is that it meant functions like `from_bytes` were overloaded, which I think can …

Chore: ed25519 dalek update in `next`

---

Cargo.lock
Cargo.toml

Update the `wsts` workspace dependency to version `8.1`.
- fixes #

Update wsts workspace dependency to v8.1

---

stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/staging_blocks.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/net/relay.rs
stackslib/src/util_lib/db.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

This actually fixes https://github.com/stacks-network/stacks-core/issues/3860, which was closed prematurely since it was not addressed by PR #3992.  Doing this now because this is a blocker for the block sync system.
This PR creates a separate DB for holding Nakamoto blocks, separate from the DB that holds processed Nakamoto block headers.  The reason this is necessary is because we can expect writes to occur concurrently on both DBs -- the network stack will create transactions against the staging blocks DB to store blocks it receives, and both the miner and chains-coordinator will create transactions on the headers DB as they create / process blocks.  In Stacks today, these two data live in the same DB, and it regularly leads to DB contention since the chains-coordinator's and miner's …

Separate Nakamoto DB for staging blocks

---

.cargo/config
.github/workflows/create-source-binary-x64.yml
.github/workflows/github-release.yml
build-scripts/Dockerfile.linux-glibc-x64
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64

When building for x86_64 CPUs, use the `x86-64-v3` target. This allows the compiler to use newer instructions in order to better optimize the code, like AVX, AVX2, and FMA. This also means older (pre-Haswell or pre-Bulldozer) CPUs won't be supported by default. See [here](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels) for full details.
This would mean than users with 10+ year old CPUs would not be able to use the binaries we distribute, and in order to run `stacks-node` they would have to modify the config and build it themselves
If we are not comfortable with this trade-off, we could build and distribute both `x86-64` and `x86-64-v3` binaries
This gives a small performance boost of about **1.4%** on my Laptop (Intel Core i7-1270P) when processing the first 3000 blocks: …

chore: Drop support for old x86_64 CPUs

---

Cargo.lock
Cargo.toml
stackslib/Cargo.toml
stackslib/src/main.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/main.rs

Use `jemalloc` allocator on supported platforms (non-Windows). `jemalloc` is used by FreeBSD, and used to be the default in Rust, so it should be perfectly safe to use
In the `replay-block` benchmark, this results in a **3.3%** performance improvement:
```console
❯ hyperfine -w 3 -r 10 "stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000" "stacks-core.next/target/release/stacks-inspect.jemalloc replay-block /home/jbencin/data/next/ first 3000"
Benchmark 1: stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000
Time (mean ± σ):     31.078 s ±  0.053 s    [User: 27.011 s, System: 3.903 s]
Range (min … max):   31.000 s … 31.173 s    10 runs
Benchmark 2: …
```

chore: Use `jemalloc` global allocator on supported platforms

---

stacks-signer/src/runloop.rs

Currently, the `next` branch [fails CI](https://github.com/stacks-network/stacks-core/actions/runs/7974981548/job/21772737936?pr=4377) due to this test timing out. The test is vastly revamped in #4287 , so we can ignore it for now. We'll want to make sure @jferrant removes the `#[ignore]` flag in her PR

fix: ignore timing out runloop test

---

CHANGELOG.md
stacks-signer/src/main.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/net/tests/mod.rs
stackslib/src/util_lib/signed_structured_data.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR implements the concept of signer key authorizations, which can be used to allow omitting the `signer-sig` parameter in pox-4 contract calls. This is a pre-requisite to updating the various stacking burn-ops, because this will allow us to handle burn ops without needing to include a signer key signature in the burn op.
Other than adding an authorization mechanism, this changes the `signer-sig` parameters to an `optional`. If the signature is omitted, the contract verifies that an authorization is present.
- closes #4379

feat: allow signer-key authorizations instead of signature

---

codecov.yml

This is an opinionated change - feedback/changes are welcome. 
the current `codecov.yml` reports coverage too early in the process, and is misleading in reporting low coverage.
the changes in this commit aim to defer that status update until most of the tests have completed. 
some notes:
- codecov documentation is infuriating
- a coverage percentage of 80 is set (with a change in 1% being allowed) - this is only relevant if we also enable codecov as a required status check (similar to how we require rustfmt to pass). 
- for the codecov dash, i'm setting anything > 79 as being fully covered, with a range of 60-79 in a "warn" state. this is only relevant for UI coloring, it has no material effect on the coverage detection
- CI is not required to pass to report on coverage (in the case of a …

Fix: only report codecov status after ci

---

.github/workflows/ci.yml

per github docs on merge queus, adds the following to the ci.yml workflow:
```yaml
on:
merge_group:
types:
- checks_requested
```
per: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
this is a required change before we can enable merge queues for the `next` branch.

trigger ci workflow when merge queue requests it

---

clarity/src/vm/analysis/contract_interface_builder/mod.rs
clarity/src/vm/analysis/type_checker/v2_05/mod.rs
clarity/src/vm/analysis/type_checker/v2_05/natives/mod.rs
clarity/src/vm/analysis/type_checker/v2_05/natives/sequences.rs
clarity/src/vm/analysis/type_checker/v2_1/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/sequences.rs
clarity/src/vm/ast/definition_sorter/mod.rs
clarity/src/vm/ast/parser/v2/mod.rs
clarity/src/vm/ast/sugar_expander/mod.rs
clarity/src/vm/ast/types.rs
clarity/src/vm/coverage.rs
clarity/src/vm/database/structures.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/functions/database.rs
clarity/src/vm/functions/mod.rs
clarity/src/vm/mod.rs
clarity/src/vm/types/mod.rs
clarity/src/vm/types/serialization.rs
clarity/src/vm/types/signatures.rs

Replace instances of `Vec::new` and `vec![]` with `vec::with_capacity()` or `.map()`/`.collect()` whenever possible in Clarity code. This should help reduce the number of calls to alloc and realloc
Currently showing about a **2%** improvement:
```console
❯ hyperfine -w 3 -r 10 "stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "stacks-core/target/release/stacks-inspect.vec-capacity replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
Time (mean ± σ):     10.565 s ±  0.039 s    [User: 10.070 s, System: 0.450 s]
Range (min … max):   10.522 s … 10.655 s    10 runs
Benchmark 2: …
```

chore(clarity): Replace `Vec::new()` and `vec![]`

---

stacks-common/src/address/c32.rs
stacks-common/src/deps_common/bech32/mod.rs
stacks-common/src/deps_common/bitcoin/blockdata/script.rs
stacks-common/src/deps_common/bitcoin/blockdata/transaction.rs
stacks-common/src/deps_common/bitcoin/util/hash.rs
stacks-common/src/types/chainstate.rs
stacks-common/src/util/hash.rs

Similar to #4408, but for `./stacks-common`. This PR also removes unnecessary intermediate `Vec`s used by `Vec::append()` by using `Vec::extend_from_slice()` instead
This gives a significant improvement of around **5%**
```console
❯ hyperfine -w 3 -r 10 "stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "stacks-core/target/release/stacks-inspect.vec-allocation-stacks-common replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
Time (mean ± σ):      9.044 s ±  0.020 s    [User: 8.556 s, System: 0.442 s]
Range (min … max):    9.022 s …  9.074 s    10 runs
Benchmark 2: …
```

chore(stacks-common): Improvements to `Vec` allocation and operations

---

.github/workflows/github-release.yml

The action used to generate a checksum for the github release flow (https://github.com/stacks-network/stacks-core/blob/develop/.github/workflows/github-release.yml#L59-L67) had to be updated to a newer version due to an error causing the step to fail. After this issue arose, a quick fix in order to make the action work was merging a PR to the `master` branch (https://github.com/stacks-network/stacks-core/pull/4374). 
The goal of this PR is to move the generation of checksums to composite actions for easier fixes if they are necessary, and do it with bash instead of a predefined action for consistency and significantly lower chances of unexpected failures.
This PR should be merged after the one in `actions` repository is: https://github.com/stacks-network/actions/pull/24
Reference issue: …

Move Checksum Generation to Composite

---

.github/workflows/atlas-tests.yml
.github/workflows/bitcoin-tests.yml
.github/workflows/epoch-tests.yml
.github/workflows/slow-tests.yml
.github/workflows/stacks-core-tests.yml
docs/ci-release.md

Using a composite action to check that multiple jobs which are running tests are successful. 
The called action is succeeding only if all the jobs parsed through the `jobs` input (JSON string of `needs` field) have `success` as status, otherwise it fails.
The purpose of implementing this step is to add the possibility of only making the job that calls the composite required in a ruleset check, instead of having each individual test required (i.e. each job from a matrix strategy).
Reference runs:
- Successful (no test failures): https://github.com/BowTiedDevOps/stacks-core/actions/runs/7978701647?pr=3
- Failed (4 test failures - check jobs also failing): https://github.com/BowTiedDevOps/stacks-core/actions/runs/7979062950?pr=4
- In both of these runs, `Docker Image` is failing because of a …

Check Multiple Tests' Success at Once

---

Cargo.lock
pox-locking/Cargo.toml

@hugocaillard and I have descended into Rust dependency hell.  It was dark and it was scary, but we have found a path to the light and will soon emerge victorious.
Essentially, at some point all roads point to the `clarity` package, and we need to ensure that all dependencies are pointing to the same version of that package. 
```
stacks-core/clarity ← stacks-core/pox-locking ← clarinet/clarity-repl
↖ clar2wasm ← clarinet/clarity-repl
↖ clarinet/clarity-repl ← clarinet/stacks-rpc-client ← chainhook-sdk ← clarinet/stacks-network
```
Because the current `main` branch for `clar2wasm` is using rev `de3e3c679e2db0336b95f1c188a3dae73b3b336f` of clarity, we are using that as a starting point. So, this PR updates the pox-locking package to use that same clarity version.

chore: specify rev for `pox-locking` package's clarity dependency

---

stacks-signer/src/signer.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

@hstove found a bug when operating a single signer with a single key. Essentially the threshold became 0 which causes wsts to panic as it should due to an invalid threshold being provided. @xoloki subsequently pointed out that we actually had a bug in our threshold calculation due to integer arithmatic forcing us to always calculate a threshold "under" our desired amount whenever we had any remainder. This pr forces us to "round up" by adding 0.9 to the result. If any remainder exists, it will force our result over into the next integer amount (note that due to integer math and the nature of dividing by 10, the remainder will always be minimum 0.1 or more hence why adding 0.9 guarantees pushing it over to the next integer if remainder is present).
Due to Joey's suggestion, I have …

Round up thresholds 

---

stacks-signer/src/client/mod.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signer.rs
stackslib/src/chainstate/nakamoto/signer_set.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/net/tests/mod.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer.rs

I simplified the transaction logic and made it the same between signers and miners. It simply filters invalidly formed transactions from the list of signer transactions, i.e. non vote for aggregate public key transactions, and invalidly formed vote for aggregate public key transactions. It no longer asserts that the actual values of the function args are as expected, leaving it up to the clarity contract to reject them. Additionally, it asserts that only one transaction is allowed per signer per block, sorting proposed transactions based first upon nonce, secondly upon txid if the nonce is the same. 
- Closes #https://github.com/stacks-network/stacks-core/issues/4387

Move signer transaction to global location and utilize in both miner and signer

---

stacks-signer/src/client/mod.rs
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/config.rs
stacks-signer/src/coordinator.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signer.rs
testnet/stacks-node/src/tests/signer.rs

In my massive PR, I aaccidentally conflated signer id and signer slot id. this did not break tests because we happened to have everything line up (odds are we ALWAYS will have everything line up since the reward set is used to buidl stackerdb, but this will make sure we do not rely on this)

Fix signer id use in stackerdb

---

Cargo.lock
stacks-signer/Cargo.toml
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/tests/conf/signer-0.toml
stacks-signer/src/tests/conf/signer-1.toml
stacks-signer/src/tests/conf/signer-2.toml
stacks-signer/src/tests/conf/signer-3.toml

This PR eliminates a race condition between tests and improves the test isolation in `client::stackerdb::tests` by ensuring the tests have different node hosts in their signer configs.
In addition, the dev-dependency `serial_test` is no longer needed and therefore removed. 
- fixes #4472

Fix race condition in stacks signer client tests

---

testnet/stacks-node/src/nakamoto_node/miner.rs

Use the latest tip when retrieving the nonces for the singers to filter transactions from the stackerdb.

Fix signer nonces

---

clarity/src/vm/ast/traits_resolver/mod.rs
clarity/src/vm/ast/types.rs
clarity/src/vm/contexts.rs
clarity/src/vm/costs/mod.rs
clarity/src/vm/coverage.rs

Like `Vec`, `HashMap` can also be initialized using `with_capacity()`. I made this change where it was possible in `./clarity` and saw around a **2%** performance gain:
```console
❯ hyperfine -w 3 -r 10 "target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "target/release/stacks-inspect.hashmap-alloc replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
Time (mean ± σ):      8.682 s ±  0.019 s    [User: 8.200 s, System: 0.435 s]
Range (min … max):    8.651 s …  8.710 s    10 runs
Benchmark 2: target/release/stacks-inspect.hashmap-alloc replay-block /home/jbencin/data/next/ range 99990 100000
Time (mean ± σ):      8.552 s ±  0.026 s    [User: …
```

chore(clarity): Allocate `HashMap`s with capacity when possible

---

stackslib/src/burnchains/mod.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs

There are already signal handlers and flags in place for handling graceful shutdown, but not prior to burnchain sync. This PR propagates an error if a Ctrl-C signal was submitted during burnchain sync instead of panicking.
In the case of network loss while adding bootstrap nodes, it applies a fixed retry before panicking.
- fixes #4427
- fixes #4423 
This PR does not aim to eliminate panics. It only handles the specific cases mentioned in above issues. 
Ctrl-C:
> Running `/Users/marzi/Projects/graceful-shutdown/stacks-core/target/debug/stacks-node start --config ./conf/mainnet-follower-conf.toml`
> INFO [1709428155.649663] [testnet/stacks-node/src/main.rs:295] [main] stacks-node 0.1.0 (:, debug build, macos [aarch64])
> INFO [1709428155.649798] [testnet/stacks-node/src/main.rs:357] [main] …

Ctrl-C graceful shutdown during burnchain initialization 

---

stackslib/src/net/api/getpoxinfo.rs

`/v2/pox` invokes `get-pox-info` in the current PoX contract to obtain information about the current cycle. However, the burn view of this invocation is _always_ one block behind the current chain tip: 2.x Stacks blocks are evaluated with a burnchain view equal to their parent (because the Stacks blocks must be assembled before the burn block in which they are committed).
This leads to an "off by one" situation at reward cycle boundaries. This isn't a huge problem for Stacks 2.x nodes, because the information returned from this endpoint isn't really critical during the reward cycle change-overs. For signers in Nakamoto, though, this is problematic: they must know that the reward cycle has changed because they are now responsible for signing any new blocks _at the time of the change-over_. …

Fix: manually calculate current reward cycle ID in /v2/pox_info

---

Cargo.lock
libsigner/src/http.rs
libsigner/src/session.rs
libsigner/src/tests/http.rs
stacks-signer/Cargo.toml
stacks-signer/src/cli.rs
stacks-signer/src/client/mod.rs
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/runloop.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer.rs

Fixes https://github.com/stacks-network/stacks-core/issues/4466

fix: resolve DNS/hostnames for signer node_host config

---

stacks-signer/src/client/mod.rs
stacks-signer/src/client/stacks_client.rs

It now returns a tuple including the weight, instead of just the key.
```clarity
(option { aggregate-public-key: (buff 33), signer-weight: uint })
```

Fix `get-vote` response type

---

stacks-signer/src/cli.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/tests/conf/signer-0.toml
stacks-signer/src/tests/conf/signer-1.toml
stacks-signer/src/tests/conf/signer-4.toml
stackslib/src/net/api/mod.rs
stackslib/src/net/api/postblock_proposal.rs
stackslib/src/net/connection.rs
stackslib/src/net/httpcore.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer.rs

Added config option to the signer and to the ConnectionOptions for adding a password. Just passing it around as a plaintext password in the authorization header.

Feat/block proposal authorization password for v2/block_proposal endpoint

---

.github/workflows/stacks-core-tests.yml

This is currently causing CI failures in all PRs, so it needs to be disabled for now.

CI: do not fail CI if the codecov upload fails

---

testnet/stacks-node/src/tests/neon_integrations.rs

The `neon_integrations::pox_integration_test` has been failing CI pretty consistently (but not 100%?), such as in this build: https://github.com/stacks-network/stacks-core/actions/runs/8161203003/job/22313964190?pr=4461
This changes the test to not use hard-coded reward cycles that are expected, and instead to calculate the reward cycle from the current burnchain height.

fix: expected reward cycle in integration test for pox info

---

.cargo/config
.github/actions/dockerfiles/Dockerfile.debian-source
stacks-signer/Cargo.toml
testnet/stacks-node/Cargo.toml

We believe this flag can cause some problems with docker images.

feat: gate `target-cpu=native` with `portable` feature

---

stackslib/src/core/mod.rs

I was playing around with running a xenon node off of the `next` branch (which I know won't work), and I caught a startup error that originates from validation of burnchain epochs. Looking in to the code, I caught that we were using mainnet consts instead of testnet consts.
I know these consts will definitely change, but I'd still like to get this merged, because I'm trying to help signers get their infra setup. Even if their node doesn't sync any Stacks blocks, it would be helpful to not have a startup crash.

fix: use testnet consts when generating xenon config

---

stacks-signer/src/client/stackerdb.rs

Improvement to our version number logic. Do not increment by one. Just immediately update to one past the last seen version number. 
Closes https://github.com/stacks-network/stacks-core/issues/4506

If data already exists in a stackerdb slot, update version number

---

pox-locking/src/events.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

This does two things:
- Adds `max-amount` and `auth-id` to synthetic events for `stack-stx`, `stack-extend`, and `stack-aggregation-commit`
- Adds all the signer key and related args to the synthetic event for `stack-increase`
- Closes https://github.com/stacks-network/stacks-core/issues/4490

feat: add signer-key to stack-increase event

---

libsigner/src/events.rs
libsigner/src/libsigner.rs
stacks-signer/src/signer.rs
stackslib/src/chainstate/nakamoto/miner.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

This uses a struct for communicating a block proposal from the miner to signers.
The signer also checks the claimed reward cycle of the block before attempting to validate the proposal.

Feat: use block proposal struct for miner -> signers communication

---

stacks-signer/src/runloop.rs
testnet/stacks-node/src/tests/signer.rs

This adds a reward-set parity check to the signer run loop so that it only sends relevant events to the signer instances.

feat: add a parity check and filter events sent to the signer instances

---

stacks-signer/src/signer.rs
stacks-signer/src/signerdb.rs

In looking at testnet logs, I've seen that we hit scenarios where a block is saved as "accepted", which deletes the block from SignerDB, and then shortly later the signer tries to process the block, but the signer has no about the block (because it's deleted).

fix: try not deleting accepted blocks from signerDB

---

stacks-signer/src/coordinator.rs

Added logic to use a const to determine whether to rotate coordinators when `update_coordinator` is called

feat: add const to determine whether to rotate coordinator

---

stacks-signer/src/signer.rs
stacks-signer/src/signerdb.rs

The blocks should always be associated with a specific reward cycle so that the signers do not take actions on blocks from the previous cycle. This should prevent a halt like the one that we saw this morning.

fix: add reward cycle to signerdb

---

stackslib/src/chainstate/stacks/boot/mod.rs

The `stacked_amt: u128` reward set property in `/new_block` event was being serialized as a json number which is unsafe for the majority of applications which treat these as 64-bit floating point. This PR fixes the issue by serializing the large integer as a string like we do in other places. 
Note: most other json serialization for u128 values in the codebase are manually constructed rather than going directly from a rust struct, so a new serialize/deserialize helper was added for this case.

fix: `stacked_amt: u128` should serialize as string

---

clarity/src/vm/clarity_wasm.rs

The clarity type `Map` had a mistake in all its related functions: the key/values read from memory in the linked functions should be able to dereference them or not. This PR adds this capability.
Tests on those fixes also showed a bug while writing the values into the Wasm memory. It seems we had a few mistakes in the computation of the type sizes for lists and buffers. This PR also adds this fix.
As usual for PRs related to clarity-wasm, the tests are in the clarity-wasm repo.

Fixes for clarity-wasm map-type functions

---

clarity/src/vm/types/serialization.rs

This fixes the condition controlling a debug message related to value sanitization.

fix: correct deserialization size check

---

stackslib/src/chainstate/burn/operations/vote_for_aggregate_key.rs

As noted in https://github.com/stacks-network/stacks-core/issues/4533, the `vote-for-aggregate-key`'s `check` method doesn't validate the aggregate key used in the payload against `wsts::Point`, which can lead to issues if there are any discrepancies between `Secp256k1PublicKey` and `Point`. This PR adds validation against `Point`, along with the existing `Secp256k1PublicKey` check.
- Closes https://github.com/stacks-network/stacks-core/issues/4533

fix: add wsts::Point validation to `vote-for-aggregate-key` burn op

---

CONTRIBUTING.md
stackslib/src/chainstate/coordinator/tests.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_22.rs
testnet/stacks-node/src/tests/epoch_23.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

- use `MAX` instead of `max_value()` for numeric types
- update repo url for CONTRIBUTING.md
- fixes #3682
- complements #4494

refactor: replace `u32::max_value()` with `u32::MAX`

---

clarity/src/vm/clarity_wasm.rs

Here is another fix for `get_type_in_memory_size`.
At first, it did not account for the actual value of an in-memory type, causing issues when returning complex types from linked functions.
Then, it accounted for it all the time, requiring too much space when sometimes not needed and breaking the function `append`.
Here is a fix that takes the best of both worlds.
This passes 500 iterations of each proptests in clarity-wasm, where the tests are.

Clarity-wasm: fix computation of in-memory size

---

.github/workflows/stacks-core-tests.yml
contrib/core-contract-tests/deployments/default.simnet-plan.yaml
contrib/core-contract-tests/package-lock.json
contrib/core-contract-tests/package.json
contrib/core-contract-tests/vitest.config.js

Upgrade npm dependencies of core-contract-tests
- vite and vitests to v1, no big impact impacts vs the previous version. Require slight changes in vitest.config file
- clarinet-sdk upgraded to the latest beta, it now uses deployment-plans, hence the new file

test: upgrade core-contract-tests dependencies

---

clarity/Cargo.toml
clarity/src/vm/callables.rs
clarity/src/vm/contexts.rs

The helper `execute_contract_allow_private` does not allow the private function to return any type and can throw `PublicFunctionMustReturnResponse` if the private function return a non-Response value.
On Clarinet, we get recurrent requests from the community and internal teams to add the ability to call private function in unit tests 
- N/A Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- N/A New clarity functions have corresponding PR in `clarity-benchmarking` repo
- N/A New integration test(s) added to `bitcoin-tests.yml`

feat: return any value type from `execute_contract_allow_private`

---

stackslib/src/chainstate/stacks/boot/signers-voting.clar
stackslib/src/chainstate/stacks/boot/signers_tests.rs
stackslib/src/chainstate/stacks/boot/signers_voting_tests.rs

This is a small PR that addresses two small issues found in the .Signers-Voting.clar Clarity contract. In draft as is it's still missing relevant tests.
#4457 
#4487

Signers-Voting Chore(s): Round Up & Round-Data Getter

---

README.md

Small fix to update the cloning instructions in the README to use the correct repo of `stacks-core` rather than `stacks-blockchain`

docs: add correct repo for cloning instructions

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStxCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackStxCommand.ts

This PR adds the `delegate-stx` command to the stateful property testing environment.

Add delegate-stx command

---

stackslib/src/chainstate/stacks/boot/mod.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Closes https://github.com/stacks-network/stacks-core/issues/4492
Supersedes https://github.com/stacks-network/stacks-core/pull/4546
A few structs used in consensus critical or db migration critical areas were also being reused for serializing to JSON in the event dispatcher. Since then, several changes were made only for the event dispatcher JSON serialization, and in one case likely broke db migrations.
This PR moves the event-dispatcher-specific code out of those more core areas.

fix: isolate event-dispatcher serialization code

---

clarity/src/vm/ast/parser/v1.rs
clarity/src/vm/ast/parser/v2/mod.rs
clarity/src/vm/ast/sugar_expander/mod.rs
clarity/src/vm/costs/mod.rs
clarity/src/vm/mod.rs
clarity/src/vm/representations.rs

`SymbolicExpression`s and `PreSymbolicExpression`s are unnecessarily `Box`ed in a few places in the `clarity` crate when used in `Vec`s. As `Vec`s are already on the heap, a `Box` is not necessary.
Closes #4445

Chore: Remove `Box`ing of `SymbolicExpression`s

---

.cargo/config
Dockerfile
Dockerfile.debian

Pass the flag `target-cpu=native` to `rustc` for local builds and tests for improved performance
**This PR also require stacks-network/actions#31 to be approved and merged**
- #4316 
- #4364: Original commit enabling this flag
- #4489: Broke flag being passed to `rustc` (not sure why)

fix: `target-cpu=native` flag working again

---

.github/workflows/bitcoin-tests.yml
stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/burnchains/db.rs
stackslib/src/chainstate/coordinator/mod.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This test (from Jude) can reproduce the problematic behavior when the burnchain flaps between two branches.
- We get blocks at height 211 - 213
- Then we get a fork, with different blocks at 211-213, as well as 214 and 215.
- We then flap back to the original fork, so it goes back to the common ancestor, 210, and tries to download 211-215
- When it gets block 211, it is already in the database, so it fails, cancelling the download of the rest of the blocks, leaving 214 and 215 in this branch not stored
- Then we try to store 216, but its parent 215 is not stored yet, so we cannot continue.
The fix for this is to ignore attempts to store duplicate blocks.
- fixes #

fix: handle burn chain flapping

---

.github/workflows/atlas-tests.yml
.github/workflows/bitcoin-tests.yml
.github/workflows/epoch-tests.yml
.github/workflows/github-release.yml
.github/workflows/slow-tests.yml
.github/workflows/stacks-core-tests.yml
CONTRIBUTING.md
docs/ci-release.md
stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/burnchains/db.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_22.rs
testnet/stacks-node/src/tests/epoch_23.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Merges latest develop into next. Among other recent changes, this includes the reorg flapping fix which is needed for testnet.

Merge develop into next

---

stacks-common/src/types/mod.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/net/mod.rs

This PR removes the unlock behavior of PoX-4 when solo stackers miss a reward slot. This behavior was broken `next`: missed reward slot unlocks have consequences for signer set calculation, which has to be addressed. This PR addresses it by removing the unlock behavior.
This PR also adds a test that covers the case of a 2.5 reward cycle having participation but no slots. Such a cycle should still allow the system to make forward progress in 2.5.

2.5: PoX missed-slot updates

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs

This enables nakamoto for xenon and mainnet modes, not just for "nakamoto-neon".

feat: make nakamoto mode the default

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackStxCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStxCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_GetStackingMinimumCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_GetStxAccountCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackStxCommand.ts

This pull request targets #4550 and adds the ability to call `delegate-stacks-stx` from the stateful property-based tests.

[DRAFT] [pox-4] Stacking stateful property-based tests - DelegateStackStxCommand

---

stackslib/src/burnchains/mod.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/core/mod.rs
testnet/stacks-node/src/main.rs

PR #4577 removed `nakamoto-neon` mode, in order to make nakamoto the default, but did not remove `nakamoto-neon` everywhere. This change re-adds support for "nakamoto-neon" mode, but also leaves nakamoto mode as the default for xenon and mainnet modes. 
Some integration tests failed in #4577, but the PR was merged anyway because it seems that the "Bitcoin Tests / Check Tests" check is not required. @wileyj can we make that check required now?

fix: allow `nakamoto-neon` mode

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStxCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_RevokeDelegateStxCommand.ts

This PR adds the `revoke-delegate-stx` command to the stateful property testing environment.

Add revoke-delegate-stx command

---

.github/workflows/ci.yml
.github/workflows/create-source-binary.yml
.github/workflows/github-release.yml
.github/workflows/image-build-binary.yml

previously, it was gated to only build a release if the default branch was tagged. 
this PR makes it possible to create a release on any branch **if** a tag is provided.

create release only requires a tag

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_AllowContractCallerCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackStxCommand.ts

This PR adds the `allow-contract-caller` command to the stateful property testing environment. It is part of #4548 and targets `feat/pox-4-stateful-property-testing` (#4550).

Add allow-contract-caller command

---

Cargo.toml

#4331 added the ability to build for multiple arches and OSes. 
this was changed in https://github.com/stacks-network/stacks-core/commit/207cb690fe8cb25cba6734ec4492f077108cc30b resulting in only glibc based sytems building as part of the ci workflows. 
this change brings back the flag added in #4331

adding missing flag to cargo.toml

---

.github/workflows/stacks-core-tests.yml
contrib/core-contract-tests/package-lock.json
contrib/core-contract-tests/package.json

- Fix broken CI
- Because the clarinet-sdk 2.4.0 was release as stable, the `-f` isn't needed anymore
I'll try to see how the lock file got corrupted in the first place

fix: core contract tests corrupted package.json

---

Cargo.lock
stacks-signer/src/cli.rs
stackslib/src/util_lib/signed_structured_data.rs

This fixes an issue where the `generate-stacking-signature` command inside the signer CLI would fail when a p2pkh address was provided as an argument.
- Closes https://github.com/stacks-network/stacks-core/issues/4596

fix: generating stacking signatures from b58 addresses

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackExtendCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackStxCommand.ts

This PR adds the `delegate-stack-extend` command to the stateful property testing environment. It is part of #4548 and targets `feat/pox-4-stateful-property-testing` (#4550).

Add delegate-stack-extend command

---

clarity/src/vm/analysis/contract_interface_builder/mod.rs
clarity/src/vm/analysis/mod.rs
clarity/src/vm/analysis/type_checker/contexts.rs
clarity/src/vm/analysis/type_checker/v2_05/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/options.rs
clarity/src/vm/analysis/type_checker/v2_1/tests/contracts.rs
clarity/src/vm/clarity.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/types/signatures.rs
stacks-common/src/types/mod.rs
stackslib/src/clarity_cli.rs

This PR replaces the BTreeMap in tuple type signatures with a more efficient hashmap, and also improves the analysis performance by simplifying the type map struct to a hash set (only when possible: the type map's values are required in testing and docs generation).

2.5: Tuple performance improvements

---

Cargo.toml
README.md

Add `release-lite` profile, which should build faster and take less RAM
- fixes #4584 
Also fixes the code blocks in the README. The `$` characters at beginning of each line were unnecessary and interfered with syntax highlighting and copy/pasting

chore: Add `release-lite` profile for low-RAM environments

---

stacks-signer/src/cli.rs
stacks-signer/src/coordinator.rs
stacks-signer/src/main.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signer.rs
stacks-signer/src/signerdb.rs

This only really matters for epoch 2.5. If this was to happen in epoch 3.0 the chain would be halted.

Do not attempt to treat miner as a coordinator when updating DKG

---

stacks-signer/src/client/stacks_client.rs
stacks-signer/src/runloop.rs

Sometimes regtest would stall on boot with the following messages:
2024-04-02, 05:32:20.104 PM	
[signer_runloop] Received a new burnchain block height (117) in the prepare phase of the next reward cycle (6). Checking for signer registration...
2024-04-02, 05:32:20.057 PM	
[signer_runloop] Received a new burnchain block height (117) in the prepare phase of the next reward cycle (5). Checking for signer registration.
This made me realize something was up with the reward cycle info or prepare phase calculation. Was accidentally storing the full reward cycle length but calling it the reward phase length and then adding and subtracting the prepare phase length again. This should fix the problem. 
Fixes https://github.com/stacks-network/stacks-core/issues/4630

Reward cycle length was being incorrectly stored as reward phase length

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackIncreaseCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_DelegateStackStxCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitAuthCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitSigCommand.ts

This PR adds the `stack-aggregation-commit` command, using both signature and authorization, to the stateful property testing environment. It is part of #4548 and targets `feat/pox-4-stateful-property-testing` (#4550).

Add stack-aggregation-commit command signature and authorization

---

contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitIndexedAuthCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitIndexedSigCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitSigCommand.ts
contrib/core-contract-tests/tests/pox-4/pox_StackStxCommand.ts

This PR adds the `stack-aggregation-commit-indexed` command, using both signature and authorization, to the stateful property testing environment. It is part of #4548 and targets `feat/pox-4-stateful-property-testing` (#4550).

 Add stack-aggregation-commit-indexed command signature and authorization

---

stackslib/src/chainstate/nakamoto/mod.rs

- Closes https://github.com/stacks-network/stacks-core/issues/4625
This changes the `warn_if_not_found_flag` from hard-coded `true` to an epoch comparison.

fix: dont warn about aggregate key in 2.5

---

pox-locking/src/events.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

- update `prepare_offset` to more fitting `pox_set_offset`
- this fixes an off-by-one error in the check for which pox txs could still be considered in the next cycle.
* adds more tests along the prepare phase border
* non consensus critical, but will output different event values
---
~_I wanted to add checks to the end of the tests to check whether the addresses are actually in (or not in) the pox-set (reward_addresses), but I couldn't get the Rust to work 🙈 If somebody has ideas on how to best do that from a TestPeer._~ thx Brice

fix: update prepare offset of start-end cycle ids

---

.cargo/config
.github/actions/dockerfiles/Dockerfile.debian-source
Dockerfile
Dockerfile.debian
README.md
stacks-signer/Cargo.toml
testnet/stacks-node/Cargo.toml

ref: #4638 
the options in .cargo/config are not being applied, this PR removes them entirely and adds some text in the README on how to enable building for `native-cpu`. 
removing the portable flag will have some downstream effects to the release build process that we'll need to address once merged (basically removing the portable feature flag, and re-enabling macos-arm64 stacks-signer binary builds).

remove portable flag

---

CHANGELOG.md
stackslib/src/net/stackerdb/sync.rs
stackslib/src/util_lib/db.rs

This just merges the latest changes from master to develop.

Chore: Merge master to develop

---

stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/util_lib/signed_structured_data.rs

Initial draft of a solution to address #4643 found by @janniks. Keeping the logic in parallel with solo 'stack-increase', we opted to adding a required signature | set approval to the existing 'stack-aggregation-increase' function. 
This PR also includes minimal testing setup seen in #4586 as well (which will likely be rebased once this is first merged in). Also includes some comment clean up.
#4643

[pox-4]  Stack Aggregation Increase Update

---

stackslib/src/core/mod.rs

This sets the 2.5 activation height to bitcoin block 839,444.
At 10 minute bitcoin blocks, this is approximately Tuesday, April 16, 14:00 Eastern.

feat: set 2.5 activation height at bitcoin block 839,444

---

stackslib/src/core/mod.rs
testnet/stacks-node/src/config.rs

This adds default overrides for the affirmation maps in Epoch 2.5 on the Xenon testnet. This is necessary because the 2.5 release version contains a different pox-4 contract than the one instantiated in Xenon testnet initially. This is similar to the reorg required during Epoch 2.4 on Xenon Testnet (see: https://github.com/stacks-network/stacks-core/pull/4560).

Feat: add affirmation map overrides to xenon default config for epoch 2.5

---

contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_DisallowContractCallerCommand.ts

This PR adds the `disallow-contract-caller` command to the stateful property testing environment. It is part of #4548 and targets `feat/pox-4-stateful-property-testing` (#4550).

Add disallow-contract-caller command

---

stackslib/src/chainstate/stacks/boot/pox-4.clar
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

This PR alters the behavior of `stacks-aggregation-increase` in an improper invocation scenario. If the delegate invokes stacks-aggregation-increase before they (or anyone else) has performed a _commit_ (or solo stacking operation), the transaction will abort rather than returning a caller-catchable error. This is a slight bug: the difference is just whether or not the error is catchable by a contract that invokes the function.
This change would require tagging an rc-3, so the tradeoff is whether or not a nicer error handling here is worth a new release candidate for 2.5.

Feat(pox-4): return an err on improper agg-incr invocations

---

pox-locking/src/events.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

- missing `)` in injected code was causing an event to not emit
> not consensus critical, but very important for the api

fix: fix delegate stack increase events

---

.github/workflows/github-release.yml

adds:
```
target_commitish: ${{ github.sha }}
generate_release_notes: true
```
to the github release workflow so the correct tag is used when not building from the default branch. 
https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing
sample workflow: https://github.com/wileyj/stacks-blockchain/actions/runs/8634094479
and tag produced from the forked `release/2.5.0.0.0` branch (with the same commit): https://github.com/wileyj/stacks-blockchain/releases/tag/2.5.0.0.0-rc5

update release workflow to tag the correct commit

---

CHANGELOG.md

adding some text addressed in https://github.com/stacks-network/stacks-core/pull/4668

Address PR comments for changelog

---

stacks-signer/src/cli.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs

- Closes https://github.com/stacks-network/stacks-core/issues/4602
This adds a simple log when the signer is started with the signer's configuration information. The goal is just to help signers ensure their signer is configured as expected. It also provides the signer's STX address and public key.
I've also added a `check-config` command which validates a config file and outputs the same startup logging information.

feat: add startup logging with config to signer

---

stacks-signer/src/cli.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs

This is the same code as #4678 , but targeted to the release branch, in hopes that we can get this included in the next RC. I think it's best to keep both PRs open, otherwise we'll have to pull from the release branch into develop (instead of the other way around as usual)
- Closes https://github.com/stacks-network/stacks-core/issues/4602
This adds a simple log when the signer is started with the signer's configuration information. The goal is just to help signers ensure their signer is configured as expected. It also provides the signer's STX address and public key.
I've also added a `check-config` command which validates a config file and outputs the same startup logging information.

feat: add signer startup logging

---

.github/actions/dockerfiles/Dockerfile.alpine-binary
.github/actions/dockerfiles/Dockerfile.debian-binary

cc @friedger 
Reported that the stacks-signer binary was missing in the rc4 docker release image. 
this changes the current dockerfile to also add `stacks-signer` along with `stacks-node` to the release docker image. 
More binaries can be added at the expense of image size, but i think these 2 are the bare minimum.

Add missing stacks-signer binary to release docker images

---

stackslib/src/core/mod.rs

The 2.5 node defines Epoch 3.0, but it does not use its network version byte, which means validate_epochs must special case 2.5 and 3.0.

Fix: validate epochs must special case 2.5

---

stackslib/src/chainstate/stacks/db/transactions.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/net/p2p.rs

These problems with transactions are normal and should not be warnings in the stacks-node logs. They are flooding the logs with warnings, making it easier to miss real warnings.

Downgrade transaction warnings

---

contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
contrib/core-contract-tests/tests/pox-4/pox_StackStxCommand.ts

This PR updates the state refreshing function for new cycles and targets `feat/pox-4-stateful-property-testing` (#4550).

Refine the next cycle state refresh function

---

clarity/src/vm/contexts.rs
clarity/src/vm/tests/contracts.rs

When calling eval_read_only with non-existing contract, the global context is not properly rolled back, which causes panic when trying to destruct the environment. 
N/A

chore: properly handle context rollback for eval readonly

---

clarity/src/vm/contexts.rs
clarity/src/vm/tests/mod.rs

This fixes (and adds a regression test) for a regression in 2.5.0.0.0 branch from 2.4.0.1.0

fix: .expect_result must try, regression from 2.4.0.1.0

---

docs/mining.md
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

Add new config parameter `nakamoto_attempt_time_ms` to control Nakamoto miner separately from existing (pre-Nakamoto) miner config
- fixes #

feat: Add `nakamoto_attempt_time_ms` to control Nakamoto miner

---

libsigner/src/session.rs
libstackerdb/src/libstackerdb.rs
stackslib/src/net/stackerdb/mod.rs

- Closes https://github.com/stacks-network/stacks-core/issues/4648
This uses the `CHUNK_SIZE` constant, which is set in `signers.clar` and used as part of its StackerDB config, when reading chunks from the `stacks-signer`. This maximum chunk length is already enforced on the node, but this PR adds a some redundancy on that maximum length check.

feat: limit length of chunks when signer reads from stackerdb

---

stacks-common/src/bitvec.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/net/api/postblock_proposal.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer.rs

This PR adds two things:
- When a new Nakamoto block is formed, it starts with a BitVec of 1's with the length of the signer set.
- In the miner's coordinator thread, a `next_signer_bitvec` property is added. After a miner has collected all block responses from the signers, it updates this BitVec to match the signers who gave a response.
Note that, from a functional perspective, all this changes is that the length of the BitVec will match the signer's length. However, the BitVec will be all 1's, even if not all signers respond. Future work is required to construct a new block in the case that a block is rejected, and in that work we can use this `next_signer_bitvec` in that new block.
- Closes https://github.com/stacks-network/stacks-core/issues/4558

feat: start of ability for miner to keep track of active signers bitvec

---

pox-locking/src/events.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

- Closes https://github.com/stacks-network/stacks-core/issues/4717
The `stack-aggregation-increase` function includes a `signer-key` and other related arguments, but these new arguments are not included in the synthetic event generated for this function. Off-chain services rely on this information to properly index Stacking data.

fix: add signer-key to synthetic `stack-aggregation-increase` event

---

stacks-signer/src/client/mod.rs
stacks-signer/src/runloop.rs

When the signer is processing a new burn block, it may hit the /v2/pox endpoint before it has been updated with the latest block. This change will check for this case and retry until it receives the expected cycle.
This also fixes a problem with refreshing the signer too early. It should only attempt to refresh the signer during the next prepare phase. This handles the case where for the first block in a cycle (height % cycle_length == 0), it will report that it is in cycle N, but it will also report that it is in the prepare phase. This was resulting in refreshing the signer config too early. For example, with a cycle length of 20, at block 160, we would see a log:
```
Received a new burnchain block height (160) in the prepare phase of the next reward cycle (9). Checking for signer …
```

fix: handle a race condition between the signer and the /v2/pox endpoint

---

.github/workflows/ci.yml

Small change to the ci workflow to reduce the frequency of when CI is triggered. 
previously, various workflows would trigger:
- open a PR
- new commits to a PR
- PR approvals
- add PR to merge group
- would not trigger if only change is yml/md
This change does the following:
- workflow triggers when a PR:
- is opened
- is changed
- only updated files are md/yml (this will be addressed in a future PR - today the required status checks would make this problematic)
- workflow no longer runs:
- when PR is approved

[CI] 4746 - Avoid extraneous CI runs (master)

---

.github/workflows/ci.yml

Small change to the ci workflow to reduce the frequency of when CI is triggered. 
previously, various workflows would trigger:
- open a PR
- new commits to a PR
- PR approvals
- add PR to merge group
- would not trigger if only change is yml/md
This change does the following:
- workflow triggers when a PR:
- is opened
- is changed
- only updated files are md/yml (this will be addressed in a future PR - today the required status checks would make this problematic)
- workflow no longer runs:
- when PR is approved

[CI] 4746 - Avoid extraneous CI runs (next)

---

.github/workflows/ci.yml

Small change to the ci workflow to reduce the frequency of when CI is triggered. 
previously, various workflows would trigger:
- open a PR
- new commits to a PR
- PR approvals
- add PR to merge group
- would not trigger if only change is yml/md
This change does the following:
- workflow triggers when a PR:
- is opened
- is changed
- only updated files are md/yml (this will be addressed in a future PR - today the required status checks would make this problematic)
- workflow no longer runs:
- when PR is approved

[CI] 4746 - Avoid extraneous CI runs (develop)

---

stacks-signer/src/monitoring/mod.rs
stacks-signer/src/monitoring/server.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signer.rs
stackslib/src/monitoring/mod.rs

Clippy got forgotten in some recent pull requests as it has not been added to CI yet. This just fixes them.

Implement this error for MonitoringError and fix clippy warnings

---

stackslib/src/net/p2p.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/peer.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/boot_nakamoto.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs

Preserve `PeerNetwork` struct from Neon node and pass to Nakamoto node during Epoch 3.0 transition to maintain network connections
- fixes #4355
- fixes #4547

feat: Preserve `PeerNetwork` during Epoch 3.0 transition

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs

The `next_initiative` is hard coded in 3 different places, with this PR, the default value is only set once.
By making it configurable, other environments can set it to a lower delay (in the Devnet, the bitcoin block production can be faster than 10sec)
/
/

feat: add a next_initiative_delay config

---

stacks-signer/src/config.rs
stacks-signer/src/main.rs

The signer converts its private key to a Stacks address when looking up whether it is registered in a reward cycle. If the configured private key didn't have a `compress_public` flag (ie ending in `01`), the public key wouldn't be compressed when generating the Stacks address. This could lead to the signer incorrectly thinking it isn't registered.
This PR also updates the `check-config` command to output the compressed public key.
Relates to:
- https://github.com/stacks-network/stacks-core/issues/4761

fix: always use compressed public keys in signer config

---

CHANGELOG.md
Dockerfile
Dockerfile.debian

Prepping for the 2.5.0.0.4 release, this PR simply adds the changelog entry. 
Secondary - i noticed a small issue with the Dockerfiles in the repo root, which were still set to use the old build command. that change is also added here, but is trivial and inconsequential. 
```
RUN cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release
```
is now
```
RUN cargo build --features monitoring_prom,slog_json --release
```

Adding 2.5.0.0.4 to the changelog

---

stacks-signer/src/main.rs

If we later want to make this an argument we can, but for now we default run v0 signer as v1 is broken as is anyway.

Run the v0 signer by default instead of v1

---

stacks-signer/src/cli.rs

- Closes https://github.com/stacks-network/stacks-core/issues/4763
The methods `stack-increase` and `agg-increase` weren't included as valid options in the `stacks-signer generate-stacking-signature` command.
This PR updates the `clap` argument type to do a direct lookup of the underlying `Pox4SignatureTopic`, so that no case can be missed. This PR also adds tests to ensure the various strings can be provided as valid options.

fix: add missing methods to `generate-stacking-signature`

---

README.md
docs/ci-release.md
docs/rpc-endpoints.md

docs: fix typos

---

stackslib/src/net/mod.rs
stackslib/src/net/p2p.rs
stackslib/src/net/stackerdb/config.rs
stackslib/src/net/stackerdb/mod.rs
stackslib/src/net/stackerdb/tests/config.rs
testnet/stacks-node/src/neon_node.rs

This addresses all of the points brought forth by a StackerDB audit.  None of them are security risks or pose a serious problem to the system's operation, so it's safe to just open it against `develop` for now without doing a hotfix.
The fixes are:
* Don't accept a private IP address from `hint-replicas` in the StackerDB config contract
* Limit the upper value of `max-neighbors` to the locally-configured `num_neighbors` in `ConnectionOptions`

Fix/StackerDB Audit

---

.github/workflows/bitcoin-tests.yml
docs/mining.md
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR changes the default value for `nakamoto_attempt_time_ms` to 20 seconds and adds an integration test, `test_nakamoto_attempt_time`, to check that this value works as expected. Specifically, it checks the following:
- No blocks are produced if no transactions are submitted
- If there is a small number of transactions, blocks will be produced at the rate of `nakamoto_attempt_time_ms`
- If there are many transactions in the mempool, where it would take longer than `nakamoto_attempt_time_ms` to include them all in a single block, blocks will still be produced at the rate of `nakamoto_attempt_time_ms`
- #4711

test: Timing of Nakamoto miner block production

---

stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/stacks/db/mod.rs

This was missed in #4812. It causes the nakamoto integration tests to fail. I added a unit test to ensure that the latest version supports the latest epoch.

Fix DB compatibility issue

---

contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox-4.stateful-prop.test.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_AllowContractCallerCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_CommandModel.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_Commands.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_DelegateStackExtendCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_DelegateStackStxCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_DelegateStxCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_DisallowContractCallerCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_RevokeDelegateStxCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_StackAggregationCommitAuthCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_StackAggregationCommitIndexedAuthCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_StackExtendAuthCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_StackStxAuthCommand.ts
contrib/boot-contracts-stateful-prop-tests/tests/pox-4/pox_StackStxSigCommand.ts

This PR implements a series of updates necessary for the PoX-4 stateful property testing environment.
The updates introduced by this PR:
- add untilBurnHt check inside `RevokeDelegateStxCommand`.
- add the `none` branch to the `delegatedUntilBurnHt` field of the model.
- pass the incremented startBurnHt to the `stack-stx` calls.
- include the authorization and the tested function call in the same block inside `StackStxAuthCommand`, `StackExtendAuthCommand`, `StackAggregationCommitAuthCommand`, `StackAggregationCommitIndexedAuthCommand`.
- convert the `allowedContractCaller` string field to `allowedContractCallers` list, as an address can allow multiple contract callers.

PoX-4 stateful property tests updates

---

stackslib/src/util_lib/db.rs

This adds a backtrace key to the `debug!` logs produced during sqlite tx busy handling. It will be invoked on every 10th such log for the same wait (so it will primarily be useful for debugging deadlocking situations).

Chore: add backtrace to db busy handler

---

stackslib/src/main.rs

This adds the `index-range` option to `replay-blocks`. This is useful for selecting a uniformly random slice of blocks for replay (because ordering by index block hash is indistinguishable from a pseudorandom function).
Note: As part of this PR, I also considered making the `replay-blocks` command alter the SQLite transaction behavior from IMMEDIATE to DEFERRED. The goal was to allow multiple processes to share a chainstate directory during replay-blocks. Unfortunately, this didn't really help, because `replay-blocks` does perform writes in its transactions: it just rolls back those transactions. This means that SQLite will try to obtain a write lock even in DEFERRED operation. 
However, one workable strategy for avoiding storage overhead when trying to run multiple process with …

`stacks-inspect`: add `index-range` option to `replay-blocks`

---

testnet/stacks-node/src/neon_node.rs

This is identical to #4886, but targeted at the staging/release branch.

Fix: never consider Stacks chain tips that are not on the canonical burn chain #4886

---

libsigner/src/v1/messages.rs
stacks-common/src/libcommon.rs
stacks-signer/src/client/stacks_client.rs

This fixes in the release branch the slot count for the `.signers` contract. It also adds a unit test that asserts the value is unchanging.
Will also open a PR against `develop` for this.

Fix: signer slots count in staging

---

libsigner/src/v1/messages.rs
stacks-common/src/libcommon.rs
stacks-signer/src/client/stacks_client.rs

This is the same PR as #4891, just targeted at `develop`.

Fix: signer slots count in develop

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

This fixes an integration test assertion in `develop`. The naka_node miner is correctly setting the bitvec length, which altered the assertion in this test.

Test: miner correctly sets bitvec to reward set length in naka_node now

---

stacks-common/src/types/mod.rs
stackslib/src/core/mempool.rs
stackslib/src/core/tests/mod.rs
stackslib/src/main.rs
stackslib/src/net/relay.rs

This addresses #4346 by changing the mempool GC behavior in nakamoto from using the block height to using the age of the transaction (measured in time since `accept_time`).
The sets the age limit to be the same as prior limit when translated with 10 minute block times (as was expected prior to 3.0).

Feat: Garbage collect mempool in nakamoto using accept time

---

testnet/stacks-node/src/neon_node.rs

This PR fixes an incident from earlier this morning whereby miners consistently failed to mine blocks because their preferred chain tip was no longer on the canonical Bitcoin fork.  This was due to (1) an omitted check when searching for ancestral Stacks tips to consider, and (2) an off-by-one error which meant that the highest considered ancestor had the same height as the already-filtered Stacks tips (instead of an earlier height).
You can see the difference as follows:
With the fix:
```
$ stacks-node pick-best-tip --config ~/mainnet-2.5.toml --at-stacks-height 153917
INFO [1718387049.331670] [testnet/stacks-node/src/main.rs:293] [main] stacks-node 0.1.0 (:, debug build, linux [x86_64])
INFO [1718387049.331731] [testnet/stacks-node/src/main.rs:66] [main] Loading config at path …
```

Fix: never consider Stacks chain tips that are not on the canonical burn chain

---

stackslib/src/chainstate/coordinator/comm.rs
stackslib/src/chainstate/stacks/miner.rs
testnet/stacks-node/src/globals.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/boot_nakamoto.rs
testnet/stacks-node/src/run_loop/mod.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

Fix 2 block downtime by passing `LeaderKeyRegistrationState` from Neon runloop to Nakamoto runloop
- fixes #4710

fix: 2 blocks dead time between 2.5 -> 3.0 transition

---

.github/workflows/bitcoin-tests.yml

The signer V1 implementation is not supported in Epoch 3.0's implementation -- the `signer::v1` tests should not be expected to pass until the an epoch that supports V1 is implemented.

CI: disable the signer::v1 integration tests

---

stackslib/src/main.rs

These blocks won't be loaded by the staging db in any event, and would lead to an error while running replay-block in bulk.

Chore: do not consider orphaned blocks during replay-block

---

clarity/src/vm/analysis/type_checker/v2_1/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/mod.rs
clarity/src/vm/analysis/type_checker/v2_1/natives/sequences.rs
clarity/src/vm/types/signatures.rs
stacks-signer/src/client/stacks_client.rs

This PR adds a handful of performance improvements to Clarity analysis (cow/arc behavior in tuple types, simple refactoring in the analysis runtime).
The existing unit tests cover this changeset.

Performance improvements in Clarity analysis

---

.github/workflows/bitcoin-tests.yml
stackslib/src/net/api/postblock_proposal.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs
testnet/stacks-node/src/tests/signer/v1.rs

Adds a test case checking for the behavior at the end of a tenure. This is currently built on top of #4903.
See #4532

End of tenure test

---

testnet/stacks-node/src/config.rs

This patch adds `antientropy_retry` to the connection options file in config.rs, making the option configurable for nodes.

chore: make connection_options.antientropy_retry configurable

---

CHANGELOG.md
stackslib/src/net/connection.rs

Adds a changelog for 2.5.0.0.5 and changes the default `antientropy_retry` from 1 minute to 1 hour

Set default antientropy_retry to one hour

---

testnet/stacks-node/src/tests/signer/v0.rs

In V0, the miner can assemble a block once it crosses the threshold, without all signers. The existing assertion causes CI to flap (because sometimes the miner is faster than the signers).

Test chore: v0 signature assert fixes

---

CHANGELOG.md

fixes a typo in #4935 - the version number in the changelog was incorrect.

2.5.0.0.5 changelog

---

testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

If a miner times out when waiting for signatures, it should not end its tenure. Instead it should just retry.

feat: make miner retry when signature collection times out

---

stacks-common/src/types/mod.rs
stackslib/src/burnchains/tests/mod.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/net/mod.rs

This fixes an issue that showed up in the naka-1 testnet. The leader block commit op in nakamoto is committing to a parent block, not a new block, so there was previously essentially an "off by one" bug in the block commit op evaluation.
This also adds a test for this behavior.

Fix: block commit pox-descendant check in nakamoto

---

stacks-signer/src/lib.rs
stacks-signer/src/runloop.rs
stacks-signer/src/v0/signer.rs
stacks-signer/src/v1/signer.rs
testnet/stacks-node/src/tests/signer/v0.rs

Fetch and cache sortition state as needed, and use it to validate incoming `BlockProposal`s
- fixes #4880
Since this is my first time contributing to the signer binary, there are some things I'm unsure of that reviewers should check:
- This adds some blocking i/o in `handle_block_proposal()`
- I think it's correct to do these checks before `submit_block_for_validation()`, since that takes longer
- I only implemented this in signer `v0`. I didn't touch `v1`
- Is the public key passed to `check_proposal()` the correct one?
- I used `inspect_err()`, which was introduced a few months ago in Rust 1.76. Is this okay, and what's our MSRV policy in general?

feat: Sortition tracking in signer binary

---

stackslib/src/net/unsolicited.rs

Add mutants skip header for the functions that aren't working with mutation testings.
- related to timeout mutants from #4881

Add skip header for timeout mutants - pr #4877 related

---

Cargo.lock

This PR updates the `time@0.3.34` crate to the latest version. 
This update addresses build failures that occur when using the nightly toolchain `nightly-x86_64-unknown-linux-gnu`.

Update `time@0.3.34` to `time@0.3.36` for nightly build on linux

---

CONTRIBUTING.md

As specified by docker tags requirements [1] and `docker-metadata` [2]. 
[1]: https://docs.docker.com/reference/cli/docker/image/tag/#description
[2]: https://github.com/docker/metadata-action?tab=readme-ov-file#image-name-and-tag-sanitization
Prevents issues like [3] on parenthesis (not actually related to tag name, but to Docker failing CI configuration).
[3]: https://github.com/stacks-network/stacks-core/actions/runs/9766520161/job/27087431713?pr=4921
Heard this on WG call, thought it would be a nice first contribution :)

docs: specify allowed character set for branch names

---

stacks-common/src/deps_common/bitcoin/blockdata/script.rs

abs() may be lead to panic in the debug mode and optimized code will return i64::MIN without a panic. so need use unsigned_abs() in here
The absolute value of i64::MIN cannot be represented as an i64, and attempting to calculate it will cause an overflow. This means that code in debug mode will trigger a panic on this case and optimized code will return i64::MIN without a panic. so
in here  need replace abs() with unsigned_abs()
- fixes #

[fix]replacement the abs() with unsigned_abs()

---

stackslib/src/burnchains/affirmation.rs
stackslib/src/burnchains/burnchain.rs
stackslib/src/burnchains/db.rs
stackslib/src/chainstate/burn/db/processing.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/burn/sortition.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tenure.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/net/download/epoch2x.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/node.rs

I have been tearing my hair out trying to compare across log lines without knowing what is a burn header hash vs stacks block hash vs consensus hash etc. This is a quick first pass to just print all the info as available in all warn and info level logs. I also did a few debug logs that were specifically standing out to me. I think we could cleanup a lot of log lines to only ever print these hashes annotated instead of inline as they are just a nebulous blob of bytes otherwise, but will leave that for a sep PR. 
I might actually implement on top of this a trait for printing internal hashes for each object that holds them, but for now this seemed the quickest way to get it done and that might be overkill especially if the object contains parent hashes.
Note I didn't bother changing really …

First pass focusing on warn and info level logging. Couple debugs

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Fixes integration test `tests::nakamoto_integrations::check_block_info_rewards`.

test: fix block reward check in `check_block_info_rewards`

---

.github/workflows/lock-threads.yml
CODEOWNERS

This is a reaction from recent events where spammers replied to closed issues and PR's (note: because of the way github works, you cannot delete PR comments after merge). 
In one case, they were able to get their userid added to the list of reviewers. 
To solve for this, an existing action https://github.com/dessant/lock-threads is used with some updated defaults and a hardcoded sha in our composite action repo: https://github.com/stacks-network/actions/tree/main/lock-threads
This PR simply adds a worflow the to stacks-core repo to lock all closed PR/issues/discussions after **7** days. 
This is adjustable however, and i think we would likely want to change so that items are locked:
prs: 1 day
issues: 1 day
discussions: 7 days
The workflow is designed to run manually and scheduled at …

Workflow to lock closed issues/pr/discussions

---

clarity/src/vm/clarity.rs

Without this change, the types we need are not saved by the type-checker, which instead just uses a set to perform the checks it needs.

fix: set the flag to make the type-checker store a map of types

---

stacks-signer/src/signerdb.rs

This adds schema versioning and migration logic to the signerdb sqlite database #4963 
The implementation of this is pretty similar to the migration logic used in other dbs. One difference is that this _drops_ tables if they were previously present. Because signers have not needed to use this DB yet in production, this is safe, and due to the previously lacking migration logic this is necessary anyways. The "drop" command just eliminates the need for someone to clear the database themselves.

Chore: signerdb schema versions

---

stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/stacks/miner.rs

Add a debug log when unblocking the miner to match the log when blocking it. This is helpful when debugging.

Add unblock log

---

stacks-signer/src/chainstate.rs

This log can be hit in the case where a nakamoto block does not build off of the most recently signed nakamoto block, so the warning message should be less specific about the other case.

fix: make signer's warning log more accurate

---

stackslib/src/chainstate/burn/operations/mod.rs

This default handling for the `treatment` field of `LeaderBlockCommitOp` is needed to support existing chainstate which did not include this field.

Support existing chainstate

---

stacks-signer/src/signerdb.rs
stacks-signer/src/v1/signer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Add enum for version-specific (Signer v0 or v1) data to `BlockInfo`
- fixes #4816

refactor(signer): Add enum for version-specific data to `BlockInfo`

---

clarity/src/vm/clarity_wasm.rs

This is the stacks-core part of [clarity-wasm's PR 443](https://github.com/stacks-network/clarity-wasm/issues/443).
It implements the remaining types and fixes the current implementation that did not respect the ABI.
The tests are not ready yet in the original repo.

Clarity-Wasm: Implement "pass_argument_to_wasm" for remaining types

---

stacks-common/src/deps_common/httparse/mod.rs

I noticed this was causing failures in several active PRs. I'm not sure what changed or when to cause this.

fix: remove bad feature gating

---

clarity/src/vm/clarity_wasm.rs

Those are fixes for the `contract-call?` function.
They come from the new property tests for this function that will be in the clarity-wasm repo soon.

Clarity-Wasm: fixes for `contract-call?`

---

.cargo/config.toml
Cargo.lock
clarity/Cargo.toml
libsigner/Cargo.toml
libstackerdb/Cargo.toml
pox-locking/Cargo.toml
stacks-signer/Cargo.toml
stackslib/Cargo.toml
testnet/stacks-node/Cargo.toml

_PR targeting `feat/clarity-wasm-develop` which is the WIP branch used in `clarity-wasm`._
Switch back the workspace internal dependencies to local path.
Since `clarity-wasm` depends on `clarity` and `stacks-common` from github.com, these dependencies are patched to always target relative versions.
Making our lives way easier

refactor: use relative path for workspace dependencies

---

testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/nakamoto.rs

~~I still need to add a test for this.~~ Unit tests added.
Fixes #4994.

feat: support resuming from a saved VRF key

---

libsigner/src/events.rs

Adds some more info to the libsigner debug logging.

chore: more info in signer logging events

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Modify integration tests so that they don't produce an extra block in between Epoch 2.5 and 3.0. Add a check to make sure that no burnchain blocks are missing from Stacks blockchain
- fixes #4987
Should I add the `contains_burn_block_range()` check to all integration tests?

test: Eliminate block between 2.5 and 3.0

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/signer/v0.rs

This PR adds a bitcoin reorg integration test to the nakamoto/signers integration test suite.
There's a couple of behaviors to note here:
1. During the reorg, the miner can't win a sortition, because of the Bitcoin MEV logic: after the reorg, the miner is marked as "not mining often enough", so has to issue some losing commits before they can win a commit.
2. During this time, the miner tries to submit a `TenureExtend`, but this is rejected by the signer set. The reason this happens is that (1) the bitcoin reorg creates a child of the common fork ancestor which has a successful sortition in it, (2) this new sortition is the "latest sortition" that the signer set sees, (3) the signer set doesn't allow the previous sortition (i.e., the parent of the latest sortition) to submit a …

test: add bitcoin reorg test to bitcoind/stacks-node/signers integrations

---

.github/workflows/bitcoin-tests.yml
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
stackslib/src/net/api/getneighbors.rs
stackslib/src/net/rpc.rs
stackslib/src/net/stackerdb/config.rs
stackslib/src/net/stackerdb/mod.rs
stackslib/src/net/stackerdb/sync.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR adds a multiple miner integration test to the `nakamoto_integrations` suite. This test _doesn't_ use the signer set (it uses the test signing channel). I'm planning on working on adding that to the signer integration test suite in a separate PR (this PR already includes a number of fixes).
As part of getting this integration test suite to work, this PR does the following:
* test: add nakamoto_integration test with multiple miners (this test uses the blind signer test signing channel)
* fix: increase the frequency of stackerdb sync, set a retry limit on stackerdb::sync pushchunks, and check for the presence of neighbors.
* fix: nakamoto miner communicates over the correct miner slot for their block election (rather than searching by pubkey)
* fix: neon miner does not submit block …

Test: multiple miner nakamoto_integration test

---

stacks-signer/Cargo.toml
stacks-signer/src/cli.rs

ref #5002 
This is the minimally viable change to allow setting the signer version at build time, defaulting to `CARGO_PKG_VERSION`. 
Since the signer already uses the same build process as stacks-core, the correct version will already be set as `STACKS_NODE_VERSION`, so that is why that env var is used here vs something more suited like `SIGNER_VERSION`. 
using `SIGNER_VERSION` would simply require some downstream changes (mainly to CI workflows), but is trivial if that env var is desired. 
I did set out to try and expose a version string like `/v2/info`, but due to how Clap was expecting a str, i wasn't able to get all the desired values returned correctly. 
```bash
~/stacks-core$ cargo run --bin stacks-signer -- --version
warning: …
```

Oneliner to set signer version at compile time with STACKS_NODE_VERSION

---

.github/workflows/bitcoin-tests.yml
libsigner/src/v0/messages.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Partially closes https://github.com/stacks-network/stacks-core/issues/4984

Feat/mock signing in 2.5

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This adds a new testing scenario to the integration suite for `v0::signer`: setting up a multiple stacks-node network with 2 miners. The signer set's event listeners (and RPC invocations) are split between the two stacks-nodes.
This test just produces bitcoin blocks and waits for block processing. It asserts that both nodes end the test with the same chain height and that they produced tenures in each bitcoin block in nakamoto.

Test: multi-miner & multi-signer scenario

---

clarity/src/vm/clarity_wasm.rs

This is a linked function for skipping an extra serialized list in a tuple.
This is needed to the "duplication of code issue" for `contract-call?`.

Clarity-wasm: Linked function for skipping a serialized list

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This PR adds a new integration test for behavior when 2 miners are running, and one of the miners engages in forking behavior. The test asserts that the signer set prevents them from producing the fork.
This PR also cleans up some the other signer set forking test some: instead of running for 20 tenures, it runs until both miners have produced 3 tenures.

Test: 2 miners with one attempting forks

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Enable mock mining in 3.0 and add integration test for it
- fixes #4898
Should I combine the `mock_mining()` integration test with `follower_bootup()` (it is based off that) or leave them separate?

feat: Enable mock mining in Epoch 3.0

---

.vscode/extensions.json

The `crates` extension is deprecated and replaced with `Dependi`, so this fixes some annoyances for VSCode developers.

Update vscode extension

---

testnet/stacks-node/src/tests/signer/v0.rs

This fixes the `empty_sortitions` integration test in CI.
Locally, this worked before because the signers stackerdb updated quickly enough, but the slower timing of CI would read the prior block responses. Now, the test waits until it gets rejections from all the signers.

CI: fix the empty_sortitions signers test in CI

---

stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/mod.rs

Ensure that the chainstate db lock is not held when attempting to lock the sortition db to avoid deadlock.

Fix deadlock

---

clarity/src/vm/analysis/type_checker/contexts.rs

Methods needed to implement typechecker workarounds in clarity-wasm

add methods to TypeMap

---

.github/workflows/stacks-core-tests.yml

When `Unit Tests` CI Job has a failure, it isn't picked up by the `check-tests` job ([example](https://github.com/stacks-network/stacks-core/actions/runs/10206028421/job/28239633529)) due to the `continue-on-error: true` line in the matrix ([here](https://github.com/stacks-network/stacks-core/blob/05280cd30f7da4f56e6bfe1c404768c9d0b24b80/.github/workflows/stacks-core-tests.yml#L75)), which causes the job status of the unit tests to show up as `success`.
This PR removes the checking of the `unit-tests` job inside `check-tests`, so this 'failed but showing up as successful' scenario is not happening anymore.

CI - Remove Unit Tests From Check

---

.github/workflows/bitcoin-tests.yml
libsigner/src/runloop.rs
stacks-signer/src/client/mod.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/lib.rs
stacks-signer/src/runloop.rs
stacks-signer/src/v0/signer.rs
stacks-signer/src/v1/signer.rs
stackslib/src/net/api/getstackers.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Fix: a handful of issues causing timing-related test failures in CI
* make `not_available_try_again` error in `GetStackers`, and make it transient in the signer binary
* make signer binary timeout on retries in client
* update signer outer runloop to differentiate between 'not in signer set' and 'have not loaded info yet'
* update signer outer runloop to handle errors and non-presence differently in the signer config refresh
* update signer outer runloop to perform signer config refresh on the current cycle (if not loaded yet) and on the next cycle (if in prepare phase for the next cycle). This was causing an issue on exactly the first cycle of Nakamoto, because the signer set cannot be loaded for the first cycle until after the prepare phase
* update the signer outer runloop to check the …

Fix: Signers CI tests and refresh signer config behaviors

---

clarity/src/vm/types/signatures.rs

Safety check in parse_trait_type_repr

fix: handle empty type_args in define-trait definition

---

.github/workflows/pr-differences-mutants.yml

This is required so that the workflow dispatch button will appear on the GUI. It is the bare minimum required for that, then the dispatch is interpreted based on the branch it is called for.
After this PR is merged, the GUI will have the manual dispatch and the custom action will be tested
https://github.com/stacks-network/actions/pull/50.
The PR for develop branch referencing is: https://github.com/stacks-network/stacks-core/pull/5083. That should be only merged after #5082 and the actions PR are merged.

CI Mutants: add workfow dispatch for GUI

---

.github/workflows/bitcoin-tests.yml
stacks-common/src/types/chainstate.rs
stacks-common/src/util/macros.rs
stacks-common/src/util/mod.rs
stackslib/src/chainstate/stacks/block.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/cli.rs
stackslib/src/lib.rs
stackslib/src/main.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

There are two parts to this PR:
- Add new config option, `node.mock_mining_output_dir`, which causes mock miner to write mock mined blocks to files
- Add subcommand to stacks-inspect, `stacks-inspect replay-mock-mining`, which will read mock mined blocks and validate them against chainstate
Added integration test `neon_integrations::replay_mock_miner()` and it passes. Have not tested against mainnet yet
Should probably add some real transactions to integration test, right now it's only coinbases
Due to refactoring `replay_block()` for use in mock mining replay, I've re-tested `stacks-inspect replay-block` and confirmed it still works
- fixes #4986
- I refactored code used by `stacks-inspect replay-block` so that could re-use it here
- I also refactored and pulled some functions out of …

feat: Neon mock miner replay

---

clarity/src/vm/ast/definition_sorter/mod.rs
contrib/boot-contracts-unit-tests/tests/misc.test.ts
stacks-signer/src/client/stacks_client.rs

chore: fix some comments

---

testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs
testnet/stacks-node/src/tests/signer/v1.rs

Looks like tihs test may have been broken for a while. It not only failed to account for a potential mined valid block randomly in the middle or proposing blocks, but it also did not properly fetch the sortition view and construct a block that would pass the signers local checks (it now does so which will force the necessary call to the API endpoint)

Fix block proposal rejection test

---

clarity/src/vm/clarity_wasm.rs

This is the stacks-core part of https://github.com/stacks-network/clarity-wasm/pull/479
This is due to an issue where we have to duplicate some parts of the code.

Clarity-Wasm: fix for the `contract-call?` host function

---

.github/ISSUE_TEMPLATE/signer_bug.md
.github/ISSUE_TEMPLATE/testnet-bug.md

Current format of the `./github/ISSUE_TEMPLATE/igner_bug.md` is incorrect for the github issues UI. 
This change modifies that so it should display correctly when loading the new issues page: https://github.com/stacks-network/stacks-core/issues/new/choose

reformat signer issue template

---

stacks-common/src/types/chainstate.rs

Revert change made in #4986 to `BurnchainHeaderHash` serialization
- fixes #5091

Fix: Revert `BurnchainHeaderHash` serialization change

---

testnet/stacks-node/src/tests/signer/v0.rs

This was causing stalls in mine_2_nakamoto_reward_cycles which would ue the block commit to trigger a stacks block and would therefore hang if no commit was submitted prior to mining the next burn block.

bugfix/boot_to_epoch_3 in SignerTest should wait for a new commit

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/keychain.rs

See title.  The partially-signed bitcoin transaction wasn't properly structured, which caused block-commits which consume multiple UTXOs to fail due to invalid signatures.  This fixes this problem and adds test coverage.

Fix: generate a well-formed Bitcoin transaction when spending multiple UTXOs

---

testnet/stacks-node/src/tests/bitcoin_regtest.rs

Config options like `rpc_port`, `username`, `password`, etc. are not consistent between `start_bitcoind()` and `stop_bitcoind()`. In `start_bitcoind()`, these are taken from the config, while in `stop_bitcoind()` they are hard-coded, and only match if the default config for integration tests is used
I came across this while working on #5096. This wasn't causing the problem, but was obviously incorrect and should be fixed anyways

fix: Use correct config opts in `stop_bitcoind()`

---

Cargo.lock
stackslib/src/net/api/getstackers.rs
stackslib/src/net/atlas/db.rs
stackslib/src/net/connection.rs
stackslib/src/net/http/mod.rs
stackslib/src/net/http/response.rs
stackslib/src/net/http/tests.rs
stackslib/src/net/httpcore.rs
stackslib/src/net/tests/httpcore.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/nakamoto_node/peer.rs

Update event dispatcher to use standard Rust to send payloads, replacing the use of async-h1 which was causing problems because `connect` cannot timeout.
- fixes #5097
This did require manually implementing the HTTP protocol, so does open the possibility for some new errors there. I added integration tests using a tiny-http server to help verify. I've also run a local network complete with signers and API as event observers and everything works as expected.

Fix event dispatcher stall

---

stacks-common/src/types/mod.rs
stackslib/src/burnchains/burnchain.rs
stackslib/src/burnchains/mod.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/test_signers.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/boot/contract_tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/chainstate/stacks/boot/signers_tests.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/core/tests/mod.rs
stackslib/src/net/api/getstackers.rs
stackslib/src/net/p2p.rs
stackslib/src/net/relay.rs
stackslib/src/net/tests/download/nakamoto.rs
stackslib/src/net/tests/mod.rs
stackslib/src/net/tests/relay/nakamoto.rs
stackslib/src/net/unsolicited.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

- Closes #5049
To help catch edge cases related to Nakamoto, this PR updates the `pox_4_tests` test suite to run tests in both epoch 2.5 and 3.0. Previously, all tests only ran in 2.5.
This PR also includes the work from @kantai to add consistent behavior to mod 0 blocks in Nakamoto, which was the cause of a previous reward cycle calculation bug. That work is included in https://github.com/stacks-network/stacks-core/pull/5072/commits/1d836175730eff88eaec9440c608267eb6303494.
This PR adds a `nakamoto_cases` rstest template, so that tests will run twice, and they're provided a `use_nakamoto` parameter. Certain setup functions have been updated (such as `prepare_pox4_test`) to utilize this argument. When `use_nakamoto` is true, the setup function utilizes the `NakamotoBootPlan` struct to …

Update pox_4_tests to run in 2.5 and 3.0

---

stackslib/src/net/httpcore.rs

Was irritated trolling the logs so figured I would open this quickly so I feel like I did SOMETHING

Chore/fix message name in httpcore.rs StacksHttpMessage

---

stackslib/src/chainstate/burn/operations/leader_key_register.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

Changed some `test_debug!` logs `debug!`. These would have helped to debug a VRF key registration error.

fix: key register op must have a change output

---

.github/workflows/bitcoin-tests.yml
stacks-common/src/util/secp256k1.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

- Add v0 signer test where first two signers have the same key
- Add checks in `mine_and_verify_confirmed_naka_block()` to confirm that no two signers have the same private key
- fixes #5077
I was trying to make this test check that only the first signer with the duplicate was accepted, and the second was rejected, but this seems impossible because the signatures from the signers are identical. So I just check that the signature is not included twice

test(signer): Add test with duplicate signer private key

---

stacks-common/src/util/mod.rs
stackslib/src/chainstate/stacks/index/node.rs
stackslib/src/chainstate/stacks/index/proofs.rs

I noticed this function while working on #5137. It's unnecessary, as `==` works fine with slices, and I'm sure Rust's `PartialEq` implementation uses something like `memcmp()` instead of a loop, so should improve performance. Using my standard benchmark, I see a small improvement in block processing times:
```console
❯ hyperfine -w 3 -r 20 "target/release/stacks-inspect.develop replay-block /home/jbencin/data/next/mainnet range 99990 100000" "target/release/stacks-inspect.remove-slice_partialeq replay-block /home/jbencin/data/next/mainnet range 99990 100000"
Benchmark 1: target/release/stacks-inspect.develop replay-block /home/jbencin/data/next/mainnet range 99990 100000
Time (mean ± σ):      9.753 s ±  0.044 s    [User: 9.042 s, System: 0.674 s]
Range (min … max):    9.698 s …  9.886 s …
```

chore: Remove unnecessary function `slice_partialeq()`

---

testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs

Caught this in the [naka-3 logs](https://grafana.hiro.tools/goto/RbS--76SR?orgId=1) at tenure 810.

fix: ignore rejections for other blocks in sign coordinator

---

testnet/stacks-node/src/tests/signer/v0.rs

Adjust the block height that it mines to to reach the next cycle in accordance with recent changes.

test: fix `signer_set_rollover` test

---

.github/workflows/pr-differences-mutants.yml

This is the PR enabling the full manual dispatch of the mutants CI so that they could run for more than 6 hours. It has a custom action limiting the access to trigger that only to the wanted team.
This should be merged only after the develop branch PR is merged https://github.com/stacks-network/stacks-core/pull/5083

CI Mutants: Action Membership Run Updated to match Develop branch

---

stackslib/src/chainstate/stacks/tests/block_construction.rs

Related Issue:
"Integration Test - Non standard transaction, but not invalid being anchored" https://github.com/stacks-network/stacks-core/issues/5129

Adds Test - Non standard transaction, but not invalid being anchored

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/signer/v0.rs

We were originally spamming wth messages that we were writing mock proposals and mock blocks when we were actually failing to do so as we were not the sortition winner. This not only fixes it to CORRECTLY report accepted == false as an error to send miner messages, but it also updates the miner to not bother attempting to write a mock proposal/block when it is not the last sortition winner.

Check if we are the sortition winner before attempting to mock sign

---

clarity/src/vm/clarity_wasm.rs

Instead of `ast::parse`, which apparently is a [testing-gated legacy function](https://github.com/stacks-network/stacks-core/blob/master/clarity/src/vm/ast/mod.rs#L46-L48), use a better one; stack-core counterpart of https://github.com/stacks-network/clarity-wasm/pull/509.

Clarity-Wasm: avoid using testing-gated parse function

---

clarity/src/vm/database/sqlite.rs
stacks-common/src/util/db.rs
stacks-common/src/util/mod.rs
stackslib/src/util_lib/db.rs

This PR makes two changes to `tx_busy_handler()`, which is passed as a callback to rusqlite and called if waiting too long for a DB lock
- Improve logging. Previously, all logs in `tx_busy_handler()` were debug level, now we have warn/error level messages if we are waiting too long
- After a certain amount of time has passed (about a minute) we should assume we have a deadlock, stop trying to open the DB, log and return an error
Note that this PR doesn't make deadlocks less likely to occur, it just makes them easier to find, and generates an error when they are detected, which may be recoverable or may crash the application (depending on how the caller handles the error)
- #5112
I could have added precise timing using `Instant::now()`, but that would require wrapping `tx_busy_handler()` …

fix: Improve DB deadlock detection/logging

---

testnet/stacks-node/src/nakamoto_node/miner.rs

This would be helpful when analyzing logs.

chore: add info to signature gathering failure logs

---

stacks-signer/src/runloop.rs

This was confusing as heck. Totally misunderstood what configured_for_cycle meant so added a useful additional field to make it more clear.

Fix confusion over what configured for cycle means by adding is_registered_for_cycle

---

stacks-signer/src/signerdb.rs

Not sure how this got missed but fixed now!

Fix unhandled result in block state machine move_to calls

---

stacks-signer/src/client/stacks_client.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5186
There are a few new RPC calls in the signer's `stacks_client.rs` that were missing prometheus timers. This PR adds timers to those missing functions.

fix: add missing prometheus timers to stacks_client

---

stacks-signer/src/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/config.rs

- Add more signer logs for help with debugging.
- Change default `nakamoto_attempt_time_ms` to 5s (from 20s)

Logs and defaults

---

clarity/src/vm/clarity_wasm.rs

Stacks-core counterpart of https://github.com/stacks-network/clarity-wasm/pull/510.
Tested with https://github.com/stacks-network/clarity-wasm/pull/510/commits/8c902d5508d381b402786e8f88401f037dc2fdea.

Clarity-Wasm: add error mapping for already used arg error

---

stacks-signer/src/client/stacks_client.rs

The signer exposes prometheus metrics, but because many of the RPC timers use the "raw" RPC path, it exposes a risk of high cardinality (ie many unique labels), especially when many signers are used across many networks.
To reduce that cardinality, the PR updates some of the RPC call timers to use a more "generic" path. For example, instead of `/v2/accounts/SP123`, it uses `/v2/accounts/:stacks_address`. Similarly, for read-only functions, the contract address is replaced with `:principal`, which will make the label the same across mainnet and testnet.
Reviewers: please double check the RPC timer labels in `stacks_client.rs` to ensure there aren't other timers that have dynamic values in them. Additionally, please double check that the labels are still descriptive enough.

fix: use lower-cardinality prometheus metrics in signer

---

testnet/stacks-node/src/tests/signer/v0.rs

This fixes:
* signer::v0::locally_rejected_blocks_overriden_by_global_acceptance
* signer::v0::reorg_locally_accepted_blocks_across_tenures_succeeds
These tests previously depended on the `blocks_mined` counter and then immediately checked a `v2/info` assertion. This is a race condition: the stacks-node may not have processed the mined block yet. This caused test flake in CI (but usually not in local runs where machines are fast enough to never experience this condition).
This doesn't resolve any of the other test flake (`signer_set_rollover` and `mine_2_nakamoto_reward_cycles`)

Chore: Fix some flaky signer tests

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This prevents the response from being too large and exceeding the 16MB limit that we support.

fix: limit number of UTXOs retrieved with `listunspent`

---

stacks-signer/src/client/stacks_client.rs

Brice and I had some trouble debugging a version mismatch between the node and the signer due to a silent failure to parse the result of a v2/stacker_set call that should have been made to v3/stacker_set. technically trying to access this endppint does not return a 404, rather it returns a text "No such file or directory" which fails at the deserialization step silently. Do not let it silently fail by logging in this case.

Print a warning if failed to parse the stackers response

---

testnet/stacks-node/src/tests/signer/v0.rs

The signer config was marking a miner invalid with a short timeout but due to CI slowing things down, it was common for this to invalidate all miners too quickly. There also was an issue where it did not properly wait for a commit to be processed and ensure the first nakamoto block was processed in boot_to_epoch.

Empty sortition needed a longer block timeout since CI is slow

---

stackslib/src/chainstate/stacks/miner.rs
stackslib/src/chainstate/stacks/tests/block_construction.rs
stackslib/src/core/mempool.rs

The mempool iteration is invoked by the stacks miner to iterate over a mempool. However, the loop exit condition (`num_considered == 0`) means that there's always an additional "empty" invocation after the mempool has been cleared. This change eliminates that by returning the reason that the iteration exited.

Feat: optimize mempool iteration by skipping last invocation

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs
testnet/stacks-node/src/tests/neon_integrations.rs

I wanted to test out whether stopping bitcoind from within the Rust code, rather than spawning the CLI, would make any difference in whether these tests pass in CI.

test: try stopping bitcoind within Rust, rather than spawning the CLI

---

testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Let's try to fix some test flake, but directly against `develop`!
Right now, I just cherry picked, but I'd like to see where that leaves us.

Chore: Fix some CI tests

---

docs/rpc/api/core-node/get_sortitions.example.json
docs/rpc/api/core-node/get_sortitions_latest_and_prior.example.json
docs/rpc/openapi.yaml
stacks-signer/src/chainstate.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/tests/chainstate.rs
stackslib/src/net/api/getsortition.rs
stackslib/src/net/api/tests/getsortition.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This implements the lowest hanging fruit for https://github.com/stacks-network/stacks-core/issues/5200 by adding an endpoint that returns both the current and prior sortitions.

feat: add a consolidated endpoint for current and prior sortitions

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

I missed this other call to `listunspent` in the previous related PR.

fix: use `max_unspent_utxos` in `get_all_utxos`

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
docs/rpc-endpoints.md
docs/rpc/openapi.yaml
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/net/api/getsigner.rs
stackslib/src/net/api/mod.rs
stackslib/src/net/api/tests/getsigner.rs
stackslib/src/net/api/tests/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Add RPC endpoint `/v3/signer/{signer_pubkey}/{reward_cycle}` that returns number of blocks signed by signer during given reward cycle
- fixes #5106
Someone with more experience with chainstate DB and SQL in general please double-check the schema migration and queries

feat: Signer signature count endpoint

---

.vscode/settings.json

This makes it easier to run and debug integration tests inside of VSCode.

test: add `BITCOIND_TEST=1` for running tests in VSCode

---

pox-locking/src/events.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs

- fixes important off-by-one error in event emitting of pox-events. not consensus critical, but should be released with next release for accurate downstream reporting (e.g. by the API)
---
I'm not familiar with the test setup, but I'd like to have the tests also do the "actual" check of the reward set being locked/set. Can someone help with that?

fix: off by one pox set offset

---

stackslib/src/net/relay.rs

This fixes a probable cause of the seed node in naka-3 freezing up.

fix: don't ban peers for sending us nakamoto blocks we can't yet handle

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/signer/v0.rs

Closes https://github.com/stacks-network/stacks-core/issues/4747
Not sure this is exactly what was wanted. I interpreted "0th tenure of a reward cycle", being make sure that blocks can be signed in the very first burn block of a reward cycle.

Add signing_in_0th_tenure_of_reward_cycle test

---

stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/stacks/mod.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This makes sure that the block commits submitted by the miner after a fork are all pointing at the correct burn block before mining more burn blocks. Otherwise, the test could fail because the miner did not validly mine often enough to beat the "null miner".

CI: Fix signer::v0::bitcoind_forking flakiness

---

.github/workflows/bitcoin-tests.yml
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/v0/signer.rs

This PR removes an infinite loop in the signer when `cfg!(test)` is active. The rationale for this is that signer integration tests often stop the `stacks-node` threads (via panic, asserts, etc.) on failure before they stop the signer threads. I think this leads to a situation where a test failure loops indefinitely, which in the CI prevents logs from appearing, making diagnosing CI failures and flaky tests _very_ difficult.
This PR also removes the first block push invocation -- if the first push in the loop succeeds, there's no need to repush.

Chore: remove infinite loop in signer during tests

---

stacks-signer/src/chainstate.rs
stacks-signer/src/tests/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

- Fixes https://github.com/stacks-network/stacks-core/issues/5251
Adds a new parameter to `check_proposal` called `reset_view_if_wrong_consensus_hash`. Inside `check_proposal`, if the block's consensus hash doesn't match the signer's sortition view, the chainstate is first refreshed, and then `check_proposal` is called one more time.

feat: refresh sortition view when proposed block has mismatch

---

stacks-signer/src/client/stacks_client.rs

This was crashing nakamoto testnet

Pass correct path to new_rpc_call_timer in get_tenure_forking_info

---

testnet/stacks-node/src/run_loop/neon.rs

CI was failing intermittently because when shutting down the neon node, it did not always do so cleanly. Specifically, it would hit line 1392 with error!("Runloop: Block relayer and miner hung up, exiting."); and then fail to pass on the peer network bind to the naka node which would then fail to spawn as the p2p bind address would already still be in use.

Do not abort the runloop unless we were not told to exit

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

we enabled prometheus metrics and it broke a few tests. I am sure I fixed miner_gather_signatures correctly, but am unconvinced the fix for simple_neon_integration is correct. I mean it passes. But I do not fully understand why it does not advance the tip. I had a hard time understanding the path of calling update_stacks_tip_height. It currently only gets called in the relayer when processing transactions so maybe this is expected that the tip would be one behind in the test? but not 100% sure.

Fix metric breakage

---

stacks-common/src/util/mod.rs

Rusqlite is only enabled with the `canonical`  feature

fix: don not use rusqlite in clarity-vm without default features

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Forgot to set pox_sync_sample_secs to a positive integer in multiple_miners and was getting lots of crashes in various tests about the stacker set not being calculated yet. This will just advance one more block into the prepare phase to ensure the stacker set is calculated and put the call to the endpoint on a retry in case there is some sort of delay.

Fix boot to epoch 3 calls to retrieve the stacker set and fix multple miners test 

---

CHANGELOG.md
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/epoch_205.rs
testnet/stacks-node/src/tests/epoch_21.rs
testnet/stacks-node/src/tests/epoch_22.rs
testnet/stacks-node/src/tests/epoch_23.rs
testnet/stacks-node/src/tests/epoch_24.rs
testnet/stacks-node/src/tests/epoch_25.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs
testnet/stacks-node/src/tests/stackerdb.rs

Adds an optional `timeout_ms` to the configuration for event observers, allowing users to set a unique timeout for each observer.

feat: make the timeout for event observers configurable

---

stackslib/src/net/p2p.rs
stackslib/src/net/stackerdb/mod.rs
stackslib/src/net/stackerdb/sync.rs
stackslib/src/net/stackerdb/tests/sync.rs

This fixes a bug in StackerDB sync present in 3.0-rc3 whereby the state machine never completes, causing it to miss StackerDB updates.  This was due to a flaw in the success condition of `connect_begin()` -- we would either fail to complete it in a timely manner if some nodes weren't routable, or we would always fail if all replicas have been connected to or attempted to be connected to (which was meant at one point to mean "there are no more replicas to try", but that had since changed).  The fix is to treat `connect_begin()` as successful if there is at least one _connected_ replica, and rely on the fact that `connect_begin()` will connect to subsequent replicas in subsequent passes.  To prevent ossification, the node will deliberately forget about one connected replica at random once …

Fix/stackerdb sync for 3.0-rc3

---

stackslib/src/chainstate/nakamoto/mod.rs

Tiny optimization that came up from code reviewers. When checking a pox bitvec, instead of an O(nm) search, do O(n)

fix: use O(n) instead of mn when checking pox bitvec

---

stackslib/src/net/poll.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Check if in feature == testing and reserve test observer port in USED_PORTS

CI fix: Fix occasional port bind error happening in mock mining

---

testnet/stacks-node/src/nakamoto_node/relayer.rs

Note: this is not a fix to the mock_mining test. I have that in the pipeline. This i just to rectify something Brice and I discovered while investigating the test.

Do not error if block submit fails in mock mining case in Nakamoto

---

stacks-signer/src/client/stackerdb.rs
stacks-signer/src/client/stacks_client.rs
stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/tests/chainstate.rs
stacks-signer/src/tests/conf/signer-custom-chain-id.toml
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5313
This adds an optional `chain_id` field to the signer's config. If present, it is used in the `/v3/block_proposal` endpoint.

feat: add chain_id to signer config

---

testnet/stacks-node/src/config.rs

3.0 can only activate in reward cycle 2 or later.

feat: add reward cycle check for 3.0 activation

---

.github/workflows/bitcoin-tests.yml
stacks-signer/src/config.rs
testnet/stacks-node/src/tests/signer/v0.rs

This was requested by Brice in https://github.com/stacks-network/stacks-core/pull/5314#pullrequestreview-2367908222

Add multiple_miners_with_custom_chain_id test to test chain id in a signer integration test

---

CHANGELOG.md
Cargo.lock
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs

Record events to be sent to event observers in a new sqlite database so that in the event that the node is killed before successfully sending, they can be re-sent on restart.
This is building on top of #5286.

feat: support re-sending events to event observers across restarts

---

clarity/src/vm/database/clarity_db.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/functions/database.rs
clarity/src/vm/test_util/mod.rs
clarity/src/vm/tests/contracts.rs
stackslib/src/burnchains/tests/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/keys.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/boot/contract_tests.rs
stackslib/src/chainstate/stacks/boot/mod.rs
stackslib/src/chainstate/stacks/tests/mod.rs
stackslib/src/clarity_cli.rs
stackslib/src/clarity_vm/database/mod.rs
stackslib/src/cli.rs
stackslib/src/net/mod.rs
stackslib/src/net/tests/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This PR makes get-block-info interpret block heights as tenure heights in Clarity 2 contracts.

Feat: block info handling in Clarity 2 contracts post-3.0

---

stacks-signer/src/cli.rs
stacks-signer/src/lib.rs
stacks-signer/src/main.rs
stacks-signer/src/monitoring/server.rs

We previously had a `VERSION_STRING` that you could use with `stacks-signer --version`. This PR does a few things:
- Use the `version_string` helper to improve code re-use (it was the same exact code anyways)
- When starting the signer, print the version
- Add version to `check-config` CLI command
- Add version to the `/info` endpoint on the metrics server

feat: better exposing of signer version

---

testnet/stacks-node/src/event_dispatcher.rs

While debugging an issue with stacks-node -> API communication, I realized we could do some things better in this retry code. They are all pretty minor changes.

Improvements to event dispatcher retry logic

---

stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/cost_estimates/tests/common.rs
stackslib/src/net/mod.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/run_loop/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Closes https://github.com/stacks-network/stacks-core/issues/5318
Part of https://github.com/hirosystems/explorer/issues/1624 and https://github.com/hirosystems/stacks-blockchain-api/issues/2124
Adds a `tenure_height` (AKA `coinbase_height`) to the `/new_block` event payload.
In epoch2.x this is the same value as `block_height`.

Include `tenure_height` in `/new_block` event payload

---

libsigner/src/libsigner.rs
libsigner/src/v0/messages.rs
stacks-signer/src/cli.rs
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/lib.rs
stacks-signer/src/main.rs
stacks-signer/src/monitoring/server.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5332
This adds the signer's version string to signer messages. To ensure backwards compatibility, I've added a light `SignerMessageMetadata` struct. Right now it only has the `server_version` string, but it's mainly used to implement special-case decoding if there are no bytes left to read.

Add version to signer messages

---

testnet/stacks-node/src/config.rs

We can now always assume that anchor blocks exist.

Fix default affirmation map settings for 3.0

---

testnet/stacks-node/src/tests/signer/v0.rs

I am an idiot and did not reason out the prior fix correctly at all....Please don't judge me...

Fix partial tenure fork test for real: Only check if we advanced pre fork miner 2 blocks forward

---

stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/chainstate/stacks/mod.rs

This updates the tx estimator when an evaluated tx yields a TransactionTooBigError. This should improve the performance of the miner.

feat: update tx estimator when tx yields too big tx error

---

testnet/stacks-node/src/tests/signer/v0.rs

Use a hashset when retrieving blocks from the test observer so we don't count duplicate blocks.
Increase the reward cycle length and max nakamoto tenures to increase the likelihood of hitting the test condition before the test ends.

Have get nakamoto headers return only the unique block ids and increase reward cycle length

---

stacks-signer/src/lib.rs

Found and fixed a stale link. 
I am afraid this might break again though. To improve, we could:
1. Have a "well-known" doc URI that we ensure never changes. It can redirect the user to the most appropriate place.
2. Show the warning only if the signer is not bound to a loopback address (core already has [code to check that](https://github.com/stacks-network/stacks-core/blob/a2dcd4c3ffdb625a6478bb2c0b23836bc9c72f9f/stacks-common/src/types/net.rs#L225) that could be used as inspiration).

fix: Signer networking setup docs link

---

testnet/stacks-node/src/tests/signer/v0.rs

We cannot guarantee all signers sign before the block is broadcasted and appended. Therefore, use the appended signatures to determine which signer metric should update 
Closes https://github.com/stacks-network/stacks-core/issues/5367

signing_in_0th_tenure_of_reward_cycle fix: only check signers who match signatures on the block 

---

testnet/stacks-node/src/tests/signer/v0.rs

We were using the burn block timestamp to compare against the stacks block timestamp. I also think the test was a bit short. So I changed it to mine a few nakamoto blocks and made sure the timestamp between all of them is as expected.

Fix min_gap_between_blocks test: Do not use the burn block timestamp when comparing the min gap between blocks

---

clarity/src/vm/docs/mod.rs

By specifying in the clarity docs if a `get-X-info?` if it takes a burn-block-height or a stacks-block-height, it makes it easier to use and less error prone by just looking at the function signature

docs: explicitly specify burn or stacks block height parameter in clarity get info functions

---

testnet/stacks-node/src/tests/signer/v0.rs

Closes https://github.com/stacks-network/stacks-core/issues/5379
Also cleaned up the loops cause why not?

Fix miner_recovers_when_broadcast_block_delay_across_tenures_occurs: Do not expect an exact number of signatures

---

stacks-signer/src/v0/signer.rs

Some tests were failing because the metrics did not increment the block responses when a proposal arrived AFTER the block reached 70% consensus (see miner_gather_signatures test in https://github.com/stacks-network/stacks-core/actions/runs/11520120250/job/32078155127?pr=5261#logs). Even though the signers still sent a response. Update every time we send a block response (this also enables duplicate proposals that are responded to be counted)
Closes: https://github.com/stacks-network/stacks-core/issues/5388

Increment block responses sent all the time

---

stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/tests/signer/v0.rs

Fixes https://github.com/stacks-network/stacks-core/issues/5389

locally_accepted_blocks_overriden_by_global_rejection fix: Store the rejected block in the database in testing directive case

---

testnet/stacks-node/src/tests/signer/v0.rs

See https://github.com/stacks-network/stacks-core/actions/runs/11559351077/job/32179118543?pr=5261

Fix miner_recovers_when_broadcast_delay_across_tenures_occurs: Wait for the tip to update before proceeding

---

stacks-signer/src/v0/signer.rs

This technically could be an accept or a reject so fix the log to be appropriate.

Chore: Change block rejection message to generic block response

---

stacks-signer/src/config.rs
stacks-signer/src/main.rs
stacks-signer/src/monitoring/mod.rs
stacks-signer/src/v0/signer.rs
stackslib/src/cli.rs

This is very low priority obviously but if you have downtime...easy review! :) 
I had fixed clippy in signer so many times. @wileyj can you add clippy to the signer CI (again incredibly low priority)?
I also fixed the build warnings in stackslib.

Clippy fix signer and stackslib cli.rs

---

Cargo.lock
Cargo.toml
libsigner/Cargo.toml
stacks-signer/Cargo.toml
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs

Made thiserror a workspace lib. I also checked and made sure no unsafe throughout even in the updated version. 
Updated the custom fmt::Display implementations throughout testnet/stacks-node to use thiserror cause I love red <3

Use thiserror throughout testnet/stacks-node

---

CHANGELOG.md
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/stacks/db/mod.rs

Optimization: add index for `index_block_hash` in `nakamoto_block_headers`

feat: add index for stacks block id in nakamoto_block_headers

---

CHANGELOG.md
stacks-common/src/util/db.rs

Instead of panicking after 5m, just print an error with a backtrace every 5 minutes. This is sufficient to detect the situation without the need to crash the node and potentially corrupt chainstate.

feat: remove panic in DB busy handler

---

stackslib/src/net/api/getattachmentsinv.rs

This causes a warning in the latest versions of Rust.

chore: remove irrefutable if let

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/signer/v0.rs

I see #5411 is also trying to test something similar. I will take a look to see if we are overlapping. I was also not able to reproduce any incorrect behavior here yet.

test: additional scenarios for empty sortition tenure extends

---

.github/workflows/bitcoin-tests.yml
stacks-signer/src/chainstate.rs
stacks-signer/src/client/mod.rs
stacks-signer/src/config.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signerdb.rs
stacks-signer/src/tests/chainstate.rs
stackslib/src/chainstate/stacks/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

Closes https://github.com/stacks-network/stacks-core/issues/5423

Add config option tenure_last_block_proposal_timeout_secs and do not allow reorgs at tenure boundary before it is exceeded

---

testnet/stacks-node/src/tests/signer/v0.rs

This test has been so flakey and it hurts my soul and its really mostly because we can't gurantee sortition winners. Now lets change that. I am 99% sure I am testing what it used to test but @kantai I think you wrote this test, so would really appreciate your input.

Fix miner forking by being strict about sortition winners

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
docs/mining.md
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This option defines the number of ms to wait after seeing a new burn block before submitting a block commit, allowing time for the first Nakamoto block to arrive so that the block commit does not need to be RBFed.
Fixes: #5064

feat: add `block_commit_delay_ms` config option

---

CHANGELOG.md
clarity/src/vm/database/sqlite.rs

Didn't see a PR so figured I'd open it
- Closes https://github.com/stacks-network/stacks-core/issues/5430

feat: add blockhash index to metadata_table Clarity VM table

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5400
(hopefully eventually)
This PR currently just contains an integration test to try and reproduce the scenario described in #5400.
The basic flow of the test is:
- boot to nakamoto
- mine a regular block (A) (burn block with TenureChange)
- Have signers reject all new block proposals
- Mine a new BTC block (B) with a sortition
- Wait for the signers to reject it
- Mine a new BTC block (C) **without** a sortition
- Turn off the block rejection flag
I thought this would reproduce the issue, but things seem fine - the miner creates a `TenureExtend` off of block A and signers approve it.
**JACINTA EDIT:**
So I modified the logic to check during continue_tenure to see if we failed to produce any blocks in our tenure which means …

Miner can continue mining after an empty tenure followed by empty sortition

---

stackslib/src/net/inv/nakamoto.rs

Switch make_tenure_bitvector debug logs to trace level logs since perf/flamegraph has shown a disproportionate amount of time being spent in these slog calls.

Replace make_tenure_bitvector debug logs with trace level logs

---

clarity/src/vm/clarity_wasm.rs
clarity/src/vm/contexts.rs

Instantiating a `wasmtime::Engine` is an expensive operation, so it is best to do it only once for the duration of a `GlobalContext`. Cloning an engine is, however, not an expensive operation (just an `Arc::clone`) and we use it to avoid referring to the global context already referred to by the instantiated `ClarityWasmContext`.
See-also: https://github.com/stacks-network/clarity-wasm/issues/468

feat(wasm): use only one `Engine` per global context

---

libsigner/src/v0/messages.rs
stacks-signer/CHANGELOG.md
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/tests/conf/signer-0.toml
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs

Needed to complete https://github.com/stacks-network/stacks-core/issues/5434

Add tenure_extend_timestamp to Block Response Accept messages

---

stacks-signer/src/v0/signer.rs

This is a small QOL change. When the signer hits an error when inserting into signerDB, the code panics without logging the specific error that happened.
This change does two things:
- Adds an explicit `error` log, because `panic!` doesn't actually create an error-level log
- Includes the exception in the log message

fix: better error logging with signerdb insert error

---

stacks-signer/CHANGELOG.md
stacks-signer/src/chainstate.rs
stacks-signer/src/client/mod.rs
stacks-signer/src/config.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signerdb.rs
stacks-signer/src/tests/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/tests/epoch_25.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

First pass. Haven't tested this at all and this was just first thoughts. EDIT: Initially way over-complicating things and assumed that we should respond to a block proposal based on who the current sortition winner is. However, if a miner proposes a block proposal that does not link to the correct consensus hash (odds are it will be rejected first off), it does not actually really matter. We will simply let the proposing miner know that the tenure extend for that timestamp has passed or not. It only matters that a valid sortition winner knows this for a valid proposal/valid attempt to tenure change. This simplified things a lot as I could just respond to every block proposal based on its provided consensus hash.

Add timestamp calculation to all block responses

---

stacks-signer/src/chainstate.rs
stacks-signer/src/signerdb.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/tests/signer/v0.rs

I think it made the most sense to put the calculate tenure extend timestamp code inside the signer db code but I could also put it in the utils if preferred.

Signers: Use tenure extend timestamp to determine if enough time has passed for a tenure extend

---

clarity/src/vm/representations.rs

Clarinet uses `clarity` with the developer-mode feature enabled.
It also needs to fetch some data from the RPC endpoints from the stacks-nodes (such as contract metadata, including contract body, as SymbolicExpressions).
The response from the stacks-node don't include the SymbolicExpression span and other `developer-mode` properties.
As a result, Clarinet can not parse the response of the api call.
By adding the `#[serde(default)]` directive, it enables Clarinet to parse the response. It's important to note that n this context, we don't care about the actual values of this properties

refactor: add serde default to symbolic expression struct

---

.github/workflows/p2p-tests.yml
stackslib/src/net/rpc.rs
stackslib/src/net/server.rs

This fixes #5490, and fixes the problem we were seeing in #5296 and #4997.  The fundamental problem was that the HTTP session state machine was not correctly treating server-generated HTTP error responses as having completed once they were flushed.  This PR fixes this, and removes some now-needless (and buggy) code that had earlier attempted (and failed) to address this problem.
Let's get this into `develop` so we can turn around and fix #5296 and #4997.

 Fix/http stall on invalid message

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
stacks-signer/CHANGELOG.md
stacks-signer/src/chainstate.rs
stacks-signer/src/signerdb.rs
stackslib/src/chainstate/burn/db/sortdb.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/tests/epoch_25.rs
testnet/stacks-node/src/tests/signer/v0.rs

Updates the miner to attempt to continue its tenure if the winner of the next tenure commits to the wrong block or if it mines no blocks within some grace period.
- fixes #5361

Tenure extend when the previous tenure is bad

---

clarity/src/vm/clarity_wasm.rs

This PR splits `get-block-info` and `get-burn-block-info` so every property has its own linked function in order to avoid pushing every property of the `get-block-info` and `get-burn-block-info` functions to the stack once they are called.
e.g. when the function `get-block-info` is compiled, the compiler generates the code for all the available properties. 
With this change, when `get-block-info` is compiled it will generate only the property that is called.
Related issue: https://github.com/stacks-network/clarity-wasm/issues/430

Split `get-(burn)-block-info` linker function

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
stacks-signer/src/signerdb.rs
stackslib/src/chainstate/burn/db/sortdb.rs

Changelogs for 3.0.0.04
edit: also including the changes in #5521 since clippy was preventing the build from succeeding

Update changelogs for 3.0.0.0.4

---

CHANGELOG.md

Add the new rpc endpoints from #4997 to the changelog

docs: add 2 new clarity endpoints to the unreleased changelog

---

.github/workflows/bitcoin-tests.yml
libsigner/src/v0/messages.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

- Relates to https://github.com/stacks-network/stacks-core/issues/5465
- Continues work of https://github.com/stacks-network/stacks-core/pull/5471
Adds a test for tenure extends happening after the idle timeout when there is active mining involved. This test ensure that multiple extends occur within a single tenure (BTC block) after each idle timeout is reached.
I've added some test helpers in here, mainly because I was over writing the same boilerplate for certain things. I didn't want to change other tests too much to limit the diff, but I'm happy to.

feat: test for idle extend with active mining

---

clarity/src/vm/mod.rs

Serializing `CostSynthesis` is needed in Clarinet.
Is it ok to add it here even though it's not used internally in stacks-core?
The alternative would be to create a identical struct in Clarinet that can be Serialized and has a `from<CostSynthesis>`, adding a bit of complexity but I'm fine with it to

feat: add serialize to cost synthesis

---

CONTRIBUTING.md
clarity/src/vm/docs/mod.rs
clarity/src/vm/mod.rs

remove redundant words in comment

chore: remove redundant words in comment

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
stackslib/src/chainstate/nakamoto/mod.rs

Changelog for 3.1 (sip-029) and cherry-pick from #5538

Add changlog for epoch 3.1 and revert block version (5538)

---

CHANGELOG.md
stackslib/src/net/api/postblock_proposal.rs

When nodes change their `NAKAMOTO_BLOCK_VERSION`, unupgraded signers reject the block, because the unupgraded signers use the old version when trying to clone (and compare the block hash) of the proposed block.
This change has the block validation endpoint clone the version of the proposed block to the local block, so that the block hash will match.
We may need more validation here about what a valid block version is - for example, I believe it needs to be <128, or it is treated as a shadow block. Thus, opening as a draft.

fix: when validating a block, clone the blocks version

---

stackslib/src/chainstate/nakamoto/mod.rs

Due to an issue with how signers validate block proposals, unupgraded signers reject blocks that have a different default version than their node. Thus, this change reverts the default version until we have a fix for the block validation endpoint (which will come in a different PR).

fix: revert stack block version change

---

clarity/src/vm/contexts.rs
clarity/src/vm/database/key_value_wrapper.rs
stackslib/src/net/tests/mod.rs

Rust 1.83 seems to be more strict about declaring lifetimes and now generates warnings for certain cases in which they are elided. Example:
```
Compiling clarity v0.0.1 (/home/jbencin/git/stacks-core/clarity)
warning: elided lifetime has a name
--> clarity/./src/vm/contexts.rs:560:31
|
500 | impl<'a, 'hooks> OwnedEnvironment<'a, 'hooks> {
|      -- lifetime `'a` declared here
...
560 |     ) -> OwnedEnvironment<'a, '_> {
|                               ^^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```
This PR fixes the warnings by explicitly declaring the lifetimes

fix: New lifetime warnings in Rust 1.83

---

stacks-signer/CHANGELOG.md
stacks-signer/src/runloop.rs

We used to keep reward cycle signers for an extra reward cycle in prep for potentially the fallback scenario where signers would continue signing blocks/sbtc transactions if the incoming signers failed to initialize. However, this is really confusing our partners who don't understand why their logs report stale signers as operating. Also this old logic was flawed anyway as we only ever kept 2 signers around anyway (the hashmap of signers is keyed by the reward_cycle % 2). The cleanup function as it was essentially was a no-op. 
This code change makes the function delete anything that has no unprocessed blocks in its database and that is for a reward cycle older than the current reward cycle. We can always revert or add additional logic about when to delete them when we start giving …

Remove signers older than the current reward cycle if they have no more blocks to process

---

CHANGELOG.md
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/clarity_vm/clarity.rs
stackslib/src/core/mod.rs

This is replacing #5559 as a hot fix against master instead of develop.

fix: set epoch to 3.1 in Clarity DB

---

.github/workflows/clippy.yml
stacks-signer/src/chainstate.rs
stacks-signer/src/cli.rs

Add clippy to CI.
Somehow this was deleted from CI...I am just in the process of adding back the existing libs and fixing the subsequent warnings, but please take a look in case you think there is something wrong with adding this back...

Add clippy to CI

---

stackslib/src/config/mod.rs

We don't need to do DNS lookups for tests and we want to encourage people to run their own Bitcoin nodes anyway.
Fixes some failing tests.

fix: remove DNS names from `peer_host` field

---

stacks-signer/CHANGELOG.md
stacks-signer/src/v0/signer.rs

@obycode discovered that the recent stall was due to the WRONG signer (one from prior reward cycle) processing a block validation response and attempting to broadcast when it thought it had enough signatures. The block proposal itself was already reward cycle gated but not the block validationr esponse. This caused some inifite looping in a signer that tried to broadcast a signed block that met its own reward cycle threshold but not the actual reward cycle threshold of the current reward cycle. 
This should be fixed in the event parity check but that would require changes to the node. This is just a hotfix for the signers only. 
This only became an issue now because of a change I made to the signer db: we no longer query the db based on reward_cycle (this never was a problem before …

Do not process block validation responses for the wrong reward cycle

---

stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/cli.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Add Nakamoto block support to `stacks-inspect try-mine`
- #5551
- #5541
This works with the testnet chainstate I've been using for testing, but I'm not sure if there are any edge cases I need to specifically handle here, depending on where in the tenure the block is

feat: Nakamoto block support for `stacks-insepct try-mine`

---

Cargo.lock
stacks-common/Cargo.toml
stacks-signer/Cargo.toml
stackslib/Cargo.toml
testnet/stacks-node/Cargo.toml

Remove unused dependencies found by running `cargo udeps` ([link](https://github.com/est31/cargo-udeps)). This removes quite a few packages from Cargo.lock (mainly from removing `criterion`), so it should speed up `cargo test` a bit

chore: Remove unused deps found by `cargo udeps`

---

stackslib/src/burnchains/tests/mod.rs
stackslib/src/chainstate/nakamoto/shadow.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/index/test/marf.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/chainstate/stacks/mod.rs
stackslib/src/core/tests/mod.rs
stackslib/src/net/dns.rs
stackslib/src/net/download/epoch2x.rs
stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
stackslib/src/net/p2p.rs
stackslib/src/net/relay.rs
stackslib/src/net/server.rs

Apply Clippy lint `iter_with_drain`, which finds places where `.drain(..)` can be replaced with `.into_iter()` (there are still a couple false positives in the code)
This is more efficient because `into_iter()` does not clear the `Vec`

chore: Apply Clippy lint `iter_with_drain`

---

stackslib/src/chainstate/stacks/transaction.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Closes https://github.com/stacks-network/stacks-core/issues/5634
We now generate phantom unlock txs and include them in tenure change blocks. These really are actually only tx receipts though not actual transactions. I attempt to filter them out from the test_observer call. I could prevent them being added to the transaction list but I feel like maybe that its better to include them and just not parse them out from the final test_observer end.

Filter out phantom txs from test_observer::parse_transaction fn

---

stackslib/Cargo.toml
stackslib/src/chainstate/nakamoto/test_signers.rs
stackslib/src/chainstate/stacks/block.rs
stackslib/src/chainstate/stacks/index/trie.rs
stackslib/src/chainstate/stacks/tests/chain_histories.rs
stackslib/src/chainstate/stacks/tests/mod.rs
stackslib/src/config/mod.rs
stackslib/src/core/tests/mod.rs
stackslib/src/net/api/postblock_proposal.rs
stackslib/src/net/chat.rs
stackslib/src/net/httpcore.rs
stackslib/src/net/inv/nakamoto.rs
stackslib/src/net/p2p.rs
stackslib/src/net/relay.rs
stackslib/src/net/tests/download/nakamoto.rs
stackslib/src/net/tests/httpcore.rs
stackslib/src/net/tests/mempool/mod.rs
stackslib/src/net/tests/neighbors.rs

Apply the following lints introduced in Clippy 1.78:
- `unnecessary_get_then_check`: Replace `.get().is_some()` with `contains_key()`
- `assigning_clones`: Use possibly more efficient `clone_from()` instead of `clone()` where available
- `to_string_trait_impl`: Implement `std::fmt::Display` instead of `ToString`
- `incompatible_msrv`: Use correct MSRV in Cargo.toml
This is a newer version of #4780 made by re-applying changes on latest `develop`
- #4780

chore: Apply new lints in Clippy 1.78 (version 2)

---

stackslib/src/clarity_vm/clarity.rs

Apply Clippy lint `borrow_deref_ref`, which removes unnecessary ref/deref pairs

chore: Apply Clippy lint `borrow_deref_ref`

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This patch increases mining timeout for 2 integration tests for allowing the CI to not fail on them.
The tests are:
```
tests::nakamoto_integrations::mock_mining
tests::signer::v0::partial_tenure_fork
```
- fixes #5556

Increased mining timeout in mock_mining and partial_tenure_fork integration tests

---

.github/workflows/ci.yml
.github/workflows/core-build-tests.yml
pox-locking/Cargo.toml
sample/expected_consts.json
stacks-common/src/util/mod.rs
stacks-signer/Cargo.toml
stackslib/src/main.rs

This can't be enabled outside of tests because it changes some default values specifically for testing purposes.

fix: do not enable `testing` feature in `stacks-common`

---

.github/workflows/ci.yml
.github/workflows/create-source-binary.yml
.github/workflows/github-release.yml
.github/workflows/image-build-binary.yml

Reverts stacks-network/stacks-core#5495

Revert "Release Signer Alongside Node"

---

clarity/src/vm/representations.rs
libsigner/src/v0/messages.rs
pox-locking/src/events.rs
pox-locking/src/events_24.rs

This just adds `allow` decorators to some message codec implementations. The `as_bytes()` invocations are indeed needless, but I think the verbosity is preferable in the codec (so that its very clear to readers that we're concerned with byte length, rather than character length).
This should fix two checks in CI.

chore: add allow(clippy::needless_as_bytes) for some Clarity codecs

---

stacks-signer/src/v0/signer.rs

This will allow us to easily identify which signer the proposal came from when reviewing logs.

chore: add consensus hash to signer's new proposal log

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/signer_coordinator.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This fixes an issue in #5515 where a `BlockFound { late: true }` mining thread would stay alive after a new burn block arrived (this caused flake in a previous test I wrote for that PR). This PR includes a test that consistently fails (I think I saw it pass once though?) in #5515, but passes with the changeset.
This changeset adds a new instance variable to the mining thread which records what burn block initiated the mining thread (so this is the chain tip even in the case of a late block found). If the burn tip ever doesn't match that, it closes the miner.

Fix: explicit burnchain checks in miner thread

---

.github/workflows/bitcoin-tests.yml

This test is flaky on CI and is not relevant any more.

fix: disable `tests::epoch_25::microblocks_disabled`

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Fix flaky Nakamoto integration test `simple_neon_integration` (or at least make it less flaky)
This test was failing sometimes because the Stacks chain skipped a burn block right at the Nakamoto transition (see [here](https://github.com/stacks-network/stacks-core/actions/runs/12775953844/job/35619342858?pr=5699#step:6:3928) for example). Since the Nakamoto transition on mainnet has already occurred, I don't think we need to test this any more
Related to #5009 which is where I added the check for missing burn blocks

fix: Flaky integration test `simple_neon_integration`

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

This should fix some flakiness in `forked_tenure_is_ignored`. It makes sure to pick the block from the current tenure (important when dealing with equal length forks, because you aren't guaranteed to get back a specific order), and also makes sure that "Tenure C" in the test produces a block before querying it.

Fix flakiness in forked_tenure_is_ignored

---

testnet/stacks-node/src/tests/signer/v0.rs

For tests with a follower node, where some signers are listening to the follower node, this can take longer than 30s to run in CI.

fix: increase timeout for waiting for signer set calculation

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

A few things occurred:
- After a merge, one changelog entry was moved from "unreleased" to "3.1.0.0.3" even though it's not in that release
- I accidentally added a changelog entry to 3.1.0.0.3 instead of "unreleased"
- I forgot to add a changelog entry

fix: moving and adding to unreleased changelog

---

stackslib/src/net/tests/inv/nakamoto.rs
stackslib/src/net/tests/mempool/mod.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Apply Clippy lint `needless_collect`. This finds places where iterators can be used directly, without having to call `collect()` and trigger a heap allocation

chore: Apply Clippy lint `needless_collect`

---

testnet/stacks-node/src/neon_node.rs

Apply Clippy `set_contains_or_insert`. It's more efficient to check the result of `insert()`, rather than call `contains()` followed by `insert()`

chore: Apply Clippy `set_contains_or_insert`

---

testnet/stacks-node/src/tests/signer/v0.rs

This tries to fix test flakiness in `signer::v0::global_acceptance_depends_on_block_announcement`.
I believe the issue was that poor timing in the CI could cause the checks at the end to work like this:
1. `info_before` is checked with stacks height N.
2. `next_block_and()` issues a bitcoin block B+1
3. Before processing `B+1`, the signers upload stacks block `N+1` (because the test directives are all reset). This happens without a new proposal being sent out.
4. `next_block_and()` finishes successfully because `N+1` advances the stacks tip
5. `info_after` is set at `N+1`, which has consensus hash for Bitcoin Block B (_not_ B+1)
6. The search for the sister proposal fails because no new proposals are submitted for Block B.
This test corrects this by making step 2 wait for a new stacks …

Test flake: global_acceptance_depends_on_block_announcement

---

.cargo/config.toml
.github/workflows/clippy.yml
CONTRIBUTING.md
clarity/src/vm/ast/parser/v2/mod.rs

Closes https://github.com/stacks-network/stacks-core/issues/5644
Hopefully this will help us stop breaking the clippy fixes we have implemented thus far.

Chore/add clippy-stacks alias

---

stackslib/src/chainstate/stacks/db/transactions.rs

Logging the contract source is excessive. It can be retrieved if needed for debugging. h/t @diwakergupta

chore: don't log the contract source on deploy error

---

stackslib/src/burnchains/bitcoin/address.rs
stackslib/src/burnchains/mod.rs
stackslib/src/chainstate/burn/operations/delegate_stx.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/stacks/auth.rs
stackslib/src/chainstate/stacks/index/node.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/chainstate/stacks/mod.rs
stackslib/src/chainstate/stacks/tests/block_construction.rs
stackslib/src/chainstate/stacks/transaction.rs
stackslib/src/clarity_cli.rs
stackslib/src/net/atlas/download.rs
stackslib/src/net/codec.rs
stackslib/src/net/http/common.rs
stackslib/src/net/tests/inv/nakamoto.rs

> [!warning]
> These change were applied manually and not with `clippy --fix`.
> Please double-check to make sure I didn't accidentally reverse any `bool`s!
Apply Clippy lint `match_like_matches_macro`, which finds `if let` and `match` expressions which evaluate to `bool` and can be simplified with the `matches!()` macro

chore: Apply Clippy lint `match_like_matches_macro`

---

stackslib/src/burnchains/bitcoin/address.rs
stackslib/src/burnchains/bitcoin/bits.rs
stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/burnchains/bitcoin/spv.rs
stackslib/src/burnchains/burnchain.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/shadow.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/chainstate/stacks/index/marf.rs
stackslib/src/chainstate/stacks/index/storage.rs
stackslib/src/chainstate/stacks/index/trie.rs
stackslib/src/chainstate/stacks/tests/mod.rs
stackslib/src/config/mod.rs
stackslib/src/net/asn.rs
stackslib/src/net/chat.rs
stackslib/src/net/download/nakamoto/download_state_machine.rs
stackslib/src/net/download/nakamoto/tenure_downloader.rs
stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
stackslib/src/net/httpcore.rs
stackslib/src/net/inv/epoch2x.rs
stackslib/src/net/inv/nakamoto.rs
stackslib/src/net/neighbors/comms.rs
stackslib/src/net/neighbors/db.rs
stackslib/src/net/p2p.rs
stackslib/src/net/relay.rs

Apply Clippy lint `manual_inspect`, which finds `map()`/`map_err()` calls that can be replaced by `inspect()`/`inspect_err()`

chore: Apply Clippy lint `manual_inspect`

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
stackslib/src/chainstate/stacks/miner.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

We want the heuristic to be such that the miner mines block found tenure changes quickly, only including the tenure change and the coinbase, but tenure extensions do not require this quick response, so they should include other transactions.
Fixes #5577

feat: allow other transactions with tenure extends

---

stacks-signer/src/v0/signer.rs

This changes the behavior in `handle_block_validation_response` to always send a pending block validation. Previously, if the signer logic determined that it wouldn't send a block response, this function would exit early, which would lead to the logic around sending pending validations to be skipped.
This was written in an attempt to maybe fix _some_ flakiness in `tests::signer::v0::global_acceptance_depends_on_block_announcement`, although I'm not 100% sure that it will. Regardless, I think this is a desirable change - if we just got a block validation response, we should always send out a pending block validation response.

fix: always send pending block validation after receiving a block validation result

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This improves how miners detect whether or not they won a sortition. This mostly impacts miners on restarts, because previously they used in-memory state to detect a winning sortition (#5750)

Fix: better win detection on restart

---

testnet/stacks-node/src/globals.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This should fix (some, but perhaps not _all_) flakiness in `partial_tenure_forking`.
I think what happened in a particular run of this test is that miner 2 won the first testing tenure of the test. This, by itself, should be okay, but the problem is that the timing of the block commit pausing/unpausing and block processing are such that miner 2's first commit is actually a fork! This is because the CI runner builds the next bitcoin block before miner 2 has a chance to RBF their commit with one that points at miner 1's tenure. I solve this particular flakiness with a new Counters variable, but like my last PR that added a Counters variable, this is a kind of check we do in a lot of places. For now, trying to refactor all of the tests to be better about this is a pretty big undertaking, but …

Test: fix some test flake in partial_tenure_forking

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/cli.rs
stackslib/src/config/mod.rs
stackslib/src/net/connection.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/signer/v0.rs

With this change, a miner will not issue a time-based tenure extend if it has used less than X% of the tenure budget, where X can be specified in the `tenure_extend_cost_threshold` config option.
This implements point 3 in #5757.

feat: do not issue a time-based tenure extend earlier than needed

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/nakamoto_integrations.rs

Disable flaky test `nakamoto_integrations::flash_blocks_on_epoch_3()`. This tests flash blocks at the Epoch 2 -> 3 transition, which is no longer needed since we've already made the transition on mainnet
- fixes #5765

fix: Disable flaky test `flash_blocks_on_epoch_3`

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

Merge release 3.1.0.0.5 to develop  (changelog changes for release)

Merge 3.1.0.0.5 to develop

---

.github/workflows/bitcoin-tests.yml

This PR is a first pass at trying to generate the test matrix automatically. Right now, I'm just trying to make sure that it gets a single test to run using the excludes functions. Once I'm convinced that works, I'll update it to match the current exclusion set.

CI: Generating the e2e test matrix

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

The test flake in the `tests::nakamoto_integrations::test_shadow_recovery` test ([logs](https://productionresultssa14.blob.core.windows.net/actions-results/62a78cd4-12e4-4e87-a5b9-1ca97364f550/workflow-job-run-a595cb68-e3d9-5efb-4385-674fcb00d490/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-02-05T15%3A05%3A55Z&sig=wJ3xyXMZKxMGLQS8OkYNVH0HkPKaWT0Pj6iLy1FcCFc%3D&ske=2025-02-06T00%3A13%3A01Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-02-05T12%3A13%3A01Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-02-05T14%3A55%3A50Z&sv=2025-01-05)) seemed to be caused by:
1. `next_block_and_commits_only()` is invoked 4 times.
2. ATC-C only prevents a winner on the first invocation -- a miner can win after that.
3. Because …

Fix flake: shadow recovery

---

contrib/tools/block-replay.sh

Adding the script used to perform block replays. 
this is a standalone helper script, designed for debian based systems and should self-install/build everything needed to run. 
storage requirements are a bit heavy, and it will cook eggs with how hot the cpus get.
commented and passed shellcheck. 
some notes:
Requires  ~73GB per slice, plus an extra ~400GB for the chainstate archive and marf DB
as of 02/2025:
- for 10 slices, total disk used is ~1.1TB
- 149GB for compressed chainstate
- 232GB decompressed marf db
- 73GB per slice dir (1 dir per cpu)
- for 15 slices, this is about 1.46TB
- for 20 slices, this is about 1.8TB
for 10 cpus, the entire block replay will take around 14 hours depending on network speed. once the chainstate is downloaded/extracted the runtime is roughly 12 hours. …

Adding block replay script to contrib/tools folder

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/signer_coordinator.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This could happen at the beginning of a tenure, if the miner for tenure T+1 proposes its first block before it sees the last block from tenure T, so the block it proposed is reorging that last block. Once it sees this block, it should immediately stop waiting for signatures and instead build a new block off of the new tip.
Fixes: #5751

feat: stop waiting for signatures if the chain tip advances

---

stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/burnchains/tests/mod.rs
stackslib/src/chainstate/nakamoto/tests/node.rs
stackslib/src/chainstate/stacks/boot/pox_2_tests.rs
stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
stackslib/src/chainstate/stacks/tests/mod.rs
stackslib/src/config/mod.rs
stackslib/src/net/chat.rs
stackslib/src/net/download/nakamoto/tenure.rs
stackslib/src/net/httpcore.rs
stackslib/src/net/mod.rs
stackslib/src/net/stackerdb/tests/config.rs
stackslib/src/net/tests/download/nakamoto.rs

Apply the following Clippy lints:
- `derivable_impls`: Replace manually implemented `Default` traits
- `eq_op`: Find instances of `a == a` (indicates copy/paste error)
- `expect_fun_call`: Find and replace format strings in `expect()` calls

chore: Apply Clippy lints `derivable_impls`, `eq_op`, and `expect_fun_call`

---

versions.toml

We merged #5399 , but that merge didn't happen to include the correct version at the time of the merge. This PR fixes that, so `develop` reflects the most recently published version.

fix: update versions.toml after merge

---

contrib/tools/block-replay.sh

missed some bash arithmetic parentheses in the previous PR (https://github.com/stacks-network/stacks-core/pull/5824)
this PR resolves that omission.

fix bash arithmetic - typo in block-replay.sh contrib script

---

libsigner/src/events.rs
stacks-signer/CHANGELOG.md
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/signer/v0.rs

Rather than using the signerdb chunks info, this PR changes the signer to recover the miner pubkey directly from the block proposal's block header.
This change improves the signer's liveness in the case when SignerDB events are coalesced.
This change is very well covered by the existing end-to-end tests of the signer binary, but the fixed behavior does not yet have a regression test. I will try to add a regression test to this PR (it's kind of a tricky case to force).

Fix: signer calculates miner pk with block header

---

clarity/src/vm/costs/mod.rs
stackslib/src/clarity_vm/tests/costs.rs

This just matches the error strings in some cost errors. This doesn't have any impact on the execution, but its more hygienic to get the error strings to exactly match.

Chore: match the error strings in cost errors

---

libsigner/src/v0/messages.rs

This fixes an issue with our new decoding of `RejectReason` in block responses, where the code would fail to deserialize an older version of BlockResponseData.

Fix: properly handle decoding older block responses

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

This merges master into develop and separates the changelogs that were mixed in from 3.1.0.0.6.

Master to develop

---

CHANGELOG.md
testnet/stacks-node/src/globals.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5583
This introduces behavior to hot-reload the `burnchain.burn_fee_cap` config field, which is what determines the amount of sats sent to reward recipients. We previously had this behavior, but it wasn't implemented in the Nakamoto miner.
(I would not that the `satoshis_per_byte` config field _is_ hot-reloaded, still)

feat: hot-reload burn_fee_cap in nakamoto

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

See description. This is a protected branch so we can't just do this when we create the `release/3.1.0.0.7` branch.

chore: bump versions to 3.1.0.0.7

---

clarity/src/vm/database/clarity_store.rs
stacks-common/src/util/secp256k1/libsecp256k1.rs

Following the removal of `allow(unused_imports)` on clarinet, we get many warnings when compiling the clarity-vm to wasm. This can be addressed later.
Also, an unused `sqlite` import was removed, but the compilation flag above it was left. Leading to an error

fix: remove unwanted compilation flag

---

clarity/src/vm/contexts.rs
clarity/src/vm/costs/mod.rs
stackslib/src/clarity_vm/tests/costs.rs

+ Avoid using `eval_all` in `compute_cost`, to make it a pure function

feat: compute_cost should borrow immutable TrackerData

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

Also, added `## [Unreleased]` into changelogs to avoid conflicts in incoming PRs.

Master (3.1.0.0.7) to develop

---

stackslib/src/chainstate/burn/db/sortdb.rs

This simple change will be helpful when debugging.

chore: add parent burn block height to commit log

---

CHANGELOG.md
stacks-signer/src/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/signer_coordinator.rs
testnet/stacks-node/src/nakamoto_node/stackerdb_listener.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

When a miner times out waiting for signatures, instead of proposing a
new block, it should only re-propose the same block. Proposing a new
block is guaranteed to fail because signers that approved the original
block will reject any new block at the same height.
This implements the miner side of #5856. A change is still needed on the
signer side to allow a signer to accept a block that it previously
rejected.

feat: on timeout, re-propose the same block

---

clarity/src/vm/errors.rs

Add a generic expect error for Wasm, similar to `InterpreterError::Expect(String)`.

wasm generic expect error

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

- Closes https://github.com/stacks-network/stacks-core/issues/5887
Fixes test flakiness by using an explicit burn_fee_cap in the original config.

fix: flaky reload_miner_config test

---

.cargo/config.toml
.github/workflows/ci.yml
.rustfmt.toml
.vscode/settings.json

We previously did this with the `cargo fmt-stacks` command because these config options were not supported in .rustfmt.toml, but they are now supported by the nightly build. Using this directly is better than the alias because we do not need to remember to run the alias.

feat: use .rustfmt.toml for formatting options

---

stackslib/src/chainstate/nakamoto/miner.rs
stackslib/src/chainstate/stacks/miner.rs
stackslib/src/chainstate/stacks/tests/block_construction.rs
stackslib/src/core/tests/mod.rs

This change makes a cleanup of `TransactionResult::success` and `TransactionResult::success_with_soft_limit`, removing the 'fee' argument, while it is possible to retrieve the same data using `StacksTransaction::get_tx_fee()` internally.
- fixes #5900 
The refactoring has been kept localized to the direct client of  `TransactionResult::success` and `TransactionResult::success_with_soft_limit`. 
Maybe could be also cleaned the `TransactionSuccess`  struct  (instantiated by the two methods above) that as a copy of the `StacksTransaction` and related `fee`. (it could also be a non-problem considering that is now computed internally, and works like a shortcut over `tx.get_txt_fee()`, but potentially could be or become an unused field) …

Removed "fee" argument from `TransactionResult::success()` and `TransactionResult::success_with_soft_limit()`

---

contrib/tools/block-replay.sh

This fixes the block replay script to run on non-Debian Linux.
Specifically:
* It adds the ability to copy over a local chainstate directory, instead of downloading one (`-c`, `--chainstate`)
* It adds the ability to resume processing from an existing log directory (`-l`, `--logdir`)
* It checks to see if `apt-get` is installed, and if it is _not_, then it does _not_ try and fetch missing packages
* It checks to see if `tput` and `sudo` are present
* It checks to see if `find` is a link to `/bin/busybox`, and if so, it errors out since we rely on GNU `find`.
There are two commits:  one with the fix (7575b634f51402fef1a4f0844bd9ceed024937d4), and one to switch all tabs to spaces (14a2ae50ba69c369fc2d55f151137efaeb65eb4f).

Fix: run block-replay.sh on non-Debian Linux

---

CHANGELOG.md
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

This patch prevents logging the warning "No UTXOs for address" when the node is configured as a miner in mock mining mode.
Here an example of the full message (unwanted):
```
stacks-node[348792]: WARN [1739887644.149435] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:1707] [relayer-http://0.0.0.0:20543/] No UTXOs for 04423252e65b4219143e4b6d90608afa651511701ea6a8d08209e8db9d2c2a4aec966a0fa3d3775a54bd3e06cbbf87315b564fc9a3eea25136e5b2b71b8f9d9ee0 (1A7396ngNGn6cotfYx4VmHEWt13Cn2dyts) in epoch 3.1
```
Basically the check about `mock_mining` has been moved from `BitcoinRegtestController::get_utxos()` to its caller `BitcoinRegtestController::prepare_tx()`, while preserving the original behaviour, namely returning `Err(BurnchainControllerError::NoUTXOs` (to avoid regression …

avoid "No UTXOs" warn log when in mock_mining mode

---

CONTRIBUTING.md

This is a proposal to improve the contributing page about what change record can be included in the changelog or not.
- fixes #5939

chore: update contributing.md adding details about a product oriented changelog

---

.github/workflows/github-release.yml

Adds an `environemnt` required check before a release build can be started, configured for `Build Release` environment. 
additionally,  moved the create github release step so that it is  triggered after the docker image is built/pushed .

Add required check for release build

---

Cargo.lock
stacks-common/Cargo.toml
stacks-common/src/util/vrf.rs
stackslib/Cargo.toml
stackslib/src/burnchains/tests/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
testnet/stacks-node/src/keychain.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs

- Upgrade `curve25519-dalek` to v4 in stacks-common
- Remove it from stackslib (wasn't used)
- `curve25519-dalek` v4 was already pulled as a subdependency of `ed25519-dalek`, so in the Cargo.lock you'll only see removed dependendencies, but no addtions.
The v4 comes with a few breaking changes list here:
https://github.com/dalek-cryptography/curve25519-dalek/tree/main/curve25519-dalek#breaking-changes-in-400
The impact for this PR are:
- `Scalar::reduce()` was removed https://github.com/dalek-cryptography/curve25519-dalek/pull/519 
-  `Scalar::from_canonical_bytes()` now return CtOptions
- `Scalar::from_bits()` was removed https://github.com/dalek-cryptography/curve25519-dalek/issues/547
- I'm actually not sure of my fixes there
/

chore: upgrade curve25519-dalek to v4

---

clarity/src/vm/clarity_wasm.rs

This PR addresses an out-of-bounds memory access issue when writing `contract-call?` arguments to memory. It ensures that sufficient memory space is available by calling `memory.grow` with the required number of pages when needed.
Closes: https://github.com/stacks-network/clarity-wasm/issues/564

`contract-call?` fix OOM

---

clarity/Cargo.toml
clarity/src/libclarity.rs
clarity/src/vm/database/structures.rs
stacks-common/src/libcommon.rs
stacks-common/src/types/sqlite.rs

_To be merged on feat/clarity-wasm-develop_
Fixing a mistake I made in #5954.
Because the `clarity/canonical` cargo feature doesn't exist anymore, stacks_common must not be marked as optional anymore.
Also fix the compilation with --no-default-features, which I think wasn't working even before the merge.

fix: --no-default-features compilation

---

Cargo.lock
stacks-common/Cargo.toml
stacks-common/src/util/log.rs

Currenlty, pretty printing is disabled for platform different from unix (where the lint warning, mentioned in the issue, is coming from)
This patch implement a general purpose `isatty` to allow log pretty printing on supported terminals (when configuring env variable `STACKS_LOG_PP=1`)
Added a "manual test" to visually verify pretty printing log configuration.
- fixes #5936
`isatty` check has been improved:
- removing os specific apis (libc and winapi) using `std::io::IsTerminal` (rust v1.70+)
- pairing isatty behavior with `get_decorator` function (previously isatty was bound to the production configuration)
As a conseguence `libc` dependency is no more needed and therefore removed from Cargo.toml (stacks-common)

feat: enable pretty print logging for windows

---

.github/workflows/github-release.yml
.github/workflows/image-build-source.yml
contrib/tools/block-replay.sh

Per @obycode the previous environment usage triggered several emails for approval due to the matrix. 
this PR adds a single job that checks for that approval before starting the matrix build jobs. 
additionally, this PR enables the image-build-source workflow, gated by an environment for ad-hoc image creation. 
lastly, there was an incorrect starting block in the block_replay.sh script used when testing a small number of blocks. rather than 1k blocks, testing mode was set to check 137,800 blocks.

chore: A few workflow fixes

---

testnet/stacks-node/src/tests/signer/v0.rs

I noticed that sometimes the miner's 5 seconds runs out before it has time to include 5000 transactions in the block, triggering a failure.

ci: reduce test flakiness (CI is so slow)

---

testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/signer/v0.rs

This further improves the mempool iteration by avoiding unnecessary resets of the mempool caches. When the block is mined successfully, then the caches are correct and can be kept intact for the building of the next block. My experiments show an additional 10% improvement in the time to process large mempools with this change.

feat: avoid clearing caches when block is successfully mined

---

.github/workflows/clippy.yml
.github/workflows/github-release.yml

Resolves issues #5991  and #5989 
- adds the merge queue workflow trigger for clippy, so it may be a required status check on future pr's
- disables the release PR workflow when a release is an `-rc`
@obycode

Resolves issues 5991 and 5989

---

stacks-common/src/util/macros.rs

This patch allows `define_name_enum!(..)` macro to accept docs comment.
This is needed in case one wants to use this macro in some packages (like stacks-signer) is defined `#![forbid(missing_docs)]` attribute, otherwise a compilation error is emitted (see issue #5992 for related analisys)
- fixes #5992 
The patch is backwards compatible where `define_name_enum` is used without docs comment.
Basically the docs comment are managed as optional within the macro generation.

support docs on 'define_named_enum'

---

stackslib/src/net/httpcore.rs

1.  Fixes a couple of misleading logs.
2.  Adds Heartbeat Logs: `info!` level heartbeat logs added to both the request sending loop and the response receiving loop. These logs will trigger every 60 seconds (`HEARTBEAT_INTERVAL`) if the operation is still in progress.
- fixes #5786

chore: add http traffic heartbeat log

---

stacks-signer/src/monitoring/mod.rs
stacks-signer/src/monitoring/prometheus.rs
stacks-signer/src/v0/signer_state.rs

This is a first PR to start implementing prometheus monitoring on signer agreement protocol.
In details, this PR implement the following metric:
`Counting state changes, eventually by type (block arrivals, inactive miners, protocol upgrades)` 
The metric is implemented a prometheus `IntCounterVec` with labels depending on the state change type (aka "reason")
I put the monitoring hooks right where the stage change happen, and discriminating the reason label by enum.
I have also considered as a reason the "Protocol Upgrades", but didn't add the related monitoring hook in the code, because we haven't the related state change logic already in place.
- fixes #5918
Just to share a thought that come up to my mind, while I introduced an enum for monitoring purpose …

feat: add monitoring for signer agreement state change reason

---

CHANGELOG.md
stackslib/src/config/mod.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This defines a time that the miner should sleep after attempting to mine and finding an empty mempool.

feat: add `empty_mempool_sleep_ms`

---

.github/workflows/ci.yml
.github/workflows/core-build-tests.yml
.github/workflows/github-release.yml
.github/workflows/image-build-source.yml

works in conjuction with https://github.com/stacks-network/actions/pull/73
- Adds image attestation for docker images built from source
- only build `stacks-inspect` in the core-build-tests workflow to save compiling time
- Adds image attestation via https://github.com/stacks-network/actions/pull/73 for the github-release workflow (with required env checks). 
note: there are 2 approvals required for the release workflow in this PR:
1. initial approval to build the arch release binary archives
2. second approval to publish the docker images 
Example workflows using these changes and the composite changes:
stacks-core:
https://github.com/wileyj/stacks-core/actions/runs/14383958535/job/40336789316
https://hub.docker.com/repository/docker/wileyj/stacks-signer/tags?name=0.0.0.5.0 …

Release workflow updates

---

stacks-signer/src/runloop.rs

In `cleanup_stale_signers`, we remove registered signers if they don't have unprocessed blocks. We don't remove unregistered signers, which can lead to a memory leak over time. This PR removes unregistered signers in `cleanup_stale_signers`.

fix: remove unregistered signers in cleanup_stale_signers

---

libsigner/src/events.rs
stacks-signer/CHANGELOG.md
stacks-signer/src/chainstate.rs
stacks-signer/src/client/mod.rs
stacks-signer/src/config.rs
stacks-signer/src/lib.rs
stacks-signer/src/runloop.rs
stacks-signer/src/signerdb.rs
stacks-signer/src/tests/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This updates the signer to check if their associated stacks-node has processed the parent block for a block proposal before submitting that block proposal. If it cannot confirm that the parent block has been processed, it waits a default time of 15s, configurable via `proposal_wait_for_parent_time_secs` in the signer config.toml.
The "wait" is realized by storing the proposal as a pending block proposal in the signerdb (as if the stacks-node returned 429). The signer runloop has been updated to check for pending block proposals at the start of event handling. The signer runloop isn't guaranteed to get an event invocation in a timely fashion, however, it will get invoked whenever the stacks-node processes a new block (or finishes a proposal).
To avoid unnecessarily pinging the stacks-node, …

Signer update: Wait for parent block before submitting proposal

---

CHANGELOG.md
stackslib/src/chainstate/nakamoto/staging_blocks.rs

This adds an index for the SQLite lookup that `next_ready_nakamoto_block()` requires. This improves block processing speeds  by replacing what was a scan with an indexed search.

Perf: improve next_ready_nakamoto_block

---

CHANGELOG.md
docs/event-dispatcher.md
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/stacks/db/blocks.rs
stackslib/src/net/mod.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

This adds a new field, `parent_burn_block_hash`, to the event observer payload for `/new_burn_block`. This will be used in https://github.com/stacks-network/stacks-core/pull/6020 to efficiently find forked btc blocks.

feat: add parent_burn_block_hash to /new_burn_block payload

---

stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/stacks/index/marf.rs
stackslib/src/chainstate/stacks/index/storage.rs
stackslib/src/clarity_vm/database/marf.rs
stackslib/src/util_lib/db.rs

This performance improvement PR adds a new MARF connection implementation which "reopens" the transient data portions of the MARF connection (i.e., the tip pointer) so that indexed gets do not need to have a mutable pointer. This improves over the prior version which reopened the whole MARF struct: the reopened connection struct reuses the existing SQLite connection. Based on perf data, I think this should primarily impact performance in the p2p thread, where there were several hotpaths bottlenecked on `reopen_readonly()` invocations.

Perf: faster readonly MARF

---

stackslib/src/chainstate/burn/db/sortdb.rs

Adds a cache for the PoX descendancy check during LeaderBlockCommitOp processing.

Perf: descendancy check

---

clarity/src/vm/database/sqlite.rs
stackslib/src/clarity_vm/clarity.rs

This adds a migration logic for the metadata index in the ClarityDB (i.e., if the database doesn't have the index on opening, it will create it).
This yields pretty significant speedup if the database didn't have the index already: a roughly 5-10x speedup for block processing in nakamoto over the previous perf improvements.

Perf: Check and create metadata index in ClarityDB

---

CONTRIBUTING.md
Cargo.lock
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

Integrate [pinny](https://github.com/BitcoinL2-Labs/pinny-rs.git) crate on `stacks-node` package.
Added a demo configuration about tag labels and tagged tests.
Here an example of test filtering  and execution using `cargo test`:
- run "slow" tests
```bash
cargo test -p stacks-node :slow:
...
running 2 tests
test tests::signer::v0::block_proposal_rejection::t::slow::signer::bitcoind::t ... ignored
test tests::integrations::contract_stx_transfer::t::slow::t ... ok
test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 251 filtered out; finished in 26.05s
```
- run "fast" tests
```bash
cargo test -p stacks-node :fast:
running 1 tests
test tests::signer::v0::block_proposal_rejection::t::fast::signer::bitcoind::t ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 252 …
```

test: integrate pinny on stacks-node 

---

stackslib/src/net/tests/convergence.rs

~~If my read of these tests is correct, we are just looking for convergence, and these tests should not be testing the pruning of neighbors, so it is best to set these soft max values to be the same as the total number of peers to avoid any non-deterministic pruning. The pruning should be tested elsewhere.~~ See later comments and fixes.
- fixes #5761
- fixes #5758
- fixes #5780

Fix: flaky `net::tests::convergence` tests

---

testnet/stacks-node/src/nakamoto_node/miner.rs

I had made this change as part of the miner transaction replay but really it is entirely independent. I think this is a net positive, but please give suggestions on function names/further cleanup .

Cleanup miner_main_loop so it does not have unnecessary nested loop and has more logical flow

---

CODEOWNERS

This will allow the rules to be adjusted so that PRs to this branch only require approvals from the Clarity Wasm team.

chore: adjust code owners for this branch

---

CHANGELOG.md
libsigner/src/v0/messages.rs
stacks-signer/CHANGELOG.md
stacks-signer/src/tests/signer_state.rs
stacks-signer/src/v0/signer.rs
stacks-signer/src/v0/signer_state.rs
stacks-signer/src/v0/tests.rs
stackslib/src/chainstate/stacks/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Pulled the state machine version upgrade to a sep PR for replay transactions.

Add StateMachineUpdateContent::V1 which inculdes a vector of replay_transactions

---

CHANGELOG.md
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

The mock miner will continuously mine off of the current chainstate. This fixes a recent regression causing the mock miner to only mine the tenure change block, then error out.

fix: mock miner should continue mining throughout tenure

---

CHANGELOG.md
stackslib/src/chainstate/burn/operations/mod.rs
stackslib/src/chainstate/burn/operations/test/mod.rs
stackslib/src/net/api/mod.rs
testnet/stacks-node/src/event_dispatcher.rs

Closes https://github.com/stacks-network/stacks-core/issues/6021

Create TransactionEventPayload struct and add vm_error to it

---

stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/stacks/db/mod.rs
stackslib/src/chainstate/stacks/index/cache.rs
stackslib/src/chainstate/stacks/index/storage.rs

This includes a handful of speedups that are primarily relevant while performing a genesis sync (these perf changes mostly impact the syncing speed of 2.x blocks, not nakamoto blocks).

Perf: 2.0 syncing speedup

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

Bumps versions in the changelogs and `versions.toml` for the 3.1.0.0.9 release branch.

Bumping versions for 3.1.0.0.9 release

---

clarity/src/vm/analysis/mod.rs
clarity/src/vm/docs/contracts.rs
clarity/src/vm/docs/mod.rs

re-opening with the "dirty" patch commits removed, and the (apparently) correct patch from https://github.com/stacks-network/stacks-core/pull/6102#issuecomment-2872747038 ( thanks @kantai ).
with this patch, cargo check is running as expected:
```
RUSTFLAGS="-D warnings" cargo check
RUSTFLAGS="-D warnings" cargo check --features monitoring_prom
RUSTFLAGS="-D warnings" cargo check -p clarity --no-default-features
RUSTFLAGS="-D warnings" cargo check -p stacks-common --no-default-features
```

Fixes unused imports from cargo check

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This pr address a usability friction concerning integration test utils, described in #6104 
Currently in draft, the goal is to show the main idea and collect early feedback.
If the direction looks good, I’ll proceed pushing the refactor further.
NOTE: This change will not address the verbosity of pre-existing integration tests
- fixes #6104

test: remove unsused mutable from test utils to improve usabilty

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
stacks-signer/src/client/mod.rs
stacks-signer/src/client/stackerdb.rs
stacks-signer/src/signerdb.rs
stackslib/src/burnchains/bitcoin/blocks.rs
stackslib/src/net/api/tests/mod.rs
stackslib/src/net/api/tests/postblock_proposal.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/miner.rs
testnet/stacks-node/src/nakamoto_node/miner_db.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/signer_coordinator.rs
testnet/stacks-node/src/nakamoto_node/tests.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

This adds persisted tracking of the latest version that a signer or miner has used, improving stackerdb push performance.
This change adds a new table to the signerdb, and a new sqlite db for persisting non-confidential tracking information for the miner.

Feat: persist stackerdb versioning for signers and miner

---

.github/workflows/core-build-tests.yml

closes #5928
This change adds the cargo check steps defined in 5928, and modifies the final steps:
- cargo run vs cargo build;cargo run to reduce some unneeded steps (time taken is marginally better, but barely noticeable)
- output the diff (if it exists) to the github summary so it's easy to see. 
There is one caveat here that needed to be addressed - the step running `cargo check -p clarity --no-default-features` will fail due to the default RUSTFLAGS being set to `-D warnings`. to get around this and continue on warnings in this workflow, i'm setting RUSTFLAGS to an empty value when running this check. 
the warning will be annotated, but the only other options are to fix the warnings or disable this step. 
ex of a successful run: …

Add cargo check workflow

---

.github/workflows/ci.yml

This change remove `ready_for_review` pull-request trigger, as demostrated to be redundant (see analysis in #6112).
- fixes #6112

ci: remove 'ready_for_review' pr trigger

---

stacks-signer/src/signerdb.rs

[A comment in another PR](https://github.com/stacks-network/stacks-core/pull/6109#discussion_r2089163529)  pointed out that SCHEMA_VERSION wasn't updated. I've also felt that the signerDB migrations code is more verbose than it needs to be, without providing that much extra safety. This is a refactor to make it easier to define new migrations, as well as some extra checks to ensure things like the db version is correct.

feat: refactor / cleanup signerDB migrations code

---

.github/workflows/workflow-cleanup.yml

Fix workflow error due to wrong GH token.
For more details look at #6132 
- fixes #6132

ci: fix wrong GH token in `workflow-cleanup` workflow

---

stacks-signer/src/v0/signer.rs
stacks-signer/src/v0/signer_state.rs

This patch fixes a race condition where a signer decides to capitulate on a miner but does not update its current sortition view potentially rejecting perfectly valid blocks
- fixes #6146 
* the relevant test here is reorging_signers_capitulate_to_nonreorging_signers_during_tenure_fork that used to be flaky
* I am doubtful about the InvalidatedBeforeFirstBlock, it does its jobs, but probably we need to check if the signer has already signed something from the previous (invalid) sortition view.

Mark current miner as invalid on capitulation

---

clarity/src/vm/contexts.rs

Errors should be propagated to the caller during the analysis step.
https://github.com/stacks-network/clarity-wasm/issues/653

Propagate error

---

.cargo/config.toml
.vscode/settings.json
stacks-common/build.rs
stacks-common/src/address/c32.rs
stacks-common/src/address/mod.rs
stacks-common/src/bitvec.rs
stacks-common/src/codec/mod.rs
stacks-common/src/deps_common/bech32/mod.rs
stacks-common/src/deps_common/bitcoin/blockdata/script.rs
stacks-common/src/deps_common/bitcoin/network/serialize.rs
stacks-common/src/deps_common/bitcoin/util/hash.rs
stacks-common/src/types/chainstate.rs
stacks-common/src/types/net.rs
stacks-common/src/util/chunked_encoding.rs
stacks-common/src/util/hash.rs
stacks-common/src/util/log.rs
stacks-common/src/util/lru_cache.rs
stacks-common/src/util/mod.rs
stacks-common/src/util/serde_serializers.rs
stx-genesis/build.rs
testnet/stacks-node/src/tests/signer/commands/block_verify.rs
testnet/stacks-node/src/tests/signer/commands/block_wait.rs
testnet/stacks-node/src/tests/signer/commands/context.rs
testnet/stacks-node/src/tests/signer/v0.rs

I recently started seeing Clippy errors due to non-inlined variables in our `build.rs` script. I also fixed the `cargo check` warnings for a few new parts of our test code that are unused.

fix clippy error and `cargo check` warnings

---

stacks-common/src/deps_common/ctrlc/tests.rs

This patch fix clippy error on windows. In details:
```
error: manually constructing a nul-terminated string
--> stacks-common\src\deps_common\ctrlc\tests.rs:138:13
|
138 |             "CONOUT$\0".as_ptr() as *const CHAR,
|             ^^^^^^^^^^^ help: use a `c""` literal: `c"CONOUT$"`
```
this error prevents to run succesfully the command `cargo clippy-stacks` on the whole codebase on windows ide.
- fixes #

fix: clippy error on windows 

---

clarity/Cargo.toml
clarity/src/vm/analysis/mod.rs
clarity/src/vm/contexts.rs
clarity/src/vm/docs/contracts.rs
clarity/src/vm/docs/mod.rs

The clarity-vm couldn't be compiled to wasm32-unknown-unknown because of the `MemoryBackingStore` import in `clarity/src/vm/contexts.rs`
The other changes in this PR avoid a few unused imports in this configuration:
```bash
cargo check -p clarity --target wasm32-unknown-unknown --no-default-features --features clarity/wasm
```
A strategy to avoid having too many compilation flag is to have qualified imports when a specific function requires a specific function locally requires a specific import
```rust
let mut marf = crate::vm::database::MemoryBackingStore::new();
```

fix: build clarity vm for wasm

---

Cargo.lock
testnet/stacks-node/Cargo.toml

The crates `http-types` is old and unmaintained.
Its default features comes with old versions of dependencies that are not needed in our case (see changes in cargo.lock).
I was hoping to get rid of the old `rand@0.7.3` dependency, but it's unfortunately not marked as optional.
It's still worth it merging this I think

chore: clean http-types dependencies

---

Cargo.lock

Fix https://github.com/stacks-network/clarity-wasm/issues/666 
Just need to update the dependency since the fix is at clarity-wasm side.

[clarity-wasm-tests] stackerdb-set-signer-slots issue

---

Cargo.lock
clarity/src/vm/clarity_wasm.rs

This change needs to be reverted, as it adds an additional call to `global_context.rollback()`, which in turn disrupts the function call context.

[clarity-wasm] fix function context rollback

---

Cargo.lock
stackslib/Cargo.toml
stackslib/src/burnchains/burnchain.rs
stackslib/src/burnchains/tests/mod.rs
stackslib/src/burnchains/tests/thread_join.rs

Related to https://github.com/stacks-network/stacks-core/issues/6240.

Handle thread join errors uniformly with helper

---

.github/workflows/github-release.yml

For the release workflow, this change excludes binaries being built for macos-x86_64
associated build script removal: https://github.com/stacks-network/actions/pull/84
https://github.com/wileyj/stacks-core/actions/runs/16528194936

skip over matrix for macos x86_64 binary builds (deprecated arch)

---

clarity/Cargo.toml
clarity/src/vm/database/structures.rs

`serde_stacker`  relies on `psm` that sometimes fails to compiue to `wasm32-unknown-unknown` with the error:
```
[watch] error: failed to build archive at `.../target/wasm32-unknown-unknown/release/deps/libpsm-b026689ff013e77e.rlib`: LLVM error: section too large
[watch] 
[watch] warning: psm@0.1.21: warning: .../ranlib: archive library: .../target/wasm32-unknown-unknown/release/build/psm-f6245e71013cd875/out/libpsm_s.a the table of contents is empty (no object file members in the library define global symbols)
[watch] error: could not compile `psm` (lib) due to 1 previous error
```
Clarinet, that was relying on a custom branch, had this change forever
https://github.com/stacks-network/stacks-core/blob/5295a70b28895d4786e6329acefea4a19a956ba2/clarity/src/vm/database/structures.rs#L55-L75 …

fix: remove serde stacker for wasm target

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

changelogs and versions.toml updated based on milestone board. 
feel free to suggest additions/changes if needed

3.2.0.0.1 changelogs

---

.github/workflows/github-release.yml

https://github.com/stacks-network/stacks-core/actions/runs/16945561662/job/48025872768#logs
the arch was incorrectly merged as x86_64, not x86-64: https://github.com/stacks-network/stacks-core/commit/2ed7b920e5da890c9e156523a77ab483728c0e15

Fix type in release arch matrix `s/x86_64/x86-64/`

---

clarity/src/vm/types/mod.rs

I noticed in some Clarinet code that there was no easy way to check these two properties.

feat: add `is_mainnet` and `is_multisig` to `StandardPrincipalData`

---

.github/workflows/github-release.yml

use larger runner for release binaries

use larger runner for release binaries
