stacks-network/stacks-core

doc/FAQ.md
doc/design.md
doc/protocol.md

Yes, I am that guy. Tidy, tidy.

Fixed a few typos in the documentation.

---

Dockerfile

A first pass at a Docker build environment for blockstored, useful for integration testing and continuous deployments. Let me know your thoughts and thanks for building such an exciting project.

Dockerfile for blockstore

---

blockstore/blockstored.py

Explicitly disable SSL certificate and hostname verification, since we
are using a self-signed certificate.  Python 2.7.9 and greater perform
certificate and hostname verification by default; this should not be a
problem for Python 2.7.8 or earlier.

Explicitly disable SSL certificate and hostname verification.

---

images/scripts/debian.sh

Added debian script, tested in ubuntu 15 x64, Fixes issue #168

added debian install script, Fixes #168

---

blockstack/lib/nameset/namedb.py

There was a typo in the method's return statement.

fix get_all_namespaces RPC call failure

---

blockstack_client/backend/nameops.py
blockstack_client/rpc.py

Fix CORS & 500 error on POST /v1/names

---

README.md

(and remove the link to release notes of v.0.14.1)

Add the general list of release notes

---

api/search/search/basic_index.py
api/search/search/substring_search.py

Added the GUID search functionality. Use the python -m search.substring_search --search_GUID <myid> to use this feature. It returns the profile and the username corresponding to the openbazaar id myid.

added GUID search

---

blockstack_client/actions.py
blockstack_client/constants.py
blockstack_client/keys.py
blockstack_client/rpc.py
blockstack_client/rpc_runner.py
blockstack_client/wallet.py

Some edits to fix wallet initialization and secrets passing in the latest version

Wallet initialization and secrets passing fixes

---

api/__init__.py
api/auth/registration.py
api/nginx/config/nginx_sites-available/blockstack_api
api/search/fetch_data.py
api/server.py
api/tests/api_tests.py
api/tests/resolver_tests.py
api/tests/search_tests.py
blockstack_client/proxy.py
blockstack_client/rpc.py
docs/search.md

Some configuration settings included for nginx-based caching.
Updated unit tests in api/tests/ so that the new resolver and search URLs are tested, and the API endpoints in the API landing page get tested.

Unit Test Updates for API

---

integration_tests/bin/blockstack-test-scenario
integration_tests/blockstack_integration_tests/scenarios/portal_test_env.py

configurable API endpoint port + an integration test that registers "id" namespace.

Changes to the integration testing which allow easier setup for portal testing.

---

blockstack/blockstackd.py
blockstack_client/backend/nameops.py
blockstack_client/backend/registrar.py
blockstack_client/backend/utxo/bitcoind_utxo.py
blockstack_client/scripts.py

Patch up some of the transaction fee calculation code-- now it's pretty much spot on calculations of tx_fee + dust_fees.
Also updated `get_profile` in `blockstackd` to match a refactor from 2063c88305b8885ad08b12d0403280b17e387e70

Patching fee calculation code

---

blockstack_client/rpc.py

This is my attempt to fix #463 by hard coding the device id.
@kantai Can you take a look at why the test added in https://github.com/blockstack/blockstack-core/commit/72185c39145172c5153fd25eaeca2f494ab79bad wasn't failing on this and add a test that catches it?

hardcode device id for legacy auth requests to 0 #463

---

blockstack_client/backend/blockchain.py
integration_tests/blockstack_integration_tests/scenarios/issue469_1.py
integration_tests/blockstack_integration_tests/scenarios/testlib.py

blockstack regtest was killing itself on a bad tx response from bitcoind. The patch also fixes a value_hash dict keyerror at the end of certain testcase passes
Fix for the first part of issue #469

fix for issue 469 part 1 + integration test for it

---

blockstack_client/actions.py
blockstack_client/cli.py
blockstack_client/config.py

now all commands may be run, regardless of advanced mode status, new config files will not have advanced mode written to them.
closes issue #457

removing advanced mode

---

blockstack_client/backend/safety.py

This fixes a few problems with the imports in `safety.py`, at least one of which led to user-facing cli misbehavior.
For example, on master@HEAD:
```
$ ./bin/blockstack lookup '&.id'
{
"error": "Unexpected error:\nTraceback (most recent call last):\n  File \"./bin/blockstack\", line 52, in <module>\n    result = run_cli()\n  File \"blockstack-core/blockstack_client/cli.py\", line 398, in run_cli\n    result = method(args, config_path=config_path)\n  File \"blockstack-core/blockstack_client/actions.py\", line 837, in cli_lookup\n    error = check_valid_name(fqu)\n  File \"blockstack-core/blockstack_client/backend/safety.py\", line 71, in check_valid_name\n    if not is_b40(name):\nNameError: global name 'is_b40' is not defined\n",
"help": "Try getting latest version of CLI with \"sudo pip …
```

Safety cleanups

---

blockstack_client/schemas.py
blockstack_client/version.py

Addresses issue #519 by adding "@" to the allowable URL schema.

URL schema to allow @

---

README.md

If this is ok, I can add it to the other repos as well :)
cc @jackzampolin
Also see https://github.com/blockstack/blockstack-core/pull/535

Fix broken Slack badge

---

blockstack_client/actions.py
blockstack_client/version.py
subdomain_registrar/subdomains_registrar.py

Fixes CORS header problem in subdomain registrar, and also fixes an old import bug in the CLI profile verification command.

Hotfix for CORS problem in Subdomain Registrar

---

README.md

Make the instructions for getting started with `blockstack` more clear.

Update Getting Started instructions

---

Dockerfile
README.md

Add better docker instructions

---

api/search/basic_index.py
api/search/fetch_data.py
api/search/server.py
api/search/utils.py
api/tests/search_tests.py
blockstack_client/profile.py
blockstack_client/subdomains.py

Adds support for indexing subdomains on search endpoint. Up and running on core.blockstack.org --
updating search indexer on master branch as the code is already live.

Indexing subdomains on search endpoint

---

blockstack_client/config.py
blockstack_client/utils.py
blockstack_client/version.py
integration_tests/bin/blockstack-test-scenario
integration_tests/blockstack_integration_tests/tests_skip.txt
integration_tests/test-launcher
release_notes/changelog-0.14.5.md

Hotfix issue described in release_notes/changelog-0.14.5.md
This also merges in code for cluster runs of integration tests with kubernetes.

Hotfix for bug related to default blockstackd ports

---

blockstack_client/actions.py
blockstack_client/rpc.py
docs/api-specs.md
integration_tests/blockstack_integration_tests/scenarios/rest_update_with_key.py

Add payment key option to withdraw endpoint

---

README.md
integration_tests/README.md

Corrects links for integration test and python2 specifications in test instructions

Correct documentation for integration tests

---

blockstack_client/rpc.py
docs/api-specs.md

Adds /v1/blockchains/bitcoin/name_count endpoint

Add endpoint for getting number of names

---

api/resolver.py
blockstack_client/version.py

Thanks @yknl for finding this!

Fixes short-name resolution in the resolver endpoints

---

blockstack_client/backend/utxo/bitcoind_utxo.py
integration_tests/blockstack_integration_tests/scenarios/issue619_regtest_wallet.py

same as PR #620, but now for master

fixes issue 619, a bug in the regtest bitcoind utxo provider

---

.dockerignore

This should reduce the size of our docker images by a bit.

adding a docker ignore

---

circle.yml

Update circle.yml -- no version bump because this is non-shipping meta-data.

Fix Circle CI brew building problems

---

blockstack/version.py
blockstack_client/backend/drivers/gaia_hub.py
blockstack_client/constants.py
blockstack_client/data.py
blockstack_client/storage.py
blockstack_client/version.py
circle.yml

- EREMOTEIO not supported on all platforms, so it's removed
- Default storage configs shouldn't require dropbox for writes
- More graceful errors when gaia_hub hasn't been configured yet
Version bumped

Hotfix for storage bugs

---

blockstack_client/actions.py
integration_tests/README.md

Plus added instructions for testing namespace CLI in the integrationtests README

Friendlier namespace CLI

---

blockstack_client/actions.py

Add currency label to the Unit Price, and set it as 'satoshi'

add currency name to format_price_formula function

---

integration_tests/bin/blockstack-test-scenario

Wrap influx writes in try/except blocks to fail silently

---

blockstack_client/backend/drivers/dropbox.py
integration_tests/bin/blockstack-storage-driver-test

Adding command line parameter to pass 'fqu' to driver initialization as per specifications in @jcnelson here: #430 (comment)

ENH: added fqu param to initialize driver

---

README.md

Fixes https://github.com/blockstack/blockstack-core/issues/656

Update docker install instructions

---

docs/setup_core_portal.md
images/scripts/ubuntu-17.04.sh

As mentioned here: https://github.com/blockstack/blockstack-browser/issues/1118
not sure how I can test it though...

attempt at fixing the linux protocol handler

---

api/README.md
api/deployment/client.ini
api/docker-compose.yaml
api/ops

This PR finishes up the changes to the API and provides instructions for spinning up the setup from source.

Update API development instructions

---

README.md
tools/docker/blockstack-server.ini
tools/docker/client.ini
tools/docker/docker-compose.yaml
tools/docker/docker-tools.sh

I've added a docker section in the `README` and some supporting scripts and config in the `tools/docker` folder. Would love some 👀 !

Add Updated Docker Install Instructions/Scripts

---

blockstack/version.py
blockstack_client/rpc.py
blockstack_client/version.py

Subdomain property `zonefile_txt` should be `zonefile` so it matches the return schema of domains.

Subdomain schema response of `/v1/names` should match domain response.

---

bin/blockstack-snapshots

Thanks @jackzampolin for helping me fix this!

snapshot.bsk is a hard link, not a symlink.  Compare inode numbers, not link paths

---

docs/api-specs.md

Fix one api doc point as per contributor task :)
Also added docs on the `?all` option.
(this from https://contribute.blockstack.org btw - might be something of a cheat as I already did one PR to this repo earlier, but I like the gamification :P)

Add fail example to /v1/blockchains/*/name_count

---

blockstack/blockstackd.py
blockstack/lib/client.py
blockstack/lib/subdomains.py
blockstack_client/rpc.py
docs/api-specs.md
integration_tests/blockstack_integration_tests/live_tests/api_tests.py
integration_tests/blockstack_integration_tests/scenarios/name_pre_regup_subdomain_batch.py

This adds two new endpoints
```
/v1/subdomains?page=x
/v1/blockchains/bitcoin/subdomains_count
```
This addresses #789, and is step 1 of addressing #794 
The new endpoints are documented in changes to `api-specs.md`

Add get all subdomains endpoint

---

Dockerfile

This updates the dockerfile to bionic, and removes the dev packages that aren't required anymore (these were necessary for building pyscypt).

Update dockerfile to bionic, remove dev packages

---

api/search/Dockerfile

adding comments in CMD https://docs.docker.com/engine/reference/builder/#cmd

Updating CMD per dockerfile docs to use commas

---

images/docker/README.md
images/docker/api/Dockerfile
images/docker/core/Dockerfile

- Docker images for core and api in images/docker upgraded to ubuntu:18.04
- Fix Docker build instruction in README

Upgrade Docker images for core and api

---

api/resolver.py
api/server.py

This just adds "begin" debug logging for the flask app, so we can better diagnose slow requests.

Add debug lines for flask app

---

blockstack/lib/nameset/db.py
blockstack/lib/nameset/namedb.py
blockstack/lib/queue.py
blockstack/lib/subdomains.py
setup.py

- Loading DB into memory
https://www.sqlite.org/mmap.html

Adding pragma mmap_size

---

setup.py

specifically install cryptography package

---

Cargo.toml
build-scripts/build-dist-linux-musl-x64.sh
build-scripts/build-dist-linux-x64.sh
build-scripts/build-dist-mac-x64.sh
build-scripts/build-dist-win-x64.sh
build-scripts/docker-run.sh
build-scripts/start-builds.sh
circle.yml
src/vm/checker/check_db.rs

Build scripts for running in the official rust docker image. Cross-compiles binaries for Win-x64, Mac-x64, Linux-gnu-x64, and Linux-musl-x64. 
CircleCI config to build and store the binaries as artifacts.

Distribution build scripts

---

src/vm/docs/mod.rs

Added name to the API gen.
Signed-off-by: Mary Anthony <mary@blockstack.com

API docs should include the API name

---

src/vm/docs/mod.rs

@kantai @zone117x  Found a typo and needed to add a bit of a human language to the operators.

Name reading

---

sip/sip-001-burn-election.md

* remove burn window and burn quota
* remove now-obsolete wire formats
* update language to describe leader election in terms of tunable proof scores

Update SIP 001

---

docs/smart-contract-vm.md
src/clarity.rs
src/main.rs

Removing .scm references for .clar instead

---

src/vm/docs/mod.rs

Name was incorrect for filter

---

src/vm/docs/mod.rs

Fixes to some mechanics in the descriptions

---

src/vm/checker/typecheck/tests/mod.rs
src/vm/tests/datamaps.rs
src/vm/types.rs

Address https://github.com/blockstack/blockstack-core/issues/1029

Streamline tuple declaration

---

README.md

- Provides links to the Clarity branch
- Updated pointer for documentation

Pointer to Clarity in Master README

---

src/vm/checker/read_only/mod.rs
src/vm/checker/read_only/tests.rs
src/vm/checker/typecheck/natives/mod.rs
src/vm/checker/typecheck/tests/mod.rs
src/vm/docs/mod.rs
src/vm/functions/mod.rs
src/vm/tests/simple_apply_eval.rs

Address https://github.com/blockstack/blockstack-core/issues/1042

Allow multiple bodies in let statements

---

docs/api-specs.md

Explicitly state that the price of a name/namespace is in satoshis or microstacks.

Price documentation update

---

sip/sip-001-burn-election.md

This updates the language to elaborate on how an anchored block's fees will be distributed among miners.  This is based on this paper out of Cornell: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3318327

Update block fee language to describe how we'll implement a fairer fee market

---

src/vm/analysis/type_checker/natives/maps.rs

This issue:
```
(define-map proposals 
((proposal-id int)) 
((name int) (author principal)))
(define-public (create-proposal (name int))
(begin
(map-insert! proposals 
((proposal-id 1)) 
((name name) (author tx-sender) (extra-field 'true)))
(ok 1)))
```
Produces this error:
`Error (line 37, column 9): expecting expression of type '(tuple (proposal-id int))', found '(tuple (proposal-id int))'.`

Fix errored error message

---

src/vm/ast/parser/mod.rs

This makes carriage returns illegal #1118

Make carriage returns illegal

---

.gitattributes

Fix linguist stats

---

src/blockstack_cli.rs

This PR is for unblocking @yknl, working on implementing wire format in TS.

Add token-transfer to blockstack-cli

---

src/vm/docs/mod.rs

Description of the Clarity `fold` special form is updated as detailed in https://github.com/blockstack/docs.blockstack/issues/511

Update the description of fold

---

sip/sip-005-blocks-and-transactions.md

SIP 005: add signing/verifying algorithm

---

README.md

This PR
* replace blockstack-core by stacks-blockchain in README.md

Replace blockstack-core by stacks-blockchain

---

src/clarity.rs
src/vm/analysis/mod.rs
src/vm/clarity.rs

This fixes the bug #1372, by including cost tracker ownership handle with analysis errors.

fix: test case and patch for corrupted clarity tx state #1372

---

.github/stale.yml
CODE_OF_CONDUCT.md

Also configuration for stale bot.

Add a code of conduct.

---

testnet/src/burnchains/mocknet_controller.rs
testnet/src/config.rs
testnet/src/node.rs
testnet/src/tenure.rs

Address https://github.com/blockstack/stacks-blockchain/issues/1454 and #1455

Fixes post #1381

---

src/chainstate/stacks/db/blocks.rs
src/net/relay.rs
src/net/rpc.rs

Slightly improved logging:
* Adds logs for validation failures in processing,
* Cleans up some of the follower logs

Slightly improved logging

---

testnet/src/neon_node.rs

* Remove a panic from the neon mining loop.
* Add some debug logging

Some debugging niceties

---

src/net/mod.rs
src/net/rpc.rs
src/net/server.rs

Make the server send HTTP 400 to all invalid HTTP requests

---

src/blockstack_cli.rs

This PR
* uses the correct documentation for token-transfer
* fixes #1492

Fix documentation for token-transfer

---

src/burnchains/bitcoin/network.rs
testnet/Cargo.toml
testnet/conf/local-follower-conf.toml
testnet/conf/local-leader-conf.toml
testnet/conf/local-second-miner.toml
testnet/src/config.rs
testnet/src/event_dispatcher.rs
testnet/src/main.rs
testnet/src/tenure.rs

This PR is addressing #1352 and #1506.
Essentially, moving from TCP to HTTP, add retry mechanism.

Revisit sidecar integration

---

docs/rpc-endpoints.md

Provide more detail in the rpc-endpoints.md file.

docs: add detail on the tx post reason_data field

---

README.md

As pointed out in Discord by @dantrevino

Fixing running instructions

---

src/main.rs

Two new tools:
1. Get an ancestor list for a staging block header, usage:
```
$ blockstack-core get-ancestors <staging-db-path> <stacks-block-hash> <burn-header-hash>
```
Outputs a list of <burn-header-hash>, <stacks-block-hash> from the block supplied back to genesis.
```
$ blockstack-core get-ancestors /tmp/sidecar-follower/chainstate/chain-00000080-testnet/blocks/staging.db 4ce2f5130eca6197709875219411ca5534bbaa80c4679cc8ea3fc0fadfa7fc53 6013b9ca60520803bb7ab5926249f96b3d2be3e131986fc87e379499a0dd6eb7
```
2. Query a MARF directly, usage:
```
$ blockstack-core marf-get <marf-path> <stacks-block-hash> <burn-header-hash> <marf-key>
```
Returns the hex of the stored MARF value. (If you run with debug/trace on, you'll also get to see the tries that were traversed during the fetch).
```
$ …
```

Add some helpful debug tools

---

src/clarity.rs

This allows you to use non-literals (which includes `true` and `false`) as arguments to execute in `clarity-cli`

fix: use eval rather than parse for execute cli arguments

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

This checks the result of sendrawtx and errors if the RPC call failed

Fix: Check Send Raw TX Error status

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

Submitted Bitcoin transactions need to ensure that any change outputs aren't dust (i.e., less than 5500 satoshis)

Fix: check change output for dust clearance

---

src/vm/docs/mod.rs

feels overkill to create a PR for such a trivial thing, so let me know if you'd rather have it filed as an issue.

fix typo in `contract-call?` doc

---

testnet/bitcoin-neon-controller/src/main.rs

Cherry pick fix from https://github.com/blockstack/stacks-blockchain/pull/1577 (blocked on the k8s setup).

Refactor initial coinbases allocations

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs

This explicitly adds a Non-OpReturn output to VRF key registers, resolving #1614 for now.
Depending on the approach to #1615, there will probably need to be additional work.

stacks-node: explicitly add a second output for VRF registers

---

src/vm/analysis/trait_checker/tests.rs
src/vm/contexts.rs
src/vm/mod.rs
src/vm/tests/traits.rs

This PR is addressing the issue https://github.com/blockstack/stacks-blockchain/issues/1643 opened by @psq.

Fix trait references not being found in nested contexts

---

testnet/stacks-node/conf/argon-follower-conf.toml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs

Per @diwakergupta demand, we'll be bumping graceful terminations from 1 day to 3 days.

Bump graceful termination: from 1d to 3d

---

testnet/stacks-node/conf/argon-follower-conf.toml
testnet/stacks-node/src/config.rs

Bump graceful termination limit

---

testnet/stacks-node/src/keychain.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/mod.rs

Address https://github.com/blockstack/stacks-blockchain/issues/1674.
Test in progress - will update.

Use u64 instead of u16 for block heights

---

Cargo.lock
Cargo.toml
src/address/b58.rs
src/deps/bitcoin/blockdata/transaction.rs
src/deps/bitcoin/network/serialize.rs
src/deps/bitcoin/util/hash.rs
src/lib.rs

This removes the byteorder dependency (see #1717)

Remove byteorder dependency

---

src/vm/clarity.rs
src/vm/mod.rs

Expose tx-sender and contract-caller to bare code in smart contracts

---

src/net/p2p.rs
testnet/stacks-node/conf/argon-follower-conf.toml
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/main.rs

display configuration at startup, configure download_interval, inv_sync_interval, public_ip_address, typo

allow more parameters to be configured via configuration file, better default download_interval for mining on testnet

---

.github/actions/docsgen/Dockerfile.docsgen
.github/workflows/docs-pr.yml

With the release of the new docs, there were minor changes to where things lived. This PR updates the file name and path for the reference that is automatically generated.

fix: update auto generated file for reference

---

src/chainstate/burn/db/processing.rs
src/chainstate/burn/db/sortdb.rs
src/chainstate/burn/mod.rs
src/chainstate/burn/operations/leader_block_commit.rs
src/chainstate/burn/operations/leader_key_register.rs
src/chainstate/burn/operations/user_burn_support.rs
src/net/chat.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/tests/bitcoin_regtest.rs

and only register a key once in the node.  No test broke on that change, so will be adding some new test if feasible.

Implement #1615 by allowing key reuse

---

src/net/download.rs
src/net/inv.rs
src/net/neighbors.rs
src/net/p2p.rs
src/net/relay.rs

The previous PR was opened against `feat/pox-network` for highlighting the changes, but should have been merged in `next`.

Krypton adjustments -> Next

---

src/net/neighbors.rs

Fixes #1912 
Looks like my editor also removed a lot of whitespace from the file, if this is an issue I can resubmit, but the actual lines changed are: L1742 and L1917.

Change neighbors failed to connect messages from info to debug

---

src/chainstate/stacks/boot/pox.clar
src/net/mod.rs
src/net/rpc.rs
src/vm/database/structures.rs

This PR is addressing needs from devx team, by augmenting some API endpoint with a few fields.

More devx adjustments

---

src/net/neighbors.rs

This PR fixes #1971 by changing the message from info to debug.
Smallest. PR. Ever. 
:upside_down_face:

update failed to check connection message

---

docs/event-dispatcher.md
src/chainstate/coordinator/mod.rs
src/chainstate/coordinator/tests.rs
testnet/stacks-node/src/event_dispatcher.rs

Add `burn_block_height` field to `/new_burn_block`

feat: add burn_block_height to /new_burn_block event-dispatcher endpoint

---

.github/workflows/stacks-blockchain.yml

Pull in changes from master to allow us to build a new docker tag off the `next` branch.
No
No

Fix GH Actions

---

src/chainstate/stacks/boot/pox-mainnet.clar
src/core/mod.rs

Update reward cycle length to 2000.

---

src/chainstate/stacks/boot/mod.rs
src/vm/analysis/errors.rs
src/vm/analysis/trait_checker/tests.rs
src/vm/analysis/type_checker/mod.rs
src/vm/analysis/type_checker/natives/mod.rs
src/vm/analysis/type_checker/tests/assets.rs
src/vm/analysis/type_checker/tests/contracts.rs
src/vm/docs/mod.rs
src/vm/tests/traits.rs
testnet/stacks-node/src/tests/integrations.rs

This PR is addressing https://github.com/clarity-lang/reference/issues/29.

Clarity: Static failures for unchecked results

---

src/chainstate/stacks/boot/costs.clar
src/chainstate/stacks/events.rs
src/vm/analysis/errors.rs
src/vm/analysis/read_only_checker/mod.rs
src/vm/analysis/type_checker/natives/assets.rs
src/vm/analysis/type_checker/natives/mod.rs
src/vm/analysis/type_checker/tests/assets.rs
src/vm/contexts.rs
src/vm/costs/cost_functions.rs
src/vm/database/clarity_db.rs
src/vm/docs/mod.rs
src/vm/errors.rs
src/vm/functions/assets.rs
src/vm/functions/mod.rs
src/vm/tests/assets.rs
src/vm/tests/costs.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/tests/integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Address https://github.com/blockstack/stacks-blockchain/issues/2125, by implementing `ft-get-supply`, `ft-burn?`, `nft-burn?`.
Theoretically code complete, still need to:

Clarity: additional token functions

---

.github/workflows/clarity-js-sdk-pr.yml

clarity-js-sdk commit message updated to follow conventional commits guidelines.
No
No

Fix clarity-js-sdk commit message

---

Cargo.lock
Cargo.toml
src/chainstate/stacks/db/mod.rs
src/lib.rs
testnet/stacks-node/src/tests/integrations.rs

This PR is testing the predictability of the chainstate process, by ensuring that we're always reproducing the same MARF root hash.

Test: add coverage for genesis consistency

---

src/vm/docs/mod.rs

This PR is addressing https://github.com/blockstack/stacks-blockchain/issues/2231.

Fix (append ...) documentation

---

src/chainstate/stacks/boot/mod.rs
src/chainstate/stacks/db/transactions.rs
src/util/strings.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This fixes the behavior in #2257

Smart contract transaction error handling

---

src/chainstate/stacks/boot/bns.clar

Address https://github.com/blockstack/stacks-blockchain/issues/2160

Fix comment in BNS

---

testnet/stacks-node/src/keychain.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR aims at merging a fix that I was running on my integration branch - required for Mainnet.

Fix: leftover from integration branch

---

README.md

Modified the contract example in the README.md so that fee amount is accurate.

docs: minor fix to README

---

CONTRIBUTORS.md

Updated CONTRIBUTING.md
- Added information about dev workflow (which branches to build off of, commit message conventions)
- Added upper level sections & a table of contents 
- Added mention of Code of Conduct

docs: update CONTRIBUTING.md

---

CHANGELOG.md
src/chainstate/stacks/db/blocks.rs
src/net/download.rs
src/net/relay.rs

This is the same changes as #2520, but applied as a hotfix/master patch rather than a develop patch.

Hotfix patch for Fix/2518+2491

---

src/vm/docs/contracts.rs

Document the `price-function` parameters for the `bns` contract's `reveal-namespace` function.

Docs: bns contract reveal-namespace

---

src/burnchains/burnchain.rs
src/chainstate/coordinator/comm.rs
src/net/atlas/download.rs
src/net/poll.rs
testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/syncctl.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Address https://github.com/blockstack/stacks-blockchain/issues/2545

Graceful termination during initial sync

---

testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/node.rs
testnet/stacks-node/src/run_loop/neon.rs

I'm opening this PR for addressing the issue raised here https://github.com/blockstack/stacks-blockchain/issues/2546.
Depending on when you terminate the node, the boot can be stuck in a loop on the subsequent relaunch.
With this patch, the node is able to recover, however I'm having a hard time measuring side effects, and would appreciated more opinions on this approach.

Boot looping

---

testnet/stacks-node/src/syncctl.rs

Fixes https://discord.com/channels/621759717756370964/730814571517968436/829186890388340816

don't wait forever while waiting for an inv-sync pass

---

CHANGELOG.md

I realized I forgot to add the changelog entries for PR #2590. This adds them.
Please also take a few moments and verify that everything we want in the 2.0.11.0.0 changelog is present.

2.0.11.0.0 changelog 

---

CONTRIBUTORS.md

We update the documentation to include guidelines for comments. This includes guidance and examples for comments on:
1. components
2. functions
3. data members
4. tests

feat(Style): Initial Guidelines for Comments

---

src/chainstate/burn/db/sortdb.rs

Addresses #2892 - adds a transition function for the sortition DB schema. 
Ran existing tests, and they passed.

Added sortition db schema transition logic

---

CHANGELOG.md

This adds a CHANGELOG.md entry for 2.05

2.05 Chore: add CHANGELOG.md entry

---

CHANGELOG.md
README.md

docs: updated changelog with features in 2.05.0.1.0

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/events.rs

Track tx index in recept for `micrblocks` and blocks transactions. 
For details:
- https://github.com/blockstack/stacks-blockchain/issues/2712
- https://github.com/blockstack/stacks-blockchain-api/issues/662

Track tx_index for blocks and microblocks transactions

---

src/net/atlas/download.rs
src/net/atlas/mod.rs
src/net/chat.rs
src/net/dns.rs
src/net/mod.rs

This PR does two things:
- I added comments to some modules I read over 
- Added better error handling in `BatchedDNSLookupsState`. In `try_proceed`, if a call to `poll_request` succeeds, I removed the query url from the list of requests to avoid unnecessary future queries for that same url.
Did not add tests since code change was minimal.

Comment network code + small fix

---

.github/actions/docsgen/Dockerfile.docsgen
.vscode/launch.json
CHANGELOG.md
Cargo.toml
build-scripts/Dockerfile.linux-arm64
build-scripts/Dockerfile.linux-armv7
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.linux-x64
build-scripts/Dockerfile.macos-arm64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64
circle.yml

This just renames a binary output (#3099)
- fixes #3099
- There are no modified code paths, so no tests
- Changelog is updated

Feat: rename blockstack-core to stacks-inspect

---

clarity/src/vm/analysis/arithmetic_checker/tests.rs
clarity/src/vm/docs/mod.rs
clarity/src/vm/functions/assets.rs
clarity/src/vm/tests/assets.rs

As I went through to add withdraw related Clarity functions for the hyperchains, I noticed some missing test cases for burn-related Clarity functions. I also updated the docs for these functions. 
- N/A

cleanup: added tests + updated docs for burn-related Clarity functions

---

clarity/src/vm/analysis/errors.rs
clarity/src/vm/types/mod.rs

replace unwrap with error

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/tests/neon_integrations.rs

Adds FLAKY_TEST_FIX_ME to flaky tests to improve dev productivity and encourage fixes.

Annotate flaky tests

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This fixes #3184 -- I want to see if this addresses the issue in my mock miner configuration before pushing more on this PR.

Fix: #3184 alter miner re-attempt logic to always make second attempt

---

CHANGELOG.md

Updating changelog for 2.05.0.3.0 release

Update CHANGELOG for 2.05.0.3.0

---

clarity/src/vm/ast/sugar_expander/mod.rs

Fixes the spans (line/column numbers) in tuple expressions.

feat: set an appropriate span for desugared tuples

---

src/chainstate/stacks/db/transactions.rs

This test verifies that the existing behavior where a contract name that
is longer than 40 characters, but less than 128 characters, can
successfully be passed to a contract call.
See: #3133

test: add test passing long contract name

---

clarity/src/vm/docs/mod.rs

- fixes https://github.com/hirosystems/clarinet/issues/736
N/A
I believe minor change like that don't need to be added to the CHANGELOG but let me know if I need to

docs: fix map snippet

---

clarity/fuzz/fuzz_targets/fuzz_admits_type.rs
clarity/fuzz/fuzz_targets/fuzz_least_supertype.rs
clarity/fuzz/keep-fuzzing.sh
clarity/src/vm/types/signatures.rs

fix(fuzz): Reduce false positives in fuzz-testing

---

Cargo.lock
Cargo.toml
contrib/tools/relay-server/Cargo.toml
contrib/tools/relay-server/README.md
contrib/tools/relay-server/src/http.rs
contrib/tools/relay-server/src/main.rs
contrib/tools/relay-server/src/server.rs
contrib/tools/relay-server/src/state.rs
contrib/tools/relay-server/src/to_io_result.rs
contrib/tools/relay-server/src/url.rs
contrib/tools/relay-server/test.sh

A `relay` server written on Rust.

---

src/chainstate/burn/db/sortdb.rs
src/chainstate/stacks/miner.rs

minor changes in `feat/2.1.0.0.0-rc2`

---

CHANGELOG.md
clarity/src/vm/analysis/type_checker/v2_1/mod.rs
src/net/chat.rs

Feat/stacks 2.1 changelog

---

CHANGELOG.md

Update CHANGELOG for release 2.3.0.0.0

chore - update changelog for 2.3.0.0.0

---

Cargo.lock
clarity/Cargo.toml
clarity/src/vm/analysis/mod.rs
stacks-common/Cargo.toml

Update versions and metadata to reflect what has _already_ been published on crates.io.
Small fix on the wasm compat

chore: bump clarity-vm and stacks-common versions

---

.github/workflows/ci.yml
.github/workflows/github-release.yml
.github/workflows/image-build-binary.yml
.github/workflows/image-build-source.yml
.github/workflows/standalone-tests.yml

Changes as discussed in #3888. Both items are separate commits, feel free to merge/cherry-pick/rebase as you like

Improvements to branch `feat/faster-ci`

---

.github/workflows/image-build-alpine-binary.yml
.github/workflows/image-build-debian-binary.yml
.github/workflows/image-build-debian-source.yml

ref: https://github.com/stacks-network/stacks-blockchain/pull/3888
This is the develop branch with https://github.com/stacks-network/stacks-blockchain/pull/3888/commits/79d376057d4cea082ba2d24f20df7b84072ad079 cherry picked.

cherry-picking docker login env var commit

---

.github/workflows/image-build-alpine-binary.yml
.github/workflows/image-build-debian-binary.yml
.github/workflows/image-build-debian-source.yml

Cherry-picked from #3888, this is similar to #3905 but for the `master` branch

ci: Fix CI failing when we don't have DockerHub credentials

---

.github/workflows/bitcoin-tests.yml

This fixes the CI issues with bitcoin-tests.yml which was failing to properly reclaim disk space with errors about failing to find packages. Adds sudo apt-get update to the cleanup step.
- fixes #https://github.com/stacks-network/stacks-blockchain/issues/3952

Add 'sudo apt-get update' to the build image step in bitcoin-tests.yml

---

CHANGELOG.md
clarity/src/vm/mod.rs

Hotfix to the trait handler.  Makes release 2.4.0.0.3.

fix: fix trait handler and cut release

---

.github/workflows/bitcoin-tests.yml
CHANGELOG.md
clarity/src/vm/functions/mod.rs

Hotfix to the print handler. Makes release 2.4.0.0.4.

Hot fix: Address issue in print

---

Cargo.lock
clarity/src/vm/contexts.rs

@obycode 
Change needed here https://github.com/hirosystems/clarinet/pull/1239/files#diff-aa6d15e9460de456c3f2951cbbaa816fe8c35783d8501dcd1cf2722aa7c05048R611
We probably won't need it in the long term
PR opened on on Brice's branch so can be merged anytilme

refactor(wasm): make wasm_module public in ContractContext

---

clarity/src/vm/callables.rs
clarity/src/vm/clarity_wasm.rs
clarity/src/vm/contexts.rs
clarity/src/vm/costs/mod.rs
stackslib/src/chainstate/stacks/db/transactions.rs

This code can still use some improvements and DRYing up.

feat(wasm): include proper rollback handling for contract-calls

---

stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/tests/mod.rs
testnet/stacks-node/src/mockamoto.rs
testnet/stacks-node/src/mockamoto/tests.rs

Fix `next` compiler error

---

contrib/init/org.stacks.stacks-blockchain.plist
contrib/init/stacks.init
contrib/init/stacks.service
docs/profiling.md
net-test/bin/start.sh
testnet/stacks-node/src/main.rs

replaces instances of `---config=` with `--config ` introduced in #4252

change --config= to --config

---

build-scripts/Dockerfile.linux-glibc-arm64
build-scripts/Dockerfile.linux-glibc-armv7
build-scripts/Dockerfile.linux-glibc-x64
build-scripts/Dockerfile.linux-musl-arm64
build-scripts/Dockerfile.linux-musl-armv7
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.macos-arm64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64

Updates the release binary dockerfiles to specifically build binaries vs building everything in the workspace.

Target specific binaries for release builds

---

stackslib/src/net/api/getinfo.rs
stackslib/src/net/p2p.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

fix: fix #4351

---

clarity/src/vm/clarity_wasm.rs

Exactly what the title say, this adds support for writing of string-utf8 to Wasm memory.
This will be extensively tested in the clarity-wasm repo.

Clarity-Wasm: add support for writing string-utf8 to Wasm memory

---

stackslib/src/lib.rs

MERGE QUEUE TEST PR

---

testnet/stacks-node/src/nakamoto_node/miner.rs

Miners should abort waiting for a signer signature if the burnchain tip has changed as the block will be invalidated.

Have miners abort signing a block if the burn tip changes

---

clarity/src/vm/ast/traits_resolver/mod.rs

There were a lot of unnecessary `Vec` allocations in `TraitsResolver`. I refactored the code to pass around iterators instead of `Vec`s, allowing the removal of several calls to `.collect()`
This gives about a **1%** improvement in block processing times:
```console
❯ hyperfine -w 3 -r 20 "target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "target/release/stacks-inspect.opt-traits-resolver-2 replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
Time (mean ± σ):      8.672 s ±  0.026 s    [User: 8.187 s, System: 0.433 s]
Range (min … max):    8.618 s …  8.725 s    20 runs
Benchmark 2: target/release/stacks-inspect.opt-traits-resolver-2 …
```

chore: Optimize`TraitsResolver`

---

stacks-signer/src/signer.rs

This makes it so that the signer ignores new block proposals that repeat previously seen block proposals.

feat: signer does not treat repeated proposals as new

---

CHANGELOG.md

fix:modified typo "environment"

---

Cargo.lock
stackslib/src/burnchains/burnchain.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/coordinator/mod.rs
stackslib/src/chainstate/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/clarity_vm/tests/epoch_switch.rs
stackslib/src/main.rs
stackslib/src/net/chat.rs
stackslib/src/net/mod.rs
stackslib/src/net/tests/mod.rs
testnet/stacks-node/src/burnchains/mocknet_controller.rs
testnet/stacks-node/src/run_loop/neon.rs

Closes #4454 
Leaving as a draft until I can test with the epoch 2.5 testnet.

Migrate Epoch 2.4 chainstate to Epoch 2.5 without a genesis sync

---

testnet/stacks-node/src/neon_node.rs

This patch applies better consensus hash handling in the `neon_node` during tip selection.

Feat: Consensus hash updates to tip selection

---

CHANGELOG.md

changelog had an incorrect bitcoin block height

update bitcoin activation height

---

stackslib/src/core/mod.rs

fix: activation height for 2.5 is 840_360

---

stackslib/src/core/mod.rs

oops, also fix peer version

---

CHANGELOG.md

This adds a changelog entry for 2.5.0.0.2

chore: changelog entry for 2.5.0.0.2

---

libsigner/src/v1/messages.rs
stacks-common/src/libcommon.rs
stacks-signer/src/client/stacks_client.rs
stackslib/src/main.rs

Reverts stacks-network/stacks-core#4845
some tests still failing, will be addressed in reverted PR

Revert "Fix/signer slot count"

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

This speeds up the `nakamoto_attempt_time` integration test by reducing some of the repetitions and also removing one of the unneccessary `thread::sleep()` calls (replacing it with a mutex check and sleep).

Test: speedup the nakamoto_attempt_time integration test

---

CHANGELOG.md

Changelog updates for 2.5.0.0.4

Add PR's to the changelog for 2.5.0.0.4

---

CHANGELOG.md
stackslib/src/net/connection.rs

merge latest release branch to master

merge release/2.5.0.0.5 to master

---

clarity/src/vm/docs/mod.rs
stacks-signer/src/v0/signer.rs
stacks-signer/src/v1/signer.rs

chore: fix some comments

---

stacks-signer/src/lib.rs

chore: fix comment typo

---

clarity/src/vm/clarity_wasm.rs

Complementar addition to fix https://github.com/stacks-network/clarity-wasm/issues/370.

Add new constant host functions

---

testnet/stacks-node/conf/testnet-follower-conf.toml

testnet-docs: update conf

---

stacks-signer/CHANGELOG.md

Adding PR's to the signer changelog

Update stacks-signer changelog for 2.5.0.0.5.1

---

testnet/stacks-node/src/event_dispatcher.rs

This will be helpful for debugging.

chore: add debug log with event dispatcher payload

---

.github/workflows/bitcoin-tests.yml
libsigner/src/events.rs
testnet/stacks-node/src/event_dispatcher.rs
testnet/stacks-node/src/nakamoto_node.rs
testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This is to stay on top of keeping these in sync.
`Naka-2` is deployed with this branch and running ok so far.

Merge develop into clarity-wasm develop branch

---

testnet/stacks-node/src/event_dispatcher.rs

Without a timout for these connections, the node can get stuck here and it is not obvious what is happening. With this timeout, we will see log messages that will point to the problem.

Timeout connections to observers

---

stacks-signer/CHANGELOG.md

simple change to add PRs to the singer changelog

Update signer changelog for 2.5.0.0.5.2-rc1

---

CHANGELOG.md

Adding changes for 2.5.0.0.6

---

stackslib/src/net/api/postblock_proposal.rs

Simple changes to add some more warn logs to make the reason behind a block proposal rejection easier to identify.

chore: add warn logs for block validate rejections

---

stackslib/src/chainstate/nakamoto/coordinator/mod.rs
stackslib/src/chainstate/nakamoto/coordinator/tests.rs
stackslib/src/chainstate/nakamoto/mod.rs
stackslib/src/chainstate/nakamoto/tenure.rs
testnet/stacks-node/src/tests/signer/v0.rs

Jude found the deadlock introduced in a prior commit.

Remove deadlock introduced in commit 1d836175730eff88eaec9440c608267eb6303494

---

stacks-signer/CHANGELOG.md

Signer release 2.5.0.0.5.2 changelog

Update changelog for signer-2.5.0.0.5.2

---

.github/workflows/bitcoin-tests.yml
testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs

feat: retry check for UTXOs on startup

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

Simple fix to a failing integration test.

test: fix `follower_bootup` integration test

---

docs/rpc-endpoints.md
docs/rpc/openapi.yaml
stacks-signer/CHANGELOG.md
stacks-signer/src/client/stacks_client.rs
stackslib/src/net/api/getstackers.rs
stackslib/src/net/api/postblock_proposal.rs
stackslib/src/net/api/poststackerdbchunk.rs
stackslib/src/net/api/tests/postblock_proposal.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Matches latest node release, 2.5.0.0.7.

fix: update `/v2/stacker_set/` to `/v3/stacker_set/`

---

.github/workflows/bitcoin-tests.yml
stacks-signer/src/chainstate.rs
stacks-signer/src/v0/signer.rs
testnet/stacks-node/src/config.rs

See if this solves any of the problems with integration tests that pass locally but fail in CI.

Test prlimit

---

stacks-signer/src/config.rs

Closes https://github.com/stacks-network/stacks-core/issues/5245

Do not leak a private key that has a small typo

---

testnet/stacks-node/src/tests/neon_integrations.rs

These tests have been flaky for a while. This gets rid of some obvious potential flaky points.

Fix flakiness in problematic microblocks tests

---

clarity/src/vm/clarity_wasm.rs

fix: correct error mapping for BadTypeConstruction

---

stackslib/src/blockstack_cli.rs

`--testnet` will use the default testnet chain id and `--testnet=0x80000100` will set it to `0x80000100`.

feat: support custom chain ids in blockstack-cli

---

clarity/src/vm/clarity_wasm.rs

Sync changes from `clarity-wasm` repo.

Update clarity wasm develop

---

testnet/stacks-node/src/tests/signer/v0.rs

Do not assume every tenure has inter_blocks_per_tenure as we may break early if toomuchchaining error gets hit.
Closes: https://github.com/stacks-network/stacks-core/issues/5335

Fix partial tenure fork test

---

stackslib/src/net/relay.rs

Closes https://github.com/stacks-network/stacks-core/issues/5342

Turn common stale chunk error into a debug with its own message

---

testnet/stacks-node/src/tests/signer/v0.rs

Closes: https://github.com/stacks-network/stacks-core/issues/5328

Fix/miner forking: increase the reward cycle length to increase liklihood of the test case hitting before reward cycle end

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs

Closes https://github.com/stacks-network/stacks-core/issues/5377

Ensure we have a minimum expected gap in flash blocks test

---

stacks-signer/CHANGELOG.md

updates the changelog with new signer version

Adding changelog for signer release

---

Cargo.lock
clarity/src/vm/clarity_wasm.rs

Updated linker functions in `clarity_wasm.rs`. Some changes on the `clarity-wasm` side seem to be missing replication in `stacks-core`.

update linker functions

---

testnet/stacks-node/src/config.rs
testnet/stacks-node/src/nakamoto_node/miner.rs

feat: add pause after block rejections

---

testnet/stacks-node/src/nakamoto_node/relayer.rs
testnet/stacks-node/src/neon_node.rs

Additional minor change I noticed when reviewing #5418.

fix: remove duplicate conditions

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

update changelog for 3.0.0.0.1

Update the changelogs

---

CHANGELOG.md
stacks-common/src/util/db.rs
stacks-signer/CHANGELOG.md

merge release branch back to develop

---

testnet/stacks-node/src/tests/epoch_25.rs

Let's see how this does in CI. This test is probably not worth any more effort if this doesn't work.

test: reduce flakiness in `microblocks_disabled`

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

Updating changelogs for 3.0.0.0.3

---

stackslib/src/net/api/postblock_v3.rs
stackslib/src/net/api/tests/postblock_v3.rs

- fixes https://github.com/stacks-network/stacks-core/issues/5386

fix  v3 update block to support no trailing

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

updating changelog for 3.1.0.0.2.x releases

Adding changelog for 3.1.0.0.2.x

---

.github/workflows/p2p-tests.yml

Partially closes https://github.com/stacks-network/stacks-core/issues/5554

Fix p2p ci no tests errors

---

stackslib/src/burnchains/tests/affirmation.rs
stackslib/src/burnchains/tests/burnchain.rs
stackslib/src/chainstate/burn/db/processing.rs
stackslib/src/chainstate/burn/db/sortdb.rs
stackslib/src/chainstate/burn/distribution.rs
stackslib/src/chainstate/burn/operations/leader_block_commit.rs
stackslib/src/chainstate/burn/operations/leader_key_register.rs
stackslib/src/chainstate/stacks/block.rs

Woops I merged this into the wrong branch...so rereview...

Fix zero_prefixed_literal warnings

---

sample/conf/testnet-follower-conf.toml
sample/conf/testnet-miner-conf.toml
sample/conf/testnet-signer.toml

Updates testnet configs with new epoch heights.

docs: update testnet configs with new epoch heights

---

stacks-signer/CHANGELOG.md

stacks-signer was missing the version in the changelog

Update versioning for stacks-signer changelog in release branch

---

stacks-signer/src/config.rs

chore: update default idle timeout to 120s

---

testnet/stacks-node/src/tests/signer/v0.rs

Before checking for the tip to be updated, make sure that both nodes have received the newest burn block

Fix miner_forking test

---

testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/mod.rs
testnet/stacks-node/src/tests/signer/v0.rs

Refactor the block waits in the nakamoto_integrations and signer tests. This _should_ reduce a little bit of flakiness across the board.

Test: Refactor block waits

---

CHANGELOG.md
stacks-signer/CHANGELOG.md

Adds the changelog entries for 3.1.0.0.5 (slight reformatting for the stacks-signer changelog for correctness)

update changelog for 3.1.0.0.5

---

.github/workflows/pr-differences-mutants.yml

See #5806 -- this PR disables the mutants runs on PRs.

CI: disable mutants on PRs

---

.vscode/launch.json

This is just cleaning up some old targets and updating names.

chore: update VSCode launch.json

---

libsigner/src/v0/messages.rs
stacks-signer/CHANGELOG.md
stacks-signer/src/signerdb.rs
stacks-signer/src/v0/signer.rs
stacks-signer/src/v0/tests.rs
testnet/stacks-node/src/tests/nakamoto_integrations.rs
testnet/stacks-node/src/tests/signer/v0.rs

This builds on #5877 to resolve the signer side of #5856.

feat: allow signers to reconsider some rejected blocks

---

clarity/src/vm/docs/mod.rs

Small docs edit proposed by @obycode and @0xpessimist in  #5879.

Remove unnecessary docs lines

---

.gitattributes
.vscode/settings.json
README.md

Currenlty eol file management is not properly configured and as a result:
- a developer is subject to a different user experience depending on the os (need to setup properly git `core.autoclrf = input` as indicated by our readme)
- compilation and or test execution may fail on windows due to the eol sensitivity of some stacks packages (`stx-genesis` and `clarity`. More details in the applicable issue)  
This patch try to standardize eol management to LF, in two directions:
- the first one, that does the trick, is to properly setting eol in `.gitattributes`. This will force git to checkout locally and commit chages to use LF.
- the second,  is configure vscode to use LF as default (mainly when creating new file). Even if it is not mandatory, this avoid (on windows) to see the following …

fix: improve eol file management

---

.github/workflows/ci.yml
.github/workflows/github-release.yml

This PR secures the release workflow. Cc @aldur 
- Action run: https://github.com/BowTiedDevOps/stacks-core/actions/runs/14200066464
- Created Release: https://github.com/BowTiedDevOps/stacks-core/releases/tag/signer-6.3.0.0.0.2
- Created Downstream PRs: https://github.com/BowTiedDevOps/stacks-core/pull/20 & https://github.com/BowTiedDevOps/stacks-core/pull/21

Update ci workflow

---

testnet/stacks-node/src/tests/signer/v0.rs

This test verifies the behavior of burn-block-height within a tenure-extend block. cc @cylewitruk
Replacing #5854

test: add integration test checking `burn-block-height` behavior

---

versions.toml

Updates `versions.toml` to prep for release.

update versions.toml for release

---

testnet/stacks-node/src/run_loop/nakamoto.rs
testnet/stacks-node/src/run_loop/neon.rs

This fixes a regression in 3.1.0.0.8.

fix: do not check for utxos when mock-mining

---

versions.toml

Bump versions.toml for the signer release value to `3.1.0.0.8.1`

bump version for signer in versions.toml

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

Updates version.toml and changelogs for 3.1.0.0.10 release

Bumping versions for 3.1.0.0.10 release

---

stacks-signer/src/v0/signer.rs
stackslib/src/net/relay.rs

Log improvements that would have been helpful when debugging a stall.

Chore: log improvements

---

stackslib/src/net/db.rs

From https://github.com/stacks-network/stacks-core/pull/6114#discussion_r2097631484 
This PR fixes a bug in the P2P peer selection logic in `get_fresh_random_neighbors()` function. The issue occurred when the function was called with `always_include_allowed = false`, causing it to:
- Include "always allowed" peers (allowed < 0)
- Include "not allowed" peers (allowed = 0 or allowed <= current_timestamp)
- But incorrectly exclude temporarily allowed peers (current_timestamp < allowed)
It also adds some comments and formatting for readability.
The fix ensures that the peer selection query properly includes temporarily allowed peers when `always_include_allowed = false`.
- Added unit test `test_get_fresh_random_neighbors_allowed_logic` with multiple test cases:
- Test Case 1: Verifies correct …

fix: `get_fresh_random_neighbors` to include allowed neigbors

---

CHANGELOG.md
stacks-signer/CHANGELOG.md
versions.toml

Updates the changelogs and versions.toml to prep for 3.1.0.0.12 release

Update changelogs for 3.1.0.0.12

---

.cargo/config.toml
stx-genesis/build.rs
stx-genesis/src/lib.rs

This was such a small change to enable clippy on stx-genesis that I went ahead and did it.

Add clippy to stx-genesis

---

clarity/src/vm/tests/contracts.rs
clarity/src/vm/tests/traits.rs

Fix https://github.com/stacks-network/clarity-wasm/issues/659

[clarity-wasm-tests] fix test failing with WriteAttemptedInReadOnlyMode

---

stackslib/src/clarity_vm/tests/forking.rs

Fix for https://github.com/stacks-network/clarity-wasm/issues/662

[clarity-wasm-tests] fix test failing with UnknownFunction

---

stackslib/Cargo.toml
stackslib/src/clarity_vm/tests/costs.rs
stackslib/src/clarity_vm/tests/events.rs

Closes: https://github.com/stacks-network/clarity-wasm/issues/656

[clarity-wasm-tests] Fix UncheckedIntermediaryResponse Error in Tests

---

clarity/src/vm/tests/contracts.rs

fix: https://github.com/stacks-network/clarity-wasm/issues/656

[clarity-wasm-tests] fix CheckErrors::UncheckedIntermediaryResponses

---

clarity/src/vm/contexts.rs
stackslib/src/chainstate/stacks/boot/contract_tests.rs

fix: https://github.com/stacks-network/clarity-wasm/issues/668

[clarity-wasm-tests] fix chainstate::stacks::boot::contract_tests

---

stackslib/src/clarity_vm/tests/costs.rs

fix https://github.com/stacks-network/clarity-wasm/issues/669

[clarity-wasm-tests] fix clarity_vm::tests::costs issues

---

stacks-signer/CHANGELOG.md
stacks-signer/src/v0/signer.rs

chore: add signer info logs for acceptance/rejections

---

CHANGELOG.md

Quick patch for adding the Changelog entry for the new `/v3/contracts/fast-call-read` endpoint.
- fixes #

Added changelog for /v3/contracts/fast-call-read

---

clarity/src/vm/clarity_wasm.rs

This PR adds Clarity arguments validation on `call_function`.
Previously, if a function call was made with incorrect argument types (e.g. `int` instead of `uint`, which are both represented similarly in WASM) or with extra arguments, the call would still go through.
With this change, `call_function` will now validate the number and types of arguments before the `func.call` is made, preventing these issues early.
This issue was found while working on https://github.com/stacks-network/clarity-wasm/issues/675.

Add Clarity Arguments Validation on `call_function`

---

.cargo/config.toml
stacks-node/src/tests/signer/mod.rs
stackslib/src/burnchains/bitcoin/indexer.rs
stackslib/src/burnchains/bitcoin/spv.rs
stackslib/src/net/api/posttransaction.rs
stackslib/src/net/p2p.rs
stackslib/src/net/relay.rs
stackslib/src/net/tests/relay/epoch2x.rs

In the process of understanding clarity error flow, this irritated me enough to open a small cleanup PR.

Fix clippy::nonminimal_bool warns throughout stackslib

---

stackslib/src/clarity_cli.rs

Resolves https://github.com/stacks-network/stacks-core/issues/6418.

Allow specifying Clarity version in `clarity-cli`

---

.github/actions/dockerfiles/Dockerfile.alpine-binary
.github/actions/dockerfiles/Dockerfile.debian-binary

update dockerfiles for release
